In [1]:
#Load packages
import pandas as pd
import numpy as np

# I. Coding Run Expectancy Dataset (2017)

In [ ]:
#Your Code Here

In [ ]:
# 1.	Import pandas and numpy packages and read in “MLBAM17.csv” data

In [2]:
# Read in MLBAM Data for 2017

MLBAM17 = pd.read_csv("../Data/MLBAM17.csv")

In [3]:
display(MLBAM17)

,Unnamed: 0,inning,batterId,pitcherId,event,x,y,ab_num,timestamp,stand,...,fielderId,gameId,isPA,isAB,isHit,isBIP,our.x,our.y,r,theta
0,1,1,458731,502042,Flyout,65.59,123.50,1,2017-04-02 17:12:18,L,...,605480.0,gid_2017_04_02_nyamlb_tbamlb_1,True,True,False,True,-148.267814,188.423160,239.763700,2.237490
1,2,1,596142,502042,Groundout,128.19,193.88,2,2017-04-02 17:15:42,R,...,502042.0,gid_2017_04_02_nyamlb_tbamlb_1,True,True,False,True,7.961190,12.777835,15.055020,1.013603
2,3,1,595885,502042,Walk,NaN,NaN,3,2017-04-02 17:16:48,L,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,False,False,False,NaN,NaN,NaN,NaN
3,4,1,407812,502042,Groundout,153.48,157.29,4,2017-04-02 17:19:09,R,...,543543.0,gid_2017_04_02_nyamlb_tbamlb_1,True,True,False,True,71.076710,104.094437,126.045827,0.971701
4,5,1,572816,547888,Single,140.75,73.31,5,2017-04-02 17:24:43,L,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,True,True,True,39.306818,313.680887,316.134030,1.446138
5,6,1,595281,547888,Double,103.34,100.63,6,2017-04-02 17:25:58,L,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,True,True,True,-54.056234,245.499156,251.380015,1.787527
6,7,1,446334,547888,Sac Fly,NaN,NaN,7,2017-04-02 17:29:16,R,...,592450.0,gid_2017_04_02_nyamlb_tbamlb_1,True,False,False,False,NaN,NaN,NaN,NaN
7,8,1,543543,547888,Single,145.19,182.67,8,2017-04-02 17:30:57,L,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,True,True,True,50.387597,40.754307,64.806045,0.680094
8,9,1,519306,547888,Walk,NaN,NaN,9,2017-04-02 17:32:58,R,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,False,False,False,NaN,NaN,NaN,NaN
9,10,1,489149,547888,Single,130.06,87.56,10,2017-04-02 17:35:40,L,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,True,True,True,12.628095,278.117575,278.404121,1.525422
10,11,1,542921,547888,Lineout,145.42,79.78,11,2017-04-02 17:38:22,R,...,453056.0,gid_2017_04_02_nyamlb_tbamlb_1,True,True,False,True,50.961602,297.533896,301.866699,1.401162
11,12,1,605480,547888,Strikeout,NaN,NaN,12,2017-04-02 17:39:11,L,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,True,False,False,NaN,NaN,NaN,NaN
12,13,2,453056,502042,Flyout,51.93,139.48,13,2017-04-02 17:42:51,L,...,605480.0,gid_2017_04_02_nyamlb_tbamlb_1,True,True,False,True,-182.358679,148.542337,235.201008,2.458036
13,14,2,516770,502042,Single,136.17,148.63,14,2017-04-02 17:45:25,R,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,True,True,True,27.876645,125.706948,128.760802,1.352569
14,15,2,452104,502042,Single,77.13,131.84,15,2017-04-02 17:49:10,L,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,True,True,True,-119.467770,167.609264,205.828602,2.190045
15,16,2,592450,502042,Double,43.57,100.85,16,2017-04-02 17:52:18,R,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,True,True,True,-203.222489,244.950108,318.276508,2.263356
16,17,2,591720,502042,Groundout,141.26,163.90,17,2017-04-02 17:53:27,R,...,543543.0,gid_2017_04_02_nyamlb_tbamlb_1,True,True,False,True,40.579610,87.598052,96.540787,1.136980
17,18,2,458731,502042,Groundout,145.84,163.40,18,2017-04-02 17:55:01,L,...,543543.0,gid_2017_04_02_nyamlb_tbamlb_1,True,True,False,True,52.009783,88.845887,102.949547,1.041186
18,19,2,519083,547888,Groundout,101.05,171.54,19,2017-04-02 17:59:49,R,...,452104.0,gid_2017_04_02_nyamlb_tbamlb_1,True,True,False,True,-59.771320,68.531125,90.934734,2.288026
19,20,2,572816,547888,Strikeout,NaN,NaN,20,2017-04-02 18:01:08,L,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,True,False,False,NaN,NaN,NaN,NaN
20,21,2,595281,547888,Walk,NaN,NaN,21,2017-04-02 18:02:02,L,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,False,False,False,NaN,NaN,NaN,NaN
21,22,2,446334,547888,Home Run,27.76,96.72,22,2017-04-02 18:05:12,R,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,True,True,False,-242.679047,255.257229,352.206435,2.330939
22,23,2,543543,547888,Flyout,98.88,79.61,23,2017-04-02 18:06:59,L,...,453056.0,gid_2017_04_02_nyamlb_tbamlb_1,True,True,False,True,-65.186926,297.958160,305.005574,1.786182
23,24,3,596142,502042,Groundout,109.20,157.80,24,2017-04-02 18:10:44,R,...,542921.0,gid_2017_04_02_nyamlb_tbamlb_1,True,True,False,True,-39.431602,102.821645,110.123303,1.936994
24,25,3,595885,502042,Flyout,49.65,139.47,25,2017-04-02 18:12:38,L,...,605480.0,gid_2017_04_02_nyamlb_tbamlb_1,True,True,False,True,-188.048809,148.567294,239.655160,2.472950
25,26,3,407812,502042,Strikeout,NaN,NaN,26,2017-04-02 18:13:19,R,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,True,False,False,NaN,NaN,NaN,NaN
26,27,3,519306,547888,Strikeout,NaN,NaN,27,2017-04-02 18:17:09,R,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,True,False,False,NaN,NaN,NaN,NaN
27,28,3,489149,547888,Home Run,166.48,31.20,28,2017-04-02 18:19:55,L,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,True,True,False,103.520433,418.773593,431.378954,1.328456
28,29,3,542921,547888,Double,41.50,111.48,29,2017-04-02 18:21:32,R,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,True,True,True,-208.388528,218.421125,301.883366,2.332693
29,30,3,605480,547888,Single,124.47,196.99,30,2017-04-02 18:23:27,L,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,True,True,True,-1.322706,5.016299,5.187755,1.828610
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185565,185566,6,594807,642239,Double,24.25,89.88,40,2017-10-01 20:47:52,R,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,True,True,True,True,-251.438852,272.327619,370.653246,2.316334
185566,185567,6,553993,642239,Single,175.04,140.69,41,2017-10-01 20:49:15,R,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,True,True,True,True,124.883376,145.522576,191.762034,0.861577
185567,185568,6,571697,642239,Single,185.48,109.50,42,2017-10-01 20:53:24,L,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,True,True,True,True,150.938182,223.362554,269.579608,0.976529
185568,185569,6,640447,642239,Lineout,111.41,144.47,43,2017-10-01 20:54:11,R,...,608365.0,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,True,-33.916169,136.088939,140.251581,1.815041
185569,185570,6,595453,642239,Strikeout,NaN,NaN,44,2017-10-01 20:54:53,R,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,False,NaN,NaN,NaN,NaN
185570,185571,6,543089,608652,Flyout,85.10,110.52,45,2017-10-01 20:59:01,R,...,594807.0,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,True,-99.577273,220.816969,242.230814,1.994439
185571,185572,6,546991,608652,Groundout,149.48,150.57,46,2017-10-01 21:00:02,R,...,571697.0,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,True,61.094026,120.865346,135.428623,1.102781
185572,185573,6,502273,608652,Groundout,149.48,149.55,47,2017-10-01 21:02:02,L,...,571697.0,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,True,61.094026,123.410931,137.705257,1.111120
185573,185574,7,623182,570240,Groundout,127.68,191.63,48,2017-10-01 21:06:19,R,...,570240.0,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,True,6.688398,18.393095,19.571424,1.222025
185574,185575,7,571740,570240,Lineout,105.83,60.24,49,2017-10-01 21:07:03,L,...,445055.0,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,True,-47.842013,346.299307,349.588427,1.708080
185575,185576,7,572227,570240,Strikeout,NaN,NaN,50,2017-10-01 21:08:25,R,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,False,NaN,NaN,NaN,NaN
185576,185577,7,450314,593974,Strikeout,NaN,NaN,51,2017-10-01 21:13:01,R,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,False,NaN,NaN,NaN,NaN
185577,185578,7,570240,593974,Strikeout,NaN,NaN,52,2017-10-01 21:16:57,R,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,False,NaN,NaN,NaN,NaN
185578,185579,7,656941,593974,Groundout,148.47,149.55,53,2017-10-01 21:17:12,L,...,571697.0,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,True,58.573398,123.410931,136.605640,1.127657
185579,185580,8,458015,570240,Double,76.68,55.67,54,2017-10-01 21:18:52,L,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,True,True,True,True,-120.590822,357.704523,377.484665,1.895955
185580,185581,8,594807,570240,Strikeout,NaN,NaN,55,2017-10-01 21:21:39,R,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,False,NaN,NaN,NaN,NaN
185581,185582,8,553993,570240,Flyout,131.59,53.12,56,2017-10-01 21:24:30,R,...,445055.0,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,True,16.446472,364.068484,364.439772,1.525653
185582,185583,8,571697,570240,Strikeout,NaN,NaN,57,2017-10-01 21:25:29,L,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,False,NaN,NaN,NaN,NaN
185583,185584,8,605170,594992,Strikeout,NaN,NaN,58,2017-10-01 21:29:32,L,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,False,NaN,NaN,NaN,NaN
185584,185585,8,600303,594992,Strikeout,NaN,NaN,59,2017-10-01 21:31:54,L,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,False,NaN,NaN,NaN,NaN
185585,185586,8,664023,594992,Strikeout,NaN,NaN,60,2017-10-01 21:34:41,L,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,False,NaN,NaN,NaN,NaN
185586,185587,9,640447,596027,Flyout,192.57,97.34,61,2017-10-01 21:38:47,R,...,518792.0,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,True,168.632489,253.709913,304.640175,0.984180
185587,185588,9,595453,596027,Strikeout,NaN,NaN,62,2017-10-01 21:39:35,R,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,False,NaN,NaN,NaN,NaN
185588,185589,9,608385,596027,Single,185.98,100.38,63,2017-10-01 21:41:30,L,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,True,True,True,True,152.186017,246.123073,289.373722,1.017006
185589,185590,9,571740,596027,Walk,NaN,NaN,64,2017-10-01 21:42:52,L,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,True,False,False,False,NaN,NaN,NaN,NaN
185590,185591,9,572227,596027,Runner Out,NaN,NaN,65,2017-10-01 21:44:19,R,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,False,False,False,False,NaN,NaN,NaN,NaN
185591,185592,9,543089,628452,Groundout,142.89,147.02,66,2017-10-01 21:49:41,R,...,571697.0,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,True,44.647554,129.724978,137.193200,1.239324
185592,185593,9,546991,628452,Home Run,119.91,21.25,67,2017-10-01 21:50:11,R,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,True,True,True,False,-12.702965,443.605519,443.787361,1.599424
185593,185594,9,502273,628452,Groundout,127.01,201.44,68,2017-10-01 21:51:15,L,...,571697.0,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,True,5.016299,-6.089437,7.889518,-0.881728
185594,185595,9,450314,628452,Groundout,126.83,200.86,69,2017-10-01 21:51:48,L,...,571697.0,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,True,4.567078,-4.641948,6.511980,-0.793528

In [ ]:
# 2.	Keep only the relevant columns (see exercise notebook)

In [4]:
# Drop column with no relevant information
MLBAM17.drop(['Unnamed: 0'], axis=1, inplace=True)
MLBAM17

,inning,batterId,pitcherId,event,x,y,ab_num,timestamp,stand,throws,...,fielderId,gameId,isPA,isAB,isHit,isBIP,our.x,our.y,r,theta
0,1,458731,502042,Flyout,65.59,123.50,1,2017-04-02 17:12:18,L,R,...,605480.0,gid_2017_04_02_nyamlb_tbamlb_1,True,True,False,True,-148.267814,188.423160,239.763700,2.237490
1,1,596142,502042,Groundout,128.19,193.88,2,2017-04-02 17:15:42,R,R,...,502042.0,gid_2017_04_02_nyamlb_tbamlb_1,True,True,False,True,7.961190,12.777835,15.055020,1.013603
2,1,595885,502042,Walk,NaN,NaN,3,2017-04-02 17:16:48,L,R,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,False,False,False,NaN,NaN,NaN,NaN
3,1,407812,502042,Groundout,153.48,157.29,4,2017-04-02 17:19:09,R,R,...,543543.0,gid_2017_04_02_nyamlb_tbamlb_1,True,True,False,True,71.076710,104.094437,126.045827,0.971701
4,1,572816,547888,Single,140.75,73.31,5,2017-04-02 17:24:43,L,R,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,True,True,True,39.306818,313.680887,316.134030,1.446138
5,1,595281,547888,Double,103.34,100.63,6,2017-04-02 17:25:58,L,R,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,True,True,True,-54.056234,245.499156,251.380015,1.787527
6,1,446334,547888,Sac Fly,NaN,NaN,7,2017-04-02 17:29:16,R,R,...,592450.0,gid_2017_04_02_nyamlb_tbamlb_1,True,False,False,False,NaN,NaN,NaN,NaN
7,1,543543,547888,Single,145.19,182.67,8,2017-04-02 17:30:57,L,R,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,True,True,True,50.387597,40.754307,64.806045,0.680094
8,1,519306,547888,Walk,NaN,NaN,9,2017-04-02 17:32:58,R,R,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,False,False,False,NaN,NaN,NaN,NaN
9,1,489149,547888,Single,130.06,87.56,10,2017-04-02 17:35:40,L,R,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,True,True,True,12.628095,278.117575,278.404121,1.525422
10,1,542921,547888,Lineout,145.42,79.78,11,2017-04-02 17:38:22,R,R,...,453056.0,gid_2017_04_02_nyamlb_tbamlb_1,True,True,False,True,50.961602,297.533896,301.866699,1.401162
11,1,605480,547888,Strikeout,NaN,NaN,12,2017-04-02 17:39:11,L,R,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,True,False,False,NaN,NaN,NaN,NaN
12,2,453056,502042,Flyout,51.93,139.48,13,2017-04-02 17:42:51,L,R,...,605480.0,gid_2017_04_02_nyamlb_tbamlb_1,True,True,False,True,-182.358679,148.542337,235.201008,2.458036
13,2,516770,502042,Single,136.17,148.63,14,2017-04-02 17:45:25,R,R,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,True,True,True,27.876645,125.706948,128.760802,1.352569
14,2,452104,502042,Single,77.13,131.84,15,2017-04-02 17:49:10,L,R,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,True,True,True,-119.467770,167.609264,205.828602,2.190045
15,2,592450,502042,Double,43.57,100.85,16,2017-04-02 17:52:18,R,R,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,True,True,True,-203.222489,244.950108,318.276508,2.263356
16,2,591720,502042,Groundout,141.26,163.90,17,2017-04-02 17:53:27,R,R,...,543543.0,gid_2017_04_02_nyamlb_tbamlb_1,True,True,False,True,40.579610,87.598052,96.540787,1.136980
17,2,458731,502042,Groundout,145.84,163.40,18,2017-04-02 17:55:01,L,R,...,543543.0,gid_2017_04_02_nyamlb_tbamlb_1,True,True,False,True,52.009783,88.845887,102.949547,1.041186
18,2,519083,547888,Groundout,101.05,171.54,19,2017-04-02 17:59:49,R,R,...,452104.0,gid_2017_04_02_nyamlb_tbamlb_1,True,True,False,True,-59.771320,68.531125,90.934734,2.288026
19,2,572816,547888,Strikeout,NaN,NaN,20,2017-04-02 18:01:08,L,R,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,True,False,False,NaN,NaN,NaN,NaN
20,2,595281,547888,Walk,NaN,NaN,21,2017-04-02 18:02:02,L,R,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,False,False,False,NaN,NaN,NaN,NaN
21,2,446334,547888,Home Run,27.76,96.72,22,2017-04-02 18:05:12,R,R,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,True,True,False,-242.679047,255.257229,352.206435,2.330939
22,2,543543,547888,Flyout,98.88,79.61,23,2017-04-02 18:06:59,L,R,...,453056.0,gid_2017_04_02_nyamlb_tbamlb_1,True,True,False,True,-65.186926,297.958160,305.005574,1.786182
23,3,596142,502042,Groundout,109.20,157.80,24,2017-04-02 18:10:44,R,R,...,542921.0,gid_2017_04_02_nyamlb_tbamlb_1,True,True,False,True,-39.431602,102.821645,110.123303,1.936994
24,3,595885,502042,Flyout,49.65,139.47,25,2017-04-02 18:12:38,L,R,...,605480.0,gid_2017_04_02_nyamlb_tbamlb_1,True,True,False,True,-188.048809,148.567294,239.655160,2.472950
25,3,407812,502042,Strikeout,NaN,NaN,26,2017-04-02 18:13:19,R,R,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,True,False,False,NaN,NaN,NaN,NaN
26,3,519306,547888,Strikeout,NaN,NaN,27,2017-04-02 18:17:09,R,R,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,True,False,False,NaN,NaN,NaN,NaN
27,3,489149,547888,Home Run,166.48,31.20,28,2017-04-02 18:19:55,L,R,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,True,True,False,103.520433,418.773593,431.378954,1.328456
28,3,542921,547888,Double,41.50,111.48,29,2017-04-02 18:21:32,R,R,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,True,True,True,-208.388528,218.421125,301.883366,2.332693
29,3,605480,547888,Single,124.47,196.99,30,2017-04-02 18:23:27,L,R,...,NaN,gid_2017_04_02_nyamlb_tbamlb_1,True,True,True,True,-1.322706,5.016299,5.187755,1.828610
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185565,6,594807,642239,Double,24.25,89.88,40,2017-10-01 20:47:52,R,L,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,True,True,True,True,-251.438852,272.327619,370.653246,2.316334
185566,6,553993,642239,Single,175.04,140.69,41,2017-10-01 20:49:15,R,L,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,True,True,True,True,124.883376,145.522576,191.762034,0.861577
185567,6,571697,642239,Single,185.48,109.50,42,2017-10-01 20:53:24,L,L,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,True,True,True,True,150.938182,223.362554,269.579608,0.976529
185568,6,640447,642239,Lineout,111.41,144.47,43,2017-10-01 20:54:11,R,L,...,608365.0,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,True,-33.916169,136.088939,140.251581,1.815041
185569,6,595453,642239,Strikeout,NaN,NaN,44,2017-10-01 20:54:53,R,L,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,False,NaN,NaN,NaN,NaN
185570,6,543089,608652,Flyout,85.10,110.52,45,2017-10-01 20:59:01,R,R,...,594807.0,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,True,-99.577273,220.816969,242.230814,1.994439
185571,6,546991,608652,Groundout,149.48,150.57,46,2017-10-01 21:00:02,R,R,...,571697.0,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,True,61.094026,120.865346,135.428623,1.102781
185572,6,502273,608652,Groundout,149.48,149.55,47,2017-10-01 21:02:02,L,R,...,571697.0,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,True,61.094026,123.410931,137.705257,1.111120
185573,7,623182,570240,Groundout,127.68,191.63,48,2017-10-01 21:06:19,R,R,...,570240.0,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,True,6.688398,18.393095,19.571424,1.222025
185574,7,571740,570240,Lineout,105.83,60.24,49,2017-10-01 21:07:03,L,R,...,445055.0,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,True,-47.842013,346.299307,349.588427,1.708080
185575,7,572227,570240,Strikeout,NaN,NaN,50,2017-10-01 21:08:25,R,R,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,False,NaN,NaN,NaN,NaN
185576,7,450314,593974,Strikeout,NaN,NaN,51,2017-10-01 21:13:01,R,L,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,False,NaN,NaN,NaN,NaN
185577,7,570240,593974,Strikeout,NaN,NaN,52,2017-10-01 21:16:57,R,L,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,False,NaN,NaN,NaN,NaN
185578,7,656941,593974,Groundout,148.47,149.55,53,2017-10-01 21:17:12,L,L,...,571697.0,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,True,58.573398,123.410931,136.605640,1.127657
185579,8,458015,570240,Double,76.68,55.67,54,2017-10-01 21:18:52,L,R,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,True,True,True,True,-120.590822,357.704523,377.484665,1.895955
185580,8,594807,570240,Strikeout,NaN,NaN,55,2017-10-01 21:21:39,R,R,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,False,NaN,NaN,NaN,NaN
185581,8,553993,570240,Flyout,131.59,53.12,56,2017-10-01 21:24:30,R,R,...,445055.0,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,True,16.446472,364.068484,364.439772,1.525653
185582,8,571697,570240,Strikeout,NaN,NaN,57,2017-10-01 21:25:29,L,R,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,False,NaN,NaN,NaN,NaN
185583,8,605170,594992,Strikeout,NaN,NaN,58,2017-10-01 21:29:32,L,R,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,False,NaN,NaN,NaN,NaN
185584,8,600303,594992,Strikeout,NaN,NaN,59,2017-10-01 21:31:54,L,R,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,False,NaN,NaN,NaN,NaN
185585,8,664023,594992,Strikeout,NaN,NaN,60,2017-10-01 21:34:41,L,R,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,False,NaN,NaN,NaN,NaN
185586,9,640447,596027,Flyout,192.57,97.34,61,2017-10-01 21:38:47,R,R,...,518792.0,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,True,168.632489,253.709913,304.640175,0.984180
185587,9,595453,596027,Strikeout,NaN,NaN,62,2017-10-01 21:39:35,R,R,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,False,NaN,NaN,NaN,NaN
185588,9,608385,596027,Single,185.98,100.38,63,2017-10-01 21:41:30,L,R,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,True,True,True,True,152.186017,246.123073,289.373722,1.017006
185589,9,571740,596027,Walk,NaN,NaN,64,2017-10-01 21:42:52,L,R,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,True,False,False,False,NaN,NaN,NaN,NaN
185590,9,572227,596027,Runner Out,NaN,NaN,65,2017-10-01 21:44:19,R,R,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,False,False,False,False,NaN,NaN,NaN,NaN
185591,9,543089,628452,Groundout,142.89,147.02,66,2017-10-01 21:49:41,R,R,...,571697.0,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,True,44.647554,129.724978,137.193200,1.239324
185592,9,546991,628452,Home Run,119.91,21.25,67,2017-10-01 21:50:11,R,R,...,NaN,gid_2017_10_01_cinmlb_chnmlb_1,True,True,True,False,-12.702965,443.605519,443.787361,1.599424
185593,9,502273,628452,Groundout,127.01,201.44,68,2017-10-01 21:51:15,L,R,...,571697.0,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,True,5.016299,-6.089437,7.889518,-0.881728
185594,9,450314,628452,Groundout,126.83,200.86,69,2017-10-01 21:51:48,L,R,...,571697.0,gid_2017_10_01_cinmlb_chnmlb_1,True,True,False,True,4.567078,-4.641948,6.511980,-0.793528

In [5]:
# Keep relevant columns
RE17 = MLBAM17[['batterName','batterId','event', 'start1B', 'start2B', 'start3B', 'end1B', 'end2B', 'end3B',\
                'startOuts','endOuts','runsFuture','runsOnPlay','outsInInning',\
                'stand', 'throws','venueId', 'stadium', 'batterPos']].copy()

display(RE17)

,batterName,batterId,event,start1B,start2B,start3B,end1B,end2B,end3B,startOuts,endOuts,runsFuture,runsOnPlay,outsInInning,stand,throws,venueId,stadium,batterPos
0,Gardner,458731,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,L,R,12,Tropicana Field,LF
1,"Sanchez, G",596142,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,R,R,12,Tropicana Field,C
2,Bird,595885,Walk,NaN,NaN,NaN,595885.0,NaN,NaN,2,2,0,0,3,L,R,12,Tropicana Field,1B
3,Holliday,407812,Groundout,595885.0,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,R,R,12,Tropicana Field,DH
4,"Dickerson, C",572816,Single,NaN,NaN,NaN,572816.0,NaN,NaN,0,0,3,0,3,L,R,12,Tropicana Field,DH
5,Kiermaier,595281,Double,572816.0,NaN,NaN,NaN,595281.0,572816.0,0,0,3,0,3,L,R,12,Tropicana Field,CF
6,Longoria,446334,Sac Fly,NaN,595281.0,572816.0,NaN,595281.0,NaN,0,1,3,1,3,R,R,12,Tropicana Field,3B
7,"Miller, B",543543,Single,NaN,595281.0,NaN,543543.0,NaN,595281.0,1,1,2,0,3,L,R,12,Tropicana Field,2B
8,Souza Jr.,519306,Walk,543543.0,NaN,595281.0,519306.0,543543.0,595281.0,1,1,2,0,3,R,R,12,Tropicana Field,RF
9,Morrison,489149,Single,519306.0,543543.0,595281.0,489149.0,519306.0,NaN,1,1,2,2,3,L,R,12,Tropicana Field,1B
10,Beckham,542921,Lineout,489149.0,519306.0,NaN,489149.0,519306.0,NaN,1,2,0,0,3,R,R,12,Tropicana Field,SS
11,"Smith, M",605480,Strikeout,489149.0,519306.0,NaN,NaN,NaN,NaN,2,3,0,0,3,L,R,12,Tropicana Field,LF
12,Ellsbury,453056,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,2,0,3,L,R,12,Tropicana Field,CF
13,"Castro, S",516770,Single,NaN,NaN,NaN,516770.0,NaN,NaN,1,1,2,0,3,R,R,12,Tropicana Field,2B
14,Headley,452104,Single,516770.0,NaN,NaN,452104.0,516770.0,NaN,1,1,2,0,3,L,R,12,Tropicana Field,3B
15,Judge,592450,Double,452104.0,516770.0,NaN,NaN,592450.0,452104.0,1,1,2,1,3,R,R,12,Tropicana Field,RF
16,Torreyes,591720,Groundout,NaN,592450.0,452104.0,NaN,NaN,592450.0,1,2,1,1,3,R,R,12,Tropicana Field,SS
17,Gardner,458731,Groundout,NaN,NaN,592450.0,NaN,NaN,NaN,2,3,0,0,3,L,R,12,Tropicana Field,LF
18,"Norris, De",519083,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,2,0,3,R,R,12,Tropicana Field,C
19,"Dickerson, C",572816,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,2,0,3,L,R,12,Tropicana Field,DH
20,Kiermaier,595281,Walk,NaN,NaN,NaN,595281.0,NaN,NaN,2,2,2,0,3,L,R,12,Tropicana Field,CF
21,Longoria,446334,Home Run,595281.0,NaN,NaN,NaN,NaN,NaN,2,2,2,2,3,R,R,12,Tropicana Field,3B
22,"Miller, B",543543,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,L,R,12,Tropicana Field,2B
23,"Sanchez, G",596142,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,R,R,12,Tropicana Field,C
24,Bird,595885,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,L,R,12,Tropicana Field,1B
25,Holliday,407812,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,R,R,12,Tropicana Field,DH
26,Souza Jr.,519306,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,2,0,3,R,R,12,Tropicana Field,RF
27,Morrison,489149,Home Run,NaN,NaN,NaN,NaN,NaN,NaN,1,1,2,1,3,L,R,12,Tropicana Field,1B
28,Beckham,542921,Double,NaN,NaN,NaN,NaN,542921.0,NaN,1,1,1,0,3,R,R,12,Tropicana Field,SS
29,"Smith, M",605480,Single,NaN,542921.0,NaN,NaN,605480.0,NaN,1,1,1,1,3,L,R,12,Tropicana Field,LF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185565,Duvall,594807,Double,NaN,NaN,NaN,NaN,594807.0,NaN,1,1,1,0,3,R,L,17,Wrigley Field,LF
185566,Suarez,553993,Single,NaN,594807.0,NaN,553993.0,NaN,594807.0,1,1,1,0,3,R,L,17,Wrigley Field,3B
185567,Gennett,571697,Single,553993.0,NaN,594807.0,571697.0,553993.0,NaN,1,1,1,1,3,L,L,17,Wrigley Field,2B
185568,Ervin,640447,Lineout,571697.0,553993.0,NaN,571697.0,553993.0,NaN,1,2,0,0,3,R,L,17,Wrigley Field,RF
185569,Wallach,595453,Strikeout,571697.0,553993.0,NaN,NaN,NaN,NaN,2,3,0,0,3,R,L,17,Wrigley Field,UN
185570,"Davis, T",543089,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,R,R,17,Wrigley Field,UN
185571,Almora Jr.,546991,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,R,R,17,Wrigley Field,UN
185572,Freeman,502273,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,L,R,17,Wrigley Field,UN
185573,Kivlehan,623182,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,R,R,17,Wrigley Field,UN
185574,Hamilton,571740,Lineout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,L,R,17,Wrigley Field,CF
185575,Vincej,572227,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,R,R,17,Wrigley Field,UN
185576,Zobrist,450314,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,R,L,17,Wrigley Field,LF
185577,"Pena, Fe",570240,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,R,L,17,Wrigley Field,UN
185578,Schwarber,656941,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,L,L,17,Wrigley Field,UN
185579,Votto,458015,Double,NaN,NaN,NaN,NaN,458015.0,NaN,0,0,0,0,3,L,R,17,Wrigley Field,1B
185580,Duvall,594807,Strikeout,NaN,458015.0,NaN,NaN,458015.0,NaN,0,1,0,0,3,R,R,17,Wrigley Field,LF
185581,Suarez,553993,Flyout,NaN,458015.0,NaN,NaN,458015.0,NaN,1,2,0,0,3,R,R,17,Wrigley Field,3B
185582,Gennett,571697,Strikeout,NaN,458015.0,NaN,NaN,NaN,NaN,2,3,0,0,3,L,R,17,Wrigley Field,2B
185583,Caratini,605170,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,L,R,17,Wrigley Field,UN
185584,La Stella,600303,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,L,R,17,Wrigley Field,UN
185585,"Happ, I",664023,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,L,R,17,Wrigley Field,UN
185586,Ervin,640447,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,R,R,17,Wrigley Field,RF
185587,Wallach,595453,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,R,R,17,Wrigley Field,UN
185588,Winker,608385,Single,NaN,NaN,NaN,608385.0,NaN,NaN,2,2,0,0,3,L,R,17,Wrigley Field,UN
185589,Hamilton,571740,Walk,608385.0,NaN,NaN,571740.0,608385.0,NaN,2,2,0,0,3,L,R,17,Wrigley Field,CF
185590,Vincej,572227,Runner Out,571740.0,608385.0,NaN,NaN,NaN,NaN,2,3,0,0,3,R,R,17,Wrigley Field,UN
185591,"Davis, T",543089,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,1,0,3,R,R,17,Wrigley Field,UN
185592,Almora Jr.,546991,Home Run,NaN,NaN,NaN,NaN,NaN,NaN,1,1,1,1,3,R,R,17,Wrigley Field,UN
185593,Freeman,502273,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,L,R,17,Wrigley Field,UN
185594,Zobrist,450314,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,L,R,17,Wrigley Field,LF

In [ ]:
# 3.	Create three indicator variables (one for each base) to denote whether or not each base is occupied prior to the plate appearance

In [6]:
# Create indicator variables to determine whether base is occupied prior to plate appearance
RE17['Start1'] = np.where(pd.isnull(RE17['start1B']),0,1)
RE17['Start2'] = np.where(pd.isnull(RE17['start2B']),0,1)
RE17['Start3'] = np.where(pd.isnull(RE17['start3B']),0,1)

In [ ]:
# 4.	Create a “start state” variable to denote the base out state prior to each plate appearance

In [8]:
# Create starting base out state for plate appearance
RE17['Start_State'] = (RE17['Start1'].astype(str) + RE17['Start2'].astype(str) + RE17['Start3'].astype(str)+\
                       " " + RE17['startOuts'].astype(str))
RE17

,batterName,batterId,event,start1B,start2B,start3B,end1B,end2B,end3B,startOuts,...,outsInInning,stand,throws,venueId,stadium,batterPos,Start1,Start2,Start3,Start_State
0,Gardner,458731,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,3,L,R,12,Tropicana Field,LF,0,0,0,000 0
1,"Sanchez, G",596142,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,3,R,R,12,Tropicana Field,C,0,0,0,000 1
2,Bird,595885,Walk,NaN,NaN,NaN,595885.0,NaN,NaN,2,...,3,L,R,12,Tropicana Field,1B,0,0,0,000 2
3,Holliday,407812,Groundout,595885.0,NaN,NaN,NaN,NaN,NaN,2,...,3,R,R,12,Tropicana Field,DH,1,0,0,100 2
4,"Dickerson, C",572816,Single,NaN,NaN,NaN,572816.0,NaN,NaN,0,...,3,L,R,12,Tropicana Field,DH,0,0,0,000 0
5,Kiermaier,595281,Double,572816.0,NaN,NaN,NaN,595281.0,572816.0,0,...,3,L,R,12,Tropicana Field,CF,1,0,0,100 0
6,Longoria,446334,Sac Fly,NaN,595281.0,572816.0,NaN,595281.0,NaN,0,...,3,R,R,12,Tropicana Field,3B,0,1,1,011 0
7,"Miller, B",543543,Single,NaN,595281.0,NaN,543543.0,NaN,595281.0,1,...,3,L,R,12,Tropicana Field,2B,0,1,0,010 1
8,Souza Jr.,519306,Walk,543543.0,NaN,595281.0,519306.0,543543.0,595281.0,1,...,3,R,R,12,Tropicana Field,RF,1,0,1,101 1
9,Morrison,489149,Single,519306.0,543543.0,595281.0,489149.0,519306.0,NaN,1,...,3,L,R,12,Tropicana Field,1B,1,1,1,111 1
10,Beckham,542921,Lineout,489149.0,519306.0,NaN,489149.0,519306.0,NaN,1,...,3,R,R,12,Tropicana Field,SS,1,1,0,110 1
11,"Smith, M",605480,Strikeout,489149.0,519306.0,NaN,NaN,NaN,NaN,2,...,3,L,R,12,Tropicana Field,LF,1,1,0,110 2
12,Ellsbury,453056,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,3,L,R,12,Tropicana Field,CF,0,0,0,000 0
13,"Castro, S",516770,Single,NaN,NaN,NaN,516770.0,NaN,NaN,1,...,3,R,R,12,Tropicana Field,2B,0,0,0,000 1
14,Headley,452104,Single,516770.0,NaN,NaN,452104.0,516770.0,NaN,1,...,3,L,R,12,Tropicana Field,3B,1,0,0,100 1
15,Judge,592450,Double,452104.0,516770.0,NaN,NaN,592450.0,452104.0,1,...,3,R,R,12,Tropicana Field,RF,1,1,0,110 1
16,Torreyes,591720,Groundout,NaN,592450.0,452104.0,NaN,NaN,592450.0,1,...,3,R,R,12,Tropicana Field,SS,0,1,1,011 1
17,Gardner,458731,Groundout,NaN,NaN,592450.0,NaN,NaN,NaN,2,...,3,L,R,12,Tropicana Field,LF,0,0,1,001 2
18,"Norris, De",519083,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,3,R,R,12,Tropicana Field,C,0,0,0,000 0
19,"Dickerson, C",572816,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,3,L,R,12,Tropicana Field,DH,0,0,0,000 1
20,Kiermaier,595281,Walk,NaN,NaN,NaN,595281.0,NaN,NaN,2,...,3,L,R,12,Tropicana Field,CF,0,0,0,000 2
21,Longoria,446334,Home Run,595281.0,NaN,NaN,NaN,NaN,NaN,2,...,3,R,R,12,Tropicana Field,3B,1,0,0,100 2
22,"Miller, B",543543,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,3,L,R,12,Tropicana Field,2B,0,0,0,000 2
23,"Sanchez, G",596142,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,3,R,R,12,Tropicana Field,C,0,0,0,000 0
24,Bird,595885,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,3,L,R,12,Tropicana Field,1B,0,0,0,000 1
25,Holliday,407812,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,3,R,R,12,Tropicana Field,DH,0,0,0,000 2
26,Souza Jr.,519306,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,3,R,R,12,Tropicana Field,RF,0,0,0,000 0
27,Morrison,489149,Home Run,NaN,NaN,NaN,NaN,NaN,NaN,1,...,3,L,R,12,Tropicana Field,1B,0,0,0,000 1
28,Beckham,542921,Double,NaN,NaN,NaN,NaN,542921.0,NaN,1,...,3,R,R,12,Tropicana Field,SS,0,0,0,000 1
29,"Smith, M",605480,Single,NaN,542921.0,NaN,NaN,605480.0,NaN,1,...,3,L,R,12,Tropicana Field,LF,0,1,0,010 1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185565,Duvall,594807,Double,NaN,NaN,NaN,NaN,594807.0,NaN,1,...,3,R,L,17,Wrigley Field,LF,0,0,0,000 1
185566,Suarez,553993,Single,NaN,594807.0,NaN,553993.0,NaN,594807.0,1,...,3,R,L,17,Wrigley Field,3B,0,1,0,010 1
185567,Gennett,571697,Single,553993.0,NaN,594807.0,571697.0,553993.0,NaN,1,...,3,L,L,17,Wrigley Field,2B,1,0,1,101 1
185568,Ervin,640447,Lineout,571697.0,553993.0,NaN,571697.0,553993.0,NaN,1,...,3,R,L,17,Wrigley Field,RF,1,1,0,110 1
185569,Wallach,595453,Strikeout,571697.0,553993.0,NaN,NaN,NaN,NaN,2,...,3,R,L,17,Wrigley Field,UN,1,1,0,110 2
185570,"Davis, T",543089,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,3,R,R,17,Wrigley Field,UN,0,0,0,000 0
185571,Almora Jr.,546991,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,3,R,R,17,Wrigley Field,UN,0,0,0,000 1
185572,Freeman,502273,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,3,L,R,17,Wrigley Field,UN,0,0,0,000 2
185573,Kivlehan,623182,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,3,R,R,17,Wrigley Field,UN,0,0,0,000 0
185574,Hamilton,571740,Lineout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,3,L,R,17,Wrigley Field,CF,0,0,0,000 1
185575,Vincej,572227,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,3,R,R,17,Wrigley Field,UN,0,0,0,000 2
185576,Zobrist,450314,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,3,R,L,17,Wrigley Field,LF,0,0,0,000 0
185577,"Pena, Fe",570240,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,3,R,L,17,Wrigley Field,UN,0,0,0,000 1
185578,Schwarber,656941,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,3,L,L,17,Wrigley Field,UN,0,0,0,000 2
185579,Votto,458015,Double,NaN,NaN,NaN,NaN,458015.0,NaN,0,...,3,L,R,17,Wrigley Field,1B,0,0,0,000 0
185580,Duvall,594807,Strikeout,NaN,458015.0,NaN,NaN,458015.0,NaN,0,...,3,R,R,17,Wrigley Field,LF,0,1,0,010 0
185581,Suarez,553993,Flyout,NaN,458015.0,NaN,NaN,458015.0,NaN,1,...,3,R,R,17,Wrigley Field,3B,0,1,0,010 1
185582,Gennett,571697,Strikeout,NaN,458015.0,NaN,NaN,NaN,NaN,2,...,3,L,R,17,Wrigley Field,2B,0,1,0,010 2
185583,Caratini,605170,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,3,L,R,17,Wrigley Field,UN,0,0,0,000 0
185584,La Stella,600303,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,3,L,R,17,Wrigley Field,UN,0,0,0,000 1
185585,"Happ, I",664023,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,3,L,R,17,Wrigley Field,UN,0,0,0,000 2
185586,Ervin,640447,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,3,R,R,17,Wrigley Field,RF,0,0,0,000 0
185587,Wallach,595453,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,3,R,R,17,Wrigley Field,UN,0,0,0,000 1
185588,Winker,608385,Single,NaN,NaN,NaN,608385.0,NaN,NaN,2,...,3,L,R,17,Wrigley Field,UN,0,0,0,000 2
185589,Hamilton,571740,Walk,608385.0,NaN,NaN,571740.0,608385.0,NaN,2,...,3,L,R,17,Wrigley Field,CF,1,0,0,100 2
185590,Vincej,572227,Runner Out,571740.0,608385.0,NaN,NaN,NaN,NaN,2,...,3,R,R,17,Wrigley Field,UN,1,1,0,110 2
185591,"Davis, T",543089,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,3,R,R,17,Wrigley Field,UN,0,0,0,000 0
185592,Almora Jr.,546991,Home Run,NaN,NaN,NaN,NaN,NaN,NaN,1,...,3,R,R,17,Wrigley Field,UN,0,0,0,000 1
185593,Freeman,502273,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,3,L,R,17,Wrigley Field,UN,0,0,0,000 1
185594,Zobrist,450314,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,3,L,R,17,Wrigley Field,LF,0,0,0,000 2

In [ ]:
# 5.	Create three indicator variables (one for each base) to denote whether or not each base is occupied after the plate appearance

In [9]:
# Create indicator variables to determine whether base is occupied after plate appearance
RE17['End1'] = np.where(pd.isnull(RE17['end1B']),0,1)
RE17['End2'] = np.where(pd.isnull(RE17['end2B']),0,1)
RE17['End3'] = np.where(pd.isnull(RE17['end3B']),0,1)

In [ ]:
# 6.	Create an “end state” variable to denote the base out state after each plate appearance

In [10]:
# Create ending base out state for plate appearance
RE17['End_State'] = (RE17['End1'].astype(str) + RE17['End2'].astype(str) + RE17['End3'].astype(str)+\
                     " " + RE17['endOuts'].astype(str))
RE17

,batterName,batterId,event,start1B,start2B,start3B,end1B,end2B,end3B,startOuts,...,stadium,batterPos,Start1,Start2,Start3,Start_State,End1,End2,End3,End_State
0,Gardner,458731,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,Tropicana Field,LF,0,0,0,000 0,0,0,0,000 1
1,"Sanchez, G",596142,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,Tropicana Field,C,0,0,0,000 1,0,0,0,000 2
2,Bird,595885,Walk,NaN,NaN,NaN,595885.0,NaN,NaN,2,...,Tropicana Field,1B,0,0,0,000 2,1,0,0,100 2
3,Holliday,407812,Groundout,595885.0,NaN,NaN,NaN,NaN,NaN,2,...,Tropicana Field,DH,1,0,0,100 2,0,0,0,000 3
4,"Dickerson, C",572816,Single,NaN,NaN,NaN,572816.0,NaN,NaN,0,...,Tropicana Field,DH,0,0,0,000 0,1,0,0,100 0
5,Kiermaier,595281,Double,572816.0,NaN,NaN,NaN,595281.0,572816.0,0,...,Tropicana Field,CF,1,0,0,100 0,0,1,1,011 0
6,Longoria,446334,Sac Fly,NaN,595281.0,572816.0,NaN,595281.0,NaN,0,...,Tropicana Field,3B,0,1,1,011 0,0,1,0,010 1
7,"Miller, B",543543,Single,NaN,595281.0,NaN,543543.0,NaN,595281.0,1,...,Tropicana Field,2B,0,1,0,010 1,1,0,1,101 1
8,Souza Jr.,519306,Walk,543543.0,NaN,595281.0,519306.0,543543.0,595281.0,1,...,Tropicana Field,RF,1,0,1,101 1,1,1,1,111 1
9,Morrison,489149,Single,519306.0,543543.0,595281.0,489149.0,519306.0,NaN,1,...,Tropicana Field,1B,1,1,1,111 1,1,1,0,110 1
10,Beckham,542921,Lineout,489149.0,519306.0,NaN,489149.0,519306.0,NaN,1,...,Tropicana Field,SS,1,1,0,110 1,1,1,0,110 2
11,"Smith, M",605480,Strikeout,489149.0,519306.0,NaN,NaN,NaN,NaN,2,...,Tropicana Field,LF,1,1,0,110 2,0,0,0,000 3
12,Ellsbury,453056,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,Tropicana Field,CF,0,0,0,000 0,0,0,0,000 1
13,"Castro, S",516770,Single,NaN,NaN,NaN,516770.0,NaN,NaN,1,...,Tropicana Field,2B,0,0,0,000 1,1,0,0,100 1
14,Headley,452104,Single,516770.0,NaN,NaN,452104.0,516770.0,NaN,1,...,Tropicana Field,3B,1,0,0,100 1,1,1,0,110 1
15,Judge,592450,Double,452104.0,516770.0,NaN,NaN,592450.0,452104.0,1,...,Tropicana Field,RF,1,1,0,110 1,0,1,1,011 1
16,Torreyes,591720,Groundout,NaN,592450.0,452104.0,NaN,NaN,592450.0,1,...,Tropicana Field,SS,0,1,1,011 1,0,0,1,001 2
17,Gardner,458731,Groundout,NaN,NaN,592450.0,NaN,NaN,NaN,2,...,Tropicana Field,LF,0,0,1,001 2,0,0,0,000 3
18,"Norris, De",519083,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,Tropicana Field,C,0,0,0,000 0,0,0,0,000 1
19,"Dickerson, C",572816,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,Tropicana Field,DH,0,0,0,000 1,0,0,0,000 2
20,Kiermaier,595281,Walk,NaN,NaN,NaN,595281.0,NaN,NaN,2,...,Tropicana Field,CF,0,0,0,000 2,1,0,0,100 2
21,Longoria,446334,Home Run,595281.0,NaN,NaN,NaN,NaN,NaN,2,...,Tropicana Field,3B,1,0,0,100 2,0,0,0,000 2
22,"Miller, B",543543,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,Tropicana Field,2B,0,0,0,000 2,0,0,0,000 3
23,"Sanchez, G",596142,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,Tropicana Field,C,0,0,0,000 0,0,0,0,000 1
24,Bird,595885,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,Tropicana Field,1B,0,0,0,000 1,0,0,0,000 2
25,Holliday,407812,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,Tropicana Field,DH,0,0,0,000 2,0,0,0,000 3
26,Souza Jr.,519306,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,Tropicana Field,RF,0,0,0,000 0,0,0,0,000 1
27,Morrison,489149,Home Run,NaN,NaN,NaN,NaN,NaN,NaN,1,...,Tropicana Field,1B,0,0,0,000 1,0,0,0,000 1
28,Beckham,542921,Double,NaN,NaN,NaN,NaN,542921.0,NaN,1,...,Tropicana Field,SS,0,0,0,000 1,0,1,0,010 1
29,"Smith, M",605480,Single,NaN,542921.0,NaN,NaN,605480.0,NaN,1,...,Tropicana Field,LF,0,1,0,010 1,0,1,0,010 1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185565,Duvall,594807,Double,NaN,NaN,NaN,NaN,594807.0,NaN,1,...,Wrigley Field,LF,0,0,0,000 1,0,1,0,010 1
185566,Suarez,553993,Single,NaN,594807.0,NaN,553993.0,NaN,594807.0,1,...,Wrigley Field,3B,0,1,0,010 1,1,0,1,101 1
185567,Gennett,571697,Single,553993.0,NaN,594807.0,571697.0,553993.0,NaN,1,...,Wrigley Field,2B,1,0,1,101 1,1,1,0,110 1
185568,Ervin,640447,Lineout,571697.0,553993.0,NaN,571697.0,553993.0,NaN,1,...,Wrigley Field,RF,1,1,0,110 1,1,1,0,110 2
185569,Wallach,595453,Strikeout,571697.0,553993.0,NaN,NaN,NaN,NaN,2,...,Wrigley Field,UN,1,1,0,110 2,0,0,0,000 3
185570,"Davis, T",543089,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,Wrigley Field,UN,0,0,0,000 0,0,0,0,000 1
185571,Almora Jr.,546991,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,Wrigley Field,UN,0,0,0,000 1,0,0,0,000 2
185572,Freeman,502273,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,Wrigley Field,UN,0,0,0,000 2,0,0,0,000 3
185573,Kivlehan,623182,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,Wrigley Field,UN,0,0,0,000 0,0,0,0,000 1
185574,Hamilton,571740,Lineout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,Wrigley Field,CF,0,0,0,000 1,0,0,0,000 2
185575,Vincej,572227,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,Wrigley Field,UN,0,0,0,000 2,0,0,0,000 3
185576,Zobrist,450314,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,Wrigley Field,LF,0,0,0,000 0,0,0,0,000 1
185577,"Pena, Fe",570240,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,Wrigley Field,UN,0,0,0,000 1,0,0,0,000 2
185578,Schwarber,656941,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,Wrigley Field,UN,0,0,0,000 2,0,0,0,000 3
185579,Votto,458015,Double,NaN,NaN,NaN,NaN,458015.0,NaN,0,...,Wrigley Field,1B,0,0,0,000 0,0,1,0,010 0
185580,Duvall,594807,Strikeout,NaN,458015.0,NaN,NaN,458015.0,NaN,0,...,Wrigley Field,LF,0,1,0,010 0,0,1,0,010 1
185581,Suarez,553993,Flyout,NaN,458015.0,NaN,NaN,458015.0,NaN,1,...,Wrigley Field,3B,0,1,0,010 1,0,1,0,010 2
185582,Gennett,571697,Strikeout,NaN,458015.0,NaN,NaN,NaN,NaN,2,...,Wrigley Field,2B,0,1,0,010 2,0,0,0,000 3
185583,Caratini,605170,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,Wrigley Field,UN,0,0,0,000 0,0,0,0,000 1
185584,La Stella,600303,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,Wrigley Field,UN,0,0,0,000 1,0,0,0,000 2
185585,"Happ, I",664023,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,Wrigley Field,UN,0,0,0,000 2,0,0,0,000 3
185586,Ervin,640447,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,Wrigley Field,RF,0,0,0,000 0,0,0,0,000 1
185587,Wallach,595453,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,Wrigley Field,UN,0,0,0,000 1,0,0,0,000 2
185588,Winker,608385,Single,NaN,NaN,NaN,608385.0,NaN,NaN,2,...,Wrigley Field,UN,0,0,0,000 2,1,0,0,100 2
185589,Hamilton,571740,Walk,608385.0,NaN,NaN,571740.0,608385.0,NaN,2,...,Wrigley Field,CF,1,0,0,100 2,1,1,0,110 2
185590,Vincej,572227,Runner Out,571740.0,608385.0,NaN,NaN,NaN,NaN,2,...,Wrigley Field,UN,1,1,0,110 2,0,0,0,000 3
185591,"Davis, T",543089,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,Wrigley Field,UN,0,0,0,000 0,0,0,0,000 1
185592,Almora Jr.,546991,Home Run,NaN,NaN,NaN,NaN,NaN,NaN,1,...,Wrigley Field,UN,0,0,0,000 1,0,0,0,000 1
185593,Freeman,502273,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,Wrigley Field,UN,0,0,0,000 1,0,0,0,000 2
185594,Zobrist,450314,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,Wrigley Field,LF,0,0,0,000 2,0,0,0,000 3

In [ ]:
# 7.	Restrict data to plays where either there is a change in state/runs scored and innings in which there were exactly 3 outs recorded

In [11]:
# Restrict data to plays where either there is a change in state or runs scored and innings that had exactly 3 outs
RE17 = RE17[((RE17.Start_State != RE17.End_State) | (RE17.runsOnPlay > 0)) & (RE17.outsInInning == 3)]
display(RE17)

,batterName,batterId,event,start1B,start2B,start3B,end1B,end2B,end3B,startOuts,...,stadium,batterPos,Start1,Start2,Start3,Start_State,End1,End2,End3,End_State
0,Gardner,458731,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,Tropicana Field,LF,0,0,0,000 0,0,0,0,000 1
1,"Sanchez, G",596142,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,Tropicana Field,C,0,0,0,000 1,0,0,0,000 2
2,Bird,595885,Walk,NaN,NaN,NaN,595885.0,NaN,NaN,2,...,Tropicana Field,1B,0,0,0,000 2,1,0,0,100 2
3,Holliday,407812,Groundout,595885.0,NaN,NaN,NaN,NaN,NaN,2,...,Tropicana Field,DH,1,0,0,100 2,0,0,0,000 3
4,"Dickerson, C",572816,Single,NaN,NaN,NaN,572816.0,NaN,NaN,0,...,Tropicana Field,DH,0,0,0,000 0,1,0,0,100 0
5,Kiermaier,595281,Double,572816.0,NaN,NaN,NaN,595281.0,572816.0,0,...,Tropicana Field,CF,1,0,0,100 0,0,1,1,011 0
6,Longoria,446334,Sac Fly,NaN,595281.0,572816.0,NaN,595281.0,NaN,0,...,Tropicana Field,3B,0,1,1,011 0,0,1,0,010 1
7,"Miller, B",543543,Single,NaN,595281.0,NaN,543543.0,NaN,595281.0,1,...,Tropicana Field,2B,0,1,0,010 1,1,0,1,101 1
8,Souza Jr.,519306,Walk,543543.0,NaN,595281.0,519306.0,543543.0,595281.0,1,...,Tropicana Field,RF,1,0,1,101 1,1,1,1,111 1
9,Morrison,489149,Single,519306.0,543543.0,595281.0,489149.0,519306.0,NaN,1,...,Tropicana Field,1B,1,1,1,111 1,1,1,0,110 1
10,Beckham,542921,Lineout,489149.0,519306.0,NaN,489149.0,519306.0,NaN,1,...,Tropicana Field,SS,1,1,0,110 1,1,1,0,110 2
11,"Smith, M",605480,Strikeout,489149.0,519306.0,NaN,NaN,NaN,NaN,2,...,Tropicana Field,LF,1,1,0,110 2,0,0,0,000 3
12,Ellsbury,453056,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,Tropicana Field,CF,0,0,0,000 0,0,0,0,000 1
13,"Castro, S",516770,Single,NaN,NaN,NaN,516770.0,NaN,NaN,1,...,Tropicana Field,2B,0,0,0,000 1,1,0,0,100 1
14,Headley,452104,Single,516770.0,NaN,NaN,452104.0,516770.0,NaN,1,...,Tropicana Field,3B,1,0,0,100 1,1,1,0,110 1
15,Judge,592450,Double,452104.0,516770.0,NaN,NaN,592450.0,452104.0,1,...,Tropicana Field,RF,1,1,0,110 1,0,1,1,011 1
16,Torreyes,591720,Groundout,NaN,592450.0,452104.0,NaN,NaN,592450.0,1,...,Tropicana Field,SS,0,1,1,011 1,0,0,1,001 2
17,Gardner,458731,Groundout,NaN,NaN,592450.0,NaN,NaN,NaN,2,...,Tropicana Field,LF,0,0,1,001 2,0,0,0,000 3
18,"Norris, De",519083,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,Tropicana Field,C,0,0,0,000 0,0,0,0,000 1
19,"Dickerson, C",572816,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,Tropicana Field,DH,0,0,0,000 1,0,0,0,000 2
20,Kiermaier,595281,Walk,NaN,NaN,NaN,595281.0,NaN,NaN,2,...,Tropicana Field,CF,0,0,0,000 2,1,0,0,100 2
21,Longoria,446334,Home Run,595281.0,NaN,NaN,NaN,NaN,NaN,2,...,Tropicana Field,3B,1,0,0,100 2,0,0,0,000 2
22,"Miller, B",543543,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,Tropicana Field,2B,0,0,0,000 2,0,0,0,000 3
23,"Sanchez, G",596142,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,Tropicana Field,C,0,0,0,000 0,0,0,0,000 1
24,Bird,595885,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,Tropicana Field,1B,0,0,0,000 1,0,0,0,000 2
25,Holliday,407812,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,Tropicana Field,DH,0,0,0,000 2,0,0,0,000 3
26,Souza Jr.,519306,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,Tropicana Field,RF,0,0,0,000 0,0,0,0,000 1
27,Morrison,489149,Home Run,NaN,NaN,NaN,NaN,NaN,NaN,1,...,Tropicana Field,1B,0,0,0,000 1,0,0,0,000 1
28,Beckham,542921,Double,NaN,NaN,NaN,NaN,542921.0,NaN,1,...,Tropicana Field,SS,0,0,0,000 1,0,1,0,010 1
29,"Smith, M",605480,Single,NaN,542921.0,NaN,NaN,605480.0,NaN,1,...,Tropicana Field,LF,0,1,0,010 1,0,1,0,010 1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185565,Duvall,594807,Double,NaN,NaN,NaN,NaN,594807.0,NaN,1,...,Wrigley Field,LF,0,0,0,000 1,0,1,0,010 1
185566,Suarez,553993,Single,NaN,594807.0,NaN,553993.0,NaN,594807.0,1,...,Wrigley Field,3B,0,1,0,010 1,1,0,1,101 1
185567,Gennett,571697,Single,553993.0,NaN,594807.0,571697.0,553993.0,NaN,1,...,Wrigley Field,2B,1,0,1,101 1,1,1,0,110 1
185568,Ervin,640447,Lineout,571697.0,553993.0,NaN,571697.0,553993.0,NaN,1,...,Wrigley Field,RF,1,1,0,110 1,1,1,0,110 2
185569,Wallach,595453,Strikeout,571697.0,553993.0,NaN,NaN,NaN,NaN,2,...,Wrigley Field,UN,1,1,0,110 2,0,0,0,000 3
185570,"Davis, T",543089,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,Wrigley Field,UN,0,0,0,000 0,0,0,0,000 1
185571,Almora Jr.,546991,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,Wrigley Field,UN,0,0,0,000 1,0,0,0,000 2
185572,Freeman,502273,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,Wrigley Field,UN,0,0,0,000 2,0,0,0,000 3
185573,Kivlehan,623182,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,Wrigley Field,UN,0,0,0,000 0,0,0,0,000 1
185574,Hamilton,571740,Lineout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,Wrigley Field,CF,0,0,0,000 1,0,0,0,000 2
185575,Vincej,572227,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,Wrigley Field,UN,0,0,0,000 2,0,0,0,000 3
185576,Zobrist,450314,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,Wrigley Field,LF,0,0,0,000 0,0,0,0,000 1
185577,"Pena, Fe",570240,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,Wrigley Field,UN,0,0,0,000 1,0,0,0,000 2
185578,Schwarber,656941,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,Wrigley Field,UN,0,0,0,000 2,0,0,0,000 3
185579,Votto,458015,Double,NaN,NaN,NaN,NaN,458015.0,NaN,0,...,Wrigley Field,1B,0,0,0,000 0,0,1,0,010 0
185580,Duvall,594807,Strikeout,NaN,458015.0,NaN,NaN,458015.0,NaN,0,...,Wrigley Field,LF,0,1,0,010 0,0,1,0,010 1
185581,Suarez,553993,Flyout,NaN,458015.0,NaN,NaN,458015.0,NaN,1,...,Wrigley Field,3B,0,1,0,010 1,0,1,0,010 2
185582,Gennett,571697,Strikeout,NaN,458015.0,NaN,NaN,NaN,NaN,2,...,Wrigley Field,2B,0,1,0,010 2,0,0,0,000 3
185583,Caratini,605170,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,Wrigley Field,UN,0,0,0,000 0,0,0,0,000 1
185584,La Stella,600303,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,Wrigley Field,UN,0,0,0,000 1,0,0,0,000 2
185585,"Happ, I",664023,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,Wrigley Field,UN,0,0,0,000 2,0,0,0,000 3
185586,Ervin,640447,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,Wrigley Field,RF,0,0,0,000 0,0,0,0,000 1
185587,Wallach,595453,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,Wrigley Field,UN,0,0,0,000 1,0,0,0,000 2
185588,Winker,608385,Single,NaN,NaN,NaN,608385.0,NaN,NaN,2,...,Wrigley Field,UN,0,0,0,000 2,1,0,0,100 2
185589,Hamilton,571740,Walk,608385.0,NaN,NaN,571740.0,608385.0,NaN,2,...,Wrigley Field,CF,1,0,0,100 2,1,1,0,110 2
185590,Vincej,572227,Runner Out,571740.0,608385.0,NaN,NaN,NaN,NaN,2,...,Wrigley Field,UN,1,1,0,110 2,0,0,0,000 3
185591,"Davis, T",543089,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,Wrigley Field,UN,0,0,0,000 0,0,0,0,000 1
185592,Almora Jr.,546991,Home Run,NaN,NaN,NaN,NaN,NaN,NaN,1,...,Wrigley Field,UN,0,0,0,000 1,0,0,0,000 1
185593,Freeman,502273,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,Wrigley Field,UN,0,0,0,000 1,0,0,0,000 2
185594,Zobrist,450314,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,Wrigley Field,LF,0,0,0,000 2,0,0,0,000 3

In [ ]:
# 8.	Calculate run expectancy by starting state and merge this into play by play data

In [12]:
# Calculate run expectancy by starting state and merge into play by play data
Start_RunExp = RE17.groupby(['Start_State'])['runsFuture'].mean().reset_index().rename(columns={'runsFuture':'Start_RE'})
RE17 = pd.merge(RE17, Start_RunExp, on=['Start_State'], how='left')
display(RE17)

,batterName,batterId,event,start1B,start2B,start3B,end1B,end2B,end3B,startOuts,...,batterPos,Start1,Start2,Start3,Start_State,End1,End2,End3,End_State,Start_RE
0,Gardner,458731,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,LF,0,0,0,000 0,0,0,0,000 1,0.516375
1,"Sanchez, G",596142,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,C,0,0,0,000 1,0,0,0,000 2,0.272176
2,Bird,595885,Walk,NaN,NaN,NaN,595885.0,NaN,NaN,2,...,1B,0,0,0,000 2,1,0,0,100 2,0.108038
3,Holliday,407812,Groundout,595885.0,NaN,NaN,NaN,NaN,NaN,2,...,DH,1,0,0,100 2,0,0,0,000 3,0.225365
4,"Dickerson, C",572816,Single,NaN,NaN,NaN,572816.0,NaN,NaN,0,...,DH,0,0,0,000 0,1,0,0,100 0,0.516375
5,Kiermaier,595281,Double,572816.0,NaN,NaN,NaN,595281.0,572816.0,0,...,CF,1,0,0,100 0,0,1,1,011 0,0.912921
6,Longoria,446334,Sac Fly,NaN,595281.0,572816.0,NaN,595281.0,NaN,0,...,3B,0,1,1,011 0,0,1,0,010 1,2.051376
7,"Miller, B",543543,Single,NaN,595281.0,NaN,543543.0,NaN,595281.0,1,...,2B,0,1,0,010 1,1,0,1,101 1,0.711650
8,Souza Jr.,519306,Walk,543543.0,NaN,595281.0,519306.0,543543.0,595281.0,1,...,RF,1,0,1,101 1,1,1,1,111 1,1.215306
9,Morrison,489149,Single,519306.0,543543.0,595281.0,489149.0,519306.0,NaN,1,...,1B,1,1,1,111 1,1,1,0,110 1,1.635608
10,Beckham,542921,Lineout,489149.0,519306.0,NaN,489149.0,519306.0,NaN,1,...,SS,1,1,0,110 1,1,1,0,110 2,0.947424
11,"Smith, M",605480,Strikeout,489149.0,519306.0,NaN,NaN,NaN,NaN,2,...,LF,1,1,0,110 2,0,0,0,000 3,0.449782
12,Ellsbury,453056,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,CF,0,0,0,000 0,0,0,0,000 1,0.516375
13,"Castro, S",516770,Single,NaN,NaN,NaN,516770.0,NaN,NaN,1,...,2B,0,0,0,000 1,1,0,0,100 1,0.272176
14,Headley,452104,Single,516770.0,NaN,NaN,452104.0,516770.0,NaN,1,...,3B,1,0,0,100 1,1,1,0,110 1,0.524904
15,Judge,592450,Double,452104.0,516770.0,NaN,NaN,592450.0,452104.0,1,...,RF,1,1,0,110 1,0,1,1,011 1,0.947424
16,Torreyes,591720,Groundout,NaN,592450.0,452104.0,NaN,NaN,592450.0,1,...,SS,0,1,1,011 1,0,0,1,001 2,1.517131
17,Gardner,458731,Groundout,NaN,NaN,592450.0,NaN,NaN,NaN,2,...,LF,0,0,1,001 2,0,0,0,000 3,0.381186
18,"Norris, De",519083,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,C,0,0,0,000 0,0,0,0,000 1,0.516375
19,"Dickerson, C",572816,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,DH,0,0,0,000 1,0,0,0,000 2,0.272176
20,Kiermaier,595281,Walk,NaN,NaN,NaN,595281.0,NaN,NaN,2,...,CF,0,0,0,000 2,1,0,0,100 2,0.108038
21,Longoria,446334,Home Run,595281.0,NaN,NaN,NaN,NaN,NaN,2,...,3B,1,0,0,100 2,0,0,0,000 2,0.225365
22,"Miller, B",543543,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,2B,0,0,0,000 2,0,0,0,000 3,0.108038
23,"Sanchez, G",596142,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,C,0,0,0,000 0,0,0,0,000 1,0.516375
24,Bird,595885,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,1B,0,0,0,000 1,0,0,0,000 2,0.272176
25,Holliday,407812,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,DH,0,0,0,000 2,0,0,0,000 3,0.108038
26,Souza Jr.,519306,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,RF,0,0,0,000 0,0,0,0,000 1,0.516375
27,Morrison,489149,Home Run,NaN,NaN,NaN,NaN,NaN,NaN,1,...,1B,0,0,0,000 1,0,0,0,000 1,0.272176
28,Beckham,542921,Double,NaN,NaN,NaN,NaN,542921.0,NaN,1,...,SS,0,0,0,000 1,0,1,0,010 1,0.272176
29,"Smith, M",605480,Single,NaN,542921.0,NaN,NaN,605480.0,NaN,1,...,LF,0,1,0,010 1,0,1,0,010 1,0.711650
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184721,Duvall,594807,Double,NaN,NaN,NaN,NaN,594807.0,NaN,1,...,LF,0,0,0,000 1,0,1,0,010 1,0.272176
184722,Suarez,553993,Single,NaN,594807.0,NaN,553993.0,NaN,594807.0,1,...,3B,0,1,0,010 1,1,0,1,101 1,0.711650
184723,Gennett,571697,Single,553993.0,NaN,594807.0,571697.0,553993.0,NaN,1,...,2B,1,0,1,101 1,1,1,0,110 1,1.215306
184724,Ervin,640447,Lineout,571697.0,553993.0,NaN,571697.0,553993.0,NaN,1,...,RF,1,1,0,110 1,1,1,0,110 2,0.947424
184725,Wallach,595453,Strikeout,571697.0,553993.0,NaN,NaN,NaN,NaN,2,...,UN,1,1,0,110 2,0,0,0,000 3,0.449782
184726,"Davis, T",543089,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,UN,0,0,0,000 0,0,0,0,000 1,0.516375
184727,Almora Jr.,546991,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,UN,0,0,0,000 1,0,0,0,000 2,0.272176
184728,Freeman,502273,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,UN,0,0,0,000 2,0,0,0,000 3,0.108038
184729,Kivlehan,623182,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,UN,0,0,0,000 0,0,0,0,000 1,0.516375
184730,Hamilton,571740,Lineout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,CF,0,0,0,000 1,0,0,0,000 2,0.272176
184731,Vincej,572227,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,UN,0,0,0,000 2,0,0,0,000 3,0.108038
184732,Zobrist,450314,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,LF,0,0,0,000 0,0,0,0,000 1,0.516375
184733,"Pena, Fe",570240,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,UN,0,0,0,000 1,0,0,0,000 2,0.272176
184734,Schwarber,656941,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,UN,0,0,0,000 2,0,0,0,000 3,0.108038
184735,Votto,458015,Double,NaN,NaN,NaN,NaN,458015.0,NaN,0,...,1B,0,0,0,000 0,0,1,0,010 0,0.516375
184736,Duvall,594807,Strikeout,NaN,458015.0,NaN,NaN,458015.0,NaN,0,...,LF,0,1,0,010 0,0,1,0,010 1,1.154829
184737,Suarez,553993,Flyout,NaN,458015.0,NaN,NaN,458015.0,NaN,1,...,3B,0,1,0,010 1,0,1,0,010 2,0.711650
184738,Gennett,571697,Strikeout,NaN,458015.0,NaN,NaN,NaN,NaN,2,...,2B,0,1,0,010 2,0,0,0,000 3,0.336702
184739,Caratini,605170,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,UN,0,0,0,000 0,0,0,0,000 1,0.516375
184740,La Stella,600303,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,UN,0,0,0,000 1,0,0,0,000 2,0.272176
184741,"Happ, I",664023,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,UN,0,0,0,000 2,0,0,0,000 3,0.108038
184742,Ervin,640447,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,RF,0,0,0,000 0,0,0,0,000 1,0.516375
184743,Wallach,595453,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,UN,0,0,0,000 1,0,0,0,000 2,0.272176
184744,Winker,608385,Single,NaN,NaN,NaN,608385.0,NaN,NaN,2,...,UN,0,0,0,000 2,1,0,0,100 2,0.108038
184745,Hamilton,571740,Walk,608385.0,NaN,NaN,571740.0,608385.0,NaN,2,...,CF,1,0,0,100 2,1,1,0,110 2,0.225365
184746,Vincej,572227,Runner Out,571740.0,608385.0,NaN,NaN,NaN,NaN,2,...,UN,1,1,0,110 2,0,0,0,000 3,0.449782
184747,"Davis, T",543089,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,UN,0,0,0,000 0,0,0,0,000 1,0.516375
184748,Almora Jr.,546991,Home Run,NaN,NaN,NaN,NaN,NaN,NaN,1,...,UN,0,0,0,000 1,0,0,0,000 1,0.272176
184749,Freeman,502273,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,UN,0,0,0,000 1,0,0,0,000 2,0.272176
184750,Zobrist,450314,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,LF,0,0,0,000 2,0,0,0,000 3,0.108038

In [ ]:
# 9.	Using the run expectancy data by starting state, create a variable to denote run expectancy by ending state 
# (in addition, make sure to include the base out states for which there are 3 outs with run expectancies of 0 to the run expectancy by ending state data)

In [13]:
# Code run expectancy values by end state using start state run expectancy including end states with 3 outs
Base_State_3 = [pd.Series(['000 3', 0], index=Start_RunExp.columns),
                pd.Series(['001 3', 0], index=Start_RunExp.columns),
                pd.Series(['010 3', 0], index=Start_RunExp.columns),
                pd.Series(['011 3', 0], index=Start_RunExp.columns),
                pd.Series(['100 3', 0], index=Start_RunExp.columns),
                pd.Series(['101 3', 0], index=Start_RunExp.columns),
                pd.Series(['110 3', 0], index=Start_RunExp.columns),
                pd.Series(['111 3', 0], index=Start_RunExp.columns)]

Start_RunExp = Start_RunExp.append(Base_State_3, ignore_index=True)

End_RunExp = Start_RunExp.rename(columns={'Start_State':'End_State', 'Start_RE':'End_RE'})

display(End_RunExp)

   End_State    End_RE
0      000 0  0.516375
1      000 1  0.272176
2      000 2  0.108038
3      001 0  1.436482
4      001 1  0.953586
5      001 2  0.381186
6      010 0  1.154829
7      010 1  0.711650
8      010 2  0.336702
9      011 0  2.051376
10     011 1  1.517131
11     011 2  0.601763
12     100 0  0.912921
13     100 1  0.524904
14     100 2  0.225365
15     101 0  1.838889
16     101 1  1.215306
17     101 2  0.496480
18     110 0  1.509497
19     110 1  0.947424
20     110 2  0.449782
21     111 0  2.241581
22     111 1  1.635608
23     111 2  0.804609
24     000 3  0.000000
25     001 3  0.000000
26     010 3  0.000000
27     011 3  0.000000
28     100 3  0.000000
29     101 3  0.000000
30     110 3  0.000000
31     111 3  0.000000

In [ ]:
# 10.	Merge the ending state run expectancy into the play by play data

In [14]:
# Merge into play by play data
RE17 = pd.merge(RE17, End_RunExp, on=['End_State'], how='left')
display(RE17)

,batterName,batterId,event,start1B,start2B,start3B,end1B,end2B,end3B,startOuts,...,Start1,Start2,Start3,Start_State,End1,End2,End3,End_State,Start_RE,End_RE
0,Gardner,458731,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,0,000 0,0,0,0,000 1,0.516375,0.272176
1,"Sanchez, G",596142,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,0,000 1,0,0,0,000 2,0.272176,0.108038
2,Bird,595885,Walk,NaN,NaN,NaN,595885.0,NaN,NaN,2,...,0,0,0,000 2,1,0,0,100 2,0.108038,0.225365
3,Holliday,407812,Groundout,595885.0,NaN,NaN,NaN,NaN,NaN,2,...,1,0,0,100 2,0,0,0,000 3,0.225365,0.000000
4,"Dickerson, C",572816,Single,NaN,NaN,NaN,572816.0,NaN,NaN,0,...,0,0,0,000 0,1,0,0,100 0,0.516375,0.912921
5,Kiermaier,595281,Double,572816.0,NaN,NaN,NaN,595281.0,572816.0,0,...,1,0,0,100 0,0,1,1,011 0,0.912921,2.051376
6,Longoria,446334,Sac Fly,NaN,595281.0,572816.0,NaN,595281.0,NaN,0,...,0,1,1,011 0,0,1,0,010 1,2.051376,0.711650
7,"Miller, B",543543,Single,NaN,595281.0,NaN,543543.0,NaN,595281.0,1,...,0,1,0,010 1,1,0,1,101 1,0.711650,1.215306
8,Souza Jr.,519306,Walk,543543.0,NaN,595281.0,519306.0,543543.0,595281.0,1,...,1,0,1,101 1,1,1,1,111 1,1.215306,1.635608
9,Morrison,489149,Single,519306.0,543543.0,595281.0,489149.0,519306.0,NaN,1,...,1,1,1,111 1,1,1,0,110 1,1.635608,0.947424
10,Beckham,542921,Lineout,489149.0,519306.0,NaN,489149.0,519306.0,NaN,1,...,1,1,0,110 1,1,1,0,110 2,0.947424,0.449782
11,"Smith, M",605480,Strikeout,489149.0,519306.0,NaN,NaN,NaN,NaN,2,...,1,1,0,110 2,0,0,0,000 3,0.449782,0.000000
12,Ellsbury,453056,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,0,000 0,0,0,0,000 1,0.516375,0.272176
13,"Castro, S",516770,Single,NaN,NaN,NaN,516770.0,NaN,NaN,1,...,0,0,0,000 1,1,0,0,100 1,0.272176,0.524904
14,Headley,452104,Single,516770.0,NaN,NaN,452104.0,516770.0,NaN,1,...,1,0,0,100 1,1,1,0,110 1,0.524904,0.947424
15,Judge,592450,Double,452104.0,516770.0,NaN,NaN,592450.0,452104.0,1,...,1,1,0,110 1,0,1,1,011 1,0.947424,1.517131
16,Torreyes,591720,Groundout,NaN,592450.0,452104.0,NaN,NaN,592450.0,1,...,0,1,1,011 1,0,0,1,001 2,1.517131,0.381186
17,Gardner,458731,Groundout,NaN,NaN,592450.0,NaN,NaN,NaN,2,...,0,0,1,001 2,0,0,0,000 3,0.381186,0.000000
18,"Norris, De",519083,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,0,000 0,0,0,0,000 1,0.516375,0.272176
19,"Dickerson, C",572816,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,0,000 1,0,0,0,000 2,0.272176,0.108038
20,Kiermaier,595281,Walk,NaN,NaN,NaN,595281.0,NaN,NaN,2,...,0,0,0,000 2,1,0,0,100 2,0.108038,0.225365
21,Longoria,446334,Home Run,595281.0,NaN,NaN,NaN,NaN,NaN,2,...,1,0,0,100 2,0,0,0,000 2,0.225365,0.108038
22,"Miller, B",543543,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,0,0,0,000 2,0,0,0,000 3,0.108038,0.000000
23,"Sanchez, G",596142,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,0,000 0,0,0,0,000 1,0.516375,0.272176
24,Bird,595885,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,0,000 1,0,0,0,000 2,0.272176,0.108038
25,Holliday,407812,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,0,0,0,000 2,0,0,0,000 3,0.108038,0.000000
26,Souza Jr.,519306,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,0,000 0,0,0,0,000 1,0.516375,0.272176
27,Morrison,489149,Home Run,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,0,000 1,0,0,0,000 1,0.272176,0.272176
28,Beckham,542921,Double,NaN,NaN,NaN,NaN,542921.0,NaN,1,...,0,0,0,000 1,0,1,0,010 1,0.272176,0.711650
29,"Smith, M",605480,Single,NaN,542921.0,NaN,NaN,605480.0,NaN,1,...,0,1,0,010 1,0,1,0,010 1,0.711650,0.711650
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184721,Duvall,594807,Double,NaN,NaN,NaN,NaN,594807.0,NaN,1,...,0,0,0,000 1,0,1,0,010 1,0.272176,0.711650
184722,Suarez,553993,Single,NaN,594807.0,NaN,553993.0,NaN,594807.0,1,...,0,1,0,010 1,1,0,1,101 1,0.711650,1.215306
184723,Gennett,571697,Single,553993.0,NaN,594807.0,571697.0,553993.0,NaN,1,...,1,0,1,101 1,1,1,0,110 1,1.215306,0.947424
184724,Ervin,640447,Lineout,571697.0,553993.0,NaN,571697.0,553993.0,NaN,1,...,1,1,0,110 1,1,1,0,110 2,0.947424,0.449782
184725,Wallach,595453,Strikeout,571697.0,553993.0,NaN,NaN,NaN,NaN,2,...,1,1,0,110 2,0,0,0,000 3,0.449782,0.000000
184726,"Davis, T",543089,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,0,000 0,0,0,0,000 1,0.516375,0.272176
184727,Almora Jr.,546991,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,0,000 1,0,0,0,000 2,0.272176,0.108038
184728,Freeman,502273,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,0,0,0,000 2,0,0,0,000 3,0.108038,0.000000
184729,Kivlehan,623182,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,0,000 0,0,0,0,000 1,0.516375,0.272176
184730,Hamilton,571740,Lineout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,0,000 1,0,0,0,000 2,0.272176,0.108038
184731,Vincej,572227,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,0,0,0,000 2,0,0,0,000 3,0.108038,0.000000
184732,Zobrist,450314,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,0,000 0,0,0,0,000 1,0.516375,0.272176
184733,"Pena, Fe",570240,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,0,000 1,0,0,0,000 2,0.272176,0.108038
184734,Schwarber,656941,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,0,0,0,000 2,0,0,0,000 3,0.108038,0.000000
184735,Votto,458015,Double,NaN,NaN,NaN,NaN,458015.0,NaN,0,...,0,0,0,000 0,0,1,0,010 0,0.516375,1.154829
184736,Duvall,594807,Strikeout,NaN,458015.0,NaN,NaN,458015.0,NaN,0,...,0,1,0,010 0,0,1,0,010 1,1.154829,0.711650
184737,Suarez,553993,Flyout,NaN,458015.0,NaN,NaN,458015.0,NaN,1,...,0,1,0,010 1,0,1,0,010 2,0.711650,0.336702
184738,Gennett,571697,Strikeout,NaN,458015.0,NaN,NaN,NaN,NaN,2,...,0,1,0,010 2,0,0,0,000 3,0.336702,0.000000
184739,Caratini,605170,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,0,000 0,0,0,0,000 1,0.516375,0.272176
184740,La Stella,600303,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,0,000 1,0,0,0,000 2,0.272176,0.108038
184741,"Happ, I",664023,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,0,0,0,000 2,0,0,0,000 3,0.108038,0.000000
184742,Ervin,640447,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,0,000 0,0,0,0,000 1,0.516375,0.272176
184743,Wallach,595453,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,0,000 1,0,0,0,000 2,0.272176,0.108038
184744,Winker,608385,Single,NaN,NaN,NaN,608385.0,NaN,NaN,2,...,0,0,0,000 2,1,0,0,100 2,0.108038,0.225365
184745,Hamilton,571740,Walk,608385.0,NaN,NaN,571740.0,608385.0,NaN,2,...,1,0,0,100 2,1,1,0,110 2,0.225365,0.449782
184746,Vincej,572227,Runner Out,571740.0,608385.0,NaN,NaN,NaN,NaN,2,...,1,1,0,110 2,0,0,0,000 3,0.449782,0.000000
184747,"Davis, T",543089,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,0,000 0,0,0,0,000 1,0.516375,0.272176
184748,Almora Jr.,546991,Home Run,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,0,000 1,0,0,0,000 1,0.272176,0.272176
184749,Freeman,502273,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,0,000 1,0,0,0,000 2,0.272176,0.108038
184750,Zobrist,450314,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,0,0,0,000 2,0,0,0,000 3,0.108038,0.000000

In [ ]:
# 11.	Calculate the run value of each event

In [15]:
# Run Value of each event
RE17['Run_Value'] = RE17['runsOnPlay'] + RE17['End_RE'] - RE17['Start_RE']

display(RE17)

,batterName,batterId,event,start1B,start2B,start3B,end1B,end2B,end3B,startOuts,...,Start2,Start3,Start_State,End1,End2,End3,End_State,Start_RE,End_RE,Run_Value
0,Gardner,458731,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,000 0,0,0,0,000 1,0.516375,0.272176,-0.244199
1,"Sanchez, G",596142,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,000 1,0,0,0,000 2,0.272176,0.108038,-0.164138
2,Bird,595885,Walk,NaN,NaN,NaN,595885.0,NaN,NaN,2,...,0,0,000 2,1,0,0,100 2,0.108038,0.225365,0.117327
3,Holliday,407812,Groundout,595885.0,NaN,NaN,NaN,NaN,NaN,2,...,0,0,100 2,0,0,0,000 3,0.225365,0.000000,-0.225365
4,"Dickerson, C",572816,Single,NaN,NaN,NaN,572816.0,NaN,NaN,0,...,0,0,000 0,1,0,0,100 0,0.516375,0.912921,0.396546
5,Kiermaier,595281,Double,572816.0,NaN,NaN,NaN,595281.0,572816.0,0,...,0,0,100 0,0,1,1,011 0,0.912921,2.051376,1.138455
6,Longoria,446334,Sac Fly,NaN,595281.0,572816.0,NaN,595281.0,NaN,0,...,1,1,011 0,0,1,0,010 1,2.051376,0.711650,-0.339727
7,"Miller, B",543543,Single,NaN,595281.0,NaN,543543.0,NaN,595281.0,1,...,1,0,010 1,1,0,1,101 1,0.711650,1.215306,0.503657
8,Souza Jr.,519306,Walk,543543.0,NaN,595281.0,519306.0,543543.0,595281.0,1,...,0,1,101 1,1,1,1,111 1,1.215306,1.635608,0.420302
9,Morrison,489149,Single,519306.0,543543.0,595281.0,489149.0,519306.0,NaN,1,...,1,1,111 1,1,1,0,110 1,1.635608,0.947424,1.311816
10,Beckham,542921,Lineout,489149.0,519306.0,NaN,489149.0,519306.0,NaN,1,...,1,0,110 1,1,1,0,110 2,0.947424,0.449782,-0.497642
11,"Smith, M",605480,Strikeout,489149.0,519306.0,NaN,NaN,NaN,NaN,2,...,1,0,110 2,0,0,0,000 3,0.449782,0.000000,-0.449782
12,Ellsbury,453056,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,000 0,0,0,0,000 1,0.516375,0.272176,-0.244199
13,"Castro, S",516770,Single,NaN,NaN,NaN,516770.0,NaN,NaN,1,...,0,0,000 1,1,0,0,100 1,0.272176,0.524904,0.252728
14,Headley,452104,Single,516770.0,NaN,NaN,452104.0,516770.0,NaN,1,...,0,0,100 1,1,1,0,110 1,0.524904,0.947424,0.422520
15,Judge,592450,Double,452104.0,516770.0,NaN,NaN,592450.0,452104.0,1,...,1,0,110 1,0,1,1,011 1,0.947424,1.517131,1.569707
16,Torreyes,591720,Groundout,NaN,592450.0,452104.0,NaN,NaN,592450.0,1,...,1,1,011 1,0,0,1,001 2,1.517131,0.381186,-0.135945
17,Gardner,458731,Groundout,NaN,NaN,592450.0,NaN,NaN,NaN,2,...,0,1,001 2,0,0,0,000 3,0.381186,0.000000,-0.381186
18,"Norris, De",519083,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,000 0,0,0,0,000 1,0.516375,0.272176,-0.244199
19,"Dickerson, C",572816,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,000 1,0,0,0,000 2,0.272176,0.108038,-0.164138
20,Kiermaier,595281,Walk,NaN,NaN,NaN,595281.0,NaN,NaN,2,...,0,0,000 2,1,0,0,100 2,0.108038,0.225365,0.117327
21,Longoria,446334,Home Run,595281.0,NaN,NaN,NaN,NaN,NaN,2,...,0,0,100 2,0,0,0,000 2,0.225365,0.108038,1.882673
22,"Miller, B",543543,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,0,0,000 2,0,0,0,000 3,0.108038,0.000000,-0.108038
23,"Sanchez, G",596142,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,000 0,0,0,0,000 1,0.516375,0.272176,-0.244199
24,Bird,595885,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,000 1,0,0,0,000 2,0.272176,0.108038,-0.164138
25,Holliday,407812,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,0,0,000 2,0,0,0,000 3,0.108038,0.000000,-0.108038
26,Souza Jr.,519306,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,000 0,0,0,0,000 1,0.516375,0.272176,-0.244199
27,Morrison,489149,Home Run,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,000 1,0,0,0,000 1,0.272176,0.272176,1.000000
28,Beckham,542921,Double,NaN,NaN,NaN,NaN,542921.0,NaN,1,...,0,0,000 1,0,1,0,010 1,0.272176,0.711650,0.439473
29,"Smith, M",605480,Single,NaN,542921.0,NaN,NaN,605480.0,NaN,1,...,1,0,010 1,0,1,0,010 1,0.711650,0.711650,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184721,Duvall,594807,Double,NaN,NaN,NaN,NaN,594807.0,NaN,1,...,0,0,000 1,0,1,0,010 1,0.272176,0.711650,0.439473
184722,Suarez,553993,Single,NaN,594807.0,NaN,553993.0,NaN,594807.0,1,...,1,0,010 1,1,0,1,101 1,0.711650,1.215306,0.503657
184723,Gennett,571697,Single,553993.0,NaN,594807.0,571697.0,553993.0,NaN,1,...,0,1,101 1,1,1,0,110 1,1.215306,0.947424,0.732118
184724,Ervin,640447,Lineout,571697.0,553993.0,NaN,571697.0,553993.0,NaN,1,...,1,0,110 1,1,1,0,110 2,0.947424,0.449782,-0.497642
184725,Wallach,595453,Strikeout,571697.0,553993.0,NaN,NaN,NaN,NaN,2,...,1,0,110 2,0,0,0,000 3,0.449782,0.000000,-0.449782
184726,"Davis, T",543089,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,000 0,0,0,0,000 1,0.516375,0.272176,-0.244199
184727,Almora Jr.,546991,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,000 1,0,0,0,000 2,0.272176,0.108038,-0.164138
184728,Freeman,502273,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,0,0,000 2,0,0,0,000 3,0.108038,0.000000,-0.108038
184729,Kivlehan,623182,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,000 0,0,0,0,000 1,0.516375,0.272176,-0.244199
184730,Hamilton,571740,Lineout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,000 1,0,0,0,000 2,0.272176,0.108038,-0.164138
184731,Vincej,572227,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,0,0,000 2,0,0,0,000 3,0.108038,0.000000,-0.108038
184732,Zobrist,450314,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,000 0,0,0,0,000 1,0.516375,0.272176,-0.244199
184733,"Pena, Fe",570240,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,000 1,0,0,0,000 2,0.272176,0.108038,-0.164138
184734,Schwarber,656941,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,0,0,000 2,0,0,0,000 3,0.108038,0.000000,-0.108038
184735,Votto,458015,Double,NaN,NaN,NaN,NaN,458015.0,NaN,0,...,0,0,000 0,0,1,0,010 0,0.516375,1.154829,0.638454
184736,Duvall,594807,Strikeout,NaN,458015.0,NaN,NaN,458015.0,NaN,0,...,1,0,010 0,0,1,0,010 1,1.154829,0.711650,-0.443179
184737,Suarez,553993,Flyout,NaN,458015.0,NaN,NaN,458015.0,NaN,1,...,1,0,010 1,0,1,0,010 2,0.711650,0.336702,-0.374947
184738,Gennett,571697,Strikeout,NaN,458015.0,NaN,NaN,NaN,NaN,2,...,1,0,010 2,0,0,0,000 3,0.336702,0.000000,-0.336702
184739,Caratini,605170,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,000 0,0,0,0,000 1,0.516375,0.272176,-0.244199
184740,La Stella,600303,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,000 1,0,0,0,000 2,0.272176,0.108038,-0.164138
184741,"Happ, I",664023,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,0,0,000 2,0,0,0,000 3,0.108038,0.000000,-0.108038
184742,Ervin,640447,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,000 0,0,0,0,000 1,0.516375,0.272176,-0.244199
184743,Wallach,595453,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,000 1,0,0,0,000 2,0.272176,0.108038,-0.164138
184744,Winker,608385,Single,NaN,NaN,NaN,608385.0,NaN,NaN,2,...,0,0,000 2,1,0,0,100 2,0.108038,0.225365,0.117327
184745,Hamilton,571740,Walk,608385.0,NaN,NaN,571740.0,608385.0,NaN,2,...,0,0,100 2,1,1,0,110 2,0.225365,0.449782,0.224418
184746,Vincej,572227,Runner Out,571740.0,608385.0,NaN,NaN,NaN,NaN,2,...,1,0,110 2,0,0,0,000 3,0.449782,0.000000,-0.449782
184747,"Davis, T",543089,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,000 0,0,0,0,000 1,0.516375,0.272176,-0.244199
184748,Almora Jr.,546991,Home Run,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,000 1,0,0,0,000 1,0.272176,0.272176,1.000000
184749,Freeman,502273,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,000 1,0,0,0,000 2,0.272176,0.108038,-0.164138
184750,Zobrist,450314,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,0,0,000 2,0,0,0,000 3,0.108038,0.000000,-0.108038

In [17]:
# Q1: What percent of plate appearances resulted in fly outs in 2017?
RE17['Count'] = 1
Flyout = RE17[RE17['event']=='Flyout']
sum(Flyout['Count'])/sum(RE17['Count'])

0.10697100421648598

In [18]:
# Q2: How many plate appearances had a starting base state in which the bases were loaded (all bases were occupied)?
RE17_BLoad = RE17[(RE17['Start_State'] == "111 0")|(RE17['Start_State'] == "111 1")|(RE17['Start_State'] == "111 2")]
RE17_BLoad

,batterName,batterId,event,start1B,start2B,start3B,end1B,end2B,end3B,startOuts,...,Start3,Start_State,End1,End2,End3,End_State,Start_RE,End_RE,Run_Value,Count
9,Morrison,489149,Single,519306.0,543543.0,595281.0,489149.0,519306.0,NaN,1,...,1,111 1,1,1,0,110 1,1.635608,0.947424,1.311816,1
57,"Sanchez, G",596142,Groundout,458731.0,452104.0,516770.0,NaN,NaN,NaN,2,...,1,111 2,0,0,0,000 3,0.804609,0.000000,-0.804609,1
72,"Miller, B",543543,Strikeout,446334.0,595281.0,572816.0,NaN,NaN,NaN,2,...,1,111 2,0,0,0,000 3,0.804609,0.000000,-0.804609,1
76,Carter,474892,Sac Fly,543305.0,592450.0,452104.0,543305.0,592450.0,NaN,0,...,1,111 0,1,1,0,110 1,2.241581,0.947424,-0.294157,1
150,Posey,457763,Flyout,452254.0,474832.0,452655.0,452254.0,474832.0,452655.0,1,...,1,111 1,1,1,1,111 2,1.635608,0.804609,-0.830999,1
151,Crawford,543063,Forceout,452254.0,474832.0,452655.0,NaN,NaN,NaN,2,...,1,111 2,0,0,0,000 3,0.804609,0.000000,-0.804609,1
198,"Martinez, C",593372,Grounded Into DP,545341.0,543939.0,425877.0,NaN,NaN,NaN,1,...,1,111 1,0,0,0,000 3,1.635608,0.000000,-1.635608,1
212,Bryant,592178,Flyout,656941.0,595879.0,575929.0,656941.0,595879.0,575929.0,1,...,1,111 1,1,1,1,111 2,1.635608,0.804609,-0.830999,1
213,Rizzo,519203,Flyout,656941.0,595879.0,575929.0,NaN,NaN,NaN,2,...,1,111 2,0,0,0,000 3,0.804609,0.000000,-0.804609,1
288,Werth,150029,Strikeout,475582.0,502517.0,547180.0,475582.0,502517.0,547180.0,0,...,1,111 0,1,1,1,111 1,2.241581,1.635608,-0.605973,1
289,Drew,452220,Grounded Into DP,475582.0,502517.0,547180.0,NaN,NaN,NaN,1,...,1,111 1,0,0,0,000 3,1.635608,0.000000,-1.635608,1
349,Granderson,434158,Sac Fly,493316.0,452678.0,408314.0,493316.0,452678.0,NaN,1,...,1,111 1,1,1,0,110 2,1.635608,0.449782,-0.185826,1
351,Bruce,457803,Walk,435522.0,493316.0,452678.0,457803.0,435522.0,493316.0,2,...,1,111 2,1,1,1,111 2,0.804609,0.804609,1.000000,1
352,Duda,446263,Double,457803.0,435522.0,493316.0,NaN,446263.0,NaN,2,...,1,111 2,0,1,0,010 2,0.804609,0.336702,2.532093,1
419,"Marte, S",516782,Sac Fly,624428.0,474568.0,543281.0,624428.0,474568.0,NaN,1,...,1,111 1,1,1,0,110 2,1.635608,0.449782,-0.185826,1
477,Villar,542340,Double,542583.0,606115.0,542908.0,NaN,542340.0,542583.0,0,...,1,111 0,0,1,1,011 0,2.241581,2.051376,1.809795,1
494,Blackmon,453568,Forceout,506924.0,547172.0,448602.0,453568.0,NaN,547172.0,1,...,1,111 1,1,0,1,101 2,1.635608,0.496480,-0.139128,1
553,Bautista,430832,Pop Out,518626.0,485567.0,607680.0,518626.0,485567.0,607680.0,1,...,1,111 1,1,1,1,111 2,1.635608,0.804609,-0.830999,1
554,Morales,434778,Walk,518626.0,485567.0,607680.0,434778.0,518626.0,485567.0,2,...,1,111 2,1,1,1,111 2,0.804609,0.804609,1.000000,1
555,Tulowitzki,453064,Groundout,434778.0,518626.0,485567.0,NaN,NaN,NaN,2,...,1,111 2,0,0,0,000 3,0.804609,0.000000,-0.804609,1
653,Grossman,543257,Walk,572821.0,596146.0,593871.0,543257.0,572821.0,596146.0,1,...,1,111 1,1,1,1,111 1,1.635608,1.635608,1.000000,1
654,Buxton,621439,Strikeout,543257.0,572821.0,596146.0,543257.0,572821.0,596146.0,1,...,1,111 1,1,1,1,111 2,1.635608,0.804609,-0.830999,1
655,Mauer,408045,Walk,543257.0,572821.0,596146.0,408045.0,543257.0,572821.0,2,...,1,111 2,1,1,1,111 2,0.804609,0.804609,1.000000,1
656,Sano,593934,Walk,408045.0,543257.0,572821.0,593934.0,408045.0,543257.0,2,...,1,111 2,1,1,1,111 2,0.804609,0.804609,1.000000,1
657,"Castro, J",488771,Single,593934.0,408045.0,543257.0,488771.0,NaN,593934.0,2,...,1,111 2,1,0,1,101 2,0.804609,0.496480,1.691871,1
693,Hamilton,571740,Sac Fly,444857.0,571466.0,446359.0,444857.0,571466.0,NaN,0,...,1,111 0,1,1,0,110 1,2.241581,0.947424,-0.294157,1
702,Cozart,446359,Flyout,594988.0,553993.0,594807.0,594988.0,553993.0,594807.0,1,...,1,111 1,1,1,1,111 2,1.635608,0.804609,-0.830999,1
703,Barnhart,571466,Flyout,594988.0,553993.0,594807.0,NaN,NaN,NaN,2,...,1,111 2,0,0,0,000 3,0.804609,0.000000,-0.804609,1
709,Saunders,459431,Groundout,596748.0,546318.0,435062.0,NaN,NaN,NaN,2,...,1,111 2,0,0,0,000 3,0.804609,0.000000,-0.804609,1
772,Pederson,592626,Home Run,523253.0,408236.0,457759.0,NaN,NaN,NaN,2,...,1,111 2,0,0,0,000 2,0.804609,0.108038,3.303429,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183885,"Gonzalez, G",461829,Strikeout,446308.0,150029.0,475582.0,446308.0,150029.0,475582.0,1,...,1,111 1,1,1,1,111 2,1.635608,0.804609,-0.830999,1
183886,Turner,607208,Groundout,446308.0,150029.0,475582.0,NaN,NaN,NaN,2,...,1,111 2,0,0,0,000 3,0.804609,0.000000,-0.804609,1
183903,Turner,607208,Strikeout,446653.0,572191.0,446308.0,446653.0,572191.0,446308.0,1,...,1,111 1,1,1,1,111 2,1.635608,0.804609,-0.830999,1
183904,Harper,547180,Groundout,446653.0,572191.0,446308.0,NaN,NaN,NaN,2,...,1,111 2,0,0,0,000 3,0.804609,0.000000,-0.804609,1
183934,Moroff,621559,Walk,656669.0,605137.0,516782.0,621559.0,656669.0,605137.0,2,...,1,111 2,1,1,1,111 2,0.804609,0.804609,1.000000,1
183935,Stallings,607732,Single,621559.0,656669.0,605137.0,607732.0,621559.0,656669.0,2,...,1,111 2,1,1,1,111 2,0.804609,0.804609,1.000000,1
183936,"Frazier, A",624428,Lineout,607732.0,621559.0,656669.0,NaN,NaN,NaN,2,...,1,111 2,0,0,0,000 3,0.804609,0.000000,-0.804609,1
183941,Lobaton,446653,Grounded Into DP,572191.0,435062.0,457477.0,NaN,NaN,NaN,1,...,1,111 1,0,0,0,000 3,1.635608,0.000000,-1.635608,1
183957,Blash,518466,Grounded Into DP,605486.0,500208.0,641319.0,NaN,NaN,NaN,1,...,1,111 1,0,0,0,000 3,1.635608,0.000000,-1.635608,1
184134,Pennington,460060,Sac Fly,543068.0,453203.0,472528.0,NaN,543068.0,453203.0,0,...,1,111 0,0,1,1,011 1,2.241581,1.517131,0.275550,1
184136,Graterol,492802,Sac Fly,592230.0,543068.0,453203.0,592230.0,543068.0,NaN,1,...,1,111 1,1,1,0,110 2,1.635608,0.449782,-0.185826,1
184296,Plouffe,461858,Walk,519306.0,489149.0,446334.0,461858.0,519306.0,489149.0,1,...,1,111 1,1,1,1,111 1,1.635608,1.635608,1.000000,1
184297,Casali,592200,Walk,461858.0,519306.0,489149.0,592200.0,461858.0,519306.0,1,...,1,111 1,1,1,1,111 1,1.635608,1.635608,1.000000,1
184298,"Smith, M",605480,Sac Fly,592200.0,461858.0,519306.0,592200.0,NaN,461858.0,1,...,1,111 1,1,0,1,101 2,1.635608,0.496480,-0.139128,1
184300,Bourjos,488721,Flyout,621002.0,592200.0,461858.0,NaN,NaN,NaN,2,...,1,111 2,0,0,0,000 3,0.804609,0.000000,-0.804609,1
184312,Encarnacion,429665,Lineout,608070.0,543401.0,596019.0,608070.0,543401.0,596019.0,0,...,1,111 0,1,1,1,111 1,2.241581,1.635608,-0.605973,1
184313,Bruce,457803,Single,608070.0,543401.0,596019.0,457803.0,NaN,608070.0,1,...,1,111 1,1,0,1,101 1,1.635608,1.215306,1.579698,1
184360,Brantley,488726,Groundout,608070.0,656185.0,650490.0,NaN,NaN,NaN,2,...,1,111 2,0,0,0,000 3,0.804609,0.000000,-0.804609,1
184461,"Hernandez, K",571771,Sac Fly,641355.0,457759.0,608369.0,641355.0,NaN,457759.0,1,...,1,111 1,1,0,1,101 2,1.635608,0.496480,-0.139128,1
184483,Culberson,518586,Walk,572204.0,592626.0,518735.0,518586.0,572204.0,592626.0,2,...,1,111 2,1,1,1,111 2,0.804609,0.804609,1.000000,1
184484,Maeda,628317,Groundout,518586.0,572204.0,592626.0,NaN,NaN,NaN,2,...,1,111 2,0,0,0,000 3,0.804609,0.000000,-0.804609,1
184559,Cain,456715,Forceout,460077.0,444876.0,593528.0,NaN,NaN,NaN,2,...,1,111 2,0,0,0,000 3,0.804609,0.000000,-0.804609,1
184575,Negron,502117,Single,453923.0,489267.0,543302.0,502117.0,453923.0,489267.0,0,...,1,111 0,1,1,1,111 0,2.241581,2.241581,1.000000,1
184576,"Vargas, I",545121,Forceout,502117.0,453923.0,489267.0,545121.0,NaN,453923.0,0,...,1,111 0,1,0,1,101 1,2.241581,1.215306,-0.026275,1
184598,Rosales,489267,Forceout,543302.0,518614.0,592273.0,489267.0,543302.0,518614.0,0,...,1,111 0,1,1,1,111 1,2.241581,1.635608,-0.605973,1
184599,"Blanco, G",453923,Forceout,489267.0,543302.0,518614.0,453923.0,NaN,543302.0,1,...,1,111 1,1,0,1,101 2,1.635608,0.496480,-0.139128,1
184616,Aguilar,542583,Sac Fly,519346.0,542340.0,519299.0,519346.0,NaN,542340.0,0,...,1,111 0,1,0,1,101 1,2.241581,1.215306,-0.026275,1
184672,DeJong,657557,Strikeout,642423.0,608348.0,594824.0,642423.0,608348.0,594824.0,0,...,1,111 0,1,1,1,111 1,2.241581,1.635608,-0.605973,1
184673,Valera,591971,Pop Out,642423.0,608348.0,594824.0,642423.0,608348.0,594824.0,1,...,1,111 1,1,1,1,111 2,1.635608,0.804609,-0.830999,1
184674,"Mejia, A",622270,Groundout,642423.0,608348.0,594824.0,NaN,NaN,NaN,2,...,1,111 2,0,0,0,000 3,0.804609,0.000000,-0.804609,1

In [21]:
# Q3: Calculate aggregate strikeouts by player position (that is, aggregate (sum) data at the positional level and not the player level).  
# What was the highest aggregate strikeout total by position?
Strikeouts = RE17[RE17['event'] == "Strikeout"]
Strikeouts.groupby(['batterPos'])['Count'].sum().reset_index()

   batterPos  Count
0         1B   4399
1         2B   3710
2         3B   4023
3          C   4090
4         CF   4374
5         DH   2354
6         LF   4317
7          P   1872
8         PH      1
9         RF   4386
10        SS   3734
11        UN   2594

# II. Coding Run Expectancy Dataset (2016)

In [ ]:
#Your Code Here

In [ ]:
# 1.	Read in “MLBAM16.csv” data

In [23]:
# Read in MLBAM Data for 2016

MLBAM16 = pd.read_csv("../Data/MLBAM16.csv")

In [ ]:
# 2.	Keep only the relevant columns (see exercise notebook)

In [24]:
# Drop column with no relevant information
MLBAM16.drop(['Unnamed: 0'], axis=1, inplace=True)

In [25]:
RE16 = MLBAM16[['batterName','batterId','event', 'start1B', 'start2B', 'start3B', 'end1B', 'end2B', 'end3B',\
                'startOuts','endOuts','runsFuture','runsOnPlay','outsInInning',\
                'stand', 'throws','venueId', 'stadium', 'batterPos']].copy()

display(RE16)

,batterName,batterId,event,start1B,start2B,start3B,end1B,end2B,end3B,startOuts,endOuts,runsFuture,runsOnPlay,outsInInning,stand,throws,venueId,stadium,batterPos
0,"Carpenter, M",572761,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,L,L,31,PNC Park,3B
1,Pham,502054,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,R,L,31,PNC Park,LF
2,Holliday,407812,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,R,L,31,PNC Park,1B
3,Jaso,444379,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,L,R,31,PNC Park,1B
4,McCutchen,457705,Hit By Pitch,NaN,NaN,NaN,457705.0,NaN,NaN,1,1,0,0,3,R,R,31,PNC Park,CF
5,Freese,501896,Single,457705.0,NaN,NaN,501896.0,NaN,457705.0,1,1,0,0,3,R,R,31,PNC Park,3B
6,"Marte, S",516782,Lineout,501896.0,NaN,457705.0,501896.0,NaN,457705.0,1,2,0,0,3,R,R,31,PNC Park,LF
7,Cervelli,465041,Pop Out,501896.0,NaN,457705.0,NaN,NaN,NaN,2,3,0,0,3,R,R,31,PNC Park,C
8,Grichuk,545341,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,R,L,31,PNC Park,CF
9,Piscotty,572039,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,R,L,31,PNC Park,RF
10,Molina,425877,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,R,L,31,PNC Park,C
11,"Polanco, G",570256,Double,NaN,NaN,NaN,NaN,570256.0,NaN,0,0,2,0,3,L,R,31,PNC Park,RF
12,Harrison,543281,Groundout,NaN,570256.0,NaN,NaN,NaN,570256.0,0,1,2,0,3,R,R,31,PNC Park,2B
13,Mercer,474568,Walk,NaN,NaN,570256.0,474568.0,NaN,570256.0,1,1,2,0,3,R,R,31,PNC Park,SS
14,Liriano,434538,Single,474568.0,NaN,570256.0,434538.0,474568.0,NaN,1,1,2,1,3,L,R,31,PNC Park,P
15,Jaso,444379,Single,434538.0,474568.0,NaN,444379.0,434538.0,NaN,1,1,1,1,3,L,R,31,PNC Park,1B
16,McCutchen,457705,Flyout,444379.0,434538.0,NaN,444379.0,434538.0,NaN,1,2,0,0,3,R,R,31,PNC Park,CF
17,Freese,501896,Groundout,444379.0,434538.0,NaN,NaN,NaN,NaN,2,3,0,0,3,R,R,31,PNC Park,3B
18,Wong,543939,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,L,L,31,PNC Park,2B
19,Gyorko,576397,Walk,NaN,NaN,NaN,576397.0,NaN,NaN,1,1,0,0,3,R,L,31,PNC Park,SS
20,Wainwright,425794,Field Error,576397.0,NaN,NaN,425794.0,NaN,576397.0,1,1,0,0,3,R,L,31,PNC Park,P
21,"Carpenter, M",572761,Grounded Into DP,425794.0,NaN,576397.0,NaN,NaN,NaN,1,3,0,0,3,L,L,31,PNC Park,3B
22,"Marte, S",516782,Lineout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,R,R,31,PNC Park,LF
23,Cervelli,465041,Walk,NaN,NaN,NaN,465041.0,NaN,NaN,1,1,0,0,3,R,R,31,PNC Park,C
24,"Polanco, G",570256,Flyout,465041.0,NaN,NaN,465041.0,NaN,NaN,1,2,0,0,3,L,R,31,PNC Park,RF
25,Harrison,543281,Strikeout,465041.0,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,R,R,31,PNC Park,2B
26,Adams,571431,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,L,L,31,PNC Park,UN
27,Holliday,407812,Single,NaN,NaN,NaN,407812.0,NaN,NaN,1,1,0,0,3,R,L,31,PNC Park,1B
28,Grichuk,545341,Single,407812.0,NaN,NaN,545341.0,407812.0,NaN,1,1,0,0,3,R,L,31,PNC Park,CF
29,Piscotty,572039,Strikeout,545341.0,407812.0,NaN,545341.0,407812.0,NaN,1,2,0,0,3,R,L,31,PNC Park,RF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184905,Grichuk,545341,Strikeout,576397.0,NaN,NaN,576397.0,NaN,NaN,1,2,3,0,3,R,L,2889,Busch Stadium,CF
184906,"Martinez, Jo",500874,Single,576397.0,NaN,NaN,500874.0,576397.0,NaN,2,2,3,0,3,R,L,2889,Busch Stadium,UN
184907,"Carpenter, M",572761,Home Run,500874.0,576397.0,NaN,NaN,NaN,NaN,2,2,3,3,3,L,L,2889,Busch Stadium,1B
184908,"Diaz, A",649557,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,R,R,2889,Busch Stadium,SS
184909,"Frazier, A",624428,Single,NaN,NaN,NaN,624428.0,NaN,NaN,0,0,2,0,3,L,R,2889,Busch Stadium,UN
184910,Jaso,444379,Home Run,624428.0,NaN,NaN,NaN,NaN,NaN,0,0,2,2,3,L,R,2889,Busch Stadium,1B
184911,"Polanco, G",570256,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,L,R,2889,Busch Stadium,RF
184912,McCutchen,457705,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,R,R,2889,Busch Stadium,CF
184913,Kang,628356,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,R,R,2889,Busch Stadium,3B
184914,Molina,425877,Double,NaN,NaN,NaN,NaN,425877.0,NaN,0,0,6,0,3,R,R,2889,Busch Stadium,C
184915,Piscotty,572039,Single,NaN,425877.0,NaN,572039.0,NaN,NaN,0,0,6,1,3,R,R,2889,Busch Stadium,RF
184916,"Peralta, J",425509,Single,572039.0,NaN,NaN,425509.0,572039.0,NaN,0,0,5,0,3,R,R,2889,Busch Stadium,3B
184917,Moss,461235,Single,425509.0,572039.0,NaN,461235.0,425509.0,572039.0,0,0,5,0,3,L,L,2889,Busch Stadium,LF
184918,Gyorko,576397,Field Error,461235.0,425509.0,572039.0,576397.0,461235.0,425509.0,0,0,5,1,3,R,L,2889,Busch Stadium,2B
184919,Grichuk,545341,Double,576397.0,461235.0,425509.0,NaN,545341.0,576397.0,0,0,4,2,3,R,L,2889,Busch Stadium,CF
184920,Adams,571431,Sac Fly,NaN,545341.0,576397.0,NaN,NaN,545341.0,0,1,2,1,3,L,L,2889,Busch Stadium,UN
184921,"Carpenter, M",572761,Sac Fly,NaN,NaN,545341.0,NaN,NaN,NaN,1,2,1,1,3,L,L,2889,Busch Stadium,1B
184922,"Diaz, A",649557,Pop Out,NaN,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,R,L,2889,Busch Stadium,SS
184923,Joyce,459964,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,L,L,2889,Busch Stadium,LF
184924,Hanson,593700,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,R,L,2889,Busch Stadium,2B
184925,Fryer,518700,Single,NaN,NaN,NaN,518700.0,NaN,NaN,2,2,0,0,3,R,L,2889,Busch Stadium,C
184926,Florimon,465753,Groundout,518700.0,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,R,L,2889,Busch Stadium,SS
184927,Molina,425877,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,R,R,2889,Busch Stadium,C
184928,Piscotty,572039,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,2,0,0,3,R,R,2889,Busch Stadium,RF
184929,"Garcia, G",594824,Single,NaN,NaN,NaN,594824.0,NaN,NaN,2,2,0,0,3,L,R,2889,Busch Stadium,UN
184930,Moss,461235,Strikeout,594824.0,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,L,R,2889,Busch Stadium,LF
184931,"Rogers, J",595386,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,1,0,0,3,R,L,2889,Busch Stadium,UN
184932,Jaso,444379,Walk,NaN,NaN,NaN,444379.0,NaN,NaN,1,1,0,0,3,L,L,2889,Busch Stadium,1B
184933,"Polanco, G",570256,Strikeout,444379.0,NaN,NaN,444379.0,NaN,NaN,1,2,0,0,3,L,L,2889,Busch Stadium,RF
184934,McCutchen,457705,Groundout,444379.0,NaN,NaN,NaN,NaN,NaN,2,3,0,0,3,R,L,2889,Busch Stadium,CF

In [ ]:
# 3.	Create three indicator variables (one for each base) to denote whether or not each base is occupied prior to the plate appearance

In [26]:
# Create indicator variables to determine whether base is occupied prior to plate appearance
RE16['Start1'] = np.where(pd.isnull(RE16['start1B']),0,1)
RE16['Start2'] = np.where(pd.isnull(RE16['start2B']),0,1)
RE16['Start3'] = np.where(pd.isnull(RE16['start3B']),0,1)

In [ ]:
# 4.	Create a “start state” variable to denote the base out state prior to each plate appearance

In [27]:
RE16['Start_State'] = (RE16['Start1'].astype(str) + RE16['Start2'].astype(str) + RE16['Start3'].astype(str)+\
                       " " + RE16['startOuts'].astype(str))
RE16

,batterName,batterId,event,start1B,start2B,start3B,end1B,end2B,end3B,startOuts,...,outsInInning,stand,throws,venueId,stadium,batterPos,Start1,Start2,Start3,Start_State
0,"Carpenter, M",572761,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,3,L,L,31,PNC Park,3B,0,0,0,000 0
1,Pham,502054,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,3,R,L,31,PNC Park,LF,0,0,0,000 1
2,Holliday,407812,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,3,R,L,31,PNC Park,1B,0,0,0,000 2
3,Jaso,444379,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,3,L,R,31,PNC Park,1B,0,0,0,000 0
4,McCutchen,457705,Hit By Pitch,NaN,NaN,NaN,457705.0,NaN,NaN,1,...,3,R,R,31,PNC Park,CF,0,0,0,000 1
5,Freese,501896,Single,457705.0,NaN,NaN,501896.0,NaN,457705.0,1,...,3,R,R,31,PNC Park,3B,1,0,0,100 1
6,"Marte, S",516782,Lineout,501896.0,NaN,457705.0,501896.0,NaN,457705.0,1,...,3,R,R,31,PNC Park,LF,1,0,1,101 1
7,Cervelli,465041,Pop Out,501896.0,NaN,457705.0,NaN,NaN,NaN,2,...,3,R,R,31,PNC Park,C,1,0,1,101 2
8,Grichuk,545341,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,3,R,L,31,PNC Park,CF,0,0,0,000 0
9,Piscotty,572039,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,3,R,L,31,PNC Park,RF,0,0,0,000 1
10,Molina,425877,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,3,R,L,31,PNC Park,C,0,0,0,000 2
11,"Polanco, G",570256,Double,NaN,NaN,NaN,NaN,570256.0,NaN,0,...,3,L,R,31,PNC Park,RF,0,0,0,000 0
12,Harrison,543281,Groundout,NaN,570256.0,NaN,NaN,NaN,570256.0,0,...,3,R,R,31,PNC Park,2B,0,1,0,010 0
13,Mercer,474568,Walk,NaN,NaN,570256.0,474568.0,NaN,570256.0,1,...,3,R,R,31,PNC Park,SS,0,0,1,001 1
14,Liriano,434538,Single,474568.0,NaN,570256.0,434538.0,474568.0,NaN,1,...,3,L,R,31,PNC Park,P,1,0,1,101 1
15,Jaso,444379,Single,434538.0,474568.0,NaN,444379.0,434538.0,NaN,1,...,3,L,R,31,PNC Park,1B,1,1,0,110 1
16,McCutchen,457705,Flyout,444379.0,434538.0,NaN,444379.0,434538.0,NaN,1,...,3,R,R,31,PNC Park,CF,1,1,0,110 1
17,Freese,501896,Groundout,444379.0,434538.0,NaN,NaN,NaN,NaN,2,...,3,R,R,31,PNC Park,3B,1,1,0,110 2
18,Wong,543939,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,3,L,L,31,PNC Park,2B,0,0,0,000 0
19,Gyorko,576397,Walk,NaN,NaN,NaN,576397.0,NaN,NaN,1,...,3,R,L,31,PNC Park,SS,0,0,0,000 1
20,Wainwright,425794,Field Error,576397.0,NaN,NaN,425794.0,NaN,576397.0,1,...,3,R,L,31,PNC Park,P,1,0,0,100 1
21,"Carpenter, M",572761,Grounded Into DP,425794.0,NaN,576397.0,NaN,NaN,NaN,1,...,3,L,L,31,PNC Park,3B,1,0,1,101 1
22,"Marte, S",516782,Lineout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,3,R,R,31,PNC Park,LF,0,0,0,000 0
23,Cervelli,465041,Walk,NaN,NaN,NaN,465041.0,NaN,NaN,1,...,3,R,R,31,PNC Park,C,0,0,0,000 1
24,"Polanco, G",570256,Flyout,465041.0,NaN,NaN,465041.0,NaN,NaN,1,...,3,L,R,31,PNC Park,RF,1,0,0,100 1
25,Harrison,543281,Strikeout,465041.0,NaN,NaN,NaN,NaN,NaN,2,...,3,R,R,31,PNC Park,2B,1,0,0,100 2
26,Adams,571431,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,3,L,L,31,PNC Park,UN,0,0,0,000 0
27,Holliday,407812,Single,NaN,NaN,NaN,407812.0,NaN,NaN,1,...,3,R,L,31,PNC Park,1B,0,0,0,000 1
28,Grichuk,545341,Single,407812.0,NaN,NaN,545341.0,407812.0,NaN,1,...,3,R,L,31,PNC Park,CF,1,0,0,100 1
29,Piscotty,572039,Strikeout,545341.0,407812.0,NaN,545341.0,407812.0,NaN,1,...,3,R,L,31,PNC Park,RF,1,1,0,110 1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184905,Grichuk,545341,Strikeout,576397.0,NaN,NaN,576397.0,NaN,NaN,1,...,3,R,L,2889,Busch Stadium,CF,1,0,0,100 1
184906,"Martinez, Jo",500874,Single,576397.0,NaN,NaN,500874.0,576397.0,NaN,2,...,3,R,L,2889,Busch Stadium,UN,1,0,0,100 2
184907,"Carpenter, M",572761,Home Run,500874.0,576397.0,NaN,NaN,NaN,NaN,2,...,3,L,L,2889,Busch Stadium,1B,1,1,0,110 2
184908,"Diaz, A",649557,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,3,R,R,2889,Busch Stadium,SS,0,0,0,000 2
184909,"Frazier, A",624428,Single,NaN,NaN,NaN,624428.0,NaN,NaN,0,...,3,L,R,2889,Busch Stadium,UN,0,0,0,000 0
184910,Jaso,444379,Home Run,624428.0,NaN,NaN,NaN,NaN,NaN,0,...,3,L,R,2889,Busch Stadium,1B,1,0,0,100 0
184911,"Polanco, G",570256,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,3,L,R,2889,Busch Stadium,RF,0,0,0,000 0
184912,McCutchen,457705,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,3,R,R,2889,Busch Stadium,CF,0,0,0,000 1
184913,Kang,628356,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,3,R,R,2889,Busch Stadium,3B,0,0,0,000 2
184914,Molina,425877,Double,NaN,NaN,NaN,NaN,425877.0,NaN,0,...,3,R,R,2889,Busch Stadium,C,0,0,0,000 0
184915,Piscotty,572039,Single,NaN,425877.0,NaN,572039.0,NaN,NaN,0,...,3,R,R,2889,Busch Stadium,RF,0,1,0,010 0
184916,"Peralta, J",425509,Single,572039.0,NaN,NaN,425509.0,572039.0,NaN,0,...,3,R,R,2889,Busch Stadium,3B,1,0,0,100 0
184917,Moss,461235,Single,425509.0,572039.0,NaN,461235.0,425509.0,572039.0,0,...,3,L,L,2889,Busch Stadium,LF,1,1,0,110 0
184918,Gyorko,576397,Field Error,461235.0,425509.0,572039.0,576397.0,461235.0,425509.0,0,...,3,R,L,2889,Busch Stadium,2B,1,1,1,111 0
184919,Grichuk,545341,Double,576397.0,461235.0,425509.0,NaN,545341.0,576397.0,0,...,3,R,L,2889,Busch Stadium,CF,1,1,1,111 0
184920,Adams,571431,Sac Fly,NaN,545341.0,576397.0,NaN,NaN,545341.0,0,...,3,L,L,2889,Busch Stadium,UN,0,1,1,011 0
184921,"Carpenter, M",572761,Sac Fly,NaN,NaN,545341.0,NaN,NaN,NaN,1,...,3,L,L,2889,Busch Stadium,1B,0,0,1,001 1
184922,"Diaz, A",649557,Pop Out,NaN,NaN,NaN,NaN,NaN,NaN,2,...,3,R,L,2889,Busch Stadium,SS,0,0,0,000 2
184923,Joyce,459964,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,3,L,L,2889,Busch Stadium,LF,0,0,0,000 0
184924,Hanson,593700,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,3,R,L,2889,Busch Stadium,2B,0,0,0,000 1
184925,Fryer,518700,Single,NaN,NaN,NaN,518700.0,NaN,NaN,2,...,3,R,L,2889,Busch Stadium,C,0,0,0,000 2
184926,Florimon,465753,Groundout,518700.0,NaN,NaN,NaN,NaN,NaN,2,...,3,R,L,2889,Busch Stadium,SS,1,0,0,100 2
184927,Molina,425877,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,3,R,R,2889,Busch Stadium,C,0,0,0,000 0
184928,Piscotty,572039,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,3,R,R,2889,Busch Stadium,RF,0,0,0,000 1
184929,"Garcia, G",594824,Single,NaN,NaN,NaN,594824.0,NaN,NaN,2,...,3,L,R,2889,Busch Stadium,UN,0,0,0,000 2
184930,Moss,461235,Strikeout,594824.0,NaN,NaN,NaN,NaN,NaN,2,...,3,L,R,2889,Busch Stadium,LF,1,0,0,100 2
184931,"Rogers, J",595386,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,3,R,L,2889,Busch Stadium,UN,0,0,0,000 0
184932,Jaso,444379,Walk,NaN,NaN,NaN,444379.0,NaN,NaN,1,...,3,L,L,2889,Busch Stadium,1B,0,0,0,000 1
184933,"Polanco, G",570256,Strikeout,444379.0,NaN,NaN,444379.0,NaN,NaN,1,...,3,L,L,2889,Busch Stadium,RF,1,0,0,100 1
184934,McCutchen,457705,Groundout,444379.0,NaN,NaN,NaN,NaN,NaN,2,...,3,R,L,2889,Busch Stadium,CF,1,0,0,100 2

In [ ]:
# 5.	Create three indicator variables (one for each base) to denote whether or not each base is occupied after the plate appearance

In [28]:
# Create indicator variables to determine whether base is occupied after plate appearance
RE16['End1'] = np.where(pd.isnull(RE16['end1B']),0,1)
RE16['End2'] = np.where(pd.isnull(RE16['end2B']),0,1)
RE16['End3'] = np.where(pd.isnull(RE16['end3B']),0,1)

In [ ]:
# 6.	Create an “end state” variable to denote the base out state after each plate appearance

In [29]:
# Create ending base out state for plate appearance
RE16['End_State'] = (RE16['End1'].astype(str) + RE16['End2'].astype(str) + RE16['End3'].astype(str)+\
                     " " + RE16['endOuts'].astype(str))
RE16

,batterName,batterId,event,start1B,start2B,start3B,end1B,end2B,end3B,startOuts,...,stadium,batterPos,Start1,Start2,Start3,Start_State,End1,End2,End3,End_State
0,"Carpenter, M",572761,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,PNC Park,3B,0,0,0,000 0,0,0,0,000 1
1,Pham,502054,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,PNC Park,LF,0,0,0,000 1,0,0,0,000 2
2,Holliday,407812,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,PNC Park,1B,0,0,0,000 2,0,0,0,000 3
3,Jaso,444379,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,PNC Park,1B,0,0,0,000 0,0,0,0,000 1
4,McCutchen,457705,Hit By Pitch,NaN,NaN,NaN,457705.0,NaN,NaN,1,...,PNC Park,CF,0,0,0,000 1,1,0,0,100 1
5,Freese,501896,Single,457705.0,NaN,NaN,501896.0,NaN,457705.0,1,...,PNC Park,3B,1,0,0,100 1,1,0,1,101 1
6,"Marte, S",516782,Lineout,501896.0,NaN,457705.0,501896.0,NaN,457705.0,1,...,PNC Park,LF,1,0,1,101 1,1,0,1,101 2
7,Cervelli,465041,Pop Out,501896.0,NaN,457705.0,NaN,NaN,NaN,2,...,PNC Park,C,1,0,1,101 2,0,0,0,000 3
8,Grichuk,545341,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,PNC Park,CF,0,0,0,000 0,0,0,0,000 1
9,Piscotty,572039,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,PNC Park,RF,0,0,0,000 1,0,0,0,000 2
10,Molina,425877,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,PNC Park,C,0,0,0,000 2,0,0,0,000 3
11,"Polanco, G",570256,Double,NaN,NaN,NaN,NaN,570256.0,NaN,0,...,PNC Park,RF,0,0,0,000 0,0,1,0,010 0
12,Harrison,543281,Groundout,NaN,570256.0,NaN,NaN,NaN,570256.0,0,...,PNC Park,2B,0,1,0,010 0,0,0,1,001 1
13,Mercer,474568,Walk,NaN,NaN,570256.0,474568.0,NaN,570256.0,1,...,PNC Park,SS,0,0,1,001 1,1,0,1,101 1
14,Liriano,434538,Single,474568.0,NaN,570256.0,434538.0,474568.0,NaN,1,...,PNC Park,P,1,0,1,101 1,1,1,0,110 1
15,Jaso,444379,Single,434538.0,474568.0,NaN,444379.0,434538.0,NaN,1,...,PNC Park,1B,1,1,0,110 1,1,1,0,110 1
16,McCutchen,457705,Flyout,444379.0,434538.0,NaN,444379.0,434538.0,NaN,1,...,PNC Park,CF,1,1,0,110 1,1,1,0,110 2
17,Freese,501896,Groundout,444379.0,434538.0,NaN,NaN,NaN,NaN,2,...,PNC Park,3B,1,1,0,110 2,0,0,0,000 3
18,Wong,543939,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,PNC Park,2B,0,0,0,000 0,0,0,0,000 1
19,Gyorko,576397,Walk,NaN,NaN,NaN,576397.0,NaN,NaN,1,...,PNC Park,SS,0,0,0,000 1,1,0,0,100 1
20,Wainwright,425794,Field Error,576397.0,NaN,NaN,425794.0,NaN,576397.0,1,...,PNC Park,P,1,0,0,100 1,1,0,1,101 1
21,"Carpenter, M",572761,Grounded Into DP,425794.0,NaN,576397.0,NaN,NaN,NaN,1,...,PNC Park,3B,1,0,1,101 1,0,0,0,000 3
22,"Marte, S",516782,Lineout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,PNC Park,LF,0,0,0,000 0,0,0,0,000 1
23,Cervelli,465041,Walk,NaN,NaN,NaN,465041.0,NaN,NaN,1,...,PNC Park,C,0,0,0,000 1,1,0,0,100 1
24,"Polanco, G",570256,Flyout,465041.0,NaN,NaN,465041.0,NaN,NaN,1,...,PNC Park,RF,1,0,0,100 1,1,0,0,100 2
25,Harrison,543281,Strikeout,465041.0,NaN,NaN,NaN,NaN,NaN,2,...,PNC Park,2B,1,0,0,100 2,0,0,0,000 3
26,Adams,571431,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,PNC Park,UN,0,0,0,000 0,0,0,0,000 1
27,Holliday,407812,Single,NaN,NaN,NaN,407812.0,NaN,NaN,1,...,PNC Park,1B,0,0,0,000 1,1,0,0,100 1
28,Grichuk,545341,Single,407812.0,NaN,NaN,545341.0,407812.0,NaN,1,...,PNC Park,CF,1,0,0,100 1,1,1,0,110 1
29,Piscotty,572039,Strikeout,545341.0,407812.0,NaN,545341.0,407812.0,NaN,1,...,PNC Park,RF,1,1,0,110 1,1,1,0,110 2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184905,Grichuk,545341,Strikeout,576397.0,NaN,NaN,576397.0,NaN,NaN,1,...,Busch Stadium,CF,1,0,0,100 1,1,0,0,100 2
184906,"Martinez, Jo",500874,Single,576397.0,NaN,NaN,500874.0,576397.0,NaN,2,...,Busch Stadium,UN,1,0,0,100 2,1,1,0,110 2
184907,"Carpenter, M",572761,Home Run,500874.0,576397.0,NaN,NaN,NaN,NaN,2,...,Busch Stadium,1B,1,1,0,110 2,0,0,0,000 2
184908,"Diaz, A",649557,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,Busch Stadium,SS,0,0,0,000 2,0,0,0,000 3
184909,"Frazier, A",624428,Single,NaN,NaN,NaN,624428.0,NaN,NaN,0,...,Busch Stadium,UN,0,0,0,000 0,1,0,0,100 0
184910,Jaso,444379,Home Run,624428.0,NaN,NaN,NaN,NaN,NaN,0,...,Busch Stadium,1B,1,0,0,100 0,0,0,0,000 0
184911,"Polanco, G",570256,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,Busch Stadium,RF,0,0,0,000 0,0,0,0,000 1
184912,McCutchen,457705,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,Busch Stadium,CF,0,0,0,000 1,0,0,0,000 2
184913,Kang,628356,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,Busch Stadium,3B,0,0,0,000 2,0,0,0,000 3
184914,Molina,425877,Double,NaN,NaN,NaN,NaN,425877.0,NaN,0,...,Busch Stadium,C,0,0,0,000 0,0,1,0,010 0
184915,Piscotty,572039,Single,NaN,425877.0,NaN,572039.0,NaN,NaN,0,...,Busch Stadium,RF,0,1,0,010 0,1,0,0,100 0
184916,"Peralta, J",425509,Single,572039.0,NaN,NaN,425509.0,572039.0,NaN,0,...,Busch Stadium,3B,1,0,0,100 0,1,1,0,110 0
184917,Moss,461235,Single,425509.0,572039.0,NaN,461235.0,425509.0,572039.0,0,...,Busch Stadium,LF,1,1,0,110 0,1,1,1,111 0
184918,Gyorko,576397,Field Error,461235.0,425509.0,572039.0,576397.0,461235.0,425509.0,0,...,Busch Stadium,2B,1,1,1,111 0,1,1,1,111 0
184919,Grichuk,545341,Double,576397.0,461235.0,425509.0,NaN,545341.0,576397.0,0,...,Busch Stadium,CF,1,1,1,111 0,0,1,1,011 0
184920,Adams,571431,Sac Fly,NaN,545341.0,576397.0,NaN,NaN,545341.0,0,...,Busch Stadium,UN,0,1,1,011 0,0,0,1,001 1
184921,"Carpenter, M",572761,Sac Fly,NaN,NaN,545341.0,NaN,NaN,NaN,1,...,Busch Stadium,1B,0,0,1,001 1,0,0,0,000 2
184922,"Diaz, A",649557,Pop Out,NaN,NaN,NaN,NaN,NaN,NaN,2,...,Busch Stadium,SS,0,0,0,000 2,0,0,0,000 3
184923,Joyce,459964,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,Busch Stadium,LF,0,0,0,000 0,0,0,0,000 1
184924,Hanson,593700,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,Busch Stadium,2B,0,0,0,000 1,0,0,0,000 2
184925,Fryer,518700,Single,NaN,NaN,NaN,518700.0,NaN,NaN,2,...,Busch Stadium,C,0,0,0,000 2,1,0,0,100 2
184926,Florimon,465753,Groundout,518700.0,NaN,NaN,NaN,NaN,NaN,2,...,Busch Stadium,SS,1,0,0,100 2,0,0,0,000 3
184927,Molina,425877,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,Busch Stadium,C,0,0,0,000 0,0,0,0,000 1
184928,Piscotty,572039,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,Busch Stadium,RF,0,0,0,000 1,0,0,0,000 2
184929,"Garcia, G",594824,Single,NaN,NaN,NaN,594824.0,NaN,NaN,2,...,Busch Stadium,UN,0,0,0,000 2,1,0,0,100 2
184930,Moss,461235,Strikeout,594824.0,NaN,NaN,NaN,NaN,NaN,2,...,Busch Stadium,LF,1,0,0,100 2,0,0,0,000 3
184931,"Rogers, J",595386,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,Busch Stadium,UN,0,0,0,000 0,0,0,0,000 1
184932,Jaso,444379,Walk,NaN,NaN,NaN,444379.0,NaN,NaN,1,...,Busch Stadium,1B,0,0,0,000 1,1,0,0,100 1
184933,"Polanco, G",570256,Strikeout,444379.0,NaN,NaN,444379.0,NaN,NaN,1,...,Busch Stadium,RF,1,0,0,100 1,1,0,0,100 2
184934,McCutchen,457705,Groundout,444379.0,NaN,NaN,NaN,NaN,NaN,2,...,Busch Stadium,CF,1,0,0,100 2,0,0,0,000 3

In [ ]:
# 7.	Restrict data to plays where either there is a change in state/runs scored and innings in which there were exactly 3 outs recorded

In [30]:
# Restrict data to plays where either there is a change in state or runs scored and innings that had exactly 3 outs
RE16 = RE16[((RE16.Start_State != RE16.End_State) | (RE16.runsOnPlay > 0)) & (RE16.outsInInning == 3)]
display(RE16)

,batterName,batterId,event,start1B,start2B,start3B,end1B,end2B,end3B,startOuts,...,stadium,batterPos,Start1,Start2,Start3,Start_State,End1,End2,End3,End_State
0,"Carpenter, M",572761,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,PNC Park,3B,0,0,0,000 0,0,0,0,000 1
1,Pham,502054,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,PNC Park,LF,0,0,0,000 1,0,0,0,000 2
2,Holliday,407812,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,PNC Park,1B,0,0,0,000 2,0,0,0,000 3
3,Jaso,444379,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,PNC Park,1B,0,0,0,000 0,0,0,0,000 1
4,McCutchen,457705,Hit By Pitch,NaN,NaN,NaN,457705.0,NaN,NaN,1,...,PNC Park,CF,0,0,0,000 1,1,0,0,100 1
5,Freese,501896,Single,457705.0,NaN,NaN,501896.0,NaN,457705.0,1,...,PNC Park,3B,1,0,0,100 1,1,0,1,101 1
6,"Marte, S",516782,Lineout,501896.0,NaN,457705.0,501896.0,NaN,457705.0,1,...,PNC Park,LF,1,0,1,101 1,1,0,1,101 2
7,Cervelli,465041,Pop Out,501896.0,NaN,457705.0,NaN,NaN,NaN,2,...,PNC Park,C,1,0,1,101 2,0,0,0,000 3
8,Grichuk,545341,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,PNC Park,CF,0,0,0,000 0,0,0,0,000 1
9,Piscotty,572039,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,PNC Park,RF,0,0,0,000 1,0,0,0,000 2
10,Molina,425877,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,PNC Park,C,0,0,0,000 2,0,0,0,000 3
11,"Polanco, G",570256,Double,NaN,NaN,NaN,NaN,570256.0,NaN,0,...,PNC Park,RF,0,0,0,000 0,0,1,0,010 0
12,Harrison,543281,Groundout,NaN,570256.0,NaN,NaN,NaN,570256.0,0,...,PNC Park,2B,0,1,0,010 0,0,0,1,001 1
13,Mercer,474568,Walk,NaN,NaN,570256.0,474568.0,NaN,570256.0,1,...,PNC Park,SS,0,0,1,001 1,1,0,1,101 1
14,Liriano,434538,Single,474568.0,NaN,570256.0,434538.0,474568.0,NaN,1,...,PNC Park,P,1,0,1,101 1,1,1,0,110 1
15,Jaso,444379,Single,434538.0,474568.0,NaN,444379.0,434538.0,NaN,1,...,PNC Park,1B,1,1,0,110 1,1,1,0,110 1
16,McCutchen,457705,Flyout,444379.0,434538.0,NaN,444379.0,434538.0,NaN,1,...,PNC Park,CF,1,1,0,110 1,1,1,0,110 2
17,Freese,501896,Groundout,444379.0,434538.0,NaN,NaN,NaN,NaN,2,...,PNC Park,3B,1,1,0,110 2,0,0,0,000 3
18,Wong,543939,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,PNC Park,2B,0,0,0,000 0,0,0,0,000 1
19,Gyorko,576397,Walk,NaN,NaN,NaN,576397.0,NaN,NaN,1,...,PNC Park,SS,0,0,0,000 1,1,0,0,100 1
20,Wainwright,425794,Field Error,576397.0,NaN,NaN,425794.0,NaN,576397.0,1,...,PNC Park,P,1,0,0,100 1,1,0,1,101 1
21,"Carpenter, M",572761,Grounded Into DP,425794.0,NaN,576397.0,NaN,NaN,NaN,1,...,PNC Park,3B,1,0,1,101 1,0,0,0,000 3
22,"Marte, S",516782,Lineout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,PNC Park,LF,0,0,0,000 0,0,0,0,000 1
23,Cervelli,465041,Walk,NaN,NaN,NaN,465041.0,NaN,NaN,1,...,PNC Park,C,0,0,0,000 1,1,0,0,100 1
24,"Polanco, G",570256,Flyout,465041.0,NaN,NaN,465041.0,NaN,NaN,1,...,PNC Park,RF,1,0,0,100 1,1,0,0,100 2
25,Harrison,543281,Strikeout,465041.0,NaN,NaN,NaN,NaN,NaN,2,...,PNC Park,2B,1,0,0,100 2,0,0,0,000 3
26,Adams,571431,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,PNC Park,UN,0,0,0,000 0,0,0,0,000 1
27,Holliday,407812,Single,NaN,NaN,NaN,407812.0,NaN,NaN,1,...,PNC Park,1B,0,0,0,000 1,1,0,0,100 1
28,Grichuk,545341,Single,407812.0,NaN,NaN,545341.0,407812.0,NaN,1,...,PNC Park,CF,1,0,0,100 1,1,1,0,110 1
29,Piscotty,572039,Strikeout,545341.0,407812.0,NaN,545341.0,407812.0,NaN,1,...,PNC Park,RF,1,1,0,110 1,1,1,0,110 2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184905,Grichuk,545341,Strikeout,576397.0,NaN,NaN,576397.0,NaN,NaN,1,...,Busch Stadium,CF,1,0,0,100 1,1,0,0,100 2
184906,"Martinez, Jo",500874,Single,576397.0,NaN,NaN,500874.0,576397.0,NaN,2,...,Busch Stadium,UN,1,0,0,100 2,1,1,0,110 2
184907,"Carpenter, M",572761,Home Run,500874.0,576397.0,NaN,NaN,NaN,NaN,2,...,Busch Stadium,1B,1,1,0,110 2,0,0,0,000 2
184908,"Diaz, A",649557,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,Busch Stadium,SS,0,0,0,000 2,0,0,0,000 3
184909,"Frazier, A",624428,Single,NaN,NaN,NaN,624428.0,NaN,NaN,0,...,Busch Stadium,UN,0,0,0,000 0,1,0,0,100 0
184910,Jaso,444379,Home Run,624428.0,NaN,NaN,NaN,NaN,NaN,0,...,Busch Stadium,1B,1,0,0,100 0,0,0,0,000 0
184911,"Polanco, G",570256,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,Busch Stadium,RF,0,0,0,000 0,0,0,0,000 1
184912,McCutchen,457705,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,Busch Stadium,CF,0,0,0,000 1,0,0,0,000 2
184913,Kang,628356,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,Busch Stadium,3B,0,0,0,000 2,0,0,0,000 3
184914,Molina,425877,Double,NaN,NaN,NaN,NaN,425877.0,NaN,0,...,Busch Stadium,C,0,0,0,000 0,0,1,0,010 0
184915,Piscotty,572039,Single,NaN,425877.0,NaN,572039.0,NaN,NaN,0,...,Busch Stadium,RF,0,1,0,010 0,1,0,0,100 0
184916,"Peralta, J",425509,Single,572039.0,NaN,NaN,425509.0,572039.0,NaN,0,...,Busch Stadium,3B,1,0,0,100 0,1,1,0,110 0
184917,Moss,461235,Single,425509.0,572039.0,NaN,461235.0,425509.0,572039.0,0,...,Busch Stadium,LF,1,1,0,110 0,1,1,1,111 0
184918,Gyorko,576397,Field Error,461235.0,425509.0,572039.0,576397.0,461235.0,425509.0,0,...,Busch Stadium,2B,1,1,1,111 0,1,1,1,111 0
184919,Grichuk,545341,Double,576397.0,461235.0,425509.0,NaN,545341.0,576397.0,0,...,Busch Stadium,CF,1,1,1,111 0,0,1,1,011 0
184920,Adams,571431,Sac Fly,NaN,545341.0,576397.0,NaN,NaN,545341.0,0,...,Busch Stadium,UN,0,1,1,011 0,0,0,1,001 1
184921,"Carpenter, M",572761,Sac Fly,NaN,NaN,545341.0,NaN,NaN,NaN,1,...,Busch Stadium,1B,0,0,1,001 1,0,0,0,000 2
184922,"Diaz, A",649557,Pop Out,NaN,NaN,NaN,NaN,NaN,NaN,2,...,Busch Stadium,SS,0,0,0,000 2,0,0,0,000 3
184923,Joyce,459964,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,Busch Stadium,LF,0,0,0,000 0,0,0,0,000 1
184924,Hanson,593700,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,Busch Stadium,2B,0,0,0,000 1,0,0,0,000 2
184925,Fryer,518700,Single,NaN,NaN,NaN,518700.0,NaN,NaN,2,...,Busch Stadium,C,0,0,0,000 2,1,0,0,100 2
184926,Florimon,465753,Groundout,518700.0,NaN,NaN,NaN,NaN,NaN,2,...,Busch Stadium,SS,1,0,0,100 2,0,0,0,000 3
184927,Molina,425877,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,Busch Stadium,C,0,0,0,000 0,0,0,0,000 1
184928,Piscotty,572039,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,Busch Stadium,RF,0,0,0,000 1,0,0,0,000 2
184929,"Garcia, G",594824,Single,NaN,NaN,NaN,594824.0,NaN,NaN,2,...,Busch Stadium,UN,0,0,0,000 2,1,0,0,100 2
184930,Moss,461235,Strikeout,594824.0,NaN,NaN,NaN,NaN,NaN,2,...,Busch Stadium,LF,1,0,0,100 2,0,0,0,000 3
184931,"Rogers, J",595386,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,Busch Stadium,UN,0,0,0,000 0,0,0,0,000 1
184932,Jaso,444379,Walk,NaN,NaN,NaN,444379.0,NaN,NaN,1,...,Busch Stadium,1B,0,0,0,000 1,1,0,0,100 1
184933,"Polanco, G",570256,Strikeout,444379.0,NaN,NaN,444379.0,NaN,NaN,1,...,Busch Stadium,RF,1,0,0,100 1,1,0,0,100 2
184934,McCutchen,457705,Groundout,444379.0,NaN,NaN,NaN,NaN,NaN,2,...,Busch Stadium,CF,1,0,0,100 2,0,0,0,000 3

In [ ]:
# 8.	Calculate run expectancy by starting state and merge this into play by play data

In [31]:
# Calculate run expectancy by starting state and merge into play by play data
Start_RunExp = RE16.groupby(['Start_State'])['runsFuture'].mean().reset_index().rename(columns={'runsFuture':'Start_RE'})
RE16 = pd.merge(RE16, Start_RunExp, on=['Start_State'], how='left')
display(RE16)

,batterName,batterId,event,start1B,start2B,start3B,end1B,end2B,end3B,startOuts,...,batterPos,Start1,Start2,Start3,Start_State,End1,End2,End3,End_State,Start_RE
0,"Carpenter, M",572761,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,3B,0,0,0,000 0,0,0,0,000 1,0.498377
1,Pham,502054,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,LF,0,0,0,000 1,0,0,0,000 2,0.268678
2,Holliday,407812,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,1B,0,0,0,000 2,0,0,0,000 3,0.106305
3,Jaso,444379,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,1B,0,0,0,000 0,0,0,0,000 1,0.498377
4,McCutchen,457705,Hit By Pitch,NaN,NaN,NaN,457705.0,NaN,NaN,1,...,CF,0,0,0,000 1,1,0,0,100 1,0.268678
5,Freese,501896,Single,457705.0,NaN,NaN,501896.0,NaN,457705.0,1,...,3B,1,0,0,100 1,1,0,1,101 1,0.512225
6,"Marte, S",516782,Lineout,501896.0,NaN,457705.0,501896.0,NaN,457705.0,1,...,LF,1,0,1,101 1,1,0,1,101 2,1.196777
7,Cervelli,465041,Pop Out,501896.0,NaN,457705.0,NaN,NaN,NaN,2,...,C,1,0,1,101 2,0,0,0,000 3,0.480175
8,Grichuk,545341,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,CF,0,0,0,000 0,0,0,0,000 1,0.498377
9,Piscotty,572039,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,RF,0,0,0,000 1,0,0,0,000 2,0.268678
10,Molina,425877,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,C,0,0,0,000 2,0,0,0,000 3,0.106305
11,"Polanco, G",570256,Double,NaN,NaN,NaN,NaN,570256.0,NaN,0,...,RF,0,0,0,000 0,0,1,0,010 0,0.498377
12,Harrison,543281,Groundout,NaN,570256.0,NaN,NaN,NaN,570256.0,0,...,2B,0,1,0,010 0,0,0,1,001 1,1.132468
13,Mercer,474568,Walk,NaN,NaN,570256.0,474568.0,NaN,570256.0,1,...,SS,0,0,1,001 1,1,0,1,101 1,0.948684
14,Liriano,434538,Single,474568.0,NaN,570256.0,434538.0,474568.0,NaN,1,...,P,1,0,1,101 1,1,1,0,110 1,1.196777
15,Jaso,444379,Single,434538.0,474568.0,NaN,444379.0,434538.0,NaN,1,...,1B,1,1,0,110 1,1,1,0,110 1,0.922572
16,McCutchen,457705,Flyout,444379.0,434538.0,NaN,444379.0,434538.0,NaN,1,...,CF,1,1,0,110 1,1,1,0,110 2,0.922572
17,Freese,501896,Groundout,444379.0,434538.0,NaN,NaN,NaN,NaN,2,...,3B,1,1,0,110 2,0,0,0,000 3,0.414466
18,Wong,543939,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,2B,0,0,0,000 0,0,0,0,000 1,0.498377
19,Gyorko,576397,Walk,NaN,NaN,NaN,576397.0,NaN,NaN,1,...,SS,0,0,0,000 1,1,0,0,100 1,0.268678
20,Wainwright,425794,Field Error,576397.0,NaN,NaN,425794.0,NaN,576397.0,1,...,P,1,0,0,100 1,1,0,1,101 1,0.512225
21,"Carpenter, M",572761,Grounded Into DP,425794.0,NaN,576397.0,NaN,NaN,NaN,1,...,3B,1,0,1,101 1,0,0,0,000 3,1.196777
22,"Marte, S",516782,Lineout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,LF,0,0,0,000 0,0,0,0,000 1,0.498377
23,Cervelli,465041,Walk,NaN,NaN,NaN,465041.0,NaN,NaN,1,...,C,0,0,0,000 1,1,0,0,100 1,0.268678
24,"Polanco, G",570256,Flyout,465041.0,NaN,NaN,465041.0,NaN,NaN,1,...,RF,1,0,0,100 1,1,0,0,100 2,0.512225
25,Harrison,543281,Strikeout,465041.0,NaN,NaN,NaN,NaN,NaN,2,...,2B,1,0,0,100 2,0,0,0,000 3,0.220539
26,Adams,571431,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,UN,0,0,0,000 0,0,0,0,000 1,0.498377
27,Holliday,407812,Single,NaN,NaN,NaN,407812.0,NaN,NaN,1,...,1B,0,0,0,000 1,1,0,0,100 1,0.268678
28,Grichuk,545341,Single,407812.0,NaN,NaN,545341.0,407812.0,NaN,1,...,CF,1,0,0,100 1,1,1,0,110 1,0.512225
29,Piscotty,572039,Strikeout,545341.0,407812.0,NaN,545341.0,407812.0,NaN,1,...,RF,1,1,0,110 1,1,1,0,110 2,0.922572
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184122,Grichuk,545341,Strikeout,576397.0,NaN,NaN,576397.0,NaN,NaN,1,...,CF,1,0,0,100 1,1,0,0,100 2,0.512225
184123,"Martinez, Jo",500874,Single,576397.0,NaN,NaN,500874.0,576397.0,NaN,2,...,UN,1,0,0,100 2,1,1,0,110 2,0.220539
184124,"Carpenter, M",572761,Home Run,500874.0,576397.0,NaN,NaN,NaN,NaN,2,...,1B,1,1,0,110 2,0,0,0,000 2,0.414466
184125,"Diaz, A",649557,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,SS,0,0,0,000 2,0,0,0,000 3,0.106305
184126,"Frazier, A",624428,Single,NaN,NaN,NaN,624428.0,NaN,NaN,0,...,UN,0,0,0,000 0,1,0,0,100 0,0.498377
184127,Jaso,444379,Home Run,624428.0,NaN,NaN,NaN,NaN,NaN,0,...,1B,1,0,0,100 0,0,0,0,000 0,0.858504
184128,"Polanco, G",570256,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,RF,0,0,0,000 0,0,0,0,000 1,0.498377
184129,McCutchen,457705,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,CF,0,0,0,000 1,0,0,0,000 2,0.268678
184130,Kang,628356,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,3B,0,0,0,000 2,0,0,0,000 3,0.106305
184131,Molina,425877,Double,NaN,NaN,NaN,NaN,425877.0,NaN,0,...,C,0,0,0,000 0,0,1,0,010 0,0.498377
184132,Piscotty,572039,Single,NaN,425877.0,NaN,572039.0,NaN,NaN,0,...,RF,0,1,0,010 0,1,0,0,100 0,1.132468
184133,"Peralta, J",425509,Single,572039.0,NaN,NaN,425509.0,572039.0,NaN,0,...,3B,1,0,0,100 0,1,1,0,110 0,0.858504
184134,Moss,461235,Single,425509.0,572039.0,NaN,461235.0,425509.0,572039.0,0,...,LF,1,1,0,110 0,1,1,1,111 0,1.447597
184135,Gyorko,576397,Field Error,461235.0,425509.0,572039.0,576397.0,461235.0,425509.0,0,...,2B,1,1,1,111 0,1,1,1,111 0,2.112409
184136,Grichuk,545341,Double,576397.0,461235.0,425509.0,NaN,545341.0,576397.0,0,...,CF,1,1,1,111 0,0,1,1,011 0,2.112409
184137,Adams,571431,Sac Fly,NaN,545341.0,576397.0,NaN,NaN,545341.0,0,...,UN,0,1,1,011 0,0,0,1,001 1,1.916190
184138,"Carpenter, M",572761,Sac Fly,NaN,NaN,545341.0,NaN,NaN,NaN,1,...,1B,0,0,1,001 1,0,0,0,000 2,0.948684
184139,"Diaz, A",649557,Pop Out,NaN,NaN,NaN,NaN,NaN,NaN,2,...,SS,0,0,0,000 2,0,0,0,000 3,0.106305
184140,Joyce,459964,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,LF,0,0,0,000 0,0,0,0,000 1,0.498377
184141,Hanson,593700,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,2B,0,0,0,000 1,0,0,0,000 2,0.268678
184142,Fryer,518700,Single,NaN,NaN,NaN,518700.0,NaN,NaN,2,...,C,0,0,0,000 2,1,0,0,100 2,0.106305
184143,Florimon,465753,Groundout,518700.0,NaN,NaN,NaN,NaN,NaN,2,...,SS,1,0,0,100 2,0,0,0,000 3,0.220539
184144,Molina,425877,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,C,0,0,0,000 0,0,0,0,000 1,0.498377
184145,Piscotty,572039,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,RF,0,0,0,000 1,0,0,0,000 2,0.268678
184146,"Garcia, G",594824,Single,NaN,NaN,NaN,594824.0,NaN,NaN,2,...,UN,0,0,0,000 2,1,0,0,100 2,0.106305
184147,Moss,461235,Strikeout,594824.0,NaN,NaN,NaN,NaN,NaN,2,...,LF,1,0,0,100 2,0,0,0,000 3,0.220539
184148,"Rogers, J",595386,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,UN,0,0,0,000 0,0,0,0,000 1,0.498377
184149,Jaso,444379,Walk,NaN,NaN,NaN,444379.0,NaN,NaN,1,...,1B,0,0,0,000 1,1,0,0,100 1,0.268678
184150,"Polanco, G",570256,Strikeout,444379.0,NaN,NaN,444379.0,NaN,NaN,1,...,RF,1,0,0,100 1,1,0,0,100 2,0.512225
184151,McCutchen,457705,Groundout,444379.0,NaN,NaN,NaN,NaN,NaN,2,...,CF,1,0,0,100 2,0,0,0,000 3,0.220539

In [ ]:
# 9.	Using the run expectancy data by starting state, create a variable to denote run expectancy by ending state 
# (in addition, make sure to include the base out states for which there are 3 outs with run expectancies of 0 to the run expectancy by ending state data)

In [32]:
# Code run expectancy values by end state using start state run expectancy including end states with 3 outs
Base_State_3 = [pd.Series(['000 3', 0], index=Start_RunExp.columns),
                pd.Series(['001 3', 0], index=Start_RunExp.columns),
                pd.Series(['010 3', 0], index=Start_RunExp.columns),
                pd.Series(['011 3', 0], index=Start_RunExp.columns),
                pd.Series(['100 3', 0], index=Start_RunExp.columns),
                pd.Series(['101 3', 0], index=Start_RunExp.columns),
                pd.Series(['110 3', 0], index=Start_RunExp.columns),
                pd.Series(['111 3', 0], index=Start_RunExp.columns)]

Start_RunExp = Start_RunExp.append(Base_State_3, ignore_index=True)

End_RunExp = Start_RunExp.rename(columns={'Start_State':'End_State', 'Start_RE':'End_RE'})

display(End_RunExp)

   End_State    End_RE
0      000 0  0.498377
1      000 1  0.268678
2      000 2  0.106305
3      001 0  1.358166
4      001 1  0.948684
5      001 2  0.377197
6      010 0  1.132468
7      010 1  0.677498
8      010 2  0.319844
9      011 0  1.916190
10     011 1  1.343899
11     011 2  0.587466
12     100 0  0.858504
13     100 1  0.512225
14     100 2  0.220539
15     101 0  1.728145
16     101 1  1.196777
17     101 2  0.480175
18     110 0  1.447597
19     110 1  0.922572
20     110 2  0.414466
21     111 0  2.112409
22     111 1  1.536937
23     111 2  0.696658
24     000 3  0.000000
25     001 3  0.000000
26     010 3  0.000000
27     011 3  0.000000
28     100 3  0.000000
29     101 3  0.000000
30     110 3  0.000000
31     111 3  0.000000

In [ ]:
# 10.	Merge the ending state run expectancy into the play by play data

In [33]:
# Merge into play by play data
RE16 = pd.merge(RE16, End_RunExp, on=['End_State'], how='left')
display(RE16)

,batterName,batterId,event,start1B,start2B,start3B,end1B,end2B,end3B,startOuts,...,Start1,Start2,Start3,Start_State,End1,End2,End3,End_State,Start_RE,End_RE
0,"Carpenter, M",572761,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,0,000 0,0,0,0,000 1,0.498377,0.268678
1,Pham,502054,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,0,000 1,0,0,0,000 2,0.268678,0.106305
2,Holliday,407812,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,0,0,0,000 2,0,0,0,000 3,0.106305,0.000000
3,Jaso,444379,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,0,000 0,0,0,0,000 1,0.498377,0.268678
4,McCutchen,457705,Hit By Pitch,NaN,NaN,NaN,457705.0,NaN,NaN,1,...,0,0,0,000 1,1,0,0,100 1,0.268678,0.512225
5,Freese,501896,Single,457705.0,NaN,NaN,501896.0,NaN,457705.0,1,...,1,0,0,100 1,1,0,1,101 1,0.512225,1.196777
6,"Marte, S",516782,Lineout,501896.0,NaN,457705.0,501896.0,NaN,457705.0,1,...,1,0,1,101 1,1,0,1,101 2,1.196777,0.480175
7,Cervelli,465041,Pop Out,501896.0,NaN,457705.0,NaN,NaN,NaN,2,...,1,0,1,101 2,0,0,0,000 3,0.480175,0.000000
8,Grichuk,545341,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,0,000 0,0,0,0,000 1,0.498377,0.268678
9,Piscotty,572039,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,0,000 1,0,0,0,000 2,0.268678,0.106305
10,Molina,425877,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,0,0,0,000 2,0,0,0,000 3,0.106305,0.000000
11,"Polanco, G",570256,Double,NaN,NaN,NaN,NaN,570256.0,NaN,0,...,0,0,0,000 0,0,1,0,010 0,0.498377,1.132468
12,Harrison,543281,Groundout,NaN,570256.0,NaN,NaN,NaN,570256.0,0,...,0,1,0,010 0,0,0,1,001 1,1.132468,0.948684
13,Mercer,474568,Walk,NaN,NaN,570256.0,474568.0,NaN,570256.0,1,...,0,0,1,001 1,1,0,1,101 1,0.948684,1.196777
14,Liriano,434538,Single,474568.0,NaN,570256.0,434538.0,474568.0,NaN,1,...,1,0,1,101 1,1,1,0,110 1,1.196777,0.922572
15,Jaso,444379,Single,434538.0,474568.0,NaN,444379.0,434538.0,NaN,1,...,1,1,0,110 1,1,1,0,110 1,0.922572,0.922572
16,McCutchen,457705,Flyout,444379.0,434538.0,NaN,444379.0,434538.0,NaN,1,...,1,1,0,110 1,1,1,0,110 2,0.922572,0.414466
17,Freese,501896,Groundout,444379.0,434538.0,NaN,NaN,NaN,NaN,2,...,1,1,0,110 2,0,0,0,000 3,0.414466,0.000000
18,Wong,543939,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,0,000 0,0,0,0,000 1,0.498377,0.268678
19,Gyorko,576397,Walk,NaN,NaN,NaN,576397.0,NaN,NaN,1,...,0,0,0,000 1,1,0,0,100 1,0.268678,0.512225
20,Wainwright,425794,Field Error,576397.0,NaN,NaN,425794.0,NaN,576397.0,1,...,1,0,0,100 1,1,0,1,101 1,0.512225,1.196777
21,"Carpenter, M",572761,Grounded Into DP,425794.0,NaN,576397.0,NaN,NaN,NaN,1,...,1,0,1,101 1,0,0,0,000 3,1.196777,0.000000
22,"Marte, S",516782,Lineout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,0,000 0,0,0,0,000 1,0.498377,0.268678
23,Cervelli,465041,Walk,NaN,NaN,NaN,465041.0,NaN,NaN,1,...,0,0,0,000 1,1,0,0,100 1,0.268678,0.512225
24,"Polanco, G",570256,Flyout,465041.0,NaN,NaN,465041.0,NaN,NaN,1,...,1,0,0,100 1,1,0,0,100 2,0.512225,0.220539
25,Harrison,543281,Strikeout,465041.0,NaN,NaN,NaN,NaN,NaN,2,...,1,0,0,100 2,0,0,0,000 3,0.220539,0.000000
26,Adams,571431,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,0,000 0,0,0,0,000 1,0.498377,0.268678
27,Holliday,407812,Single,NaN,NaN,NaN,407812.0,NaN,NaN,1,...,0,0,0,000 1,1,0,0,100 1,0.268678,0.512225
28,Grichuk,545341,Single,407812.0,NaN,NaN,545341.0,407812.0,NaN,1,...,1,0,0,100 1,1,1,0,110 1,0.512225,0.922572
29,Piscotty,572039,Strikeout,545341.0,407812.0,NaN,545341.0,407812.0,NaN,1,...,1,1,0,110 1,1,1,0,110 2,0.922572,0.414466
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184122,Grichuk,545341,Strikeout,576397.0,NaN,NaN,576397.0,NaN,NaN,1,...,1,0,0,100 1,1,0,0,100 2,0.512225,0.220539
184123,"Martinez, Jo",500874,Single,576397.0,NaN,NaN,500874.0,576397.0,NaN,2,...,1,0,0,100 2,1,1,0,110 2,0.220539,0.414466
184124,"Carpenter, M",572761,Home Run,500874.0,576397.0,NaN,NaN,NaN,NaN,2,...,1,1,0,110 2,0,0,0,000 2,0.414466,0.106305
184125,"Diaz, A",649557,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,0,0,0,000 2,0,0,0,000 3,0.106305,0.000000
184126,"Frazier, A",624428,Single,NaN,NaN,NaN,624428.0,NaN,NaN,0,...,0,0,0,000 0,1,0,0,100 0,0.498377,0.858504
184127,Jaso,444379,Home Run,624428.0,NaN,NaN,NaN,NaN,NaN,0,...,1,0,0,100 0,0,0,0,000 0,0.858504,0.498377
184128,"Polanco, G",570256,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,0,000 0,0,0,0,000 1,0.498377,0.268678
184129,McCutchen,457705,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,0,000 1,0,0,0,000 2,0.268678,0.106305
184130,Kang,628356,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,0,0,0,000 2,0,0,0,000 3,0.106305,0.000000
184131,Molina,425877,Double,NaN,NaN,NaN,NaN,425877.0,NaN,0,...,0,0,0,000 0,0,1,0,010 0,0.498377,1.132468
184132,Piscotty,572039,Single,NaN,425877.0,NaN,572039.0,NaN,NaN,0,...,0,1,0,010 0,1,0,0,100 0,1.132468,0.858504
184133,"Peralta, J",425509,Single,572039.0,NaN,NaN,425509.0,572039.0,NaN,0,...,1,0,0,100 0,1,1,0,110 0,0.858504,1.447597
184134,Moss,461235,Single,425509.0,572039.0,NaN,461235.0,425509.0,572039.0,0,...,1,1,0,110 0,1,1,1,111 0,1.447597,2.112409
184135,Gyorko,576397,Field Error,461235.0,425509.0,572039.0,576397.0,461235.0,425509.0,0,...,1,1,1,111 0,1,1,1,111 0,2.112409,2.112409
184136,Grichuk,545341,Double,576397.0,461235.0,425509.0,NaN,545341.0,576397.0,0,...,1,1,1,111 0,0,1,1,011 0,2.112409,1.916190
184137,Adams,571431,Sac Fly,NaN,545341.0,576397.0,NaN,NaN,545341.0,0,...,0,1,1,011 0,0,0,1,001 1,1.916190,0.948684
184138,"Carpenter, M",572761,Sac Fly,NaN,NaN,545341.0,NaN,NaN,NaN,1,...,0,0,1,001 1,0,0,0,000 2,0.948684,0.106305
184139,"Diaz, A",649557,Pop Out,NaN,NaN,NaN,NaN,NaN,NaN,2,...,0,0,0,000 2,0,0,0,000 3,0.106305,0.000000
184140,Joyce,459964,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,0,000 0,0,0,0,000 1,0.498377,0.268678
184141,Hanson,593700,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,0,000 1,0,0,0,000 2,0.268678,0.106305
184142,Fryer,518700,Single,NaN,NaN,NaN,518700.0,NaN,NaN,2,...,0,0,0,000 2,1,0,0,100 2,0.106305,0.220539
184143,Florimon,465753,Groundout,518700.0,NaN,NaN,NaN,NaN,NaN,2,...,1,0,0,100 2,0,0,0,000 3,0.220539,0.000000
184144,Molina,425877,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,0,000 0,0,0,0,000 1,0.498377,0.268678
184145,Piscotty,572039,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,0,000 1,0,0,0,000 2,0.268678,0.106305
184146,"Garcia, G",594824,Single,NaN,NaN,NaN,594824.0,NaN,NaN,2,...,0,0,0,000 2,1,0,0,100 2,0.106305,0.220539
184147,Moss,461235,Strikeout,594824.0,NaN,NaN,NaN,NaN,NaN,2,...,1,0,0,100 2,0,0,0,000 3,0.220539,0.000000
184148,"Rogers, J",595386,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,0,000 0,0,0,0,000 1,0.498377,0.268678
184149,Jaso,444379,Walk,NaN,NaN,NaN,444379.0,NaN,NaN,1,...,0,0,0,000 1,1,0,0,100 1,0.268678,0.512225
184150,"Polanco, G",570256,Strikeout,444379.0,NaN,NaN,444379.0,NaN,NaN,1,...,1,0,0,100 1,1,0,0,100 2,0.512225,0.220539
184151,McCutchen,457705,Groundout,444379.0,NaN,NaN,NaN,NaN,NaN,2,...,1,0,0,100 2,0,0,0,000 3,0.220539,0.000000

In [ ]:
# 11.	Calculate the run value of each event

In [34]:
# Run Value of each event
RE16['Run_Value'] = RE16['runsOnPlay'] + RE16['End_RE'] - RE16['Start_RE']

display(RE16)

,batterName,batterId,event,start1B,start2B,start3B,end1B,end2B,end3B,startOuts,...,Start2,Start3,Start_State,End1,End2,End3,End_State,Start_RE,End_RE,Run_Value
0,"Carpenter, M",572761,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,000 0,0,0,0,000 1,0.498377,0.268678,-0.229699
1,Pham,502054,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,000 1,0,0,0,000 2,0.268678,0.106305,-0.162373
2,Holliday,407812,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,0,0,000 2,0,0,0,000 3,0.106305,0.000000,-0.106305
3,Jaso,444379,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,000 0,0,0,0,000 1,0.498377,0.268678,-0.229699
4,McCutchen,457705,Hit By Pitch,NaN,NaN,NaN,457705.0,NaN,NaN,1,...,0,0,000 1,1,0,0,100 1,0.268678,0.512225,0.243547
5,Freese,501896,Single,457705.0,NaN,NaN,501896.0,NaN,457705.0,1,...,0,0,100 1,1,0,1,101 1,0.512225,1.196777,0.684552
6,"Marte, S",516782,Lineout,501896.0,NaN,457705.0,501896.0,NaN,457705.0,1,...,0,1,101 1,1,0,1,101 2,1.196777,0.480175,-0.716603
7,Cervelli,465041,Pop Out,501896.0,NaN,457705.0,NaN,NaN,NaN,2,...,0,1,101 2,0,0,0,000 3,0.480175,0.000000,-0.480175
8,Grichuk,545341,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,000 0,0,0,0,000 1,0.498377,0.268678,-0.229699
9,Piscotty,572039,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,000 1,0,0,0,000 2,0.268678,0.106305,-0.162373
10,Molina,425877,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,0,0,000 2,0,0,0,000 3,0.106305,0.000000,-0.106305
11,"Polanco, G",570256,Double,NaN,NaN,NaN,NaN,570256.0,NaN,0,...,0,0,000 0,0,1,0,010 0,0.498377,1.132468,0.634090
12,Harrison,543281,Groundout,NaN,570256.0,NaN,NaN,NaN,570256.0,0,...,1,0,010 0,0,0,1,001 1,1.132468,0.948684,-0.183783
13,Mercer,474568,Walk,NaN,NaN,570256.0,474568.0,NaN,570256.0,1,...,0,1,001 1,1,0,1,101 1,0.948684,1.196777,0.248093
14,Liriano,434538,Single,474568.0,NaN,570256.0,434538.0,474568.0,NaN,1,...,0,1,101 1,1,1,0,110 1,1.196777,0.922572,0.725795
15,Jaso,444379,Single,434538.0,474568.0,NaN,444379.0,434538.0,NaN,1,...,1,0,110 1,1,1,0,110 1,0.922572,0.922572,1.000000
16,McCutchen,457705,Flyout,444379.0,434538.0,NaN,444379.0,434538.0,NaN,1,...,1,0,110 1,1,1,0,110 2,0.922572,0.414466,-0.508107
17,Freese,501896,Groundout,444379.0,434538.0,NaN,NaN,NaN,NaN,2,...,1,0,110 2,0,0,0,000 3,0.414466,0.000000,-0.414466
18,Wong,543939,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,000 0,0,0,0,000 1,0.498377,0.268678,-0.229699
19,Gyorko,576397,Walk,NaN,NaN,NaN,576397.0,NaN,NaN,1,...,0,0,000 1,1,0,0,100 1,0.268678,0.512225,0.243547
20,Wainwright,425794,Field Error,576397.0,NaN,NaN,425794.0,NaN,576397.0,1,...,0,0,100 1,1,0,1,101 1,0.512225,1.196777,0.684552
21,"Carpenter, M",572761,Grounded Into DP,425794.0,NaN,576397.0,NaN,NaN,NaN,1,...,0,1,101 1,0,0,0,000 3,1.196777,0.000000,-1.196777
22,"Marte, S",516782,Lineout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,000 0,0,0,0,000 1,0.498377,0.268678,-0.229699
23,Cervelli,465041,Walk,NaN,NaN,NaN,465041.0,NaN,NaN,1,...,0,0,000 1,1,0,0,100 1,0.268678,0.512225,0.243547
24,"Polanco, G",570256,Flyout,465041.0,NaN,NaN,465041.0,NaN,NaN,1,...,0,0,100 1,1,0,0,100 2,0.512225,0.220539,-0.291686
25,Harrison,543281,Strikeout,465041.0,NaN,NaN,NaN,NaN,NaN,2,...,0,0,100 2,0,0,0,000 3,0.220539,0.000000,-0.220539
26,Adams,571431,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,000 0,0,0,0,000 1,0.498377,0.268678,-0.229699
27,Holliday,407812,Single,NaN,NaN,NaN,407812.0,NaN,NaN,1,...,0,0,000 1,1,0,0,100 1,0.268678,0.512225,0.243547
28,Grichuk,545341,Single,407812.0,NaN,NaN,545341.0,407812.0,NaN,1,...,0,0,100 1,1,1,0,110 1,0.512225,0.922572,0.410347
29,Piscotty,572039,Strikeout,545341.0,407812.0,NaN,545341.0,407812.0,NaN,1,...,1,0,110 1,1,1,0,110 2,0.922572,0.414466,-0.508107
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184122,Grichuk,545341,Strikeout,576397.0,NaN,NaN,576397.0,NaN,NaN,1,...,0,0,100 1,1,0,0,100 2,0.512225,0.220539,-0.291686
184123,"Martinez, Jo",500874,Single,576397.0,NaN,NaN,500874.0,576397.0,NaN,2,...,0,0,100 2,1,1,0,110 2,0.220539,0.414466,0.193926
184124,"Carpenter, M",572761,Home Run,500874.0,576397.0,NaN,NaN,NaN,NaN,2,...,1,0,110 2,0,0,0,000 2,0.414466,0.106305,2.691840
184125,"Diaz, A",649557,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,0,0,000 2,0,0,0,000 3,0.106305,0.000000,-0.106305
184126,"Frazier, A",624428,Single,NaN,NaN,NaN,624428.0,NaN,NaN,0,...,0,0,000 0,1,0,0,100 0,0.498377,0.858504,0.360127
184127,Jaso,444379,Home Run,624428.0,NaN,NaN,NaN,NaN,NaN,0,...,0,0,100 0,0,0,0,000 0,0.858504,0.498377,1.639873
184128,"Polanco, G",570256,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,000 0,0,0,0,000 1,0.498377,0.268678,-0.229699
184129,McCutchen,457705,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,000 1,0,0,0,000 2,0.268678,0.106305,-0.162373
184130,Kang,628356,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,2,...,0,0,000 2,0,0,0,000 3,0.106305,0.000000,-0.106305
184131,Molina,425877,Double,NaN,NaN,NaN,NaN,425877.0,NaN,0,...,0,0,000 0,0,1,0,010 0,0.498377,1.132468,0.634090
184132,Piscotty,572039,Single,NaN,425877.0,NaN,572039.0,NaN,NaN,0,...,1,0,010 0,1,0,0,100 0,1.132468,0.858504,0.726037
184133,"Peralta, J",425509,Single,572039.0,NaN,NaN,425509.0,572039.0,NaN,0,...,0,0,100 0,1,1,0,110 0,0.858504,1.447597,0.589092
184134,Moss,461235,Single,425509.0,572039.0,NaN,461235.0,425509.0,572039.0,0,...,1,0,110 0,1,1,1,111 0,1.447597,2.112409,0.664812
184135,Gyorko,576397,Field Error,461235.0,425509.0,572039.0,576397.0,461235.0,425509.0,0,...,1,1,111 0,1,1,1,111 0,2.112409,2.112409,1.000000
184136,Grichuk,545341,Double,576397.0,461235.0,425509.0,NaN,545341.0,576397.0,0,...,1,1,111 0,0,1,1,011 0,2.112409,1.916190,1.803782
184137,Adams,571431,Sac Fly,NaN,545341.0,576397.0,NaN,NaN,545341.0,0,...,1,1,011 0,0,0,1,001 1,1.916190,0.948684,0.032494
184138,"Carpenter, M",572761,Sac Fly,NaN,NaN,545341.0,NaN,NaN,NaN,1,...,0,1,001 1,0,0,0,000 2,0.948684,0.106305,0.157621
184139,"Diaz, A",649557,Pop Out,NaN,NaN,NaN,NaN,NaN,NaN,2,...,0,0,000 2,0,0,0,000 3,0.106305,0.000000,-0.106305
184140,Joyce,459964,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,000 0,0,0,0,000 1,0.498377,0.268678,-0.229699
184141,Hanson,593700,Flyout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,000 1,0,0,0,000 2,0.268678,0.106305,-0.162373
184142,Fryer,518700,Single,NaN,NaN,NaN,518700.0,NaN,NaN,2,...,0,0,000 2,1,0,0,100 2,0.106305,0.220539,0.114234
184143,Florimon,465753,Groundout,518700.0,NaN,NaN,NaN,NaN,NaN,2,...,0,0,100 2,0,0,0,000 3,0.220539,0.000000,-0.220539
184144,Molina,425877,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,000 0,0,0,0,000 1,0.498377,0.268678,-0.229699
184145,Piscotty,572039,Strikeout,NaN,NaN,NaN,NaN,NaN,NaN,1,...,0,0,000 1,0,0,0,000 2,0.268678,0.106305,-0.162373
184146,"Garcia, G",594824,Single,NaN,NaN,NaN,594824.0,NaN,NaN,2,...,0,0,000 2,1,0,0,100 2,0.106305,0.220539,0.114234
184147,Moss,461235,Strikeout,594824.0,NaN,NaN,NaN,NaN,NaN,2,...,0,0,100 2,0,0,0,000 3,0.220539,0.000000,-0.220539
184148,"Rogers, J",595386,Groundout,NaN,NaN,NaN,NaN,NaN,NaN,0,...,0,0,000 0,0,0,0,000 1,0.498377,0.268678,-0.229699
184149,Jaso,444379,Walk,NaN,NaN,NaN,444379.0,NaN,NaN,1,...,0,0,000 1,1,0,0,100 1,0.268678,0.512225,0.243547
184150,"Polanco, G",570256,Strikeout,444379.0,NaN,NaN,444379.0,NaN,NaN,1,...,0,0,100 1,1,0,0,100 2,0.512225,0.220539,-0.291686
184151,McCutchen,457705,Groundout,444379.0,NaN,NaN,NaN,NaN,NaN,2,...,0,0,100 2,0,0,0,000 3,0.220539,0.000000,-0.220539

In [48]:
# Q1: What percent of plate appearances resulted in ground outs in 2016?
RE16['Count'] = 1
Flyout = RE16[RE16['event']=='Groundout']
sum(Flyout['Count'])/sum(RE16['Count'])

0.18445088839654197

In [50]:
# Q2: How many plate appearances had a starting base state in which at least one base was occupied?
RE16_BOcc = RE16[(RE16['Start_State'] != "000 0")&(RE16['Start_State'] != "000 1")&(RE16['Start_State'] != "000 2")]
RE16_BOcc

,batterName,batterId,event,start1B,start2B,start3B,end1B,end2B,end3B,startOuts,...,Start3,Start_State,End1,End2,End3,End_State,Start_RE,End_RE,Run_Value,Count
5,Freese,501896,Single,457705.0,NaN,NaN,501896.0,NaN,457705.0,1,...,0,100 1,1,0,1,101 1,0.512225,1.196777,0.684552,1
6,"Marte, S",516782,Lineout,501896.0,NaN,457705.0,501896.0,NaN,457705.0,1,...,1,101 1,1,0,1,101 2,1.196777,0.480175,-0.716603,1
7,Cervelli,465041,Pop Out,501896.0,NaN,457705.0,NaN,NaN,NaN,2,...,1,101 2,0,0,0,000 3,0.480175,0.000000,-0.480175,1
12,Harrison,543281,Groundout,NaN,570256.0,NaN,NaN,NaN,570256.0,0,...,0,010 0,0,0,1,001 1,1.132468,0.948684,-0.183783,1
13,Mercer,474568,Walk,NaN,NaN,570256.0,474568.0,NaN,570256.0,1,...,1,001 1,1,0,1,101 1,0.948684,1.196777,0.248093,1
14,Liriano,434538,Single,474568.0,NaN,570256.0,434538.0,474568.0,NaN,1,...,1,101 1,1,1,0,110 1,1.196777,0.922572,0.725795,1
15,Jaso,444379,Single,434538.0,474568.0,NaN,444379.0,434538.0,NaN,1,...,0,110 1,1,1,0,110 1,0.922572,0.922572,1.000000,1
16,McCutchen,457705,Flyout,444379.0,434538.0,NaN,444379.0,434538.0,NaN,1,...,0,110 1,1,1,0,110 2,0.922572,0.414466,-0.508107,1
17,Freese,501896,Groundout,444379.0,434538.0,NaN,NaN,NaN,NaN,2,...,0,110 2,0,0,0,000 3,0.414466,0.000000,-0.414466,1
20,Wainwright,425794,Field Error,576397.0,NaN,NaN,425794.0,NaN,576397.0,1,...,0,100 1,1,0,1,101 1,0.512225,1.196777,0.684552,1
21,"Carpenter, M",572761,Grounded Into DP,425794.0,NaN,576397.0,NaN,NaN,NaN,1,...,1,101 1,0,0,0,000 3,1.196777,0.000000,-1.196777,1
24,"Polanco, G",570256,Flyout,465041.0,NaN,NaN,465041.0,NaN,NaN,1,...,0,100 1,1,0,0,100 2,0.512225,0.220539,-0.291686,1
25,Harrison,543281,Strikeout,465041.0,NaN,NaN,NaN,NaN,NaN,2,...,0,100 2,0,0,0,000 3,0.220539,0.000000,-0.220539,1
28,Grichuk,545341,Single,407812.0,NaN,NaN,545341.0,407812.0,NaN,1,...,0,100 1,1,1,0,110 1,0.512225,0.922572,0.410347,1
29,Piscotty,572039,Strikeout,545341.0,407812.0,NaN,545341.0,407812.0,NaN,1,...,0,110 1,1,1,0,110 2,0.922572,0.414466,-0.508107,1
30,Molina,425877,Walk,545341.0,407812.0,NaN,425877.0,545341.0,407812.0,2,...,0,110 2,1,1,1,111 2,0.414466,0.696658,0.282193,1
31,Wong,543939,Strikeout,425877.0,545341.0,407812.0,NaN,NaN,NaN,2,...,1,111 2,0,0,0,000 3,0.696658,0.000000,-0.696658,1
38,Adams,571431,Groundout,572761.0,NaN,NaN,NaN,NaN,NaN,2,...,0,100 2,0,0,0,000 3,0.220539,0.000000,-0.220539,1
41,"Marte, S",516782,Grounded Into DP,501896.0,NaN,NaN,NaN,NaN,NaN,1,...,0,100 1,0,0,0,000 3,0.512225,0.000000,-0.512225,1
43,Grichuk,545341,Strikeout,407812.0,NaN,NaN,407812.0,NaN,NaN,0,...,0,100 0,1,0,0,100 1,0.858504,0.512225,-0.346279,1
44,Piscotty,572039,Walk,407812.0,NaN,NaN,572039.0,407812.0,NaN,1,...,0,100 1,1,1,0,110 1,0.512225,0.922572,0.410347,1
45,Molina,425877,Single,572039.0,407812.0,NaN,425877.0,572039.0,407812.0,1,...,0,110 1,1,1,1,111 1,0.922572,1.536937,0.614365,1
46,Wong,543939,Pop Out,425877.0,572039.0,407812.0,425877.0,572039.0,407812.0,1,...,1,111 1,1,1,1,111 2,1.536937,0.696658,-0.840279,1
47,Gyorko,576397,Forceout,425877.0,572039.0,407812.0,NaN,NaN,NaN,2,...,1,111 2,0,0,0,000 3,0.696658,0.000000,-0.696658,1
49,"Polanco, G",570256,Walk,NaN,NaN,465041.0,570256.0,NaN,465041.0,0,...,1,001 0,1,0,1,101 0,1.358166,1.728145,0.369979,1
50,Harrison,543281,Sac Fly DP,570256.0,NaN,465041.0,NaN,NaN,NaN,0,...,1,101 0,0,0,0,000 2,1.728145,0.106305,-0.621840,1
56,Jaso,444379,Groundout,459964.0,NaN,NaN,NaN,459964.0,NaN,0,...,0,100 0,0,1,0,010 1,0.858504,0.677498,-0.181006,1
57,McCutchen,457705,Walk,NaN,459964.0,NaN,457705.0,459964.0,NaN,1,...,0,010 1,1,1,0,110 1,0.677498,0.922572,0.245074,1
58,Freese,501896,Strikeout,457705.0,459964.0,NaN,457705.0,459964.0,NaN,1,...,0,110 1,1,1,0,110 2,0.922572,0.414466,-0.508107,1
59,"Marte, S",516782,Strikeout,457705.0,459964.0,NaN,NaN,NaN,NaN,2,...,0,110 2,0,0,0,000 3,0.414466,0.000000,-0.414466,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184094,Piscotty,572039,Single,425877.0,NaN,NaN,572039.0,NaN,425877.0,2,...,0,100 2,1,0,1,101 2,0.220539,0.480175,0.259635,1
184095,"Peralta, J",425509,Flyout,572039.0,NaN,425877.0,NaN,NaN,NaN,2,...,1,101 2,0,0,0,000 3,0.480175,0.000000,-0.480175,1
184099,Hanson,593700,Groundout,459964.0,NaN,NaN,NaN,NaN,NaN,2,...,0,100 2,0,0,0,000 3,0.220539,0.000000,-0.220539,1
184102,Grichuk,545341,Flyout,576397.0,NaN,NaN,576397.0,NaN,NaN,1,...,0,100 1,1,0,0,100 2,0.512225,0.220539,-0.291686,1
184103,Wainwright,425794,Field Error,576397.0,NaN,NaN,NaN,425794.0,576397.0,2,...,0,100 2,0,1,1,011 2,0.220539,0.587466,0.366926,1
184104,"Carpenter, M",572761,Walk,NaN,425794.0,576397.0,572761.0,425794.0,576397.0,2,...,1,011 2,1,1,1,111 2,0.587466,0.696658,0.109193,1
184105,"Diaz, A",649557,Lineout,572761.0,425794.0,576397.0,NaN,NaN,NaN,2,...,1,111 2,0,0,0,000 3,0.696658,0.000000,-0.696658,1
184107,Florimon,465753,Strikeout - DP,518700.0,NaN,NaN,NaN,NaN,NaN,0,...,0,100 0,0,0,0,000 2,0.858504,0.106305,-0.752199,1
184109,Jaso,444379,Single,285064.0,NaN,NaN,444379.0,285064.0,NaN,2,...,0,100 2,1,1,0,110 2,0.220539,0.414466,0.193926,1
184110,"Polanco, G",570256,Walk,444379.0,285064.0,NaN,570256.0,444379.0,285064.0,2,...,0,110 2,1,1,1,111 2,0.414466,0.696658,0.282193,1
184111,McCutchen,457705,Single,570256.0,444379.0,285064.0,457705.0,570256.0,NaN,2,...,1,111 2,1,1,0,110 2,0.696658,0.414466,1.717807,1
184112,Kang,628356,Flyout,457705.0,570256.0,NaN,NaN,NaN,NaN,2,...,0,110 2,0,0,0,000 3,0.414466,0.000000,-0.414466,1
184117,Hanson,593700,Flyout,459964.0,NaN,NaN,NaN,459964.0,NaN,0,...,0,100 0,0,1,0,010 1,0.858504,0.677498,-0.181006,1
184118,Fryer,518700,Strikeout,NaN,459964.0,NaN,NaN,459964.0,NaN,1,...,0,010 1,0,1,0,010 2,0.677498,0.319844,-0.357654,1
184119,Florimon,465753,Strikeout,NaN,459964.0,NaN,NaN,NaN,NaN,2,...,0,010 2,0,0,0,000 3,0.319844,0.000000,-0.319844,1
184122,Grichuk,545341,Strikeout,576397.0,NaN,NaN,576397.0,NaN,NaN,1,...,0,100 1,1,0,0,100 2,0.512225,0.220539,-0.291686,1
184123,"Martinez, Jo",500874,Single,576397.0,NaN,NaN,500874.0,576397.0,NaN,2,...,0,100 2,1,1,0,110 2,0.220539,0.414466,0.193926,1
184124,"Carpenter, M",572761,Home Run,500874.0,576397.0,NaN,NaN,NaN,NaN,2,...,0,110 2,0,0,0,000 2,0.414466,0.106305,2.691840,1
184127,Jaso,444379,Home Run,624428.0,NaN,NaN,NaN,NaN,NaN,0,...,0,100 0,0,0,0,000 0,0.858504,0.498377,1.639873,1
184132,Piscotty,572039,Single,NaN,425877.0,NaN,572039.0,NaN,NaN,0,...,0,010 0,1,0,0,100 0,1.132468,0.858504,0.726037,1
184133,"Peralta, J",425509,Single,572039.0,NaN,NaN,425509.0,572039.0,NaN,0,...,0,100 0,1,1,0,110 0,0.858504,1.447597,0.589092,1
184134,Moss,461235,Single,425509.0,572039.0,NaN,461235.0,425509.0,572039.0,0,...,0,110 0,1,1,1,111 0,1.447597,2.112409,0.664812,1
184135,Gyorko,576397,Field Error,461235.0,425509.0,572039.0,576397.0,461235.0,425509.0,0,...,1,111 0,1,1,1,111 0,2.112409,2.112409,1.000000,1
184136,Grichuk,545341,Double,576397.0,461235.0,425509.0,NaN,545341.0,576397.0,0,...,1,111 0,0,1,1,011 0,2.112409,1.916190,1.803782,1
184137,Adams,571431,Sac Fly,NaN,545341.0,576397.0,NaN,NaN,545341.0,0,...,1,011 0,0,0,1,001 1,1.916190,0.948684,0.032494,1
184138,"Carpenter, M",572761,Sac Fly,NaN,NaN,545341.0,NaN,NaN,NaN,1,...,1,001 1,0,0,0,000 2,0.948684,0.106305,0.157621,1
184143,Florimon,465753,Groundout,518700.0,NaN,NaN,NaN,NaN,NaN,2,...,0,100 2,0,0,0,000 3,0.220539,0.000000,-0.220539,1
184147,Moss,461235,Strikeout,594824.0,NaN,NaN,NaN,NaN,NaN,2,...,0,100 2,0,0,0,000 3,0.220539,0.000000,-0.220539,1
184150,"Polanco, G",570256,Strikeout,444379.0,NaN,NaN,444379.0,NaN,NaN,1,...,0,100 1,1,0,0,100 2,0.512225,0.220539,-0.291686,1
184151,McCutchen,457705,Groundout,444379.0,NaN,NaN,NaN,NaN,NaN,2,...,0,100 2,0,0,0,000 3,0.220539,0.000000,-0.220539,1

In [37]:
# Q3: Calculate aggregate home runs by player position (that is, aggregate (sum) data at the positional level and not the player level). 
# What was the highest aggregate home run total by position?

Strikeouts = RE16[RE16['event'] == "Home Run"]
Strikeouts.groupby(['batterPos'])['Count'].sum().reset_index()

   batterPos  Count
0         1B    797
1         2B    576
2         3B    710
3          C    541
4         CF    532
5         DH    424
6         LF    576
7          P     22
8         RF    694
9         SS    486
10        UN    178

# III. Comparing 2016 vs. 2017

In [ ]:
#Your Code Here

In [ ]:
# 1.	Calculate the average run value for each event for both 2016 and 2017

In [51]:
Event_Value_16 = RE16.groupby(['event'])['Run_Value'].mean().reset_index()
Event_Value_17 = RE17.groupby(['event'])['Run_Value'].mean().reset_index()
Event_Value_16 = Event_Value_16.rename(columns={'Run_Value':'Run_Value_16'})
Event_Value_17 = Event_Value_17.rename(columns={'Run_Value':'Run_Value_17'})

In [ ]:
# 2.	Merge the 2016 and 2017 run values by event into one dataframe 
# (before merging, it may be helpful to rename the run value variables Run_Value16 and Run_Value17 respectively)

In [52]:
EV_1617 = pd.merge(Event_Value_16, Event_Value_17, on=['event'])
EV_1617

                   event  Run_Value_16  Run_Value_17
0    Batter Interference     -0.284649     -0.430019
1         Bunt Groundout     -0.218826     -0.209411
2           Bunt Lineout     -0.352295     -0.328292
3           Bunt Pop Out     -0.342802     -0.373225
4   Catcher Interference      0.301623      0.399070
5                 Double      0.743467      0.779338
6            Double Play     -0.864981     -0.897164
7       Fan interference      0.533316      0.590743
8            Field Error      0.469989      0.493206
9        Fielders Choice      0.701447      0.764112
10   Fielders Choice Out     -0.610757     -0.662400
11                Flyout     -0.247896     -0.262548
12              Forceout     -0.326657     -0.345347
13      Grounded Into DP     -0.773318     -0.818005
14             Groundout     -0.212992     -0.224579
15          Hit By Pitch      0.320569      0.338679
16              Home Run      1.382476      1.378739
17           Intent Walk      0.172551      0.180109
18               Lineout     -0.248542     -0.259682
19               Pop Out     -0.267062     -0.283498
20            Runner Out     -0.257904     -0.274991
21              Sac Bunt     -0.126691     -0.109283
22               Sac Fly      0.023233     -0.032119
23            Sac Fly DP     -0.370443     -0.543715
24                Single      0.440258      0.455773
25             Strikeout     -0.259940     -0.269985
26        Strikeout - DP     -0.622787     -0.682819
27                Triple      1.023911      1.063607
28           Triple Play     -1.637543     -1.471223
29                  Walk      0.299404      0.322635

In [ ]:
# 3.	Calculate the aggregate run value (sum) for all players in both 2016 and 2017

In [53]:
Player_Value_16 = RE16.groupby(['batterName'])['Run_Value'].sum().reset_index()
Player_Value_17 = RE17.groupby(['batterName'])['Run_Value'].sum().reset_index()
Player_Value_16 = Player_Value_16.rename(columns={'Run_Value':'Run_Value_16'})
Player_Value_17 = Player_Value_17.rename(columns={'Run_Value':'Run_Value_17'})

In [ ]:
# 4.	Merge the 2016 and 2017 run values by player into one dataframe so that only players appearing in both datasets appear in the merged data 
# (before merging, it may be helpful to rename the run value variables Run_Value16 and Run_Value17 respectively)

In [54]:
PV_1617 = pd.merge(Player_Value_16, Player_Value_17, on=['batterName'])
PV_1617

       batterName  Run_Value_16  Run_Value_17
0           Abreu     13.395343     31.392604
1          Adames    -12.866394     -2.872021
2           Adams      4.063644      9.681144
3         Adleman      0.713572     -5.242051
4        Adrianza     -3.300578      0.425352
5         Aguilar     -1.270121     12.154386
6           Ahmed    -23.000581     -4.176089
7          Albers      0.634090      0.610527
8    Alcantara, A     -2.744564    -11.996816
9          Alfaro     -3.636230      5.001877
10        Almonte     -3.207517     -3.431680
11     Almora Jr.     -2.338380      4.952449
12         Alonso     -6.983720     18.374849
13        Altherr     -4.181921     14.218364
14         Altuve     34.657744     36.862616
15     Alvarez, P      7.037067      2.230533
16       Amarista     -7.595233    -10.988646
17    Anderson, B     -0.711917      0.069557
18   Anderson, Ch     -8.735219    -11.194264
19    Anderson, T     -4.093650     -8.731515
20   Anderson, Ti    -11.022494    -29.855271
21         Andrus     22.382872     27.967803
22           Aoki     -0.585886     -8.130340
23         Archer     -1.735221     -0.114079
24       Arcia, O     -9.579620      0.660274
25        Arenado     48.979171     56.111576
26        Arrieta     -0.450807     -9.630616
27          Asche     -3.013706     -8.008246
28          Asher     -0.380892     -0.164138
29         Asuaje     -0.135144     -5.254972
..            ...           ...           ...
661        Watson     -0.183783     -0.108038
662        Weaver     -0.701936     -2.781183
663     Weaver, J     -2.349965     -2.457789
664     Weeks Jr.      6.696188     -0.429381
665        Wendle     -2.455882      3.037176
666         Werth      6.368448     -7.246145
667         White     -9.482369      2.336055
668       Wieters      6.150161    -18.729529
669   Williams, M     -2.034368     -0.891243
670   Williams, T      1.384666    -10.530757
671    Williamson     -3.607482     -1.251784
672        Wisler    -10.809493     -0.826656
673       Wolters      8.888596     -8.639259
674          Wong     -3.909032     10.751263
675       Wood, A     -2.623027    -11.017261
676       Wood, B     -0.540384     -0.244199
677       Wood, T     -0.019259      2.250361
678        Yelich     26.369344     18.527345
679       Ynoa, G     -0.374983     -0.374947
680     Young Jr.     -0.229699      5.291459
681      Young, C      4.397001     -6.469925
682     Zastryzny     -1.046863     -0.301836
683     Zimmerman    -22.942623     33.179676
684    Zimmermann     -0.397956     -1.439659
685       Zobrist     18.888483    -13.718812
686        Zunino      8.816774      4.710472
687      d'Arnaud    -10.768827     -7.884709
688   d'Arnaud, T    -12.314196     -2.301919
689        deGrom     -8.532559     -9.500759
690    den Dekker      0.085717     -1.647911

[691 rows x 3 columns]

In [ ]:
# Q1: What was the highest player run value in 2017?

In [55]:
RV2017 = PV_1617.sort_values(by=['Run_Value_17'],  ascending=False)
RV2017

       batterName  Run_Value_16  Run_Value_17
657         Votto     45.883627     67.650742
56       Blackmon     33.411154     62.032793
312         Judge     -4.179157     57.081625
25        Arenado     48.979171     56.111576
223   Goldschmidt     36.197730     56.078941
595       Stanton     10.070038     51.784088
636         Trout     68.143360     50.431739
131          Cruz     30.882125     46.105828
451         Ozuna      7.040069     45.648106
509        Rendon     18.235958     41.422600
520         Rizzo     43.080606     37.865377
263        Harper     30.806830     37.730864
422     Murphy, D     48.234104     37.079417
125        Correa     23.912180     37.070614
14         Altuve     34.657744     36.862616
230   Gonzalez, M    -16.649256     35.951866
640         Upton     10.642522     35.833621
121      Conforto     -3.607318     35.827160
292        Hosmer     21.181723     35.598466
74         Bryant     47.832680     34.845708
205    Garcia, Av      0.792947     34.612266
375   Martinez, J     23.124182     34.223665
499    Ramirez, J     17.126864     34.159423
128        Cozart     -2.402277     33.761590
683     Zimmerman    -22.942623     33.179676
154     Donaldson     48.510824     32.587402
382         Mauer      3.738712     32.012389
0           Abreu     13.395343     31.392604
472          Pham     -1.695485     31.204334
593      Springer     22.381899     30.023925
..            ...           ...           ...
484    Polanco, G     10.610631    -15.892235
516       Rickard     -6.883333    -15.978439
379   Martinez, V      7.335464    -16.021087
359         Maile     -6.727172    -16.044167
380        Mathis     -4.741811    -16.127175
345       Lobaton     -2.289553    -16.670948
47        Beltran     21.279393    -16.883042
633     Tomlinson     -0.289284    -17.312695
637        Trumbo     21.644283    -17.990412
174      Espinosa     -5.907984    -18.184425
668       Wieters      6.150161    -18.729529
274       Heredia      1.467905    -18.875920
420        Motter     -3.072219    -19.013532
190        Franco      9.611410    -19.115330
260        Hanson     -2.099752    -19.162321
554      Sandoval     -0.594356    -19.354734
498    Ramirez, H     30.676190    -19.461039
262         Hardy     -2.402668    -19.928385
33          Aybar    -14.072908    -20.157301
39         Barney    -10.754477    -21.064248
140      Davis, R     -6.396303    -21.569964
171    Escobar, A    -26.555530    -22.348618
232     Gordon, A    -12.963542    -23.693836
360     Maldonado    -11.455571    -25.796475
476        Pillar     -4.311137    -26.049496
483       Plouffe     -0.725095    -29.004223
546      Saladino     -3.574239    -29.484769
20   Anderson, Ti    -11.022494    -29.855271
255      Hamilton    -15.101036    -30.668233
444          Odor     11.679587    -36.464351

[691 rows x 3 columns]

In [ ]:
# Q2: What was the lowest player run value in 2016?

In [56]:
RV2016 = PV_1617.sort_values(by=['Run_Value_16'],  ascending=True)
RV2016

      batterName  Run_Value_16  Run_Value_17
269  Hechavarria    -32.142529     -6.378460
440   Norris, De    -26.841250    -11.798153
171   Escobar, A    -26.555530    -22.348618
78         Burns    -23.335961     -1.429560
6          Ahmed    -23.000581     -4.176089
683    Zimmerman    -22.942623     33.179676
201       Galvis    -22.751256    -13.695274
370     Marte, K    -21.742476     -3.503534
296  Iglesias, J    -21.271729    -11.173195
309   Joseph, Ca    -20.085234     -8.346937
511       Revere    -19.493233     -6.619925
358      Mahtook    -18.597420     -1.184826
372    Martin, L    -17.784503    -13.139457
282      Heyward    -17.099341      2.479838
32        Aviles    -16.951381     -6.077192
184    Flores, R    -16.733862     -1.172803
230  Gonzalez, M    -16.649256     35.951866
585    Smolinski    -16.406132     -2.443034
329        Kratz    -16.389089      1.892890
224        Gomes    -16.172017     -6.767861
454        Parra    -15.948345     12.319789
132        Cueto    -15.836621    -10.643992
579      Simmons    -15.754664     -1.742177
302    Jankowski    -15.612078     -9.545011
222        Goins    -15.580144     -5.032530
119        Colon    -15.380841     -6.053060
386       McCann    -15.379222     -1.999418
365    Marisnick    -15.271764      1.176953
255     Hamilton    -15.101036    -30.668233
557   Santana, D    -14.330371     -0.480378
..           ...           ...           ...
46          Belt     27.272456      7.753233
426        Myers     27.423018      3.708292
556   Santana, C     27.831142     19.651084
70         Braun     27.845791      4.101122
91          Cano     28.497452     26.869401
227  Gonzalez, C     28.576921     -5.394397
572       Segura     28.717694     -5.523280
569    Seager, C     28.741630     26.499725
48        Beltre     29.745115     27.205050
498   Ramirez, H     30.676190    -19.461039
263       Harper     30.806830     37.730864
131         Cruz     30.882125     46.105828
339     LeMahieu     31.058310      1.844428
355      Machado     31.742868      1.759563
56      Blackmon     33.411154     62.032793
14        Altuve     34.657744     36.862616
223  Goldschmidt     36.197730     56.078941
170  Encarnacion     36.225266     21.707405
54         Betts     36.363718     25.043520
82       Cabrera     37.520249     -4.336300
639       Turner     39.048572     18.814733
520        Rizzo     43.080606     37.865377
194      Freeman     45.551348     24.477837
657        Votto     45.883627     67.650742
74        Bryant     47.832680     34.845708
422    Murphy, D     48.234104     37.079417
154    Donaldson     48.510824     32.587402
25       Arenado     48.979171     56.111576
449        Ortiz     60.938730     -2.629789
636        Trout     68.143360     50.431739

[691 rows x 3 columns]

In [ ]:
# Q3: For each event, calculate the difference in run value between 2017 and 2016 (RV 2017-RV 2016). 
#     Which event saw the largest change (in absolute value) from 2016 to 2017?

In [57]:
EV_1617['RVDiff'] = abs(EV_1617['Run_Value_17'] - EV_1617['Run_Value_16']) 
EV_1617 = EV_1617.sort_values(by=['RVDiff'], ascending=False)
EV_1617

                   event  Run_Value_16  Run_Value_17    RVDiff
23            Sac Fly DP     -0.370443     -0.543715  0.173272
28           Triple Play     -1.637543     -1.471223  0.166319
0    Batter Interference     -0.284649     -0.430019  0.145369
4   Catcher Interference      0.301623      0.399070  0.097447
9        Fielders Choice      0.701447      0.764112  0.062665
26        Strikeout - DP     -0.622787     -0.682819  0.060032
7       Fan interference      0.533316      0.590743  0.057427
22               Sac Fly      0.023233     -0.032119  0.055352
10   Fielders Choice Out     -0.610757     -0.662400  0.051643
13      Grounded Into DP     -0.773318     -0.818005  0.044687
27                Triple      1.023911      1.063607  0.039695
5                 Double      0.743467      0.779338  0.035870
6            Double Play     -0.864981     -0.897164  0.032183
3           Bunt Pop Out     -0.342802     -0.373225  0.030423
2           Bunt Lineout     -0.352295     -0.328292  0.024003
29                  Walk      0.299404      0.322635  0.023231
8            Field Error      0.469989      0.493206  0.023217
12              Forceout     -0.326657     -0.345347  0.018691
15          Hit By Pitch      0.320569      0.338679  0.018110
21              Sac Bunt     -0.126691     -0.109283  0.017409
20            Runner Out     -0.257904     -0.274991  0.017087
19               Pop Out     -0.267062     -0.283498  0.016436
24                Single      0.440258      0.455773  0.015515
11                Flyout     -0.247896     -0.262548  0.014652
14             Groundout     -0.212992     -0.224579  0.011588
18               Lineout     -0.248542     -0.259682  0.011140
25             Strikeout     -0.259940     -0.269985  0.010045
1         Bunt Groundout     -0.218826     -0.209411  0.009415
17           Intent Walk      0.172551      0.180109  0.007558
16              Home Run      1.382476      1.378739  0.003737

In [ ]:
# Q4: Calculate the difference in player run value between 2017 and 2016 for players that accumulated run values in both seasons. 
# According to this calculation, what was the largest improvement in run value from 2016 to 2017?

In [58]:
PV_1617['RVDiff'] = PV_1617['Run_Value_17'] - PV_1617['Run_Value_16']
PV_1617 = PV_1617.sort_values(by=['RVDiff'], ascending=False)
PV_1617

       batterName  Run_Value_16  Run_Value_17     RVDiff
312         Judge     -4.179157     57.081625  61.260782
683     Zimmerman    -22.942623     33.179676  56.122300
230   Gonzalez, M    -16.649256     35.951866  52.601121
595       Stanton     10.070038     51.784088  41.714049
121      Conforto     -3.607318     35.827160  39.434477
451         Ozuna      7.040069     45.648106  38.608037
215       Gennett     -8.970409     29.352662  38.323071
128        Cozart     -2.402277     33.761590  36.163867
583         Smoak    -12.844614     22.263561  35.108175
205    Garcia, Av      0.792947     34.612266  33.819319
472          Pham     -1.695485     31.204334  32.899819
343          Lind    -12.359832     20.276339  32.636172
350        Lowrie    -12.914838     16.438851  29.353689
56       Blackmon     33.411154     62.032793  28.621639
382         Mauer      3.738712     32.012389  28.273677
454         Parra    -15.948345     12.319789  28.268134
123     Contreras     -0.530910     27.219171  27.750081
283      Hicks, A    -13.219054     14.428142  27.647196
506       Reddick      2.184347     29.449762  27.265415
250       Gurriel     -4.873403     22.053024  26.926427
269   Hechavarria    -32.142529     -6.378460  25.764069
12         Alonso     -6.983720     18.374849  25.358569
640         Upton     10.642522     35.833621  25.191098
243     Gregorius     -3.591038     20.475311  24.066349
295      Iannetta    -10.007643     14.045915  24.053558
590     Souza Jr.     -4.894369     18.886509  23.780878
509        Rendon     18.235958     41.422600  23.186642
623     Taylor, C     -2.211697     20.588698  22.800395
200         Gallo     -4.786957     17.459019  22.245976
78          Burns    -23.335961     -1.429560  21.906401
..            ...           ...           ...        ...
379   Martinez, V      7.335464    -16.021087 -23.356552
426         Myers     27.423018      3.708292 -23.714726
70          Braun     27.845791      4.101122 -23.744669
668       Wieters      6.150161    -18.729529 -24.879690
325        Kipnis     24.175581     -1.279526 -25.455107
226   Gonzalez, A     18.186314     -7.670641 -25.856956
587       Solarte     22.286786     -3.617288 -25.904074
546      Saladino     -3.574239    -29.484769 -25.910531
484    Polanco, G     10.610631    -15.892235 -26.502865
481      Piscotty     24.063534     -3.609730 -27.673263
483       Plouffe     -0.725095    -29.004223 -28.279128
190        Franco      9.611410    -19.115330 -28.726740
339      LeMahieu     31.058310      1.844428 -29.213882
495        Pujols     15.581010    -13.892055 -29.473065
527  Rodriguez, S     14.448815    -15.182604 -29.631419
148       Diaz, A     16.695314    -12.989348 -29.684661
355       Machado     31.742868      1.759563 -29.983305
43       Bautista     15.171797    -15.256682 -30.428479
324       Kinsler     21.481252    -10.076064 -31.557316
685       Zobrist     18.888483    -13.718812 -32.607296
160        Duvall     21.819293    -11.639746 -33.459040
227   Gonzalez, C     28.576921     -5.394397 -33.971317
572        Segura     28.717694     -5.523280 -34.240974
384        Maybin     23.263283    -12.318532 -35.581815
47        Beltran     21.279393    -16.883042 -38.162435
637        Trumbo     21.644283    -17.990412 -39.634695
82        Cabrera     37.520249     -4.336300 -41.856549
444          Odor     11.679587    -36.464351 -48.143938
498    Ramirez, H     30.676190    -19.461039 -50.137229
449         Ortiz     60.938730     -2.629789 -63.568519

[691 rows x 4 columns]