## Does the **Money** follow the **Ball**?

The Notebook you just completed reproduced Table 1 from the Hakes and Sauer Moneyball paper. This showed that in the period
1999-2003, winning percentage in Major League Baseball could, to a significant degree, be accounted for by on-base percentage (OBP). The effect of OBP appeared to be much larger than that of slugging percentage (SLG), a statistic commonly relied upon as an indicator of likely success.

The implication of Table 1 is that batters whose productivity measured by OBP should, all else equal, be valued more highly than batters with an equivalent value of SLG. In a competitive market, we should expect to observe salaries to be strongly correlated with OBP, more so than with SLG.

Hakes and Sauer set out to test this proposition by running a regression of batter salaries on OBP and SLG, as well as some other key factors likely to influence salary level. These other factors are

>**Plate appearances**: consistency is likely to be prized
<br>
>**Arbitration eligibility and free agency**: as players length of service increases then so does their bargaining power
<br>
>**Fielding position**: catchers in particular provide a valuable service so can command a higher salary for the same level of batting performance
<br>

Note that the focus of the analysis is batters- we are not including pitchers in this analysis.
<br>
<br>
The pattern of results in Table 3 is very striking. The top two rows tell us the importance of OBP and SLG. In every year SLG is statistically significant and affects the salary value in roughly the same way (the size of the coefficient is consistently between 2 and 3). However, in the top row we can see that OBP is statistically insignificant in every season (conventional statistical significance is denoted by the ratio of the coefficient and the standard error (in parentheses) being roughly larger than 2 in absolute value). But then in 2004, the year after Moneyball was published, OBP is not only statistically significant, the coefficient is almost twice the size as the coefficient on SLG. Suddenly, the market seemed to reward OBP.
<br>
<br>
<!-- ![H&S%20Table%203.png](attachment:H&S%20Table%203.png) -->

<br>
<br>

# Creating the dataframe

We will now set about reproducing Table 3.
<br>
To re-run the Hakes and Sauer Table 3 regression we need to create a df containing the the variables they used:

>log(Salary) = b<sub>0</sub> + b<sub>1</sub> OBP + b<sub>2</sub> SLG + b<sub>3</sub> PA + b<sub>4</sub> Arb + b<sub>5</sub> Free + b<sub>6</sub> Catcher + b<sub>7</sub> Infielder


*The Salary data is in the salary file (Step 1)*

*The OBP, SLG and PA data can be created from the batting file (Step 2)*

*The Arb (arbitration elegible) and Free (agent) data can be created from the People file (Step 3)*

*The Catcher and Infielder can be created from the Appearances file (Step 4)*

We will combine all these variables in a Master file, and then run the regessions.


## Merging dataframes

Before running the code, it's useful to visualize the process. To run the regression at the end, we want to create a "rectangular" dataframe. All our variables will be lined up in columns and the number of rows will be the same for each variable. We will also discard rows where there are missing variables. You can think of the df as looking like this:

<!-- ![rectangular%20df.PNG](attachment:rectangular%20df.PNG) -->

To create our df we need to merge data from different sources.

<!-- ![merging%20dfs.PNG](attachment:merging%20dfs.PNG) -->

This will involve operations to:
<br>
>Create new variables inside an existing df.
<br>
>Merge two dfs.
<br>
>Drop variables that are not relevant for our final df.

# Step 1

In [ ]:
# First we load the packages

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

### Note that at each step we look at the data (using "display()") - this is both to keep a check on what we are doing and to look out for mistakes.

In [ ]:
# Read in salary data retrieved from Lahman's Database

Salary = pd.read_csv("../Data/Salaries.csv")
display(Salary)

       yearID teamID lgID   playerID    salary
0        1985    ATL   NL  barkele01    870000
1        1985    ATL   NL  bedrost01    550000
2        1985    ATL   NL  benedbr01    545000
3        1985    ATL   NL   campri01    633333
4        1985    ATL   NL  ceronri01    625000
5        1985    ATL   NL  chambch01    800000
6        1985    ATL   NL  dedmoje01    150000
7        1985    ATL   NL  forstte01    483333
8        1985    ATL   NL  garbege01    772000
9        1985    ATL   NL  harpete01    250000
10       1985    ATL   NL  hornebo01   1500000
11       1985    ATL   NL  hubbagl01    455000
12       1985    ATL   NL  mahleri01    407500
13       1985    ATL   NL  mcmurcr01    275000
14       1985    ATL   NL  mumphje01    775000
15       1985    ATL   NL  murphda05   1625000
16       1985    ATL   NL  oberkke01    616667
17       1985    ATL   NL  perezpa01    450000
18       1985    ATL   NL  perryge01    120000
19       1985    ATL   NL  ramirra01    750000
20       1985    ATL   NL  suttebr01   1354167
21       1985    ATL   NL  washicl01    800000
22       1985    BAL   AL  boddimi01    625000
23       1985    BAL   AL  dauerri01    480000
24       1985    BAL   AL  davisst02    437500
25       1985    BAL   AL  dempsri01    512500
26       1985    BAL   AL  dwyerji01    375000
27       1985    BAL   AL  flanami01    641667
28       1985    BAL   AL   fordda01    450000
29       1985    BAL   AL  grosswa01    483333
...       ...    ...  ...        ...       ...
26398    2016    TOR   AL  stromma01    515900
26399    2016    TOR   AL  tholejo01    800000
26400    2016    TOR   AL  travide01    511200
26401    2016    TOR   AL  tulowtr01  20000000
26402    2016    WAS   NL  barreaa01    519400
26403    2016    WAS   NL  belisma01   1250000
26404    2016    WAS   NL   drewst01   3000000
26405    2016    WAS   NL  espinda01   2875000
26406    2016    WAS   NL  gonzagi01  12100000
26407    2016    WAS   NL  harpebr03   5000000
26408    2016    WAS   NL  heisech01   1250000
26409    2016    WAS   NL  kellesh01   4000000
26410    2016    WAS   NL  lobatjo01   1387500
26411    2016    WAS   NL  murphda08   8000000
26412    2016    WAS   NL  papeljo01  10936574
26413    2016    WAS   NL  perezol01   3000000
26414    2016    WAS   NL  petityu01   2500000
26415    2016    WAS   NL  ramoswi01   5350000
26416    2016    WAS   NL  rendoan01   2800000
26417    2016    WAS   NL  reverbe01   6250000
26418    2016    WAS   NL  riverfe01    516100
26419    2016    WAS   NL  roarkta01    543400
26420    2016    WAS   NL  robincl01    534900
26421    2016    WAS   NL   rossjo01    514400
26422    2016    WAS   NL  scherma01  22142857
26423    2016    WAS   NL  strasst01  10400000
26424    2016    WAS   NL  taylomi02    524000
26425    2016    WAS   NL  treinbl01    524900
26426    2016    WAS   NL  werthja01  21733615
26427    2016    WAS   NL  zimmery01  14000000

[26428 rows x 5 columns]

In [ ]:
# Not every salary is recorded, so first drop missing values

Salary = Salary[Salary.salary > 0]
Salary

       yearID teamID lgID   playerID    salary
0        1985    ATL   NL  barkele01    870000
1        1985    ATL   NL  bedrost01    550000
2        1985    ATL   NL  benedbr01    545000
3        1985    ATL   NL   campri01    633333
4        1985    ATL   NL  ceronri01    625000
5        1985    ATL   NL  chambch01    800000
6        1985    ATL   NL  dedmoje01    150000
7        1985    ATL   NL  forstte01    483333
8        1985    ATL   NL  garbege01    772000
9        1985    ATL   NL  harpete01    250000
10       1985    ATL   NL  hornebo01   1500000
11       1985    ATL   NL  hubbagl01    455000
12       1985    ATL   NL  mahleri01    407500
13       1985    ATL   NL  mcmurcr01    275000
14       1985    ATL   NL  mumphje01    775000
15       1985    ATL   NL  murphda05   1625000
16       1985    ATL   NL  oberkke01    616667
17       1985    ATL   NL  perezpa01    450000
18       1985    ATL   NL  perryge01    120000
19       1985    ATL   NL  ramirra01    750000
20       1985    ATL   NL  suttebr01   1354167
21       1985    ATL   NL  washicl01    800000
22       1985    BAL   AL  boddimi01    625000
23       1985    BAL   AL  dauerri01    480000
24       1985    BAL   AL  davisst02    437500
25       1985    BAL   AL  dempsri01    512500
26       1985    BAL   AL  dwyerji01    375000
27       1985    BAL   AL  flanami01    641667
28       1985    BAL   AL   fordda01    450000
29       1985    BAL   AL  grosswa01    483333
...       ...    ...  ...        ...       ...
26398    2016    TOR   AL  stromma01    515900
26399    2016    TOR   AL  tholejo01    800000
26400    2016    TOR   AL  travide01    511200
26401    2016    TOR   AL  tulowtr01  20000000
26402    2016    WAS   NL  barreaa01    519400
26403    2016    WAS   NL  belisma01   1250000
26404    2016    WAS   NL   drewst01   3000000
26405    2016    WAS   NL  espinda01   2875000
26406    2016    WAS   NL  gonzagi01  12100000
26407    2016    WAS   NL  harpebr03   5000000
26408    2016    WAS   NL  heisech01   1250000
26409    2016    WAS   NL  kellesh01   4000000
26410    2016    WAS   NL  lobatjo01   1387500
26411    2016    WAS   NL  murphda08   8000000
26412    2016    WAS   NL  papeljo01  10936574
26413    2016    WAS   NL  perezol01   3000000
26414    2016    WAS   NL  petityu01   2500000
26415    2016    WAS   NL  ramoswi01   5350000
26416    2016    WAS   NL  rendoan01   2800000
26417    2016    WAS   NL  reverbe01   6250000
26418    2016    WAS   NL  riverfe01    516100
26419    2016    WAS   NL  roarkta01    543400
26420    2016    WAS   NL  robincl01    534900
26421    2016    WAS   NL   rossjo01    514400
26422    2016    WAS   NL  scherma01  22142857
26423    2016    WAS   NL  strasst01  10400000
26424    2016    WAS   NL  taylomi02    524000
26425    2016    WAS   NL  treinbl01    524900
26426    2016    WAS   NL  werthja01  21733615
26427    2016    WAS   NL  zimmery01  14000000

[26426 rows x 5 columns]

In [ ]:
# Calculate natural log of salary

Salary['lnSal'] = np.log(Salary['salary'])
Salary

       yearID teamID lgID   playerID    salary      lnSal
0        1985    ATL   NL  barkele01    870000  13.676248
1        1985    ATL   NL  bedrost01    550000  13.217674
2        1985    ATL   NL  benedbr01    545000  13.208541
3        1985    ATL   NL   campri01    633333  13.358752
4        1985    ATL   NL  ceronri01    625000  13.345507
5        1985    ATL   NL  chambch01    800000  13.592367
6        1985    ATL   NL  dedmoje01    150000  11.918391
7        1985    ATL   NL  forstte01    483333  13.088461
8        1985    ATL   NL  garbege01    772000  13.556740
9        1985    ATL   NL  harpete01    250000  12.429216
10       1985    ATL   NL  hornebo01   1500000  14.220976
11       1985    ATL   NL  hubbagl01    455000  13.028053
12       1985    ATL   NL  mahleri01    407500  12.917796
13       1985    ATL   NL  mcmurcr01    275000  12.524526
14       1985    ATL   NL  mumphje01    775000  13.560618
15       1985    ATL   NL  murphda05   1625000  14.301018
16       1985    ATL   NL  oberkke01    616667  13.332084
17       1985    ATL   NL  perezpa01    450000  13.017003
18       1985    ATL   NL  perryge01    120000  11.695247
19       1985    ATL   NL  ramirra01    750000  13.527828
20       1985    ATL   NL  suttebr01   1354167  14.118697
21       1985    ATL   NL  washicl01    800000  13.592367
22       1985    BAL   AL  boddimi01    625000  13.345507
23       1985    BAL   AL  dauerri01    480000  13.081541
24       1985    BAL   AL  davisst02    437500  12.988832
25       1985    BAL   AL  dempsri01    512500  13.147056
26       1985    BAL   AL  dwyerji01    375000  12.834681
27       1985    BAL   AL  flanami01    641667  13.371825
28       1985    BAL   AL   fordda01    450000  13.017003
29       1985    BAL   AL  grosswa01    483333  13.088461
...       ...    ...  ...        ...       ...        ...
26398    2016    TOR   AL  stromma01    515900  13.153668
26399    2016    TOR   AL  tholejo01    800000  13.592367
26400    2016    TOR   AL  travide01    511200  13.144516
26401    2016    TOR   AL  tulowtr01  20000000  16.811243
26402    2016    WAS   NL  barreaa01    519400  13.160430
26403    2016    WAS   NL  belisma01   1250000  14.038654
26404    2016    WAS   NL   drewst01   3000000  14.914123
26405    2016    WAS   NL  espinda01   2875000  14.871563
26406    2016    WAS   NL  gonzagi01  12100000  16.308716
26407    2016    WAS   NL  harpebr03   5000000  15.424948
26408    2016    WAS   NL  heisech01   1250000  14.038654
26409    2016    WAS   NL  kellesh01   4000000  15.201805
26410    2016    WAS   NL  lobatjo01   1387500  14.143014
26411    2016    WAS   NL  murphda08   8000000  15.894952
26412    2016    WAS   NL  papeljo01  10936574  16.207623
26413    2016    WAS   NL  perezol01   3000000  14.914123
26414    2016    WAS   NL  petityu01   2500000  14.731801
26415    2016    WAS   NL  ramoswi01   5350000  15.492607
26416    2016    WAS   NL  rendoan01   2800000  14.845130
26417    2016    WAS   NL  reverbe01   6250000  15.648092
26418    2016    WAS   NL  riverfe01    516100  13.154056
26419    2016    WAS   NL  roarkta01    543400  13.205601
26420    2016    WAS   NL  robincl01    534900  13.189835
26421    2016    WAS   NL   rossjo01    514400  13.150756
26422    2016    WAS   NL  scherma01  22142857  16.913026
26423    2016    WAS   NL  strasst01  10400000  16.157316
26424    2016    WAS   NL  taylomi02    524000  13.169247
26425    2016    WAS   NL  treinbl01    524900  13.170963
26426    2016    WAS   NL  werthja01  21733615  16.894371
26427    2016    WAS   NL  zimmery01  14000000  16.454568

[26426 rows x 6 columns]

In [ ]:
# Rename 'YearID' as 'SalYear'

# we're doing this because the salary is the money earned in the year the same year that player appeared
# we want to match salary with the previous year's performance, to see if the wage is determined by it

Salary = Salary.rename(columns = {'yearID':'SalYear'})
Salary

       SalYear teamID lgID   playerID    salary      lnSal
0         1985    ATL   NL  barkele01    870000  13.676248
1         1985    ATL   NL  bedrost01    550000  13.217674
2         1985    ATL   NL  benedbr01    545000  13.208541
3         1985    ATL   NL   campri01    633333  13.358752
4         1985    ATL   NL  ceronri01    625000  13.345507
5         1985    ATL   NL  chambch01    800000  13.592367
6         1985    ATL   NL  dedmoje01    150000  11.918391
7         1985    ATL   NL  forstte01    483333  13.088461
8         1985    ATL   NL  garbege01    772000  13.556740
9         1985    ATL   NL  harpete01    250000  12.429216
10        1985    ATL   NL  hornebo01   1500000  14.220976
11        1985    ATL   NL  hubbagl01    455000  13.028053
12        1985    ATL   NL  mahleri01    407500  12.917796
13        1985    ATL   NL  mcmurcr01    275000  12.524526
14        1985    ATL   NL  mumphje01    775000  13.560618
15        1985    ATL   NL  murphda05   1625000  14.301018
16        1985    ATL   NL  oberkke01    616667  13.332084
17        1985    ATL   NL  perezpa01    450000  13.017003
18        1985    ATL   NL  perryge01    120000  11.695247
19        1985    ATL   NL  ramirra01    750000  13.527828
20        1985    ATL   NL  suttebr01   1354167  14.118697
21        1985    ATL   NL  washicl01    800000  13.592367
22        1985    BAL   AL  boddimi01    625000  13.345507
23        1985    BAL   AL  dauerri01    480000  13.081541
24        1985    BAL   AL  davisst02    437500  12.988832
25        1985    BAL   AL  dempsri01    512500  13.147056
26        1985    BAL   AL  dwyerji01    375000  12.834681
27        1985    BAL   AL  flanami01    641667  13.371825
28        1985    BAL   AL   fordda01    450000  13.017003
29        1985    BAL   AL  grosswa01    483333  13.088461
...        ...    ...  ...        ...       ...        ...
26398     2016    TOR   AL  stromma01    515900  13.153668
26399     2016    TOR   AL  tholejo01    800000  13.592367
26400     2016    TOR   AL  travide01    511200  13.144516
26401     2016    TOR   AL  tulowtr01  20000000  16.811243
26402     2016    WAS   NL  barreaa01    519400  13.160430
26403     2016    WAS   NL  belisma01   1250000  14.038654
26404     2016    WAS   NL   drewst01   3000000  14.914123
26405     2016    WAS   NL  espinda01   2875000  14.871563
26406     2016    WAS   NL  gonzagi01  12100000  16.308716
26407     2016    WAS   NL  harpebr03   5000000  15.424948
26408     2016    WAS   NL  heisech01   1250000  14.038654
26409     2016    WAS   NL  kellesh01   4000000  15.201805
26410     2016    WAS   NL  lobatjo01   1387500  14.143014
26411     2016    WAS   NL  murphda08   8000000  15.894952
26412     2016    WAS   NL  papeljo01  10936574  16.207623
26413     2016    WAS   NL  perezol01   3000000  14.914123
26414     2016    WAS   NL  petityu01   2500000  14.731801
26415     2016    WAS   NL  ramoswi01   5350000  15.492607
26416     2016    WAS   NL  rendoan01   2800000  14.845130
26417     2016    WAS   NL  reverbe01   6250000  15.648092
26418     2016    WAS   NL  riverfe01    516100  13.154056
26419     2016    WAS   NL  roarkta01    543400  13.205601
26420     2016    WAS   NL  robincl01    534900  13.189835
26421     2016    WAS   NL   rossjo01    514400  13.150756
26422     2016    WAS   NL  scherma01  22142857  16.913026
26423     2016    WAS   NL  strasst01  10400000  16.157316
26424     2016    WAS   NL  taylomi02    524000  13.169247
26425     2016    WAS   NL  treinbl01    524900  13.170963
26426     2016    WAS   NL  werthja01  21733615  16.894371
26427     2016    WAS   NL  zimmery01  14000000  16.454568

[26426 rows x 6 columns]

In [ ]:
# Let's create a copy of the df which we call "Master", which we can then use to merge the information from all the other dfs

Master = Salary
Master

       SalYear teamID lgID   playerID    salary      lnSal
0         1985    ATL   NL  barkele01    870000  13.676248
1         1985    ATL   NL  bedrost01    550000  13.217674
2         1985    ATL   NL  benedbr01    545000  13.208541
3         1985    ATL   NL   campri01    633333  13.358752
4         1985    ATL   NL  ceronri01    625000  13.345507
5         1985    ATL   NL  chambch01    800000  13.592367
6         1985    ATL   NL  dedmoje01    150000  11.918391
7         1985    ATL   NL  forstte01    483333  13.088461
8         1985    ATL   NL  garbege01    772000  13.556740
9         1985    ATL   NL  harpete01    250000  12.429216
10        1985    ATL   NL  hornebo01   1500000  14.220976
11        1985    ATL   NL  hubbagl01    455000  13.028053
12        1985    ATL   NL  mahleri01    407500  12.917796
13        1985    ATL   NL  mcmurcr01    275000  12.524526
14        1985    ATL   NL  mumphje01    775000  13.560618
15        1985    ATL   NL  murphda05   1625000  14.301018
16        1985    ATL   NL  oberkke01    616667  13.332084
17        1985    ATL   NL  perezpa01    450000  13.017003
18        1985    ATL   NL  perryge01    120000  11.695247
19        1985    ATL   NL  ramirra01    750000  13.527828
20        1985    ATL   NL  suttebr01   1354167  14.118697
21        1985    ATL   NL  washicl01    800000  13.592367
22        1985    BAL   AL  boddimi01    625000  13.345507
23        1985    BAL   AL  dauerri01    480000  13.081541
24        1985    BAL   AL  davisst02    437500  12.988832
25        1985    BAL   AL  dempsri01    512500  13.147056
26        1985    BAL   AL  dwyerji01    375000  12.834681
27        1985    BAL   AL  flanami01    641667  13.371825
28        1985    BAL   AL   fordda01    450000  13.017003
29        1985    BAL   AL  grosswa01    483333  13.088461
...        ...    ...  ...        ...       ...        ...
26398     2016    TOR   AL  stromma01    515900  13.153668
26399     2016    TOR   AL  tholejo01    800000  13.592367
26400     2016    TOR   AL  travide01    511200  13.144516
26401     2016    TOR   AL  tulowtr01  20000000  16.811243
26402     2016    WAS   NL  barreaa01    519400  13.160430
26403     2016    WAS   NL  belisma01   1250000  14.038654
26404     2016    WAS   NL   drewst01   3000000  14.914123
26405     2016    WAS   NL  espinda01   2875000  14.871563
26406     2016    WAS   NL  gonzagi01  12100000  16.308716
26407     2016    WAS   NL  harpebr03   5000000  15.424948
26408     2016    WAS   NL  heisech01   1250000  14.038654
26409     2016    WAS   NL  kellesh01   4000000  15.201805
26410     2016    WAS   NL  lobatjo01   1387500  14.143014
26411     2016    WAS   NL  murphda08   8000000  15.894952
26412     2016    WAS   NL  papeljo01  10936574  16.207623
26413     2016    WAS   NL  perezol01   3000000  14.914123
26414     2016    WAS   NL  petityu01   2500000  14.731801
26415     2016    WAS   NL  ramoswi01   5350000  15.492607
26416     2016    WAS   NL  rendoan01   2800000  14.845130
26417     2016    WAS   NL  reverbe01   6250000  15.648092
26418     2016    WAS   NL  riverfe01    516100  13.154056
26419     2016    WAS   NL  roarkta01    543400  13.205601
26420     2016    WAS   NL  robincl01    534900  13.189835
26421     2016    WAS   NL   rossjo01    514400  13.150756
26422     2016    WAS   NL  scherma01  22142857  16.913026
26423     2016    WAS   NL  strasst01  10400000  16.157316
26424     2016    WAS   NL  taylomi02    524000  13.169247
26425     2016    WAS   NL  treinbl01    524900  13.170963
26426     2016    WAS   NL  werthja01  21733615  16.894371
26427     2016    WAS   NL  zimmery01  14000000  16.454568

[26426 rows x 6 columns]

# Step 2

We now generate the individual statistics on OBP, SLG and plate appearances (PA). This data is taken from the Lahman database which can be accessed from  [Sean Lahman's website](http://www.seanlahman.com/). Sean Lahman is a journalist and baseball analyst with a strong commitment to the open source movement. Thanks to his pioneering work, much of the data needed to generate your own research is freely available on the web.

The Batting file from the Lahman database covers all major league players from 1871 to the present day (the database is updated annually - the version used here is the update published in March 2018 which included all seasons up to 2017).

Each statistic in the database is coded with a short name for ease of use. All the [definitions](http://www.seanlahman.com/files/database/readme2017.txt) can be found on the Lahman website.

In [ ]:
# Read in batting

Batting = pd.read_csv("../Data/Batting.csv")
pd.set_option('display.max_columns', 50)
display(Batting)

# Scrolling to the bottom of the window you can see that the size of the dataframe is 104324 rows × 22 columns

,playerID,yearID,stint,teamID,lgID,G,AB,R,H,Doubles,Triples,HR,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP
0,abercda01,1871,1,TRO,NaN,1,4,0,0,0,0,0,0.0,0.0,0.0,0,0.0,NaN,NaN,NaN,NaN,NaN
1,addybo01,1871,1,RC1,NaN,25,118,30,32,6,0,0,13.0,8.0,1.0,4,0.0,NaN,NaN,NaN,NaN,NaN
2,allisar01,1871,1,CL1,NaN,29,137,28,40,4,5,0,19.0,3.0,1.0,2,5.0,NaN,NaN,NaN,NaN,NaN
3,allisdo01,1871,1,WS3,NaN,27,133,28,44,10,2,2,27.0,1.0,1.0,0,2.0,NaN,NaN,NaN,NaN,NaN
4,ansonca01,1871,1,RC1,NaN,25,120,29,39,11,3,0,16.0,6.0,2.0,2,1.0,NaN,NaN,NaN,NaN,NaN
5,armstbo01,1871,1,FW1,NaN,12,49,9,11,2,1,0,5.0,0.0,1.0,0,1.0,NaN,NaN,NaN,NaN,NaN
6,barkeal01,1871,1,RC1,NaN,1,4,0,1,0,0,0,2.0,0.0,0.0,1,0.0,NaN,NaN,NaN,NaN,NaN
7,barnero01,1871,1,BS1,NaN,31,157,66,63,10,9,0,34.0,11.0,6.0,13,1.0,NaN,NaN,NaN,NaN,NaN
8,barrebi01,1871,1,FW1,NaN,1,5,1,1,1,0,0,1.0,0.0,0.0,0,0.0,NaN,NaN,NaN,NaN,NaN
9,barrofr01,1871,1,BS1,NaN,18,86,13,13,2,1,0,11.0,1.0,0.0,0,0.0,NaN,NaN,NaN,NaN,NaN
10,bassjo01,1871,1,CL1,NaN,22,89,18,27,1,10,3,18.0,0.0,1.0,3,4.0,NaN,NaN,NaN,NaN,NaN
11,battijo01,1871,1,CL1,NaN,1,3,0,0,0,0,0,0.0,0.0,0.0,1,0.0,NaN,NaN,NaN,NaN,NaN
12,bealsto01,1871,1,WS3,NaN,10,36,6,7,0,0,0,1.0,2.0,0.0,2,0.0,NaN,NaN,NaN,NaN,NaN
13,beaveed01,1871,1,TRO,NaN,3,15,7,6,0,0,0,5.0,2.0,0.0,0,0.0,NaN,NaN,NaN,NaN,NaN
14,bechtge01,1871,1,PH1,NaN,20,94,24,33,9,1,1,21.0,4.0,0.0,2,2.0,NaN,NaN,NaN,NaN,NaN
15,bellast01,1871,1,TRO,NaN,29,128,26,32,3,3,0,23.0,4.0,4.0,9,2.0,NaN,NaN,NaN,NaN,NaN
16,berkena01,1871,1,PH1,NaN,1,4,0,0,0,0,0,0.0,0.0,0.0,0,3.0,NaN,NaN,NaN,NaN,NaN
17,berryto01,1871,1,PH1,NaN,1,4,0,1,0,0,0,0.0,0.0,0.0,0,0.0,NaN,NaN,NaN,NaN,NaN
18,berthha01,1871,1,WS3,NaN,17,73,17,17,1,1,0,8.0,3.0,1.0,4,2.0,NaN,NaN,NaN,NaN,NaN
19,biermch01,1871,1,FW1,NaN,1,2,0,0,0,0,0,0.0,0.0,0.0,1,0.0,NaN,NaN,NaN,NaN,NaN
20,birdge01,1871,1,RC1,NaN,25,106,19,28,2,5,0,13.0,1.0,0.0,3,2.0,NaN,NaN,NaN,NaN,NaN
21,birdsda01,1871,1,BS1,NaN,29,152,51,46,3,3,0,24.0,6.0,0.0,4,4.0,NaN,NaN,NaN,NaN,NaN
22,brainas01,1871,1,WS3,NaN,30,134,24,30,4,0,0,21.0,4.0,0.0,7,2.0,NaN,NaN,NaN,NaN,NaN
23,brannmi01,1871,1,CH1,NaN,3,14,2,1,0,0,0,0.0,0.0,0.0,0,0.0,NaN,NaN,NaN,NaN,NaN
24,burrohe01,1871,1,WS3,NaN,12,63,11,15,2,3,1,14.0,0.0,0.0,1,1.0,NaN,NaN,NaN,NaN,NaN
25,careyto01,1871,1,FW1,NaN,19,87,16,20,2,0,0,10.0,5.0,0.0,2,1.0,NaN,NaN,NaN,NaN,NaN
26,carleji01,1871,1,CL1,NaN,29,127,31,32,8,1,0,18.0,2.0,1.0,8,3.0,NaN,NaN,NaN,NaN,NaN
27,conefr01,1871,1,BS1,NaN,19,77,17,20,3,1,0,16.0,12.0,1.0,8,2.0,NaN,NaN,NaN,NaN,NaN
28,connone01,1871,1,TRO,NaN,7,33,6,7,0,0,0,2.0,0.0,0.0,0,0.0,NaN,NaN,NaN,NaN,NaN
29,cravebi01,1871,1,TRO,NaN,27,118,26,38,8,1,0,26.0,6.0,3.0,3,0.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102786,wittgni01,2016,1,MIA,NL,48,0,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
102787,wolteto01,2016,1,COL,NL,71,205,27,53,15,2,3,30.0,4.0,1.0,21,53.0,2.0,0.0,4.0,0.0,1.0
102788,wongko01,2016,1,SLN,NL,121,313,39,75,7,7,5,23.0,7.0,0.0,34,52.0,2.0,9.0,0.0,5.0,3.0
102789,woodal02,2016,1,LAN,NL,15,16,2,4,0,0,0,2.0,0.0,0.0,1,9.0,0.0,0.0,2.0,0.0,0.0
102790,woodbl01,2016,1,CIN,NL,70,2,0,0,0,0,0,0.0,0.0,0.0,0,2.0,0.0,0.0,0.0,0.0,0.0
102791,woodtr01,2016,1,CHN,NL,81,11,0,2,0,0,0,1.0,0.0,0.0,1,5.0,0.0,0.0,0.0,0.0,0.0
102792,worleva01,2016,1,BAL,AL,35,0,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
102793,worthda01,2016,1,HOU,AL,16,39,4,7,2,0,0,1.0,0.0,0.0,1,6.0,0.0,0.0,0.0,0.0,1.0
102794,wrighda03,2016,1,NYN,NL,37,137,18,31,8,0,7,14.0,3.0,2.0,26,55.0,0.0,0.0,0.0,0.0,0.0
102795,wrighda04,2016,1,CIN,NL,4,5,0,0,0,0,0,0.0,0.0,0.0,0,2.0,0.0,0.0,1.0,0.0,0.0
102796,wrighda04,2016,2,LAA,AL,5,0,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
102797,wrighmi01,2016,1,BAL,AL,18,0,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
102798,wrighst01,2016,1,BOS,AL,25,4,0,0,0,0,0,0.0,0.0,0.0,0,3.0,0.0,0.0,0.0,0.0,0.0
102799,yateski01,2016,1,NYA,AL,41,0,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
102800,yelicch01,2016,1,MIA,NL,155,578,78,172,38,3,21,98.0,9.0,4.0,72,138.0,4.0,4.0,0.0,5.0,20.0
102801,ynoaga01,2016,1,NYN,NL,10,3,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
102802,ynoami01,2016,1,CHA,AL,23,0,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
102803,ynoara01,2016,1,COL,NL,3,5,0,0,0,0,0,0.0,0.0,0.0,0,2.0,0.0,0.0,0.0,0.0,0.0
102804,youngch03,2016,1,KCA,AL,34,1,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
102805,youngch04,2016,1,BOS,AL,76,203,29,56,18,0,9,24.0,4.0,2.0,21,50.0,0.0,3.0,0.0,0.0,4.0
102806,younger03,2016,1,NYA,AL,6,1,2,0,0,0,0,0.0,1.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
102807,youngma03,2016,1,ATL,NL,8,0,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
102808,zastrro01,2016,1,CHN,NL,8,3,0,0,0,0,0,0.0,0.0,0.0,0,2.0,0.0,0.0,0.0,0.0,0.0
102809,zieglbr01,2016,1,ARI,NL,36,0,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
102810,zieglbr01,2016,2,BOS,AL,33,0,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
102811,zimmejo02,2016,1,DET,AL,19,4,0,1,0,0,0,0.0,0.0,0.0,0,2.0,0.0,0.0,1.0,0.0,0.0
102812,zimmery01,2016,1,WAS,NL,115,427,60,93,18,1,15,46.0,4.0,1.0,29,104.0,1.0,5.0,0.0,6.0,12.0
102813,zobribe01,2016,1,CHN,NL,147,523,94,142,31,3,18,76.0,6.0,4.0,96,82.0,6.0,4.0,4.0,4.0,17.0
102814,zuninmi01,2016,1,SEA,AL,55,164,16,34,7,0,12,31.0,0.0,0.0,21,65.0,0.0,6.0,0.0,1.0,0.0
102815,zychto01,2016,1,SEA,AL,12,0,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0

## Self test

Note that we used the command, pd.set_option('display.max_columns', 50).

Try running the code again without this line, and see what happens.

## Stints

A player who moves teams can play for more than one club in a season. These are recorded as "stints" in the dataframe. We adjust a player's total performance statistics for the year, so we simply sum the data across stints.

In [ ]:
# Using '.groupby' to sum across stints

Batting = Batting.groupby(['playerID','yearID']).sum()
Batting.reset_index(inplace=True)
Batting

,playerID,yearID,stint,G,AB,R,H,Doubles,Triples,HR,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP
0,aardsda01,2004,1,11,0,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
1,aardsda01,2006,1,45,2,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,1.0,0.0,0.0
2,aardsda01,2007,1,25,0,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,aardsda01,2008,1,47,1,0,0,0,0,0,0.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0
4,aardsda01,2009,1,73,0,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
5,aardsda01,2010,1,53,0,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
6,aardsda01,2012,1,1,0,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
7,aardsda01,2013,1,43,0,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
8,aardsda01,2015,1,33,1,0,0,0,0,0,0.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0
9,aaronha01,1954,1,122,468,58,131,27,6,13,69.0,2.0,2.0,28,39.0,0.0,3.0,6.0,4.0,13.0
10,aaronha01,1955,1,153,602,105,189,37,9,27,106.0,3.0,1.0,49,61.0,5.0,3.0,7.0,4.0,20.0
11,aaronha01,1956,1,153,609,106,200,34,14,26,92.0,2.0,4.0,37,54.0,6.0,2.0,5.0,7.0,21.0
12,aaronha01,1957,1,151,615,118,198,27,6,44,132.0,1.0,1.0,57,58.0,15.0,0.0,0.0,3.0,13.0
13,aaronha01,1958,1,153,601,109,196,34,4,30,95.0,4.0,1.0,59,49.0,16.0,1.0,0.0,3.0,21.0
14,aaronha01,1959,1,154,629,116,223,46,7,39,123.0,8.0,0.0,51,54.0,17.0,4.0,0.0,9.0,19.0
15,aaronha01,1960,1,153,590,102,172,20,11,40,126.0,16.0,7.0,60,63.0,13.0,2.0,0.0,12.0,8.0
16,aaronha01,1961,1,155,603,115,197,39,10,34,120.0,21.0,9.0,56,64.0,20.0,2.0,1.0,9.0,16.0
17,aaronha01,1962,1,156,592,127,191,28,6,45,128.0,15.0,7.0,66,73.0,14.0,3.0,0.0,6.0,14.0
18,aaronha01,1963,1,161,631,121,201,29,4,44,130.0,31.0,5.0,78,94.0,18.0,0.0,0.0,5.0,11.0
19,aaronha01,1964,1,145,570,103,187,30,2,24,95.0,22.0,4.0,62,46.0,9.0,0.0,0.0,2.0,22.0
20,aaronha01,1965,1,150,570,109,181,40,1,32,89.0,24.0,4.0,60,81.0,10.0,1.0,0.0,8.0,15.0
21,aaronha01,1966,1,158,603,117,168,23,1,44,127.0,21.0,3.0,76,96.0,15.0,1.0,0.0,8.0,14.0
22,aaronha01,1967,1,155,600,113,184,37,3,39,109.0,17.0,6.0,63,97.0,19.0,0.0,0.0,6.0,11.0
23,aaronha01,1968,1,160,606,84,174,33,4,29,86.0,28.0,5.0,64,62.0,23.0,1.0,0.0,5.0,21.0
24,aaronha01,1969,1,147,547,100,164,30,3,44,97.0,9.0,10.0,87,47.0,19.0,2.0,0.0,3.0,14.0
25,aaronha01,1970,1,150,516,103,154,26,1,38,118.0,9.0,0.0,74,63.0,15.0,2.0,0.0,6.0,13.0
26,aaronha01,1971,1,139,495,95,162,22,3,47,118.0,1.0,1.0,71,58.0,21.0,2.0,0.0,5.0,9.0
27,aaronha01,1972,1,129,449,75,119,10,0,34,77.0,4.0,0.0,92,55.0,15.0,1.0,0.0,2.0,17.0
28,aaronha01,1973,1,120,392,84,118,12,1,40,96.0,1.0,1.0,68,51.0,13.0,1.0,0.0,4.0,7.0
29,aaronha01,1974,1,112,340,47,91,16,0,20,69.0,1.0,0.0,39,29.0,6.0,0.0,1.0,2.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95220,zupcibo01,1991,1,18,25,3,4,0,0,1,3.0,0.0,0.0,1,6.0,0.0,0.0,1.0,0.0,0.0
95221,zupcibo01,1992,1,124,392,46,108,19,1,3,43.0,2.0,2.0,25,60.0,1.0,4.0,7.0,4.0,6.0
95222,zupcibo01,1993,1,141,286,40,69,24,2,2,26.0,5.0,2.0,27,54.0,2.0,2.0,8.0,3.0,7.0
95223,zupcibo01,1994,3,36,92,10,18,4,1,1,8.0,0.0,1.0,4,17.0,0.0,0.0,4.0,1.0,2.0
95224,zupofr01,1957,1,10,12,2,1,0,0,0,0.0,0.0,0.0,1,4.0,0.0,0.0,0.0,0.0,0.0
95225,zupofr01,1958,1,1,2,0,0,0,0,0,0.0,0.0,0.0,0,1.0,0.0,0.0,0.0,0.0,0.0
95226,zupofr01,1961,1,5,4,1,2,1,0,0,0.0,0.0,0.0,1,1.0,0.0,0.0,0.0,0.0,0.0
95227,zuvelpa01,1982,1,2,1,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
95228,zuvelpa01,1983,1,3,5,0,0,0,0,0,0.0,0.0,0.0,2,1.0,0.0,1.0,0.0,0.0,0.0
95229,zuvelpa01,1984,1,11,25,2,5,1,0,0,1.0,0.0,0.0,2,3.0,0.0,0.0,0.0,0.0,0.0
95230,zuvelpa01,1985,1,81,190,16,48,8,1,0,4.0,2.0,0.0,16,14.0,1.0,0.0,4.0,0.0,3.0
95231,zuvelpa01,1986,1,21,48,2,4,1,0,0,2.0,0.0,0.0,5,4.0,0.0,0.0,4.0,0.0,1.0
95232,zuvelpa01,1987,1,14,34,2,6,0,0,0,0.0,0.0,0.0,0,4.0,0.0,0.0,2.0,0.0,1.0
95233,zuvelpa01,1988,1,51,130,9,30,5,1,0,7.0,0.0,0.0,8,13.0,0.0,0.0,8.0,0.0,3.0
95234,zuvelpa01,1989,1,24,58,10,16,2,0,2,6.0,0.0,0.0,1,11.0,0.0,1.0,0.0,0.0,0.0
95235,zuvelpa01,1991,1,2,0,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
95236,zuverge01,1951,1,16,0,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
95237,zuverge01,1952,1,2,0,1,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
95238,zuverge01,1954,3,37,66,2,9,1,0,0,3.0,0.0,1.0,1,15.0,0.0,0.0,9.0,0.0,2.0
95239,zuverge01,1955,3,42,27,1,5,1,0,0,0.0,0.0,0.0,1,7.0,0.0,0.0,1.0,0.0,1.0
95240,zuverge01,1956,1,62,17,0,2,0,0,0,2.0,0.0,0.0,1,7.0,0.0,0.0,4.0,0.0,0.0
95241,zuverge01,1957,1,56,23,1,3,0,0,0,0.0,0.0,0.0,3,8.0,0.0,0.0,2.0,0.0,0.0
95242,zuverge01,1958,1,45,9,0,2,0,1,0,2.0,0.0,0.0,1,2.0,0.0,0.0,0.0,0.0,0.0
95243,zuverge01,1959,1,6,0,0,0,0,0,0,0.0,0.0,0.0,2,0.0,0.0,0.0,0.0,0.0,0.0
95244,zwilldu01,1910,1,27,87,7,16,5,0,0,5.0,1.0,0.0,11,0.0,0.0,1.0,1.0,0.0,0.0
95245,zwilldu01,1914,1,154,592,91,185,38,8,16,95.0,21.0,0.0,46,68.0,0.0,1.0,10.0,0.0,0.0
95246,zwilldu01,1915,1,150,548,65,157,32,7,13,94.0,24.0,0.0,67,65.0,0.0,2.0,18.0,0.0,0.0
95247,zwilldu01,1916,1,35,53,4,6,1,0,1,8.0,0.0,0.0,4,6.0,0.0,0.0,2.0,0.0,0.0
95248,zychto01,2015,1,13,0,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
95249,zychto01,2016,1,12,0,0,0,0,0,0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0

## Self test

Note that we've now lost the name of the team and the league from the data - since with the sum() command Python can't add together strings and so just drops them (which is fine since we won't need them). However, the player identifiers, which are also strings, are retained since the name never changes when a player has multiple stints.

We added the command, Batting.reset_index(inplace=True).

Trying running the code without this. Can you see why this would be a problem later on without reset_index?

## Variables required to define OBP and SLG

**SLG is defined as (Singles + 2x Doubles + 3x Triples + 4 x Home runs) / At bats**  
**OBP is defined as (Hits + Bases on Balls + Hit by Pitch)/(At bats + Bases on Balls + Hit by Pitch + Sacrifice Flies)**  

Singles and Plate Appearances are not listed separately in the Lahman batting dataframe, but singles can be defined as Hits - Home runs - Triples - Doubles. Plate appearances can be defined as At bats + Base on Balls (Walk) + Hit by pitch + Sacrfice hits + Sacrifice flies.

The variables we need have mostly intuitive names: AB, H, 2B, 3B, HR, R, BB, HBP, SF, SH.

We're not going to use all the data back to 1871. Hakes and Sauer worked on the data from 1999-2004. Later, we will extend this analysis. So right now we'll limit our data range to the years 1993-2016. In addition, we limit the player sample to players with more than 130  At Bats. All players below this threshold are defined as rookies.

In [ ]:
# Subset Batting data to only include seasons 1994-2016 and batters with at least 130 AB

Batting = Batting[(Batting.yearID >= 1993) & (Batting.yearID <= 2016) & (Batting.AB >= 130)].copy()
display(Batting)

# you can see that our dt now consists of 8937 rows × 20 columns

,playerID,yearID,stint,G,AB,R,H,Doubles,Triples,HR,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP
98,abbotje01,1998,1,89,244,33,68,14,1,12,41.0,3.0,3.0,9,28.0,1.0,0.0,2.0,5.0,2.0
100,abbotje01,2000,1,80,215,31,59,15,1,3,29.0,2.0,1.0,21,38.0,1.0,2.0,2.0,1.0,2.0
113,abbotku01,1994,1,101,345,41,86,17,3,9,33.0,3.0,0.0,16,98.0,1.0,5.0,3.0,2.0,5.0
114,abbotku01,1995,1,120,420,60,107,18,7,17,60.0,4.0,3.0,36,110.0,4.0,5.0,2.0,5.0,6.0
115,abbotku01,1996,1,109,320,37,81,18,7,8,33.0,3.0,3.0,22,99.0,1.0,3.0,4.0,0.0,7.0
116,abbotku01,1997,1,94,252,35,69,18,2,6,30.0,3.0,1.0,14,68.0,3.0,1.0,6.0,0.0,5.0
117,abbotku01,1998,3,77,194,26,51,13,1,5,24.0,2.0,1.0,12,53.0,0.0,2.0,1.0,3.0,5.0
118,abbotku01,1999,1,96,286,41,78,17,2,8,41.0,3.0,2.0,16,69.0,0.0,0.0,2.0,1.0,4.0
119,abbotku01,2000,1,79,157,22,34,7,1,6,12.0,1.0,1.0,14,51.0,2.0,1.0,0.0,1.0,2.0
144,abercre01,2006,1,111,255,39,54,12,2,5,24.0,6.0,5.0,18,78.0,2.0,3.0,4.0,1.0,2.0
148,abernbr01,2001,1,79,304,43,82,17,1,5,33.0,8.0,3.0,27,35.0,1.0,0.0,3.0,1.0,3.0
149,abernbr01,2002,1,117,463,46,112,18,4,2,40.0,10.0,4.0,25,46.0,0.0,6.0,8.0,2.0,8.0
194,abreubo01,1997,1,59,188,22,47,10,2,3,26.0,7.0,2.0,21,48.0,0.0,1.0,0.0,0.0,0.0
195,abreubo01,1998,1,151,497,68,155,29,6,17,74.0,19.0,10.0,84,133.0,14.0,0.0,4.0,4.0,6.0
196,abreubo01,1999,1,152,546,118,183,35,11,20,93.0,27.0,9.0,109,113.0,8.0,3.0,0.0,4.0,13.0
197,abreubo01,2000,1,154,576,103,182,42,10,25,79.0,28.0,8.0,100,116.0,9.0,1.0,0.0,3.0,12.0
198,abreubo01,2001,1,162,588,118,170,48,4,31,110.0,36.0,14.0,106,137.0,11.0,1.0,0.0,9.0,13.0
199,abreubo01,2002,1,157,572,102,176,50,6,20,85.0,31.0,12.0,104,117.0,9.0,3.0,0.0,6.0,11.0
200,abreubo01,2003,1,158,577,99,173,35,1,20,101.0,22.0,9.0,109,126.0,13.0,2.0,0.0,7.0,13.0
201,abreubo01,2004,1,159,574,118,173,47,1,30,105.0,40.0,5.0,127,116.0,10.0,5.0,0.0,7.0,5.0
202,abreubo01,2005,1,162,588,104,168,37,1,24,102.0,31.0,9.0,117,134.0,15.0,6.0,0.0,8.0,7.0
203,abreubo01,2006,3,156,548,98,163,41,2,15,107.0,30.0,6.0,124,138.0,6.0,3.0,2.0,9.0,13.0
204,abreubo01,2007,1,158,605,123,171,40,5,16,101.0,25.0,8.0,84,115.0,0.0,3.0,0.0,7.0,11.0
205,abreubo01,2008,1,156,609,100,180,39,4,20,100.0,22.0,11.0,73,109.0,2.0,1.0,0.0,1.0,14.0
206,abreubo01,2009,1,152,563,96,165,29,3,15,103.0,30.0,8.0,94,113.0,7.0,1.0,0.0,9.0,15.0
207,abreubo01,2010,1,154,573,88,146,41,1,20,78.0,24.0,10.0,87,132.0,3.0,2.0,0.0,5.0,13.0
208,abreubo01,2011,1,142,502,54,127,30,1,8,60.0,21.0,5.0,78,113.0,5.0,1.0,1.0,3.0,8.0
209,abreubo01,2012,3,100,219,29,53,11,1,3,24.0,6.0,2.0,37,56.0,3.0,0.0,0.0,1.0,7.0
210,abreubo01,2014,1,78,133,12,33,9,0,1,14.0,1.0,0.0,20,21.0,0.0,0.0,0.0,2.0,3.0
212,abreujo02,2014,1,145,556,80,176,35,2,36,107.0,3.0,1.0,51,131.0,15.0,11.0,0.0,4.0,14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94987,zeileto01,2001,1,151,531,66,141,25,1,10,62.0,1.0,0.0,73,102.0,3.0,6.0,0.0,2.0,15.0
94988,zeileto01,2002,1,144,506,61,138,23,0,18,87.0,1.0,1.0,66,92.0,3.0,1.0,0.0,7.0,27.0
94989,zeileto01,2003,3,100,299,40,68,10,2,11,42.0,1.0,0.0,34,54.0,0.0,3.0,0.0,5.0,6.0
94990,zeileto01,2004,1,137,348,30,81,16,0,9,35.0,0.0,0.0,44,83.0,1.0,1.0,1.0,2.0,13.0
95105,zimmery01,2006,1,157,614,84,176,47,3,20,110.0,11.0,8.0,61,120.0,7.0,2.0,1.0,4.0,15.0
95106,zimmery01,2007,1,162,653,99,174,43,5,24,91.0,4.0,1.0,61,125.0,3.0,3.0,0.0,5.0,26.0
95107,zimmery01,2008,1,106,428,51,121,24,1,14,51.0,1.0,1.0,31,71.0,1.0,3.0,0.0,4.0,12.0
95108,zimmery01,2009,1,157,610,110,178,37,3,33,106.0,2.0,0.0,72,119.0,9.0,2.0,0.0,9.0,22.0
95109,zimmery01,2010,1,142,525,85,161,32,0,25,85.0,4.0,1.0,69,98.0,6.0,4.0,0.0,5.0,16.0
95110,zimmery01,2011,1,101,395,52,114,21,2,12,49.0,3.0,1.0,41,73.0,4.0,1.0,0.0,3.0,14.0
95111,zimmery01,2012,1,145,578,93,163,36,1,25,95.0,5.0,2.0,57,116.0,8.0,2.0,0.0,4.0,20.0
95112,zimmery01,2013,1,147,568,84,156,26,2,26,79.0,6.0,0.0,60,133.0,2.0,2.0,0.0,3.0,16.0
95113,zimmery01,2014,1,61,214,26,60,19,1,5,38.0,0.0,0.0,22,37.0,0.0,0.0,0.0,4.0,6.0
95114,zimmery01,2015,1,95,346,43,86,25,1,16,73.0,1.0,0.0,33,79.0,0.0,1.0,0.0,10.0,13.0
95115,zimmery01,2016,1,115,427,60,93,18,1,15,46.0,4.0,1.0,29,104.0,1.0,5.0,0.0,6.0,12.0
95170,zobribe01,2006,1,52,183,10,41,6,2,2,18.0,2.0,3.0,10,26.0,1.0,0.0,2.0,3.0,2.0
95172,zobribe01,2008,1,62,198,32,50,10,2,12,30.0,3.0,0.0,25,37.0,1.0,2.0,0.0,2.0,4.0
95173,zobribe01,2009,1,152,501,91,149,28,7,27,91.0,17.0,6.0,91,104.0,4.0,2.0,1.0,4.0,7.0
95174,zobribe01,2010,1,151,541,77,129,28,2,10,75.0,24.0,3.0,92,107.0,1.0,3.0,7.0,12.0,10.0
95175,zobribe01,2011,1,156,588,99,158,46,6,20,91.0,19.0,6.0,77,128.0,1.0,2.0,2.0,5.0,9.0
95176,zobribe01,2012,1,157,560,88,151,39,7,20,74.0,14.0,9.0,97,103.0,7.0,3.0,2.0,6.0,13.0
95177,zobribe01,2013,1,157,612,77,168,36,3,12,71.0,11.0,3.0,72,91.0,4.0,7.0,1.0,6.0,18.0
95178,zobribe01,2014,1,146,570,83,155,34,3,10,52.0,10.0,5.0,75,84.0,4.0,1.0,2.0,6.0,8.0
95179,zobribe01,2015,3,126,467,76,129,36,3,13,56.0,3.0,4.0,62,56.0,3.0,1.0,0.0,5.0,8.0
95180,zobribe01,2016,1,147,523,94,142,31,3,18,76.0,6.0,4.0,96,82.0,6.0,4.0,4.0,4.0,17.0
95216,zuninmi01,2013,1,52,173,22,37,5,0,5,14.0,1.0,0.0,16,49.0,0.0,3.0,0.0,1.0,5.0
95217,zuninmi01,2014,1,131,438,51,87,20,2,22,60.0,0.0,3.0,17,158.0,1.0,17.0,0.0,4.0,12.0
95218,zuninmi01,2015,1,112,350,28,61,11,0,11,28.0,0.0,1.0,21,132.0,0.0,5.0,8.0,2.0,6.0
95219,zuninmi01,2016,1,55,164,16,34,7,0,12,31.0,0.0,0.0,21,65.0,0.0,6.0,0.0,1.0,0.0
95222,zupcibo01,1993,1,141,286,40,69,24,2,2,26.0,5.0,2.0,27,54.0,2.0,2.0,8.0,3.0,7.0

Note: Note the addition of ".copy()" to the command. The code will, in fact, run without this addition, but it will produce a warning message. This is not the same as an error message when your code doesn't run at all. Leaving out ".copy()" will not in fact affect anything in this notebook, but will continue to generate irritating warning messages. You will see this come up at other places in the notebooks.

## We now use the formulas to calculate PA, OBP and SLG

PA = AB + BB + HBP + SH + SF

OBP = (H + BB + HBP)/(AB + BB + HBP + SF)

SLG (H - 2B - 3B - HR + 2x2B + 3x3B + 4xHR) / AB

(Recall that Singles = H - 2B - 3B - HR)

In [ ]:
# Calculate OBP and SLG in Batting data

Batting['PA'] = Batting['AB'] + Batting['BB'] + Batting['HBP'] + Batting['SH'] + Batting['SF']

Batting['OBP'] = (Batting['H'] + Batting['BB'] + Batting['HBP'])/(Batting['AB'] + Batting['BB']
                                                                  + Batting['HBP'] + Batting['SF'])

Batting['SLG'] = ((Batting['H'] - Batting['Doubles'] - Batting['Triples'] - Batting['HR'])
                  + 2*Batting['Doubles'] + 3*Batting['Triples'] + 4*Batting['HR'])/Batting['AB']

display(Batting)

,playerID,yearID,stint,G,AB,R,H,Doubles,Triples,HR,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP,PA,OBP,SLG
98,abbotje01,1998,1,89,244,33,68,14,1,12,41.0,3.0,3.0,9,28.0,1.0,0.0,2.0,5.0,2.0,260.0,0.298450,0.491803
100,abbotje01,2000,1,80,215,31,59,15,1,3,29.0,2.0,1.0,21,38.0,1.0,2.0,2.0,1.0,2.0,241.0,0.343096,0.395349
113,abbotku01,1994,1,101,345,41,86,17,3,9,33.0,3.0,0.0,16,98.0,1.0,5.0,3.0,2.0,5.0,371.0,0.290761,0.394203
114,abbotku01,1995,1,120,420,60,107,18,7,17,60.0,4.0,3.0,36,110.0,4.0,5.0,2.0,5.0,6.0,468.0,0.317597,0.452381
115,abbotku01,1996,1,109,320,37,81,18,7,8,33.0,3.0,3.0,22,99.0,1.0,3.0,4.0,0.0,7.0,349.0,0.307246,0.428125
116,abbotku01,1997,1,94,252,35,69,18,2,6,30.0,3.0,1.0,14,68.0,3.0,1.0,6.0,0.0,5.0,273.0,0.314607,0.432540
117,abbotku01,1998,3,77,194,26,51,13,1,5,24.0,2.0,1.0,12,53.0,0.0,2.0,1.0,3.0,5.0,212.0,0.308057,0.417526
118,abbotku01,1999,1,96,286,41,78,17,2,8,41.0,3.0,2.0,16,69.0,0.0,0.0,2.0,1.0,4.0,305.0,0.310231,0.430070
119,abbotku01,2000,1,79,157,22,34,7,1,6,12.0,1.0,1.0,14,51.0,2.0,1.0,0.0,1.0,2.0,173.0,0.283237,0.388535
144,abercre01,2006,1,111,255,39,54,12,2,5,24.0,6.0,5.0,18,78.0,2.0,3.0,4.0,1.0,2.0,281.0,0.270758,0.333333
148,abernbr01,2001,1,79,304,43,82,17,1,5,33.0,8.0,3.0,27,35.0,1.0,0.0,3.0,1.0,3.0,335.0,0.328313,0.381579
149,abernbr01,2002,1,117,463,46,112,18,4,2,40.0,10.0,4.0,25,46.0,0.0,6.0,8.0,2.0,8.0,504.0,0.288306,0.311015
194,abreubo01,1997,1,59,188,22,47,10,2,3,26.0,7.0,2.0,21,48.0,0.0,1.0,0.0,0.0,0.0,210.0,0.328571,0.372340
195,abreubo01,1998,1,151,497,68,155,29,6,17,74.0,19.0,10.0,84,133.0,14.0,0.0,4.0,4.0,6.0,589.0,0.408547,0.496982
196,abreubo01,1999,1,152,546,118,183,35,11,20,93.0,27.0,9.0,109,113.0,8.0,3.0,0.0,4.0,13.0,662.0,0.445619,0.549451
197,abreubo01,2000,1,154,576,103,182,42,10,25,79.0,28.0,8.0,100,116.0,9.0,1.0,0.0,3.0,12.0,680.0,0.416176,0.553819
198,abreubo01,2001,1,162,588,118,170,48,4,31,110.0,36.0,14.0,106,137.0,11.0,1.0,0.0,9.0,13.0,704.0,0.393466,0.542517
199,abreubo01,2002,1,157,572,102,176,50,6,20,85.0,31.0,12.0,104,117.0,9.0,3.0,0.0,6.0,11.0,685.0,0.413139,0.520979
200,abreubo01,2003,1,158,577,99,173,35,1,20,101.0,22.0,9.0,109,126.0,13.0,2.0,0.0,7.0,13.0,695.0,0.408633,0.467938
201,abreubo01,2004,1,159,574,118,173,47,1,30,105.0,40.0,5.0,127,116.0,10.0,5.0,0.0,7.0,5.0,713.0,0.427770,0.543554
202,abreubo01,2005,1,162,588,104,168,37,1,24,102.0,31.0,9.0,117,134.0,15.0,6.0,0.0,8.0,7.0,719.0,0.404729,0.474490
203,abreubo01,2006,3,156,548,98,163,41,2,15,107.0,30.0,6.0,124,138.0,6.0,3.0,2.0,9.0,13.0,686.0,0.423977,0.461679
204,abreubo01,2007,1,158,605,123,171,40,5,16,101.0,25.0,8.0,84,115.0,0.0,3.0,0.0,7.0,11.0,699.0,0.369099,0.444628
205,abreubo01,2008,1,156,609,100,180,39,4,20,100.0,22.0,11.0,73,109.0,2.0,1.0,0.0,1.0,14.0,684.0,0.371345,0.471264
206,abreubo01,2009,1,152,563,96,165,29,3,15,103.0,30.0,8.0,94,113.0,7.0,1.0,0.0,9.0,15.0,667.0,0.389805,0.435169
207,abreubo01,2010,1,154,573,88,146,41,1,20,78.0,24.0,10.0,87,132.0,3.0,2.0,0.0,5.0,13.0,667.0,0.352324,0.434555
208,abreubo01,2011,1,142,502,54,127,30,1,8,60.0,21.0,5.0,78,113.0,5.0,1.0,1.0,3.0,8.0,585.0,0.352740,0.364542
209,abreubo01,2012,3,100,219,29,53,11,1,3,24.0,6.0,2.0,37,56.0,3.0,0.0,0.0,1.0,7.0,257.0,0.350195,0.342466
210,abreubo01,2014,1,78,133,12,33,9,0,1,14.0,1.0,0.0,20,21.0,0.0,0.0,0.0,2.0,3.0,155.0,0.341935,0.338346
212,abreujo02,2014,1,145,556,80,176,35,2,36,107.0,3.0,1.0,51,131.0,15.0,11.0,0.0,4.0,14.0,622.0,0.382637,0.580935
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94987,zeileto01,2001,1,151,531,66,141,25,1,10,62.0,1.0,0.0,73,102.0,3.0,6.0,0.0,2.0,15.0,612.0,0.359477,0.372881
94988,zeileto01,2002,1,144,506,61,138,23,0,18,87.0,1.0,1.0,66,92.0,3.0,1.0,0.0,7.0,27.0,580.0,0.353448,0.424901
94989,zeileto01,2003,3,100,299,40,68,10,2,11,42.0,1.0,0.0,34,54.0,0.0,3.0,0.0,5.0,6.0,341.0,0.307918,0.384615
94990,zeileto01,2004,1,137,348,30,81,16,0,9,35.0,0.0,0.0,44,83.0,1.0,1.0,1.0,2.0,13.0,396.0,0.318987,0.356322
95105,zimmery01,2006,1,157,614,84,176,47,3,20,110.0,11.0,8.0,61,120.0,7.0,2.0,1.0,4.0,15.0,682.0,0.350954,0.470684
95106,zimmery01,2007,1,162,653,99,174,43,5,24,91.0,4.0,1.0,61,125.0,3.0,3.0,0.0,5.0,26.0,722.0,0.329640,0.457887
95107,zimmery01,2008,1,106,428,51,121,24,1,14,51.0,1.0,1.0,31,71.0,1.0,3.0,0.0,4.0,12.0,466.0,0.332618,0.441589
95108,zimmery01,2009,1,157,610,110,178,37,3,33,106.0,2.0,0.0,72,119.0,9.0,2.0,0.0,9.0,22.0,693.0,0.363636,0.524590
95109,zimmery01,2010,1,142,525,85,161,32,0,25,85.0,4.0,1.0,69,98.0,6.0,4.0,0.0,5.0,16.0,603.0,0.388060,0.510476
95110,zimmery01,2011,1,101,395,52,114,21,2,12,49.0,3.0,1.0,41,73.0,4.0,1.0,0.0,3.0,14.0,440.0,0.354545,0.443038
95111,zimmery01,2012,1,145,578,93,163,36,1,25,95.0,5.0,2.0,57,116.0,8.0,2.0,0.0,4.0,20.0,641.0,0.346334,0.477509
95112,zimmery01,2013,1,147,568,84,156,26,2,26,79.0,6.0,0.0,60,133.0,2.0,2.0,0.0,3.0,16.0,633.0,0.344392,0.464789
95113,zimmery01,2014,1,61,214,26,60,19,1,5,38.0,0.0,0.0,22,37.0,0.0,0.0,0.0,4.0,6.0,240.0,0.341667,0.448598
95114,zimmery01,2015,1,95,346,43,86,25,1,16,73.0,1.0,0.0,33,79.0,0.0,1.0,0.0,10.0,13.0,390.0,0.307692,0.465318
95115,zimmery01,2016,1,115,427,60,93,18,1,15,46.0,4.0,1.0,29,104.0,1.0,5.0,0.0,6.0,12.0,467.0,0.271949,0.370023
95170,zobribe01,2006,1,52,183,10,41,6,2,2,18.0,2.0,3.0,10,26.0,1.0,0.0,2.0,3.0,2.0,198.0,0.260204,0.311475
95172,zobribe01,2008,1,62,198,32,50,10,2,12,30.0,3.0,0.0,25,37.0,1.0,2.0,0.0,2.0,4.0,227.0,0.339207,0.505051
95173,zobribe01,2009,1,152,501,91,149,28,7,27,91.0,17.0,6.0,91,104.0,4.0,2.0,1.0,4.0,7.0,599.0,0.404682,0.542914
95174,zobribe01,2010,1,151,541,77,129,28,2,10,75.0,24.0,3.0,92,107.0,1.0,3.0,7.0,12.0,10.0,655.0,0.345679,0.353050
95175,zobribe01,2011,1,156,588,99,158,46,6,20,91.0,19.0,6.0,77,128.0,1.0,2.0,2.0,5.0,9.0,674.0,0.352679,0.469388
95176,zobribe01,2012,1,157,560,88,151,39,7,20,74.0,14.0,9.0,97,103.0,7.0,3.0,2.0,6.0,13.0,668.0,0.376877,0.471429
95177,zobribe01,2013,1,157,612,77,168,36,3,12,71.0,11.0,3.0,72,91.0,4.0,7.0,1.0,6.0,18.0,698.0,0.354376,0.401961
95178,zobribe01,2014,1,146,570,83,155,34,3,10,52.0,10.0,5.0,75,84.0,4.0,1.0,2.0,6.0,8.0,654.0,0.354294,0.394737
95179,zobribe01,2015,3,126,467,76,129,36,3,13,56.0,3.0,4.0,62,56.0,3.0,1.0,0.0,5.0,8.0,535.0,0.358879,0.449679
95180,zobribe01,2016,1,147,523,94,142,31,3,18,76.0,6.0,4.0,96,82.0,6.0,4.0,4.0,4.0,17.0,631.0,0.385965,0.445507
95216,zuninmi01,2013,1,52,173,22,37,5,0,5,14.0,1.0,0.0,16,49.0,0.0,3.0,0.0,1.0,5.0,193.0,0.290155,0.329480
95217,zuninmi01,2014,1,131,438,51,87,20,2,22,60.0,0.0,3.0,17,158.0,1.0,17.0,0.0,4.0,12.0,476.0,0.254202,0.404110
95218,zuninmi01,2015,1,112,350,28,61,11,0,11,28.0,0.0,1.0,21,132.0,0.0,5.0,8.0,2.0,6.0,386.0,0.230159,0.300000
95219,zuninmi01,2016,1,55,164,16,34,7,0,12,31.0,0.0,0.0,21,65.0,0.0,6.0,0.0,1.0,0.0,192.0,0.317708,0.469512
95222,zupcibo01,1993,1,141,286,40,69,24,2,2,26.0,5.0,2.0,27,54.0,2.0,2.0,8.0,3.0,7.0,326.0,0.308176,0.360140

We now want to merge the batting data with the salary data. Salary data relates to the year of the contract. We want to match the contract value with the statistics of the player in the year preceding - the economic logic is that the salary is based on batting performance, and for that to be the case, the performance must be observable. Last year's statistics are available to the team when negotiating salaries, but not the current year's salary.

To match this year's salary to last year's batting statistics, we simply add one to the year variable (yearID) in the batting df before we carry out the merge.

In [ ]:
# Create another year variable to link previous season stats to next year's salary in batting data

Batting['SalYear'] = Batting['yearID'] + 1
display(Batting)

,playerID,yearID,stint,G,AB,R,H,Doubles,Triples,HR,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP,PA,OBP,SLG,SalYear
98,abbotje01,1998,1,89,244,33,68,14,1,12,41.0,3.0,3.0,9,28.0,1.0,0.0,2.0,5.0,2.0,260.0,0.298450,0.491803,1999
100,abbotje01,2000,1,80,215,31,59,15,1,3,29.0,2.0,1.0,21,38.0,1.0,2.0,2.0,1.0,2.0,241.0,0.343096,0.395349,2001
113,abbotku01,1994,1,101,345,41,86,17,3,9,33.0,3.0,0.0,16,98.0,1.0,5.0,3.0,2.0,5.0,371.0,0.290761,0.394203,1995
114,abbotku01,1995,1,120,420,60,107,18,7,17,60.0,4.0,3.0,36,110.0,4.0,5.0,2.0,5.0,6.0,468.0,0.317597,0.452381,1996
115,abbotku01,1996,1,109,320,37,81,18,7,8,33.0,3.0,3.0,22,99.0,1.0,3.0,4.0,0.0,7.0,349.0,0.307246,0.428125,1997
116,abbotku01,1997,1,94,252,35,69,18,2,6,30.0,3.0,1.0,14,68.0,3.0,1.0,6.0,0.0,5.0,273.0,0.314607,0.432540,1998
117,abbotku01,1998,3,77,194,26,51,13,1,5,24.0,2.0,1.0,12,53.0,0.0,2.0,1.0,3.0,5.0,212.0,0.308057,0.417526,1999
118,abbotku01,1999,1,96,286,41,78,17,2,8,41.0,3.0,2.0,16,69.0,0.0,0.0,2.0,1.0,4.0,305.0,0.310231,0.430070,2000
119,abbotku01,2000,1,79,157,22,34,7,1,6,12.0,1.0,1.0,14,51.0,2.0,1.0,0.0,1.0,2.0,173.0,0.283237,0.388535,2001
144,abercre01,2006,1,111,255,39,54,12,2,5,24.0,6.0,5.0,18,78.0,2.0,3.0,4.0,1.0,2.0,281.0,0.270758,0.333333,2007
148,abernbr01,2001,1,79,304,43,82,17,1,5,33.0,8.0,3.0,27,35.0,1.0,0.0,3.0,1.0,3.0,335.0,0.328313,0.381579,2002
149,abernbr01,2002,1,117,463,46,112,18,4,2,40.0,10.0,4.0,25,46.0,0.0,6.0,8.0,2.0,8.0,504.0,0.288306,0.311015,2003
194,abreubo01,1997,1,59,188,22,47,10,2,3,26.0,7.0,2.0,21,48.0,0.0,1.0,0.0,0.0,0.0,210.0,0.328571,0.372340,1998
195,abreubo01,1998,1,151,497,68,155,29,6,17,74.0,19.0,10.0,84,133.0,14.0,0.0,4.0,4.0,6.0,589.0,0.408547,0.496982,1999
196,abreubo01,1999,1,152,546,118,183,35,11,20,93.0,27.0,9.0,109,113.0,8.0,3.0,0.0,4.0,13.0,662.0,0.445619,0.549451,2000
197,abreubo01,2000,1,154,576,103,182,42,10,25,79.0,28.0,8.0,100,116.0,9.0,1.0,0.0,3.0,12.0,680.0,0.416176,0.553819,2001
198,abreubo01,2001,1,162,588,118,170,48,4,31,110.0,36.0,14.0,106,137.0,11.0,1.0,0.0,9.0,13.0,704.0,0.393466,0.542517,2002
199,abreubo01,2002,1,157,572,102,176,50,6,20,85.0,31.0,12.0,104,117.0,9.0,3.0,0.0,6.0,11.0,685.0,0.413139,0.520979,2003
200,abreubo01,2003,1,158,577,99,173,35,1,20,101.0,22.0,9.0,109,126.0,13.0,2.0,0.0,7.0,13.0,695.0,0.408633,0.467938,2004
201,abreubo01,2004,1,159,574,118,173,47,1,30,105.0,40.0,5.0,127,116.0,10.0,5.0,0.0,7.0,5.0,713.0,0.427770,0.543554,2005
202,abreubo01,2005,1,162,588,104,168,37,1,24,102.0,31.0,9.0,117,134.0,15.0,6.0,0.0,8.0,7.0,719.0,0.404729,0.474490,2006
203,abreubo01,2006,3,156,548,98,163,41,2,15,107.0,30.0,6.0,124,138.0,6.0,3.0,2.0,9.0,13.0,686.0,0.423977,0.461679,2007
204,abreubo01,2007,1,158,605,123,171,40,5,16,101.0,25.0,8.0,84,115.0,0.0,3.0,0.0,7.0,11.0,699.0,0.369099,0.444628,2008
205,abreubo01,2008,1,156,609,100,180,39,4,20,100.0,22.0,11.0,73,109.0,2.0,1.0,0.0,1.0,14.0,684.0,0.371345,0.471264,2009
206,abreubo01,2009,1,152,563,96,165,29,3,15,103.0,30.0,8.0,94,113.0,7.0,1.0,0.0,9.0,15.0,667.0,0.389805,0.435169,2010
207,abreubo01,2010,1,154,573,88,146,41,1,20,78.0,24.0,10.0,87,132.0,3.0,2.0,0.0,5.0,13.0,667.0,0.352324,0.434555,2011
208,abreubo01,2011,1,142,502,54,127,30,1,8,60.0,21.0,5.0,78,113.0,5.0,1.0,1.0,3.0,8.0,585.0,0.352740,0.364542,2012
209,abreubo01,2012,3,100,219,29,53,11,1,3,24.0,6.0,2.0,37,56.0,3.0,0.0,0.0,1.0,7.0,257.0,0.350195,0.342466,2013
210,abreubo01,2014,1,78,133,12,33,9,0,1,14.0,1.0,0.0,20,21.0,0.0,0.0,0.0,2.0,3.0,155.0,0.341935,0.338346,2015
212,abreujo02,2014,1,145,556,80,176,35,2,36,107.0,3.0,1.0,51,131.0,15.0,11.0,0.0,4.0,14.0,622.0,0.382637,0.580935,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94987,zeileto01,2001,1,151,531,66,141,25,1,10,62.0,1.0,0.0,73,102.0,3.0,6.0,0.0,2.0,15.0,612.0,0.359477,0.372881,2002
94988,zeileto01,2002,1,144,506,61,138,23,0,18,87.0,1.0,1.0,66,92.0,3.0,1.0,0.0,7.0,27.0,580.0,0.353448,0.424901,2003
94989,zeileto01,2003,3,100,299,40,68,10,2,11,42.0,1.0,0.0,34,54.0,0.0,3.0,0.0,5.0,6.0,341.0,0.307918,0.384615,2004
94990,zeileto01,2004,1,137,348,30,81,16,0,9,35.0,0.0,0.0,44,83.0,1.0,1.0,1.0,2.0,13.0,396.0,0.318987,0.356322,2005
95105,zimmery01,2006,1,157,614,84,176,47,3,20,110.0,11.0,8.0,61,120.0,7.0,2.0,1.0,4.0,15.0,682.0,0.350954,0.470684,2007
95106,zimmery01,2007,1,162,653,99,174,43,5,24,91.0,4.0,1.0,61,125.0,3.0,3.0,0.0,5.0,26.0,722.0,0.329640,0.457887,2008
95107,zimmery01,2008,1,106,428,51,121,24,1,14,51.0,1.0,1.0,31,71.0,1.0,3.0,0.0,4.0,12.0,466.0,0.332618,0.441589,2009
95108,zimmery01,2009,1,157,610,110,178,37,3,33,106.0,2.0,0.0,72,119.0,9.0,2.0,0.0,9.0,22.0,693.0,0.363636,0.524590,2010
95109,zimmery01,2010,1,142,525,85,161,32,0,25,85.0,4.0,1.0,69,98.0,6.0,4.0,0.0,5.0,16.0,603.0,0.388060,0.510476,2011
95110,zimmery01,2011,1,101,395,52,114,21,2,12,49.0,3.0,1.0,41,73.0,4.0,1.0,0.0,3.0,14.0,440.0,0.354545,0.443038,2012
95111,zimmery01,2012,1,145,578,93,163,36,1,25,95.0,5.0,2.0,57,116.0,8.0,2.0,0.0,4.0,20.0,641.0,0.346334,0.477509,2013
95112,zimmery01,2013,1,147,568,84,156,26,2,26,79.0,6.0,0.0,60,133.0,2.0,2.0,0.0,3.0,16.0,633.0,0.344392,0.464789,2014
95113,zimmery01,2014,1,61,214,26,60,19,1,5,38.0,0.0,0.0,22,37.0,0.0,0.0,0.0,4.0,6.0,240.0,0.341667,0.448598,2015
95114,zimmery01,2015,1,95,346,43,86,25,1,16,73.0,1.0,0.0,33,79.0,0.0,1.0,0.0,10.0,13.0,390.0,0.307692,0.465318,2016
95115,zimmery01,2016,1,115,427,60,93,18,1,15,46.0,4.0,1.0,29,104.0,1.0,5.0,0.0,6.0,12.0,467.0,0.271949,0.370023,2017
95170,zobribe01,2006,1,52,183,10,41,6,2,2,18.0,2.0,3.0,10,26.0,1.0,0.0,2.0,3.0,2.0,198.0,0.260204,0.311475,2007
95172,zobribe01,2008,1,62,198,32,50,10,2,12,30.0,3.0,0.0,25,37.0,1.0,2.0,0.0,2.0,4.0,227.0,0.339207,0.505051,2009
95173,zobribe01,2009,1,152,501,91,149,28,7,27,91.0,17.0,6.0,91,104.0,4.0,2.0,1.0,4.0,7.0,599.0,0.404682,0.542914,2010
95174,zobribe01,2010,1,151,541,77,129,28,2,10,75.0,24.0,3.0,92,107.0,1.0,3.0,7.0,12.0,10.0,655.0,0.345679,0.353050,2011
95175,zobribe01,2011,1,156,588,99,158,46,6,20,91.0,19.0,6.0,77,128.0,1.0,2.0,2.0,5.0,9.0,674.0,0.352679,0.469388,2012
95176,zobribe01,2012,1,157,560,88,151,39,7,20,74.0,14.0,9.0,97,103.0,7.0,3.0,2.0,6.0,13.0,668.0,0.376877,0.471429,2013
95177,zobribe01,2013,1,157,612,77,168,36,3,12,71.0,11.0,3.0,72,91.0,4.0,7.0,1.0,6.0,18.0,698.0,0.354376,0.401961,2014
95178,zobribe01,2014,1,146,570,83,155,34,3,10,52.0,10.0,5.0,75,84.0,4.0,1.0,2.0,6.0,8.0,654.0,0.354294,0.394737,2015
95179,zobribe01,2015,3,126,467,76,129,36,3,13,56.0,3.0,4.0,62,56.0,3.0,1.0,0.0,5.0,8.0,535.0,0.358879,0.449679,2016
95180,zobribe01,2016,1,147,523,94,142,31,3,18,76.0,6.0,4.0,96,82.0,6.0,4.0,4.0,4.0,17.0,631.0,0.385965,0.445507,2017
95216,zuninmi01,2013,1,52,173,22,37,5,0,5,14.0,1.0,0.0,16,49.0,0.0,3.0,0.0,1.0,5.0,193.0,0.290155,0.329480,2014
95217,zuninmi01,2014,1,131,438,51,87,20,2,22,60.0,0.0,3.0,17,158.0,1.0,17.0,0.0,4.0,12.0,476.0,0.254202,0.404110,2015
95218,zuninmi01,2015,1,112,350,28,61,11,0,11,28.0,0.0,1.0,21,132.0,0.0,5.0,8.0,2.0,6.0,386.0,0.230159,0.300000,2016
95219,zuninmi01,2016,1,55,164,16,34,7,0,12,31.0,0.0,0.0,21,65.0,0.0,6.0,0.0,1.0,0.0,192.0,0.317708,0.469512,2017
95222,zupcibo01,1993,1,141,286,40,69,24,2,2,26.0,5.0,2.0,27,54.0,2.0,2.0,8.0,3.0,7.0,326.0,0.308176,0.360140,1994

To carry out the merge we use pd.merge, identify the two dfs and the two variables that line the two dfs.

In [ ]:
# carrying out the merge
Master = pd.merge(Batting, Master, on=['SalYear', 'playerID'])
display(Master)

,playerID,yearID,stint,G,AB,R,H,Doubles,Triples,HR,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP,PA,OBP,SLG,SalYear,teamID,lgID,salary,lnSal
0,abbotje01,1998,1,89,244,33,68,14,1,12,41.0,3.0,3.0,9,28.0,1.0,0.0,2.0,5.0,2.0,260.0,0.298450,0.491803,1999,CHA,AL,255000,12.449019
1,abbotje01,2000,1,80,215,31,59,15,1,3,29.0,2.0,1.0,21,38.0,1.0,2.0,2.0,1.0,2.0,241.0,0.343096,0.395349,2001,FLO,NL,300000,12.611538
2,abbotku01,1994,1,101,345,41,86,17,3,9,33.0,3.0,0.0,16,98.0,1.0,5.0,3.0,2.0,5.0,371.0,0.290761,0.394203,1995,FLO,NL,119000,11.686879
3,abbotku01,1995,1,120,420,60,107,18,7,17,60.0,4.0,3.0,36,110.0,4.0,5.0,2.0,5.0,6.0,468.0,0.317597,0.452381,1996,FLO,NL,250000,12.429216
4,abbotku01,1996,1,109,320,37,81,18,7,8,33.0,3.0,3.0,22,99.0,1.0,3.0,4.0,0.0,7.0,349.0,0.307246,0.428125,1997,FLO,NL,650000,13.384728
5,abbotku01,1997,1,94,252,35,69,18,2,6,30.0,3.0,1.0,14,68.0,3.0,1.0,6.0,0.0,5.0,273.0,0.314607,0.432540,1998,OAK,AL,1000000,13.815511
6,abbotku01,1998,3,77,194,26,51,13,1,5,24.0,2.0,1.0,12,53.0,0.0,2.0,1.0,3.0,5.0,212.0,0.308057,0.417526,1999,COL,NL,900000,13.710150
7,abbotku01,1999,1,96,286,41,78,17,2,8,41.0,3.0,2.0,16,69.0,0.0,0.0,2.0,1.0,4.0,305.0,0.310231,0.430070,2000,NYN,NL,500000,13.122363
8,abbotku01,2000,1,79,157,22,34,7,1,6,12.0,1.0,1.0,14,51.0,2.0,1.0,0.0,1.0,2.0,173.0,0.283237,0.388535,2001,ATL,NL,600000,13.304685
9,abernbr01,2001,1,79,304,43,82,17,1,5,33.0,8.0,3.0,27,35.0,1.0,0.0,3.0,1.0,3.0,335.0,0.328313,0.381579,2002,TBA,AL,215000,12.278393
10,abernbr01,2002,1,117,463,46,112,18,4,2,40.0,10.0,4.0,25,46.0,0.0,6.0,8.0,2.0,8.0,504.0,0.288306,0.311015,2003,TBA,AL,300000,12.611538
11,abreubo01,1997,1,59,188,22,47,10,2,3,26.0,7.0,2.0,21,48.0,0.0,1.0,0.0,0.0,0.0,210.0,0.328571,0.372340,1998,PHI,NL,180000,12.100712
12,abreubo01,1998,1,151,497,68,155,29,6,17,74.0,19.0,10.0,84,133.0,14.0,0.0,4.0,4.0,6.0,589.0,0.408547,0.496982,1999,PHI,NL,400000,12.899220
13,abreubo01,1999,1,152,546,118,183,35,11,20,93.0,27.0,9.0,109,113.0,8.0,3.0,0.0,4.0,13.0,662.0,0.445619,0.549451,2000,PHI,NL,2933333,14.891650
14,abreubo01,2000,1,154,576,103,182,42,10,25,79.0,28.0,8.0,100,116.0,9.0,1.0,0.0,3.0,12.0,680.0,0.416176,0.553819,2001,PHI,NL,4983000,15.421543
15,abreubo01,2001,1,162,588,118,170,48,4,31,110.0,36.0,14.0,106,137.0,11.0,1.0,0.0,9.0,13.0,704.0,0.393466,0.542517,2002,PHI,NL,6333333,15.661337
16,abreubo01,2002,1,157,572,102,176,50,6,20,85.0,31.0,12.0,104,117.0,9.0,3.0,0.0,6.0,11.0,685.0,0.413139,0.520979,2003,PHI,NL,9100000,16.023785
17,abreubo01,2003,1,158,577,99,173,35,1,20,101.0,22.0,9.0,109,126.0,13.0,2.0,0.0,7.0,13.0,695.0,0.408633,0.467938,2004,PHI,NL,10600000,16.176365
18,abreubo01,2004,1,159,574,118,173,47,1,30,105.0,40.0,5.0,127,116.0,10.0,5.0,0.0,7.0,5.0,713.0,0.427770,0.543554,2005,PHI,NL,13100000,16.388123
19,abreubo01,2005,1,162,588,104,168,37,1,24,102.0,31.0,9.0,117,134.0,15.0,6.0,0.0,8.0,7.0,719.0,0.404729,0.474490,2006,PHI,NL,13600000,16.425580
20,abreubo01,2006,3,156,548,98,163,41,2,15,107.0,30.0,6.0,124,138.0,6.0,3.0,2.0,9.0,13.0,686.0,0.423977,0.461679,2007,NYA,AL,15000000,16.523561
21,abreubo01,2007,1,158,605,123,171,40,5,16,101.0,25.0,8.0,84,115.0,0.0,3.0,0.0,7.0,11.0,699.0,0.369099,0.444628,2008,NYA,AL,16000000,16.588099
22,abreubo01,2008,1,156,609,100,180,39,4,20,100.0,22.0,11.0,73,109.0,2.0,1.0,0.0,1.0,14.0,684.0,0.371345,0.471264,2009,LAA,AL,5000000,15.424948
23,abreubo01,2009,1,152,563,96,165,29,3,15,103.0,30.0,8.0,94,113.0,7.0,1.0,0.0,9.0,15.0,667.0,0.389805,0.435169,2010,LAA,AL,9000000,16.012735
24,abreubo01,2010,1,154,573,88,146,41,1,20,78.0,24.0,10.0,87,132.0,3.0,2.0,0.0,5.0,13.0,667.0,0.352324,0.434555,2011,LAA,AL,9000000,16.012735
25,abreubo01,2011,1,142,502,54,127,30,1,8,60.0,21.0,5.0,78,113.0,5.0,1.0,1.0,3.0,8.0,585.0,0.352740,0.364542,2012,LAA,AL,9000000,16.012735
26,abreujo02,2014,1,145,556,80,176,35,2,36,107.0,3.0,1.0,51,131.0,15.0,11.0,0.0,4.0,14.0,622.0,0.382637,0.580935,2015,CHA,AL,8666000,15.974918
27,abreujo02,2015,1,154,613,88,178,34,3,30,101.0,0.0,0.0,39,140.0,11.0,15.0,0.0,1.0,16.0,668.0,0.347305,0.502447,2016,CHA,AL,11666667,16.272246
28,abreuto01,2007,1,59,166,19,45,14,1,2,17.0,0.0,0.0,7,21.0,1.0,3.0,0.0,2.0,5.0,178.0,0.308989,0.403614,2008,LAN,NL,393000,12.881565
29,abreuto01,2013,1,53,138,21,37,12,3,2,14.0,0.0,2.0,6,33.0,1.0,1.0,1.0,1.0,5.0,147.0,0.301370,0.442029,2014,SFN,NL,745000,13.521139
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7754,zeileto01,1994,1,113,415,62,111,25,1,19,75.0,1.0,3.0,52,56.0,3.0,3.0,0.0,7.0,13.0,477.0,0.348008,0.469880,1995,SLN,NL,3700000,15.123843
7755,zeileto01,1995,3,113,426,50,105,22,0,14,52.0,1.0,0.0,34,76.0,1.0,4.0,4.0,5.0,13.0,473.0,0.304904,0.396714,1996,PHI,NL,2700000,14.808762
7756,zeileto01,1996,3,163,617,78,162,32,0,25,99.0,1.0,1.0,82,104.0,4.0,1.0,0.0,4.0,18.0,704.0,0.348011,0.435981,1997,LAN,NL,3100000,14.946913
7757,zeileto01,1997,1,160,575,89,154,17,0,31,90.0,8.0,7.0,85,112.0,7.0,6.0,0.0,6.0,18.0,672.0,0.364583,0.459130,1998,LAN,NL,3200000,14.978661
7758,zeileto01,1998,6,158,572,85,155,32,3,19,94.0,4.0,4.0,69,90.0,2.0,4.0,1.0,7.0,12.0,653.0,0.349693,0.437063,1999,TEX,AL,3200000,14.978661
7759,zeileto01,1999,1,156,588,80,172,41,1,24,98.0,1.0,2.0,56,94.0,3.0,4.0,1.0,7.0,20.0,656.0,0.354198,0.488095,2000,NYN,NL,4333333,15.281848
7760,zeileto01,2000,1,153,544,67,146,36,3,22,79.0,3.0,4.0,74,85.0,4.0,2.0,0.0,3.0,15.0,623.0,0.356340,0.466912,2001,NYN,NL,6833333,15.737323
7761,zeileto01,2001,1,151,531,66,141,25,1,10,62.0,1.0,0.0,73,102.0,3.0,6.0,0.0,2.0,15.0,612.0,0.359477,0.372881,2002,COL,NL,6833333,15.737323
7762,zeileto01,2002,1,144,506,61,138,23,0,18,87.0,1.0,1.0,66,92.0,3.0,1.0,0.0,7.0,27.0,580.0,0.353448,0.424901,2003,NYA,AL,1500000,14.220976
7763,zeileto01,2003,3,100,299,40,68,10,2,11,42.0,1.0,0.0,34,54.0,0.0,3.0,0.0,5.0,6.0,341.0,0.307918,0.384615,2004,NYN,NL,1000000,13.815511
7764,zimmery01,2007,1,162,653,99,174,43,5,24,91.0,4.0,1.0,61,125.0,3.0,3.0,0.0,5.0,26.0,722.0,0.329640,0.457887,2008,WAS,NL,465000,13.049793
7765,zimmery01,2008,1,106,428,51,121,24,1,14,51.0,1.0,1.0,31,71.0,1.0,3.0,0.0,4.0,12.0,466.0,0.332618,0.441589,2009,WAS,NL,3325000,15.016980
7766,zimmery01,2009,1,157,610,110,178,37,3,33,106.0,2.0,0.0,72,119.0,9.0,2.0,0.0,9.0,22.0,693.0,0.363636,0.524590,2010,WAS,NL,6350000,15.663965
7767,zimmery01,2010,1,142,525,85,161,32,0,25,85.0,4.0,1.0,69,98.0,6.0,4.0,0.0,5.0,16.0,603.0,0.388060,0.510476,2011,WAS,NL,9025000,16.015509
7768,zimmery01,2011,1,101,395,52,114,21,2,12,49.0,3.0,1.0,41,73.0,4.0,1.0,0.0,3.0,14.0,440.0,0.354545,0.443038,2012,WAS,NL,12000000,16.300417
7769,zimmery01,2012,1,145,578,93,163,36,1,25,95.0,5.0,2.0,57,116.0,8.0,2.0,0.0,4.0,20.0,641.0,0.346334,0.477509,2013,WAS,NL,14100000,16.461685
7770,zimmery01,2013,1,147,568,84,156,26,2,26,79.0,6.0,0.0,60,133.0,2.0,2.0,0.0,3.0,16.0,633.0,0.344392,0.464789,2014,WAS,NL,14000000,16.454568
7771,zimmery01,2014,1,61,214,26,60,19,1,5,38.0,0.0,0.0,22,37.0,0.0,0.0,0.0,4.0,6.0,240.0,0.341667,0.448598,2015,WAS,NL,14000000,16.454568
7772,zimmery01,2015,1,95,346,43,86,25,1,16,73.0,1.0,0.0,33,79.0,0.0,1.0,0.0,10.0,13.0,390.0,0.307692,0.465318,2016,WAS,NL,14000000,16.454568
7773,zobribe01,2006,1,52,183,10,41,6,2,2,18.0,2.0,3.0,10,26.0,1.0,0.0,2.0,3.0,2.0,198.0,0.260204,0.311475,2007,TBA,AL,383400,12.856834
7774,zobribe01,2008,1,62,198,32,50,10,2,12,30.0,3.0,0.0,25,37.0,1.0,2.0,0.0,2.0,4.0,227.0,0.339207,0.505051,2009,TBA,AL,415900,12.938200
7775,zobribe01,2009,1,152,501,91,149,28,7,27,91.0,17.0,6.0,91,104.0,4.0,2.0,1.0,4.0,7.0,599.0,0.404682,0.542914,2010,TBA,AL,438100,12.990202
7776,zobribe01,2010,1,151,541,77,129,28,2,10,75.0,24.0,3.0,92,107.0,1.0,3.0,7.0,12.0,10.0,655.0,0.345679,0.353050,2011,TBA,AL,4687300,15.360367
7777,zobribe01,2011,1,156,588,99,158,46,6,20,91.0,19.0,6.0,77,128.0,1.0,2.0,2.0,5.0,9.0,674.0,0.352679,0.469388,2012,TBA,AL,4687300,15.360367
7778,zobribe01,2012,1,157,560,88,151,39,7,20,74.0,14.0,9.0,97,103.0,7.0,3.0,2.0,6.0,13.0,668.0,0.376877,0.471429,2013,TBA,AL,5687300,15.553746
7779,zobribe01,2013,1,157,612,77,168,36,3,12,71.0,11.0,3.0,72,91.0,4.0,7.0,1.0,6.0,18.0,698.0,0.354376,0.401961,2014,TBA,AL,7000000,15.761421
7780,zobribe01,2014,1,146,570,83,155,34,3,10,52.0,10.0,5.0,75,84.0,4.0,1.0,2.0,6.0,8.0,654.0,0.354294,0.394737,2015,OAK,AL,7500000,15.830414
7781,zobribe01,2015,3,126,467,76,129,36,3,13,56.0,3.0,4.0,62,56.0,3.0,1.0,0.0,5.0,8.0,535.0,0.358879,0.449679,2016,CHN,NL,10500000,16.166886
7782,zuninmi01,2013,1,52,173,22,37,5,0,5,14.0,1.0,0.0,16,49.0,0.0,3.0,0.0,1.0,5.0,193.0,0.290155,0.329480,2014,SEA,AL,504100,13.130530
7783,zuninmi01,2014,1,131,438,51,87,20,2,22,60.0,0.0,3.0,17,158.0,1.0,17.0,0.0,4.0,12.0,476.0,0.254202,0.404110,2015,SEA,AL,523500,13.168292

# Step 3

Now we want to take account of the player's status in salary negotiations. For the first two years in the Majors you are tied to your club, and therefore your ability to bargain over salary is limited.

After two years you become "aribtration eligible", which means that if you are not satisfied with the salary you are offered you can take your dispute to arbitration, which will give you additional bargaining power.

Then, at the end of six years of service you become a free agent and are able to sign a contract with the highest bidder for your services.

These differences are likely to lead to differences in salary even among players of identical ability. As a result we want to define the bargaining status of each player based on their years of service.

To do this, we identify the year in which the player made his debut, and then calculate the years elapsed in order to identify his status.

Date of a player's debut is contained in the "People" file.

In [ ]:
# Read in People data retrieved from Lahman's Database

People = pd.read_csv("../Data/People.csv")
display(People)

,playerID,birthYear,birthMonth,birthDay,birthCountry,birthState,birthCity,deathYear,deathMonth,deathDay,deathCountry,deathState,deathCity,nameFirst,nameLast,nameGiven,weight,height,bats,throws,debut,finalGame,retroID,bbrefID
0,aardsda01,1981.0,12.0,27.0,USA,CO,Denver,NaN,NaN,NaN,NaN,NaN,NaN,David,Aardsma,David Allan,215.0,75.0,R,R,2004-04-06,2015-08-23,aardd001,aardsda01
1,aaronha01,1934.0,2.0,5.0,USA,AL,Mobile,NaN,NaN,NaN,NaN,NaN,NaN,Hank,Aaron,Henry Louis,180.0,72.0,R,R,1954-04-13,1976-10-03,aaroh101,aaronha01
2,aaronto01,1939.0,8.0,5.0,USA,AL,Mobile,1984.0,8.0,16.0,USA,GA,Atlanta,Tommie,Aaron,Tommie Lee,190.0,75.0,R,R,1962-04-10,1971-09-26,aarot101,aaronto01
3,aasedo01,1954.0,9.0,8.0,USA,CA,Orange,NaN,NaN,NaN,NaN,NaN,NaN,Don,Aase,Donald William,190.0,75.0,R,R,1977-07-26,1990-10-03,aased001,aasedo01
4,abadan01,1972.0,8.0,25.0,USA,FL,Palm Beach,NaN,NaN,NaN,NaN,NaN,NaN,Andy,Abad,Fausto Andres,184.0,73.0,L,L,2001-09-10,2006-04-13,abada001,abadan01
5,abadfe01,1985.0,12.0,17.0,D.R.,La Romana,La Romana,NaN,NaN,NaN,NaN,NaN,NaN,Fernando,Abad,Fernando Antonio,220.0,73.0,L,L,2010-07-28,2017-10-01,abadf001,abadfe01
6,abadijo01,1850.0,11.0,4.0,USA,PA,Philadelphia,1905.0,5.0,17.0,USA,NJ,Pemberton,John,Abadie,John W.,192.0,72.0,R,R,1875-04-26,1875-06-10,abadj101,abadijo01
7,abbated01,1877.0,4.0,15.0,USA,PA,Latrobe,1957.0,1.0,6.0,USA,FL,Fort Lauderdale,Ed,Abbaticchio,Edward James,170.0,71.0,R,R,1897-09-04,1910-09-15,abbae101,abbated01
8,abbeybe01,1869.0,11.0,11.0,USA,VT,Essex,1962.0,6.0,11.0,USA,VT,Colchester,Bert,Abbey,Bert Wood,175.0,71.0,R,R,1892-06-14,1896-09-23,abbeb101,abbeybe01
9,abbeych01,1866.0,10.0,14.0,USA,NE,Falls City,1926.0,4.0,27.0,USA,CA,San Francisco,Charlie,Abbey,Charles S.,169.0,68.0,L,L,1893-08-16,1897-08-19,abbec101,abbeych01
10,abbotda01,1862.0,3.0,16.0,USA,OH,Portage,1930.0,2.0,13.0,USA,MI,Ottawa Lake,Dan,Abbott,Leander Franklin,190.0,71.0,R,R,1890-04-19,1890-05-23,abbod101,abbotda01
11,abbotfr01,1874.0,10.0,22.0,USA,OH,Versailles,1935.0,6.0,11.0,USA,CA,Los Angeles,Fred,Abbott,Harry Frederick,180.0,70.0,R,R,1903-04-25,1905-09-20,abbof101,abbotfr01
12,abbotgl01,1951.0,2.0,16.0,USA,AR,Little Rock,NaN,NaN,NaN,NaN,NaN,NaN,Glenn,Abbott,William Glenn,200.0,78.0,R,R,1973-07-29,1984-08-08,abbog001,abbotgl01
13,abbotje01,1972.0,8.0,17.0,USA,GA,Atlanta,NaN,NaN,NaN,NaN,NaN,NaN,Jeff,Abbott,Jeffrey William,190.0,74.0,R,L,1997-06-10,2001-09-29,abboj002,abbotje01
14,abbotji01,1967.0,9.0,19.0,USA,MI,Flint,NaN,NaN,NaN,NaN,NaN,NaN,Jim,Abbott,James Anthony,200.0,75.0,L,L,1989-04-08,1999-07-21,abboj001,abbotji01
15,abbotku01,1969.0,6.0,2.0,USA,OH,Zanesville,NaN,NaN,NaN,NaN,NaN,NaN,Kurt,Abbott,Kurt Thomas,180.0,71.0,R,R,1993-09-07,2001-04-13,abbok002,abbotku01
16,abbotky01,1968.0,2.0,18.0,USA,MA,Newburyport,NaN,NaN,NaN,NaN,NaN,NaN,Kyle,Abbott,Lawrence Kyle,200.0,76.0,L,L,1991-09-10,1996-08-24,abbok001,abbotky01
17,abbotod01,1886.0,9.0,5.0,USA,PA,New Eagle,1933.0,4.0,13.0,USA,DC,Washington,Ody,Abbott,Ody Cleon,165.0,69.0,L,R,1910-09-10,1910-10-15,abboo101,abbotod01
18,abbotpa01,1967.0,9.0,15.0,USA,CA,Van Nuys,NaN,NaN,NaN,NaN,NaN,NaN,Paul,Abbott,Paul David,185.0,75.0,R,R,1990-08-21,2004-08-07,abbop001,abbotpa01
19,aberal01,1927.0,7.0,31.0,USA,OH,Cleveland,1993.0,5.0,20.0,USA,OH,Garfield Heights,Al,Aber,Albert Julius,195.0,74.0,L,L,1950-09-15,1957-09-11,abera101,aberal01
20,abercda01,1850.0,1.0,2.0,USA,OK,Fort Towson,1939.0,11.0,11.0,USA,PA,Philadelphia,Frank,Abercrombie,Francis Patterson,NaN,NaN,NaN,NaN,1871-10-21,1871-10-21,aberd101,abercda01
21,abercre01,1980.0,7.0,15.0,USA,GA,Columbus,NaN,NaN,NaN,NaN,NaN,NaN,Reggie,Abercrombie,Reginald Damascus,215.0,75.0,R,R,2006-04-04,2008-09-28,aberr001,abercre01
22,abernbi01,1929.0,1.0,30.0,USA,CA,Torrance,2006.0,2.0,19.0,USA,CA,Yucaipa,Bill,Abernathie,William Edward,190.0,70.0,R,R,1952-09-27,1952-09-27,aberb101,abernbi01
23,abernbr01,1977.0,9.0,23.0,USA,GA,Atlanta,NaN,NaN,NaN,NaN,NaN,NaN,Brent,Abernathy,Michael Brent,185.0,73.0,R,R,2001-06-25,2005-09-29,aberb001,abernbr01
24,abernte01,1921.0,10.0,30.0,USA,NC,Bynum,2001.0,11.0,16.0,USA,NC,Charlotte,Ted,Abernathy,Talmadge Lafayette,210.0,74.0,R,L,1942-09-19,1944-04-29,abert102,abernte01
25,abernte02,1933.0,3.0,6.0,USA,NC,Stanley,2004.0,12.0,16.0,USA,NC,Gastonia,Ted,Abernathy,Theodore Wade,215.0,76.0,R,R,1955-04-13,1972-09-30,abert101,abernte02
26,abernwo01,1915.0,2.0,1.0,USA,NC,Forest City,1994.0,12.0,5.0,USA,KY,Louisville,Woody,Abernathy,Virgil Woodrow,170.0,72.0,L,L,1946-07-28,1947-04-17,aberw101,abernwo01
27,aberscl01,1921.0,8.0,28.0,USA,IL,Chicago,1973.0,6.0,23.0,USA,CA,Vallejo,Cliff,Aberson,Clifford Alexander,200.0,72.0,R,R,1947-07-18,1949-05-09,aberc101,aberscl01
28,ablesha01,1883.0,10.0,4.0,USA,TX,Terrell,1951.0,2.0,8.0,USA,TX,San Antonio,Harry,Ables,Harry Terrell,200.0,74.0,R,L,1905-09-04,1911-05-05,ableh101,ablesha01
29,abnersh01,1966.0,6.0,17.0,USA,OH,Hamilton,NaN,NaN,NaN,NaN,NaN,NaN,Shawn,Abner,Shawn Wesley,190.0,73.0,R,R,1987-09-08,1992-10-03,abnes001,abnersh01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19340,zimmejo02,1986.0,5.0,23.0,USA,WI,Auburndale,NaN,NaN,NaN,NaN,NaN,NaN,Jordan,Zimmermann,Jordan M.,225.0,74.0,R,R,2009-04-20,2017-09-27,zimmj003,zimmejo02
19341,zimmero01,1913.0,9.0,13.0,USA,PA,Pine Grove,1991.0,11.0,22.0,USA,PA,Pine Grove,Roy,Zimmerman,Roy Franklin,187.0,74.0,L,L,1945-08-27,1945-09-30,zimmr101,zimmero01
19342,zimmery01,1984.0,9.0,28.0,USA,NC,Washington,NaN,NaN,NaN,NaN,NaN,NaN,Ryan,Zimmerman,Ryan Wallace,225.0,75.0,R,R,2005-09-01,2017-10-01,zimmr001,zimmery01
19343,zinkch01,1979.0,8.0,26.0,USA,CA,Carmichael,NaN,NaN,NaN,NaN,NaN,NaN,Charlie,Zink,Charles Tadao,190.0,73.0,R,R,2008-08-12,2008-08-12,zinkc001,zinkch01
19344,zinkwa01,1898.0,11.0,21.0,USA,MA,Pittsfield,1964.0,6.0,12.0,USA,MA,Quincy,Walter,Zink,Walter Noble,165.0,72.0,R,R,1921-07-06,1921-07-19,zinkw101,zinkwa01
19345,zinnfr01,1865.0,12.0,21.0,USA,PA,Phoenixville,1936.0,5.0,12.0,USA,PA,Philadelphia,Frank,Zinn,Frank Patrick,150.0,68.0,NaN,NaN,1888-04-18,1888-05-03,zinnf101,zinnfr01
19346,zinngu01,1887.0,2.0,13.0,USA,WV,Holbrook,1949.0,10.0,6.0,USA,WV,Park,Guy,Zinn,Guy,170.0,70.0,L,R,1911-09-11,1915-09-16,zinng101,zinngu01
19347,zinnji01,1895.0,1.0,31.0,USA,AR,Benton,1991.0,2.0,26.0,USA,TN,Memphis,Jimmy,Zinn,James Edward,195.0,72.0,L,R,1919-09-04,1929-08-25,zinnj101,zinnji01
19348,zinsebi01,1918.0,1.0,6.0,USA,NY,Astoria,1993.0,2.0,16.0,USA,FL,Englewood,Bill,Zinser,William Francis,185.0,73.0,R,R,1944-08-19,1944-08-26,zinsb101,zinsebi01
19349,zinteal01,1968.0,5.0,19.0,USA,TX,El Paso,NaN,NaN,NaN,NaN,NaN,NaN,Alan,Zinter,Alan Michael,200.0,74.0,B,R,2002-06-18,2004-10-03,zinta001,zinteal01
19350,zipfebu01,1938.0,11.0,18.0,USA,IL,Belleville,NaN,NaN,NaN,NaN,NaN,NaN,Bud,Zipfel,Marion Sylvester,200.0,75.0,L,R,1961-07-26,1962-09-30,zipfb101,zipfebu01
19351,ziskri01,1949.0,2.0,6.0,USA,NY,Brooklyn,NaN,NaN,NaN,NaN,NaN,NaN,Richie,Zisk,Richard Walter,200.0,73.0,R,R,1971-09-08,1983-09-21,ziskr101,ziskri01
19352,zitoba01,1978.0,5.0,13.0,USA,NV,Las Vegas,NaN,NaN,NaN,NaN,NaN,NaN,Barry,Zito,Barry William,205.0,74.0,L,L,2000-07-22,2015-09-30,zitob001,zitoba01
19353,zitzmbi01,1895.0,11.0,19.0,USA,NY,Long Island City,1985.0,5.0,29.0,USA,NJ,Passaic,Billy,Zitzmann,William Arthur,175.0,70.0,R,R,1919-04-27,1929-09-25,zitzb101,zitzmbi01
19354,zmiched01,1884.0,10.0,1.0,USA,OH,Cleveland,1950.0,8.0,20.0,USA,OH,Cleveland,Ed,Zmich,Edward Albert,180.0,72.0,L,L,1910-07-23,1911-06-01,zmice101,zmiched01
19355,zobribe01,1981.0,5.0,26.0,USA,IL,Eureka,NaN,NaN,NaN,NaN,NaN,NaN,Ben,Zobrist,Benjamin Thomas,210.0,75.0,B,R,2006-08-01,2017-10-01,zobrb001,zobribe01
19356,zoccope01,1977.0,2.0,6.0,USA,NY,Bronx,NaN,NaN,NaN,NaN,NaN,NaN,Peter,Zoccolillo,Peter Jude,200.0,74.0,L,R,2003-09-05,2003-09-28,zoccp001,zoccope01
19357,zoldasa01,1918.0,12.0,8.0,USA,NY,Brooklyn,1966.0,8.0,25.0,USA,NY,New Hyde Park,Sam,Zoldak,Samuel Walter,185.0,71.0,L,L,1944-05-13,1952-08-26,zolds101,zoldasa01
19358,zoskyed01,1968.0,2.0,10.0,USA,CA,Whittier,NaN,NaN,NaN,NaN,NaN,NaN,Eddie,Zosky,Edward James,175.0,72.0,R,R,1991-09-02,2000-10-01,zoske001,zoskyed01
19359,zuberbi01,1913.0,3.0,26.0,USA,IA,Middle Amana,1982.0,11.0,2.0,USA,IA,Cedar Rapids,Bill,Zuber,William Henry,195.0,74.0,R,R,1936-09-16,1947-09-23,zubeb101,zuberbi01
19360,zuberjo01,1969.0,12.0,10.0,USA,CA,Encino,NaN,NaN,NaN,NaN,NaN,NaN,Jon,Zuber,Jon Edward,190.0,73.0,L,L,1996-04-19,1998-09-27,zubej001,zuberjo01
19361,zuletju01,1975.0,3.0,28.0,Panama,Panama,Panama,NaN,NaN,NaN,NaN,NaN,NaN,Julio,Zuleta,Julio Ernesto,230.0,78.0,R,R,2000-04-06,2001-06-25,zulej001,zuletju01
19362,zumayjo01,1984.0,11.0,9.0,USA,CA,Chula Vista,NaN,NaN,NaN,NaN,NaN,NaN,Joel,Zumaya,Joel Martin,215.0,75.0,R,R,2006-04-03,2010-06-28,zumaj001,zumayjo01
19363,zuninmi01,1991.0,3.0,25.0,USA,FL,Cape Coral,NaN,NaN,NaN,NaN,NaN,NaN,Mike,Zunino,Michael Accorsi,220.0,74.0,R,R,2013-06-12,2017-09-29,zunim001,zuninmi01
19364,zupcibo01,1966.0,8.0,18.0,USA,PA,Pittsburgh,NaN,NaN,NaN,NaN,NaN,NaN,Bob,Zupcic,Robert,220.0,76.0,R,R,1991-09-07,1994-08-04,zupcb001,zupcibo01
19365,zupofr01,1939.0,8.0,29.0,USA,CA,San Francisco,2005.0,3.0,25.0,USA,CA,Burlingame,Frank,Zupo,Frank Joseph,182.0,71.0,L,R,1957-07-01,1961-05-09,zupof101,zupofr01
19366,zuvelpa01,1958.0,10.0,31.0,USA,CA,San Mateo,NaN,NaN,NaN,NaN,NaN,NaN,Paul,Zuvella,Paul,173.0,72.0,R,R,1982-09-04,1991-05-02,zuvep001,zuvelpa01
19367,zuverge01,1924.0,8.0,20.0,USA,MI,Holland,2014.0,9.0,8.0,USA,AZ,Tempe,George,Zuverink,George,195.0,76.0,R,R,1951-04-21,1959-06-15,zuveg101,zuverge01
19368,zwilldu01,1888.0,11.0,2.0,USA,MO,St. Louis,1978.0,3.0,27.0,USA,CA,La Crescenta,Dutch,Zwilling,Edward Harrison,160.0,66.0,L,L,1910-08-14,1916-07-12,zwild101,zwilldu01
19369,zychto01,1990.0,8.0,7.0,USA,IL,Monee,NaN,NaN,NaN,NaN,NaN,NaN,Tony,Zych,Anthony Aaron,190.0,75.0,R,R,2015-09-04,2017-08-19,zycht001,zychto01

In [ ]:
# Extract debut year from debut date in player info data ("Debut" date is the only variable we want from this file)

Debut = People[['playerID','debut']].copy()

display(Debut)

        playerID       debut
0      aardsda01  2004-04-06
1      aaronha01  1954-04-13
2      aaronto01  1962-04-10
3       aasedo01  1977-07-26
4       abadan01  2001-09-10
5       abadfe01  2010-07-28
6      abadijo01  1875-04-26
7      abbated01  1897-09-04
8      abbeybe01  1892-06-14
9      abbeych01  1893-08-16
10     abbotda01  1890-04-19
11     abbotfr01  1903-04-25
12     abbotgl01  1973-07-29
13     abbotje01  1997-06-10
14     abbotji01  1989-04-08
15     abbotku01  1993-09-07
16     abbotky01  1991-09-10
17     abbotod01  1910-09-10
18     abbotpa01  1990-08-21
19      aberal01  1950-09-15
20     abercda01  1871-10-21
21     abercre01  2006-04-04
22     abernbi01  1952-09-27
23     abernbr01  2001-06-25
24     abernte01  1942-09-19
25     abernte02  1955-04-13
26     abernwo01  1946-07-28
27     aberscl01  1947-07-18
28     ablesha01  1905-09-04
29     abnersh01  1987-09-08
...          ...         ...
19340  zimmejo02  2009-04-20
19341  zimmero01  1945-08-27
19342  zimmery01  2005-09-01
19343   zinkch01  2008-08-12
19344   zinkwa01  1921-07-06
19345   zinnfr01  1888-04-18
19346   zinngu01  1911-09-11
19347   zinnji01  1919-09-04
19348  zinsebi01  1944-08-19
19349  zinteal01  2002-06-18
19350  zipfebu01  1961-07-26
19351   ziskri01  1971-09-08
19352   zitoba01  2000-07-22
19353  zitzmbi01  1919-04-27
19354  zmiched01  1910-07-23
19355  zobribe01  2006-08-01
19356  zoccope01  2003-09-05
19357  zoldasa01  1944-05-13
19358  zoskyed01  1991-09-02
19359  zuberbi01  1936-09-16
19360  zuberjo01  1996-04-19
19361  zuletju01  2000-04-06
19362  zumayjo01  2006-04-03
19363  zuninmi01  2013-06-12
19364  zupcibo01  1991-09-07
19365   zupofr01  1957-07-01
19366  zuvelpa01  1982-09-04
19367  zuverge01  1951-04-21
19368  zwilldu01  1910-08-14
19369   zychto01  2015-09-04

[19370 rows x 2 columns]

## Strings and integers

Data in Python can be recognized as strings (str) - characters making up a text - or as integers (int), meaning numbers.

We want to treat the debut date, e.g. 2015-09-04, as a string (even though it contains numbers). We have to tell Python to treat it as a string using the .astype(str) function. Strings can be sliced by identifying the first and last characters - the first character being identified as one less than its place in order. Thus the first character can be identified by 0.

To obtain the debut year, we need to extract only the first four characters from each string. Even though this will then look like numbers, e.g. 2015, it will still be treated as string. But, since 2015 can also be a number, we can convert it to an integer value later.

In [ ]:
# extracting the first four characters

Debut['debutyr'] = Debut['debut'].astype(str).str[0:4]
Debut

        playerID       debut debutyr
0      aardsda01  2004-04-06    2004
1      aaronha01  1954-04-13    1954
2      aaronto01  1962-04-10    1962
3       aasedo01  1977-07-26    1977
4       abadan01  2001-09-10    2001
5       abadfe01  2010-07-28    2010
6      abadijo01  1875-04-26    1875
7      abbated01  1897-09-04    1897
8      abbeybe01  1892-06-14    1892
9      abbeych01  1893-08-16    1893
10     abbotda01  1890-04-19    1890
11     abbotfr01  1903-04-25    1903
12     abbotgl01  1973-07-29    1973
13     abbotje01  1997-06-10    1997
14     abbotji01  1989-04-08    1989
15     abbotku01  1993-09-07    1993
16     abbotky01  1991-09-10    1991
17     abbotod01  1910-09-10    1910
18     abbotpa01  1990-08-21    1990
19      aberal01  1950-09-15    1950
20     abercda01  1871-10-21    1871
21     abercre01  2006-04-04    2006
22     abernbi01  1952-09-27    1952
23     abernbr01  2001-06-25    2001
24     abernte01  1942-09-19    1942
25     abernte02  1955-04-13    1955
26     abernwo01  1946-07-28    1946
27     aberscl01  1947-07-18    1947
28     ablesha01  1905-09-04    1905
29     abnersh01  1987-09-08    1987
...          ...         ...     ...
19340  zimmejo02  2009-04-20    2009
19341  zimmero01  1945-08-27    1945
19342  zimmery01  2005-09-01    2005
19343   zinkch01  2008-08-12    2008
19344   zinkwa01  1921-07-06    1921
19345   zinnfr01  1888-04-18    1888
19346   zinngu01  1911-09-11    1911
19347   zinnji01  1919-09-04    1919
19348  zinsebi01  1944-08-19    1944
19349  zinteal01  2002-06-18    2002
19350  zipfebu01  1961-07-26    1961
19351   ziskri01  1971-09-08    1971
19352   zitoba01  2000-07-22    2000
19353  zitzmbi01  1919-04-27    1919
19354  zmiched01  1910-07-23    1910
19355  zobribe01  2006-08-01    2006
19356  zoccope01  2003-09-05    2003
19357  zoldasa01  1944-05-13    1944
19358  zoskyed01  1991-09-02    1991
19359  zuberbi01  1936-09-16    1936
19360  zuberjo01  1996-04-19    1996
19361  zuletju01  2000-04-06    2000
19362  zumayjo01  2006-04-03    2006
19363  zuninmi01  2013-06-12    2013
19364  zupcibo01  1991-09-07    1991
19365   zupofr01  1957-07-01    1957
19366  zuvelpa01  1982-09-04    1982
19367  zuverge01  1951-04-21    1951
19368  zwilldu01  1910-08-14    1910
19369   zychto01  2015-09-04    2015

[19370 rows x 3 columns]

## Self test

In the expression [0:4], the zero indicates the element in the string before the first one you want (which is 1), and the 4 represents the last element. Try using the same method to create the debut month ('debutm') and the debut day (debutd').

In [ ]:
# Restrict the data to the playerID and debutyr

Debut = Debut[['playerID','debutyr']]

display(Debut)

        playerID debutyr
0      aardsda01    2004
1      aaronha01    1954
2      aaronto01    1962
3       aasedo01    1977
4       abadan01    2001
5       abadfe01    2010
6      abadijo01    1875
7      abbated01    1897
8      abbeybe01    1892
9      abbeych01    1893
10     abbotda01    1890
11     abbotfr01    1903
12     abbotgl01    1973
13     abbotje01    1997
14     abbotji01    1989
15     abbotku01    1993
16     abbotky01    1991
17     abbotod01    1910
18     abbotpa01    1990
19      aberal01    1950
20     abercda01    1871
21     abercre01    2006
22     abernbi01    1952
23     abernbr01    2001
24     abernte01    1942
25     abernte02    1955
26     abernwo01    1946
27     aberscl01    1947
28     ablesha01    1905
29     abnersh01    1987
...          ...     ...
19340  zimmejo02    2009
19341  zimmero01    1945
19342  zimmery01    2005
19343   zinkch01    2008
19344   zinkwa01    1921
19345   zinnfr01    1888
19346   zinngu01    1911
19347   zinnji01    1919
19348  zinsebi01    1944
19349  zinteal01    2002
19350  zipfebu01    1961
19351   ziskri01    1971
19352   zitoba01    2000
19353  zitzmbi01    1919
19354  zmiched01    1910
19355  zobribe01    2006
19356  zoccope01    2003
19357  zoldasa01    1944
19358  zoskyed01    1991
19359  zuberbi01    1936
19360  zuberjo01    1996
19361  zuletju01    2000
19362  zumayjo01    2006
19363  zuninmi01    2013
19364  zupcibo01    1991
19365   zupofr01    1957
19366  zuvelpa01    1982
19367  zuverge01    1951
19368  zwilldu01    1910
19369   zychto01    2015

[19370 rows x 2 columns]

In [ ]:
# Now merge debut year into master data
Master = pd.merge(Master, Debut, on=['playerID'], how = 'left')
display(Master)

,playerID,yearID,stint,G,AB,R,H,Doubles,Triples,HR,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP,PA,OBP,SLG,SalYear,teamID,lgID,salary,lnSal,debutyr
0,abbotje01,1998,1,89,244,33,68,14,1,12,41.0,3.0,3.0,9,28.0,1.0,0.0,2.0,5.0,2.0,260.0,0.298450,0.491803,1999,CHA,AL,255000,12.449019,1997
1,abbotje01,2000,1,80,215,31,59,15,1,3,29.0,2.0,1.0,21,38.0,1.0,2.0,2.0,1.0,2.0,241.0,0.343096,0.395349,2001,FLO,NL,300000,12.611538,1997
2,abbotku01,1994,1,101,345,41,86,17,3,9,33.0,3.0,0.0,16,98.0,1.0,5.0,3.0,2.0,5.0,371.0,0.290761,0.394203,1995,FLO,NL,119000,11.686879,1993
3,abbotku01,1995,1,120,420,60,107,18,7,17,60.0,4.0,3.0,36,110.0,4.0,5.0,2.0,5.0,6.0,468.0,0.317597,0.452381,1996,FLO,NL,250000,12.429216,1993
4,abbotku01,1996,1,109,320,37,81,18,7,8,33.0,3.0,3.0,22,99.0,1.0,3.0,4.0,0.0,7.0,349.0,0.307246,0.428125,1997,FLO,NL,650000,13.384728,1993
5,abbotku01,1997,1,94,252,35,69,18,2,6,30.0,3.0,1.0,14,68.0,3.0,1.0,6.0,0.0,5.0,273.0,0.314607,0.432540,1998,OAK,AL,1000000,13.815511,1993
6,abbotku01,1998,3,77,194,26,51,13,1,5,24.0,2.0,1.0,12,53.0,0.0,2.0,1.0,3.0,5.0,212.0,0.308057,0.417526,1999,COL,NL,900000,13.710150,1993
7,abbotku01,1999,1,96,286,41,78,17,2,8,41.0,3.0,2.0,16,69.0,0.0,0.0,2.0,1.0,4.0,305.0,0.310231,0.430070,2000,NYN,NL,500000,13.122363,1993
8,abbotku01,2000,1,79,157,22,34,7,1,6,12.0,1.0,1.0,14,51.0,2.0,1.0,0.0,1.0,2.0,173.0,0.283237,0.388535,2001,ATL,NL,600000,13.304685,1993
9,abernbr01,2001,1,79,304,43,82,17,1,5,33.0,8.0,3.0,27,35.0,1.0,0.0,3.0,1.0,3.0,335.0,0.328313,0.381579,2002,TBA,AL,215000,12.278393,2001
10,abernbr01,2002,1,117,463,46,112,18,4,2,40.0,10.0,4.0,25,46.0,0.0,6.0,8.0,2.0,8.0,504.0,0.288306,0.311015,2003,TBA,AL,300000,12.611538,2001
11,abreubo01,1997,1,59,188,22,47,10,2,3,26.0,7.0,2.0,21,48.0,0.0,1.0,0.0,0.0,0.0,210.0,0.328571,0.372340,1998,PHI,NL,180000,12.100712,1996
12,abreubo01,1998,1,151,497,68,155,29,6,17,74.0,19.0,10.0,84,133.0,14.0,0.0,4.0,4.0,6.0,589.0,0.408547,0.496982,1999,PHI,NL,400000,12.899220,1996
13,abreubo01,1999,1,152,546,118,183,35,11,20,93.0,27.0,9.0,109,113.0,8.0,3.0,0.0,4.0,13.0,662.0,0.445619,0.549451,2000,PHI,NL,2933333,14.891650,1996
14,abreubo01,2000,1,154,576,103,182,42,10,25,79.0,28.0,8.0,100,116.0,9.0,1.0,0.0,3.0,12.0,680.0,0.416176,0.553819,2001,PHI,NL,4983000,15.421543,1996
15,abreubo01,2001,1,162,588,118,170,48,4,31,110.0,36.0,14.0,106,137.0,11.0,1.0,0.0,9.0,13.0,704.0,0.393466,0.542517,2002,PHI,NL,6333333,15.661337,1996
16,abreubo01,2002,1,157,572,102,176,50,6,20,85.0,31.0,12.0,104,117.0,9.0,3.0,0.0,6.0,11.0,685.0,0.413139,0.520979,2003,PHI,NL,9100000,16.023785,1996
17,abreubo01,2003,1,158,577,99,173,35,1,20,101.0,22.0,9.0,109,126.0,13.0,2.0,0.0,7.0,13.0,695.0,0.408633,0.467938,2004,PHI,NL,10600000,16.176365,1996
18,abreubo01,2004,1,159,574,118,173,47,1,30,105.0,40.0,5.0,127,116.0,10.0,5.0,0.0,7.0,5.0,713.0,0.427770,0.543554,2005,PHI,NL,13100000,16.388123,1996
19,abreubo01,2005,1,162,588,104,168,37,1,24,102.0,31.0,9.0,117,134.0,15.0,6.0,0.0,8.0,7.0,719.0,0.404729,0.474490,2006,PHI,NL,13600000,16.425580,1996
20,abreubo01,2006,3,156,548,98,163,41,2,15,107.0,30.0,6.0,124,138.0,6.0,3.0,2.0,9.0,13.0,686.0,0.423977,0.461679,2007,NYA,AL,15000000,16.523561,1996
21,abreubo01,2007,1,158,605,123,171,40,5,16,101.0,25.0,8.0,84,115.0,0.0,3.0,0.0,7.0,11.0,699.0,0.369099,0.444628,2008,NYA,AL,16000000,16.588099,1996
22,abreubo01,2008,1,156,609,100,180,39,4,20,100.0,22.0,11.0,73,109.0,2.0,1.0,0.0,1.0,14.0,684.0,0.371345,0.471264,2009,LAA,AL,5000000,15.424948,1996
23,abreubo01,2009,1,152,563,96,165,29,3,15,103.0,30.0,8.0,94,113.0,7.0,1.0,0.0,9.0,15.0,667.0,0.389805,0.435169,2010,LAA,AL,9000000,16.012735,1996
24,abreubo01,2010,1,154,573,88,146,41,1,20,78.0,24.0,10.0,87,132.0,3.0,2.0,0.0,5.0,13.0,667.0,0.352324,0.434555,2011,LAA,AL,9000000,16.012735,1996
25,abreubo01,2011,1,142,502,54,127,30,1,8,60.0,21.0,5.0,78,113.0,5.0,1.0,1.0,3.0,8.0,585.0,0.352740,0.364542,2012,LAA,AL,9000000,16.012735,1996
26,abreujo02,2014,1,145,556,80,176,35,2,36,107.0,3.0,1.0,51,131.0,15.0,11.0,0.0,4.0,14.0,622.0,0.382637,0.580935,2015,CHA,AL,8666000,15.974918,2014
27,abreujo02,2015,1,154,613,88,178,34,3,30,101.0,0.0,0.0,39,140.0,11.0,15.0,0.0,1.0,16.0,668.0,0.347305,0.502447,2016,CHA,AL,11666667,16.272246,2014
28,abreuto01,2007,1,59,166,19,45,14,1,2,17.0,0.0,0.0,7,21.0,1.0,3.0,0.0,2.0,5.0,178.0,0.308989,0.403614,2008,LAN,NL,393000,12.881565,2007
29,abreuto01,2013,1,53,138,21,37,12,3,2,14.0,0.0,2.0,6,33.0,1.0,1.0,1.0,1.0,5.0,147.0,0.301370,0.442029,2014,SFN,NL,745000,13.521139,2007
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7754,zeileto01,1994,1,113,415,62,111,25,1,19,75.0,1.0,3.0,52,56.0,3.0,3.0,0.0,7.0,13.0,477.0,0.348008,0.469880,1995,SLN,NL,3700000,15.123843,1989
7755,zeileto01,1995,3,113,426,50,105,22,0,14,52.0,1.0,0.0,34,76.0,1.0,4.0,4.0,5.0,13.0,473.0,0.304904,0.396714,1996,PHI,NL,2700000,14.808762,1989
7756,zeileto01,1996,3,163,617,78,162,32,0,25,99.0,1.0,1.0,82,104.0,4.0,1.0,0.0,4.0,18.0,704.0,0.348011,0.435981,1997,LAN,NL,3100000,14.946913,1989
7757,zeileto01,1997,1,160,575,89,154,17,0,31,90.0,8.0,7.0,85,112.0,7.0,6.0,0.0,6.0,18.0,672.0,0.364583,0.459130,1998,LAN,NL,3200000,14.978661,1989
7758,zeileto01,1998,6,158,572,85,155,32,3,19,94.0,4.0,4.0,69,90.0,2.0,4.0,1.0,7.0,12.0,653.0,0.349693,0.437063,1999,TEX,AL,3200000,14.978661,1989
7759,zeileto01,1999,1,156,588,80,172,41,1,24,98.0,1.0,2.0,56,94.0,3.0,4.0,1.0,7.0,20.0,656.0,0.354198,0.488095,2000,NYN,NL,4333333,15.281848,1989
7760,zeileto01,2000,1,153,544,67,146,36,3,22,79.0,3.0,4.0,74,85.0,4.0,2.0,0.0,3.0,15.0,623.0,0.356340,0.466912,2001,NYN,NL,6833333,15.737323,1989
7761,zeileto01,2001,1,151,531,66,141,25,1,10,62.0,1.0,0.0,73,102.0,3.0,6.0,0.0,2.0,15.0,612.0,0.359477,0.372881,2002,COL,NL,6833333,15.737323,1989
7762,zeileto01,2002,1,144,506,61,138,23,0,18,87.0,1.0,1.0,66,92.0,3.0,1.0,0.0,7.0,27.0,580.0,0.353448,0.424901,2003,NYA,AL,1500000,14.220976,1989
7763,zeileto01,2003,3,100,299,40,68,10,2,11,42.0,1.0,0.0,34,54.0,0.0,3.0,0.0,5.0,6.0,341.0,0.307918,0.384615,2004,NYN,NL,1000000,13.815511,1989
7764,zimmery01,2007,1,162,653,99,174,43,5,24,91.0,4.0,1.0,61,125.0,3.0,3.0,0.0,5.0,26.0,722.0,0.329640,0.457887,2008,WAS,NL,465000,13.049793,2005
7765,zimmery01,2008,1,106,428,51,121,24,1,14,51.0,1.0,1.0,31,71.0,1.0,3.0,0.0,4.0,12.0,466.0,0.332618,0.441589,2009,WAS,NL,3325000,15.016980,2005
7766,zimmery01,2009,1,157,610,110,178,37,3,33,106.0,2.0,0.0,72,119.0,9.0,2.0,0.0,9.0,22.0,693.0,0.363636,0.524590,2010,WAS,NL,6350000,15.663965,2005
7767,zimmery01,2010,1,142,525,85,161,32,0,25,85.0,4.0,1.0,69,98.0,6.0,4.0,0.0,5.0,16.0,603.0,0.388060,0.510476,2011,WAS,NL,9025000,16.015509,2005
7768,zimmery01,2011,1,101,395,52,114,21,2,12,49.0,3.0,1.0,41,73.0,4.0,1.0,0.0,3.0,14.0,440.0,0.354545,0.443038,2012,WAS,NL,12000000,16.300417,2005
7769,zimmery01,2012,1,145,578,93,163,36,1,25,95.0,5.0,2.0,57,116.0,8.0,2.0,0.0,4.0,20.0,641.0,0.346334,0.477509,2013,WAS,NL,14100000,16.461685,2005
7770,zimmery01,2013,1,147,568,84,156,26,2,26,79.0,6.0,0.0,60,133.0,2.0,2.0,0.0,3.0,16.0,633.0,0.344392,0.464789,2014,WAS,NL,14000000,16.454568,2005
7771,zimmery01,2014,1,61,214,26,60,19,1,5,38.0,0.0,0.0,22,37.0,0.0,0.0,0.0,4.0,6.0,240.0,0.341667,0.448598,2015,WAS,NL,14000000,16.454568,2005
7772,zimmery01,2015,1,95,346,43,86,25,1,16,73.0,1.0,0.0,33,79.0,0.0,1.0,0.0,10.0,13.0,390.0,0.307692,0.465318,2016,WAS,NL,14000000,16.454568,2005
7773,zobribe01,2006,1,52,183,10,41,6,2,2,18.0,2.0,3.0,10,26.0,1.0,0.0,2.0,3.0,2.0,198.0,0.260204,0.311475,2007,TBA,AL,383400,12.856834,2006
7774,zobribe01,2008,1,62,198,32,50,10,2,12,30.0,3.0,0.0,25,37.0,1.0,2.0,0.0,2.0,4.0,227.0,0.339207,0.505051,2009,TBA,AL,415900,12.938200,2006
7775,zobribe01,2009,1,152,501,91,149,28,7,27,91.0,17.0,6.0,91,104.0,4.0,2.0,1.0,4.0,7.0,599.0,0.404682,0.542914,2010,TBA,AL,438100,12.990202,2006
7776,zobribe01,2010,1,151,541,77,129,28,2,10,75.0,24.0,3.0,92,107.0,1.0,3.0,7.0,12.0,10.0,655.0,0.345679,0.353050,2011,TBA,AL,4687300,15.360367,2006
7777,zobribe01,2011,1,156,588,99,158,46,6,20,91.0,19.0,6.0,77,128.0,1.0,2.0,2.0,5.0,9.0,674.0,0.352679,0.469388,2012,TBA,AL,4687300,15.360367,2006
7778,zobribe01,2012,1,157,560,88,151,39,7,20,74.0,14.0,9.0,97,103.0,7.0,3.0,2.0,6.0,13.0,668.0,0.376877,0.471429,2013,TBA,AL,5687300,15.553746,2006
7779,zobribe01,2013,1,157,612,77,168,36,3,12,71.0,11.0,3.0,72,91.0,4.0,7.0,1.0,6.0,18.0,698.0,0.354376,0.401961,2014,TBA,AL,7000000,15.761421,2006
7780,zobribe01,2014,1,146,570,83,155,34,3,10,52.0,10.0,5.0,75,84.0,4.0,1.0,2.0,6.0,8.0,654.0,0.354294,0.394737,2015,OAK,AL,7500000,15.830414,2006
7781,zobribe01,2015,3,126,467,76,129,36,3,13,56.0,3.0,4.0,62,56.0,3.0,1.0,0.0,5.0,8.0,535.0,0.358879,0.449679,2016,CHN,NL,10500000,16.166886,2006
7782,zuninmi01,2013,1,52,173,22,37,5,0,5,14.0,1.0,0.0,16,49.0,0.0,3.0,0.0,1.0,5.0,193.0,0.290155,0.329480,2014,SEA,AL,504100,13.130530,2013
7783,zuninmi01,2014,1,131,438,51,87,20,2,22,60.0,0.0,3.0,17,158.0,1.0,17.0,0.0,4.0,12.0,476.0,0.254202,0.404110,2015,SEA,AL,523500,13.168292,2013

We now calculate years of experience.

Note that because we defined 'debut' as a string in order to edit it, we now have to turn it back into an integer (int) in order to carry out an arithmetical operation. To turn it back into an integer we use .astype(int).

In [ ]:
# Calculating years of experience

Master['Exp'] = Master['yearID'] - Master['debutyr'].astype(int)
display(Master)

,playerID,yearID,stint,G,AB,R,H,Doubles,Triples,HR,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP,PA,OBP,SLG,SalYear,teamID,lgID,salary,lnSal,debutyr,Exp
0,abbotje01,1998,1,89,244,33,68,14,1,12,41.0,3.0,3.0,9,28.0,1.0,0.0,2.0,5.0,2.0,260.0,0.298450,0.491803,1999,CHA,AL,255000,12.449019,1997,1
1,abbotje01,2000,1,80,215,31,59,15,1,3,29.0,2.0,1.0,21,38.0,1.0,2.0,2.0,1.0,2.0,241.0,0.343096,0.395349,2001,FLO,NL,300000,12.611538,1997,3
2,abbotku01,1994,1,101,345,41,86,17,3,9,33.0,3.0,0.0,16,98.0,1.0,5.0,3.0,2.0,5.0,371.0,0.290761,0.394203,1995,FLO,NL,119000,11.686879,1993,1
3,abbotku01,1995,1,120,420,60,107,18,7,17,60.0,4.0,3.0,36,110.0,4.0,5.0,2.0,5.0,6.0,468.0,0.317597,0.452381,1996,FLO,NL,250000,12.429216,1993,2
4,abbotku01,1996,1,109,320,37,81,18,7,8,33.0,3.0,3.0,22,99.0,1.0,3.0,4.0,0.0,7.0,349.0,0.307246,0.428125,1997,FLO,NL,650000,13.384728,1993,3
5,abbotku01,1997,1,94,252,35,69,18,2,6,30.0,3.0,1.0,14,68.0,3.0,1.0,6.0,0.0,5.0,273.0,0.314607,0.432540,1998,OAK,AL,1000000,13.815511,1993,4
6,abbotku01,1998,3,77,194,26,51,13,1,5,24.0,2.0,1.0,12,53.0,0.0,2.0,1.0,3.0,5.0,212.0,0.308057,0.417526,1999,COL,NL,900000,13.710150,1993,5
7,abbotku01,1999,1,96,286,41,78,17,2,8,41.0,3.0,2.0,16,69.0,0.0,0.0,2.0,1.0,4.0,305.0,0.310231,0.430070,2000,NYN,NL,500000,13.122363,1993,6
8,abbotku01,2000,1,79,157,22,34,7,1,6,12.0,1.0,1.0,14,51.0,2.0,1.0,0.0,1.0,2.0,173.0,0.283237,0.388535,2001,ATL,NL,600000,13.304685,1993,7
9,abernbr01,2001,1,79,304,43,82,17,1,5,33.0,8.0,3.0,27,35.0,1.0,0.0,3.0,1.0,3.0,335.0,0.328313,0.381579,2002,TBA,AL,215000,12.278393,2001,0
10,abernbr01,2002,1,117,463,46,112,18,4,2,40.0,10.0,4.0,25,46.0,0.0,6.0,8.0,2.0,8.0,504.0,0.288306,0.311015,2003,TBA,AL,300000,12.611538,2001,1
11,abreubo01,1997,1,59,188,22,47,10,2,3,26.0,7.0,2.0,21,48.0,0.0,1.0,0.0,0.0,0.0,210.0,0.328571,0.372340,1998,PHI,NL,180000,12.100712,1996,1
12,abreubo01,1998,1,151,497,68,155,29,6,17,74.0,19.0,10.0,84,133.0,14.0,0.0,4.0,4.0,6.0,589.0,0.408547,0.496982,1999,PHI,NL,400000,12.899220,1996,2
13,abreubo01,1999,1,152,546,118,183,35,11,20,93.0,27.0,9.0,109,113.0,8.0,3.0,0.0,4.0,13.0,662.0,0.445619,0.549451,2000,PHI,NL,2933333,14.891650,1996,3
14,abreubo01,2000,1,154,576,103,182,42,10,25,79.0,28.0,8.0,100,116.0,9.0,1.0,0.0,3.0,12.0,680.0,0.416176,0.553819,2001,PHI,NL,4983000,15.421543,1996,4
15,abreubo01,2001,1,162,588,118,170,48,4,31,110.0,36.0,14.0,106,137.0,11.0,1.0,0.0,9.0,13.0,704.0,0.393466,0.542517,2002,PHI,NL,6333333,15.661337,1996,5
16,abreubo01,2002,1,157,572,102,176,50,6,20,85.0,31.0,12.0,104,117.0,9.0,3.0,0.0,6.0,11.0,685.0,0.413139,0.520979,2003,PHI,NL,9100000,16.023785,1996,6
17,abreubo01,2003,1,158,577,99,173,35,1,20,101.0,22.0,9.0,109,126.0,13.0,2.0,0.0,7.0,13.0,695.0,0.408633,0.467938,2004,PHI,NL,10600000,16.176365,1996,7
18,abreubo01,2004,1,159,574,118,173,47,1,30,105.0,40.0,5.0,127,116.0,10.0,5.0,0.0,7.0,5.0,713.0,0.427770,0.543554,2005,PHI,NL,13100000,16.388123,1996,8
19,abreubo01,2005,1,162,588,104,168,37,1,24,102.0,31.0,9.0,117,134.0,15.0,6.0,0.0,8.0,7.0,719.0,0.404729,0.474490,2006,PHI,NL,13600000,16.425580,1996,9
20,abreubo01,2006,3,156,548,98,163,41,2,15,107.0,30.0,6.0,124,138.0,6.0,3.0,2.0,9.0,13.0,686.0,0.423977,0.461679,2007,NYA,AL,15000000,16.523561,1996,10
21,abreubo01,2007,1,158,605,123,171,40,5,16,101.0,25.0,8.0,84,115.0,0.0,3.0,0.0,7.0,11.0,699.0,0.369099,0.444628,2008,NYA,AL,16000000,16.588099,1996,11
22,abreubo01,2008,1,156,609,100,180,39,4,20,100.0,22.0,11.0,73,109.0,2.0,1.0,0.0,1.0,14.0,684.0,0.371345,0.471264,2009,LAA,AL,5000000,15.424948,1996,12
23,abreubo01,2009,1,152,563,96,165,29,3,15,103.0,30.0,8.0,94,113.0,7.0,1.0,0.0,9.0,15.0,667.0,0.389805,0.435169,2010,LAA,AL,9000000,16.012735,1996,13
24,abreubo01,2010,1,154,573,88,146,41,1,20,78.0,24.0,10.0,87,132.0,3.0,2.0,0.0,5.0,13.0,667.0,0.352324,0.434555,2011,LAA,AL,9000000,16.012735,1996,14
25,abreubo01,2011,1,142,502,54,127,30,1,8,60.0,21.0,5.0,78,113.0,5.0,1.0,1.0,3.0,8.0,585.0,0.352740,0.364542,2012,LAA,AL,9000000,16.012735,1996,15
26,abreujo02,2014,1,145,556,80,176,35,2,36,107.0,3.0,1.0,51,131.0,15.0,11.0,0.0,4.0,14.0,622.0,0.382637,0.580935,2015,CHA,AL,8666000,15.974918,2014,0
27,abreujo02,2015,1,154,613,88,178,34,3,30,101.0,0.0,0.0,39,140.0,11.0,15.0,0.0,1.0,16.0,668.0,0.347305,0.502447,2016,CHA,AL,11666667,16.272246,2014,1
28,abreuto01,2007,1,59,166,19,45,14,1,2,17.0,0.0,0.0,7,21.0,1.0,3.0,0.0,2.0,5.0,178.0,0.308989,0.403614,2008,LAN,NL,393000,12.881565,2007,0
29,abreuto01,2013,1,53,138,21,37,12,3,2,14.0,0.0,2.0,6,33.0,1.0,1.0,1.0,1.0,5.0,147.0,0.301370,0.442029,2014,SFN,NL,745000,13.521139,2007,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7754,zeileto01,1994,1,113,415,62,111,25,1,19,75.0,1.0,3.0,52,56.0,3.0,3.0,0.0,7.0,13.0,477.0,0.348008,0.469880,1995,SLN,NL,3700000,15.123843,1989,5
7755,zeileto01,1995,3,113,426,50,105,22,0,14,52.0,1.0,0.0,34,76.0,1.0,4.0,4.0,5.0,13.0,473.0,0.304904,0.396714,1996,PHI,NL,2700000,14.808762,1989,6
7756,zeileto01,1996,3,163,617,78,162,32,0,25,99.0,1.0,1.0,82,104.0,4.0,1.0,0.0,4.0,18.0,704.0,0.348011,0.435981,1997,LAN,NL,3100000,14.946913,1989,7
7757,zeileto01,1997,1,160,575,89,154,17,0,31,90.0,8.0,7.0,85,112.0,7.0,6.0,0.0,6.0,18.0,672.0,0.364583,0.459130,1998,LAN,NL,3200000,14.978661,1989,8
7758,zeileto01,1998,6,158,572,85,155,32,3,19,94.0,4.0,4.0,69,90.0,2.0,4.0,1.0,7.0,12.0,653.0,0.349693,0.437063,1999,TEX,AL,3200000,14.978661,1989,9
7759,zeileto01,1999,1,156,588,80,172,41,1,24,98.0,1.0,2.0,56,94.0,3.0,4.0,1.0,7.0,20.0,656.0,0.354198,0.488095,2000,NYN,NL,4333333,15.281848,1989,10
7760,zeileto01,2000,1,153,544,67,146,36,3,22,79.0,3.0,4.0,74,85.0,4.0,2.0,0.0,3.0,15.0,623.0,0.356340,0.466912,2001,NYN,NL,6833333,15.737323,1989,11
7761,zeileto01,2001,1,151,531,66,141,25,1,10,62.0,1.0,0.0,73,102.0,3.0,6.0,0.0,2.0,15.0,612.0,0.359477,0.372881,2002,COL,NL,6833333,15.737323,1989,12
7762,zeileto01,2002,1,144,506,61,138,23,0,18,87.0,1.0,1.0,66,92.0,3.0,1.0,0.0,7.0,27.0,580.0,0.353448,0.424901,2003,NYA,AL,1500000,14.220976,1989,13
7763,zeileto01,2003,3,100,299,40,68,10,2,11,42.0,1.0,0.0,34,54.0,0.0,3.0,0.0,5.0,6.0,341.0,0.307918,0.384615,2004,NYN,NL,1000000,13.815511,1989,14
7764,zimmery01,2007,1,162,653,99,174,43,5,24,91.0,4.0,1.0,61,125.0,3.0,3.0,0.0,5.0,26.0,722.0,0.329640,0.457887,2008,WAS,NL,465000,13.049793,2005,2
7765,zimmery01,2008,1,106,428,51,121,24,1,14,51.0,1.0,1.0,31,71.0,1.0,3.0,0.0,4.0,12.0,466.0,0.332618,0.441589,2009,WAS,NL,3325000,15.016980,2005,3
7766,zimmery01,2009,1,157,610,110,178,37,3,33,106.0,2.0,0.0,72,119.0,9.0,2.0,0.0,9.0,22.0,693.0,0.363636,0.524590,2010,WAS,NL,6350000,15.663965,2005,4
7767,zimmery01,2010,1,142,525,85,161,32,0,25,85.0,4.0,1.0,69,98.0,6.0,4.0,0.0,5.0,16.0,603.0,0.388060,0.510476,2011,WAS,NL,9025000,16.015509,2005,5
7768,zimmery01,2011,1,101,395,52,114,21,2,12,49.0,3.0,1.0,41,73.0,4.0,1.0,0.0,3.0,14.0,440.0,0.354545,0.443038,2012,WAS,NL,12000000,16.300417,2005,6
7769,zimmery01,2012,1,145,578,93,163,36,1,25,95.0,5.0,2.0,57,116.0,8.0,2.0,0.0,4.0,20.0,641.0,0.346334,0.477509,2013,WAS,NL,14100000,16.461685,2005,7
7770,zimmery01,2013,1,147,568,84,156,26,2,26,79.0,6.0,0.0,60,133.0,2.0,2.0,0.0,3.0,16.0,633.0,0.344392,0.464789,2014,WAS,NL,14000000,16.454568,2005,8
7771,zimmery01,2014,1,61,214,26,60,19,1,5,38.0,0.0,0.0,22,37.0,0.0,0.0,0.0,4.0,6.0,240.0,0.341667,0.448598,2015,WAS,NL,14000000,16.454568,2005,9
7772,zimmery01,2015,1,95,346,43,86,25,1,16,73.0,1.0,0.0,33,79.0,0.0,1.0,0.0,10.0,13.0,390.0,0.307692,0.465318,2016,WAS,NL,14000000,16.454568,2005,10
7773,zobribe01,2006,1,52,183,10,41,6,2,2,18.0,2.0,3.0,10,26.0,1.0,0.0,2.0,3.0,2.0,198.0,0.260204,0.311475,2007,TBA,AL,383400,12.856834,2006,0
7774,zobribe01,2008,1,62,198,32,50,10,2,12,30.0,3.0,0.0,25,37.0,1.0,2.0,0.0,2.0,4.0,227.0,0.339207,0.505051,2009,TBA,AL,415900,12.938200,2006,2
7775,zobribe01,2009,1,152,501,91,149,28,7,27,91.0,17.0,6.0,91,104.0,4.0,2.0,1.0,4.0,7.0,599.0,0.404682,0.542914,2010,TBA,AL,438100,12.990202,2006,3
7776,zobribe01,2010,1,151,541,77,129,28,2,10,75.0,24.0,3.0,92,107.0,1.0,3.0,7.0,12.0,10.0,655.0,0.345679,0.353050,2011,TBA,AL,4687300,15.360367,2006,4
7777,zobribe01,2011,1,156,588,99,158,46,6,20,91.0,19.0,6.0,77,128.0,1.0,2.0,2.0,5.0,9.0,674.0,0.352679,0.469388,2012,TBA,AL,4687300,15.360367,2006,5
7778,zobribe01,2012,1,157,560,88,151,39,7,20,74.0,14.0,9.0,97,103.0,7.0,3.0,2.0,6.0,13.0,668.0,0.376877,0.471429,2013,TBA,AL,5687300,15.553746,2006,6
7779,zobribe01,2013,1,157,612,77,168,36,3,12,71.0,11.0,3.0,72,91.0,4.0,7.0,1.0,6.0,18.0,698.0,0.354376,0.401961,2014,TBA,AL,7000000,15.761421,2006,7
7780,zobribe01,2014,1,146,570,83,155,34,3,10,52.0,10.0,5.0,75,84.0,4.0,1.0,2.0,6.0,8.0,654.0,0.354294,0.394737,2015,OAK,AL,7500000,15.830414,2006,8
7781,zobribe01,2015,3,126,467,76,129,36,3,13,56.0,3.0,4.0,62,56.0,3.0,1.0,0.0,5.0,8.0,535.0,0.358879,0.449679,2016,CHN,NL,10500000,16.166886,2006,9
7782,zuninmi01,2013,1,52,173,22,37,5,0,5,14.0,1.0,0.0,16,49.0,0.0,3.0,0.0,1.0,5.0,193.0,0.290155,0.329480,2014,SEA,AL,504100,13.130530,2013,0
7783,zuninmi01,2014,1,131,438,51,87,20,2,22,60.0,0.0,3.0,17,158.0,1.0,17.0,0.0,4.0,12.0,476.0,0.254202,0.404110,2015,SEA,AL,523500,13.168292,2013,1

We now use np.where (which, for anyone familiar with Excel, works like an "if" formula) to identify arbitration eligible players and free agents. These are "dummy variables" - they either have a value of one if the player has that status, or zero. We don't need to define rookies - they are the default category.

There must always be default category when using dummy variables in a regression.

In [ ]:
# Use experience as proxy to classify players contract status as arbitration eligible or free agent
Master['Arb'] = np.where((Master['Exp'] <= 6) & (Master['Exp'] >= 3),1,0)
Master['Free'] = np.where(Master['Exp'] > 6, 1, 0)
display(Master)

,playerID,yearID,stint,G,AB,R,H,Doubles,Triples,HR,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP,PA,OBP,SLG,SalYear,teamID,lgID,salary,lnSal,debutyr,Exp,Arb,Free
0,abbotje01,1998,1,89,244,33,68,14,1,12,41.0,3.0,3.0,9,28.0,1.0,0.0,2.0,5.0,2.0,260.0,0.298450,0.491803,1999,CHA,AL,255000,12.449019,1997,1,0,0
1,abbotje01,2000,1,80,215,31,59,15,1,3,29.0,2.0,1.0,21,38.0,1.0,2.0,2.0,1.0,2.0,241.0,0.343096,0.395349,2001,FLO,NL,300000,12.611538,1997,3,1,0
2,abbotku01,1994,1,101,345,41,86,17,3,9,33.0,3.0,0.0,16,98.0,1.0,5.0,3.0,2.0,5.0,371.0,0.290761,0.394203,1995,FLO,NL,119000,11.686879,1993,1,0,0
3,abbotku01,1995,1,120,420,60,107,18,7,17,60.0,4.0,3.0,36,110.0,4.0,5.0,2.0,5.0,6.0,468.0,0.317597,0.452381,1996,FLO,NL,250000,12.429216,1993,2,0,0
4,abbotku01,1996,1,109,320,37,81,18,7,8,33.0,3.0,3.0,22,99.0,1.0,3.0,4.0,0.0,7.0,349.0,0.307246,0.428125,1997,FLO,NL,650000,13.384728,1993,3,1,0
5,abbotku01,1997,1,94,252,35,69,18,2,6,30.0,3.0,1.0,14,68.0,3.0,1.0,6.0,0.0,5.0,273.0,0.314607,0.432540,1998,OAK,AL,1000000,13.815511,1993,4,1,0
6,abbotku01,1998,3,77,194,26,51,13,1,5,24.0,2.0,1.0,12,53.0,0.0,2.0,1.0,3.0,5.0,212.0,0.308057,0.417526,1999,COL,NL,900000,13.710150,1993,5,1,0
7,abbotku01,1999,1,96,286,41,78,17,2,8,41.0,3.0,2.0,16,69.0,0.0,0.0,2.0,1.0,4.0,305.0,0.310231,0.430070,2000,NYN,NL,500000,13.122363,1993,6,1,0
8,abbotku01,2000,1,79,157,22,34,7,1,6,12.0,1.0,1.0,14,51.0,2.0,1.0,0.0,1.0,2.0,173.0,0.283237,0.388535,2001,ATL,NL,600000,13.304685,1993,7,0,1
9,abernbr01,2001,1,79,304,43,82,17,1,5,33.0,8.0,3.0,27,35.0,1.0,0.0,3.0,1.0,3.0,335.0,0.328313,0.381579,2002,TBA,AL,215000,12.278393,2001,0,0,0
10,abernbr01,2002,1,117,463,46,112,18,4,2,40.0,10.0,4.0,25,46.0,0.0,6.0,8.0,2.0,8.0,504.0,0.288306,0.311015,2003,TBA,AL,300000,12.611538,2001,1,0,0
11,abreubo01,1997,1,59,188,22,47,10,2,3,26.0,7.0,2.0,21,48.0,0.0,1.0,0.0,0.0,0.0,210.0,0.328571,0.372340,1998,PHI,NL,180000,12.100712,1996,1,0,0
12,abreubo01,1998,1,151,497,68,155,29,6,17,74.0,19.0,10.0,84,133.0,14.0,0.0,4.0,4.0,6.0,589.0,0.408547,0.496982,1999,PHI,NL,400000,12.899220,1996,2,0,0
13,abreubo01,1999,1,152,546,118,183,35,11,20,93.0,27.0,9.0,109,113.0,8.0,3.0,0.0,4.0,13.0,662.0,0.445619,0.549451,2000,PHI,NL,2933333,14.891650,1996,3,1,0
14,abreubo01,2000,1,154,576,103,182,42,10,25,79.0,28.0,8.0,100,116.0,9.0,1.0,0.0,3.0,12.0,680.0,0.416176,0.553819,2001,PHI,NL,4983000,15.421543,1996,4,1,0
15,abreubo01,2001,1,162,588,118,170,48,4,31,110.0,36.0,14.0,106,137.0,11.0,1.0,0.0,9.0,13.0,704.0,0.393466,0.542517,2002,PHI,NL,6333333,15.661337,1996,5,1,0
16,abreubo01,2002,1,157,572,102,176,50,6,20,85.0,31.0,12.0,104,117.0,9.0,3.0,0.0,6.0,11.0,685.0,0.413139,0.520979,2003,PHI,NL,9100000,16.023785,1996,6,1,0
17,abreubo01,2003,1,158,577,99,173,35,1,20,101.0,22.0,9.0,109,126.0,13.0,2.0,0.0,7.0,13.0,695.0,0.408633,0.467938,2004,PHI,NL,10600000,16.176365,1996,7,0,1
18,abreubo01,2004,1,159,574,118,173,47,1,30,105.0,40.0,5.0,127,116.0,10.0,5.0,0.0,7.0,5.0,713.0,0.427770,0.543554,2005,PHI,NL,13100000,16.388123,1996,8,0,1
19,abreubo01,2005,1,162,588,104,168,37,1,24,102.0,31.0,9.0,117,134.0,15.0,6.0,0.0,8.0,7.0,719.0,0.404729,0.474490,2006,PHI,NL,13600000,16.425580,1996,9,0,1
20,abreubo01,2006,3,156,548,98,163,41,2,15,107.0,30.0,6.0,124,138.0,6.0,3.0,2.0,9.0,13.0,686.0,0.423977,0.461679,2007,NYA,AL,15000000,16.523561,1996,10,0,1
21,abreubo01,2007,1,158,605,123,171,40,5,16,101.0,25.0,8.0,84,115.0,0.0,3.0,0.0,7.0,11.0,699.0,0.369099,0.444628,2008,NYA,AL,16000000,16.588099,1996,11,0,1
22,abreubo01,2008,1,156,609,100,180,39,4,20,100.0,22.0,11.0,73,109.0,2.0,1.0,0.0,1.0,14.0,684.0,0.371345,0.471264,2009,LAA,AL,5000000,15.424948,1996,12,0,1
23,abreubo01,2009,1,152,563,96,165,29,3,15,103.0,30.0,8.0,94,113.0,7.0,1.0,0.0,9.0,15.0,667.0,0.389805,0.435169,2010,LAA,AL,9000000,16.012735,1996,13,0,1
24,abreubo01,2010,1,154,573,88,146,41,1,20,78.0,24.0,10.0,87,132.0,3.0,2.0,0.0,5.0,13.0,667.0,0.352324,0.434555,2011,LAA,AL,9000000,16.012735,1996,14,0,1
25,abreubo01,2011,1,142,502,54,127,30,1,8,60.0,21.0,5.0,78,113.0,5.0,1.0,1.0,3.0,8.0,585.0,0.352740,0.364542,2012,LAA,AL,9000000,16.012735,1996,15,0,1
26,abreujo02,2014,1,145,556,80,176,35,2,36,107.0,3.0,1.0,51,131.0,15.0,11.0,0.0,4.0,14.0,622.0,0.382637,0.580935,2015,CHA,AL,8666000,15.974918,2014,0,0,0
27,abreujo02,2015,1,154,613,88,178,34,3,30,101.0,0.0,0.0,39,140.0,11.0,15.0,0.0,1.0,16.0,668.0,0.347305,0.502447,2016,CHA,AL,11666667,16.272246,2014,1,0,0
28,abreuto01,2007,1,59,166,19,45,14,1,2,17.0,0.0,0.0,7,21.0,1.0,3.0,0.0,2.0,5.0,178.0,0.308989,0.403614,2008,LAN,NL,393000,12.881565,2007,0,0,0
29,abreuto01,2013,1,53,138,21,37,12,3,2,14.0,0.0,2.0,6,33.0,1.0,1.0,1.0,1.0,5.0,147.0,0.301370,0.442029,2014,SFN,NL,745000,13.521139,2007,6,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7754,zeileto01,1994,1,113,415,62,111,25,1,19,75.0,1.0,3.0,52,56.0,3.0,3.0,0.0,7.0,13.0,477.0,0.348008,0.469880,1995,SLN,NL,3700000,15.123843,1989,5,1,0
7755,zeileto01,1995,3,113,426,50,105,22,0,14,52.0,1.0,0.0,34,76.0,1.0,4.0,4.0,5.0,13.0,473.0,0.304904,0.396714,1996,PHI,NL,2700000,14.808762,1989,6,1,0
7756,zeileto01,1996,3,163,617,78,162,32,0,25,99.0,1.0,1.0,82,104.0,4.0,1.0,0.0,4.0,18.0,704.0,0.348011,0.435981,1997,LAN,NL,3100000,14.946913,1989,7,0,1
7757,zeileto01,1997,1,160,575,89,154,17,0,31,90.0,8.0,7.0,85,112.0,7.0,6.0,0.0,6.0,18.0,672.0,0.364583,0.459130,1998,LAN,NL,3200000,14.978661,1989,8,0,1
7758,zeileto01,1998,6,158,572,85,155,32,3,19,94.0,4.0,4.0,69,90.0,2.0,4.0,1.0,7.0,12.0,653.0,0.349693,0.437063,1999,TEX,AL,3200000,14.978661,1989,9,0,1
7759,zeileto01,1999,1,156,588,80,172,41,1,24,98.0,1.0,2.0,56,94.0,3.0,4.0,1.0,7.0,20.0,656.0,0.354198,0.488095,2000,NYN,NL,4333333,15.281848,1989,10,0,1
7760,zeileto01,2000,1,153,544,67,146,36,3,22,79.0,3.0,4.0,74,85.0,4.0,2.0,0.0,3.0,15.0,623.0,0.356340,0.466912,2001,NYN,NL,6833333,15.737323,1989,11,0,1
7761,zeileto01,2001,1,151,531,66,141,25,1,10,62.0,1.0,0.0,73,102.0,3.0,6.0,0.0,2.0,15.0,612.0,0.359477,0.372881,2002,COL,NL,6833333,15.737323,1989,12,0,1
7762,zeileto01,2002,1,144,506,61,138,23,0,18,87.0,1.0,1.0,66,92.0,3.0,1.0,0.0,7.0,27.0,580.0,0.353448,0.424901,2003,NYA,AL,1500000,14.220976,1989,13,0,1
7763,zeileto01,2003,3,100,299,40,68,10,2,11,42.0,1.0,0.0,34,54.0,0.0,3.0,0.0,5.0,6.0,341.0,0.307918,0.384615,2004,NYN,NL,1000000,13.815511,1989,14,0,1
7764,zimmery01,2007,1,162,653,99,174,43,5,24,91.0,4.0,1.0,61,125.0,3.0,3.0,0.0,5.0,26.0,722.0,0.329640,0.457887,2008,WAS,NL,465000,13.049793,2005,2,0,0
7765,zimmery01,2008,1,106,428,51,121,24,1,14,51.0,1.0,1.0,31,71.0,1.0,3.0,0.0,4.0,12.0,466.0,0.332618,0.441589,2009,WAS,NL,3325000,15.016980,2005,3,1,0
7766,zimmery01,2009,1,157,610,110,178,37,3,33,106.0,2.0,0.0,72,119.0,9.0,2.0,0.0,9.0,22.0,693.0,0.363636,0.524590,2010,WAS,NL,6350000,15.663965,2005,4,1,0
7767,zimmery01,2010,1,142,525,85,161,32,0,25,85.0,4.0,1.0,69,98.0,6.0,4.0,0.0,5.0,16.0,603.0,0.388060,0.510476,2011,WAS,NL,9025000,16.015509,2005,5,1,0
7768,zimmery01,2011,1,101,395,52,114,21,2,12,49.0,3.0,1.0,41,73.0,4.0,1.0,0.0,3.0,14.0,440.0,0.354545,0.443038,2012,WAS,NL,12000000,16.300417,2005,6,1,0
7769,zimmery01,2012,1,145,578,93,163,36,1,25,95.0,5.0,2.0,57,116.0,8.0,2.0,0.0,4.0,20.0,641.0,0.346334,0.477509,2013,WAS,NL,14100000,16.461685,2005,7,0,1
7770,zimmery01,2013,1,147,568,84,156,26,2,26,79.0,6.0,0.0,60,133.0,2.0,2.0,0.0,3.0,16.0,633.0,0.344392,0.464789,2014,WAS,NL,14000000,16.454568,2005,8,0,1
7771,zimmery01,2014,1,61,214,26,60,19,1,5,38.0,0.0,0.0,22,37.0,0.0,0.0,0.0,4.0,6.0,240.0,0.341667,0.448598,2015,WAS,NL,14000000,16.454568,2005,9,0,1
7772,zimmery01,2015,1,95,346,43,86,25,1,16,73.0,1.0,0.0,33,79.0,0.0,1.0,0.0,10.0,13.0,390.0,0.307692,0.465318,2016,WAS,NL,14000000,16.454568,2005,10,0,1
7773,zobribe01,2006,1,52,183,10,41,6,2,2,18.0,2.0,3.0,10,26.0,1.0,0.0,2.0,3.0,2.0,198.0,0.260204,0.311475,2007,TBA,AL,383400,12.856834,2006,0,0,0
7774,zobribe01,2008,1,62,198,32,50,10,2,12,30.0,3.0,0.0,25,37.0,1.0,2.0,0.0,2.0,4.0,227.0,0.339207,0.505051,2009,TBA,AL,415900,12.938200,2006,2,0,0
7775,zobribe01,2009,1,152,501,91,149,28,7,27,91.0,17.0,6.0,91,104.0,4.0,2.0,1.0,4.0,7.0,599.0,0.404682,0.542914,2010,TBA,AL,438100,12.990202,2006,3,1,0
7776,zobribe01,2010,1,151,541,77,129,28,2,10,75.0,24.0,3.0,92,107.0,1.0,3.0,7.0,12.0,10.0,655.0,0.345679,0.353050,2011,TBA,AL,4687300,15.360367,2006,4,1,0
7777,zobribe01,2011,1,156,588,99,158,46,6,20,91.0,19.0,6.0,77,128.0,1.0,2.0,2.0,5.0,9.0,674.0,0.352679,0.469388,2012,TBA,AL,4687300,15.360367,2006,5,1,0
7778,zobribe01,2012,1,157,560,88,151,39,7,20,74.0,14.0,9.0,97,103.0,7.0,3.0,2.0,6.0,13.0,668.0,0.376877,0.471429,2013,TBA,AL,5687300,15.553746,2006,6,1,0
7779,zobribe01,2013,1,157,612,77,168,36,3,12,71.0,11.0,3.0,72,91.0,4.0,7.0,1.0,6.0,18.0,698.0,0.354376,0.401961,2014,TBA,AL,7000000,15.761421,2006,7,0,1
7780,zobribe01,2014,1,146,570,83,155,34,3,10,52.0,10.0,5.0,75,84.0,4.0,1.0,2.0,6.0,8.0,654.0,0.354294,0.394737,2015,OAK,AL,7500000,15.830414,2006,8,0,1
7781,zobribe01,2015,3,126,467,76,129,36,3,13,56.0,3.0,4.0,62,56.0,3.0,1.0,0.0,5.0,8.0,535.0,0.358879,0.449679,2016,CHN,NL,10500000,16.166886,2006,9,0,1
7782,zuninmi01,2013,1,52,173,22,37,5,0,5,14.0,1.0,0.0,16,49.0,0.0,3.0,0.0,1.0,5.0,193.0,0.290155,0.329480,2014,SEA,AL,504100,13.130530,2013,0,0,0
7783,zuninmi01,2014,1,131,438,51,87,20,2,22,60.0,0.0,3.0,17,158.0,1.0,17.0,0.0,4.0,12.0,476.0,0.254202,0.404110,2015,SEA,AL,523500,13.168292,2013,1,0,0

# Step 4

The final step in preparing the data is to identify the fielding position of the players, since this may also affect the salary that the player can command.

There are eight fielding positions, but Hakes and Sauer break these up into three groups: Catchers and Infielders, whom they define as either second base, third base or short stop. All other fielding positions are the default category.

The Appearances file from the Lahman database identifies each player's position, but to put the data into the format to run the regression requires a little manipulation.

In [ ]:
# Read in player appearance data retrieved from Lahman's Database

Appearances = pd.read_csv("../Data/Appearances.csv")
display(Appearances)

,yearID,teamID,lgID,playerID,G_all,GS,G_batting,G_defense,G_p,G_c,G_1b,G_2b,G_3b,G_ss,G_lf,G_cf,G_rf,G_of,G_dh,G_ph,G_pr
0,1871,TRO,NaN,abercda01,1,1.0,1,1.0,0,0,0,0,0,1,0,0,0,0,0.0,0.0,0.0
1,1871,RC1,NaN,addybo01,25,25.0,25,25.0,0,0,0,22,0,3,0,0,0,0,0.0,0.0,0.0
2,1871,CL1,NaN,allisar01,29,29.0,29,29.0,0,0,0,2,0,0,0,29,0,29,0.0,0.0,0.0
3,1871,WS3,NaN,allisdo01,27,27.0,27,27.0,0,27,0,0,0,0,0,0,0,0,0.0,0.0,0.0
4,1871,RC1,NaN,ansonca01,25,25.0,25,25.0,0,5,1,2,20,0,1,0,0,1,0.0,0.0,0.0
5,1871,FW1,NaN,armstbo01,12,12.0,12,12.0,0,0,0,0,0,0,0,11,1,12,0.0,0.0,0.0
6,1871,RC1,NaN,barkeal01,1,1.0,1,1.0,0,0,0,0,0,0,1,0,0,1,0.0,0.0,0.0
7,1871,BS1,NaN,barnero01,31,31.0,31,31.0,0,0,0,16,0,15,0,0,0,0,0.0,0.0,0.0
8,1871,FW1,NaN,barrebi01,1,1.0,1,1.0,0,1,0,0,1,0,0,0,0,0,0.0,0.0,0.0
9,1871,BS1,NaN,barrofr01,18,17.0,18,18.0,0,0,0,1,0,0,13,0,4,17,0.0,0.0,0.0
10,1871,CL1,NaN,bassjo01,22,22.0,22,22.0,0,1,0,0,0,22,0,0,0,0,0.0,0.0,0.0
11,1871,CL1,NaN,battijo01,1,1.0,1,1.0,0,0,0,0,0,0,0,0,1,1,0.0,0.0,0.0
12,1871,WS3,NaN,bealsto01,10,10.0,10,10.0,0,0,0,2,0,0,4,0,4,8,0.0,0.0,0.0
13,1871,TRO,NaN,beaveed01,3,3.0,3,3.0,0,0,0,3,0,0,0,0,0,0,0.0,0.0,0.0
14,1871,PH1,NaN,bechtge01,20,19.0,20,20.0,3,0,0,0,3,0,1,3,11,15,0.0,0.0,0.0
15,1871,TRO,NaN,bellast01,29,29.0,29,29.0,0,0,0,0,28,1,0,0,0,0,0.0,0.0,0.0
16,1871,PH1,NaN,berkena01,1,1.0,1,1.0,0,0,0,0,0,0,0,0,1,1,0.0,0.0,0.0
17,1871,PH1,NaN,berryto01,1,1.0,1,1.0,0,0,0,0,0,0,0,0,1,1,0.0,0.0,0.0
18,1871,WS3,NaN,berthha01,17,17.0,17,17.0,0,1,0,5,0,0,11,1,0,12,0.0,0.0,0.0
19,1871,FW1,NaN,biermch01,1,1.0,1,1.0,0,0,1,0,0,0,0,0,0,0,0.0,0.0,0.0
20,1871,RC1,NaN,birdge01,25,25.0,25,25.0,0,0,0,0,0,0,1,25,0,25,0.0,0.0,0.0
21,1871,BS1,NaN,birdsda01,29,29.0,29,29.0,0,7,0,0,0,0,0,0,27,27,0.0,0.0,0.0
22,1871,WS3,NaN,brainas01,30,30.0,30,30.0,30,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0
23,1871,CH1,NaN,brannmi01,3,3.0,3,3.0,0,0,0,0,3,0,0,0,0,0,0.0,0.0,0.0
24,1871,WS3,NaN,burrohe01,12,11.0,12,12.0,0,0,0,1,5,0,4,0,4,8,0.0,0.0,0.0
25,1871,FW1,NaN,careyto01,19,19.0,19,19.0,0,0,0,19,0,0,0,0,0,0,0.0,0.0,0.0
26,1871,CL1,NaN,carleji01,29,29.0,29,29.0,0,0,29,0,0,0,0,0,0,0,0.0,0.0,0.0
27,1871,BS1,NaN,conefr01,19,18.0,19,19.0,0,0,0,0,0,0,18,0,1,19,0.0,0.0,0.0
28,1871,TRO,NaN,connone01,7,7.0,7,7.0,0,0,4,0,0,0,0,0,3,3,0.0,0.0,0.0
29,1871,TRO,NaN,cravebi01,27,27.0,27,27.0,0,3,2,18,0,4,0,0,1,1,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104226,2017,LAN,NL,woodal02,27,25.0,27,27.0,27,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0
104227,2017,CIN,NL,woodbl01,55,0.0,52,55.0,55,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0
104228,2017,LAA,AL,woodbl01,17,0.0,0,17.0,17,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0
104229,2017,TBA,AL,woodhu01,1,0.0,0,1.0,1,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0
104230,2017,MIL,NL,woodrbr01,8,8.0,7,8.0,8,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0
104231,2017,KCA,AL,woodtr01,28,3.0,3,28.0,28,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0
104232,2017,SDN,NL,woodtr01,12,11.0,11,11.0,11,0,0,0,0,0,0,0,0,0,0.0,0.0,1.0
104233,2017,BOS,AL,workmbr01,33,0.0,1,33.0,33,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0
104234,2017,MIA,NL,worleva01,26,12.0,25,24.0,24,0,0,0,0,0,0,0,0,0,0.0,2.0,0.0
104235,2017,LAA,AL,wrighda04,5,2.0,0,5.0,5,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0
104236,2017,BAL,AL,wrighmi01,13,0.0,2,13.0,13,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0
104237,2017,BOS,AL,wrighst01,5,5.0,0,5.0,5,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0
104238,2017,BAL,AL,yacabji01,14,0.0,2,14.0,14,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0
104239,2017,LAA,AL,yateski01,1,0.0,0,1.0,1,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0
104240,2017,SDN,NL,yateski01,61,0.0,55,61.0,61,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0
104241,2017,MIA,NL,yelicch01,156,155.0,156,155.0,0,0,0,0,0,0,0,155,0,155,0.0,1.0,0.0
104242,2017,BAL,AL,ynoaga01,9,4.0,1,9.0,9,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0
104243,2017,CHA,AL,ynoami01,22,0.0,1,22.0,22,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0
104244,2017,KCA,AL,youngch03,14,2.0,2,14.0,14,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0
104245,2017,BOS,AL,youngch04,90,65.0,90,46.0,0,0,0,0,0,0,39,0,8,46,26.0,19.0,3.0
104246,2017,LAA,AL,younger03,47,30.0,47,34.0,0,0,0,0,0,0,22,15,2,34,4.0,5.0,10.0
104247,2017,CHN,NL,zagunma01,7,4.0,7,4.0,0,0,0,0,0,0,0,0,4,4,0.0,3.0,0.0
104248,2017,CHN,NL,zastrro01,4,0.0,4,4.0,4,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0
104249,2017,MIA,NL,zieglbr01,53,0.0,51,53.0,53,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0
104250,2017,CLE,AL,zimmebr01,101,73.0,101,97.0,0,0,0,0,0,0,0,97,0,97,0.0,13.0,3.0
104251,2017,DET,AL,zimmejo02,29,29.0,3,29.0,29,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0
104252,2017,WAS,NL,zimmery01,144,132.0,144,143.0,0,0,143,0,0,0,0,0,0,0,1.0,4.0,0.0
104253,2017,CHN,NL,zobribe01,128,105.0,128,118.0,0,0,5,81,0,5,36,0,32,61,0.0,20.0,0.0
104254,2017,SEA,AL,zuninmi01,124,112.0,124,120.0,0,120,0,0,0,0,0,0,0,0,2.0,4.0,1.0
104255,2017,SEA,AL,zychto01,45,0.0,4,45.0,45,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0

The fielding positions defined in Appearances are catcher (G_c), first base (G_1b), second base (G_2b),third base (G_3b), short stop (G_ss) and outfielder (G_of). We should also include designated hitters (G_dh) since they are batters, even if they do not field. If unfamiliar with baseball click on the link for an explanation of the [designated hitter rule](http://m.mlb.com/glossary/rules/designated-hitter-rule).

As with the batting data, we once again have the problem of stints, so we now sum the data, including only the fielding positions, since the other variables are irrelevant for our analysis.

In [ ]:
# Aggregate appearance data by stint using playerID and yearID

Appearances = Appearances.groupby(['playerID','yearID'])['G_c','G_1b','G_2b','G_3b','G_ss','G_of','G_dh'].sum()
Appearances.reset_index(inplace=True)
display(Appearances)

# Note that we need to use 'reset.index' again

        playerID  yearID  G_c  G_1b  G_2b  G_3b  G_ss  G_of  G_dh
0      aardsda01    2004    0     0     0     0     0     0   0.0
1      aardsda01    2006    0     0     0     0     0     0   0.0
2      aardsda01    2007    0     0     0     0     0     0   0.0
3      aardsda01    2008    0     0     0     0     0     0   0.0
4      aardsda01    2009    0     0     0     0     0     0   0.0
5      aardsda01    2010    0     0     0     0     0     0   0.0
6      aardsda01    2012    0     0     0     0     0     0   0.0
7      aardsda01    2013    0     0     0     0     0     0   0.0
8      aardsda01    2015    0     0     0     0     0     0   0.0
9      aaronha01    1954    0     0     0     0     0   116   0.0
10     aaronha01    1955    0     0    27     0     0   126   0.0
11     aaronha01    1956    0     0     0     0     0   152   0.0
12     aaronha01    1957    0     0     0     0     0   150   0.0
13     aaronha01    1958    0     0     0     0     0   153   0.0
14     aaronha01    1959    0     0     0     5     0   152   0.0
15     aaronha01    1960    0     0     2     0     0   153   0.0
16     aaronha01    1961    0     0     0     2     0   154   0.0
17     aaronha01    1962    0     1     0     0     0   153   0.0
18     aaronha01    1963    0     0     0     0     0   161   0.0
19     aaronha01    1964    0     0    11     0     0   139   0.0
20     aaronha01    1965    0     0     0     0     0   148   0.0
21     aaronha01    1966    0     0     2     0     0   158   0.0
22     aaronha01    1967    0     0     1     0     0   152   0.0
23     aaronha01    1968    0    14     0     0     0   151   0.0
24     aaronha01    1969    0     4     0     0     0   144   0.0
25     aaronha01    1970    0    11     0     0     0   125   0.0
26     aaronha01    1971    0    71     0     0     0    60   0.0
27     aaronha01    1972    0   109     0     0     0    15   0.0
28     aaronha01    1973    0     0     0     0     0   105   0.0
29     aaronha01    1974    0     0     0     0     0    89   0.0
...          ...     ...  ...   ...   ...   ...   ...   ...   ...
96582  zupcibo01    1992    0     0     0     0     0   114   5.0
96583  zupcibo01    1993    0     0     0     0     0   122   5.0
96584  zupcibo01    1994    0     1     0     2     0    30   1.0
96585   zupofr01    1957    8     0     0     0     0     0   0.0
96586   zupofr01    1958    1     0     0     0     0     0   0.0
96587   zupofr01    1961    4     0     0     0     0     0   0.0
96588  zuvelpa01    1982    0     0     0     0     1     0   0.0
96589  zuvelpa01    1983    0     0     0     0     2     0   0.0
96590  zuvelpa01    1984    0     0     6     0     6     0   0.0
96591  zuvelpa01    1985    0     0    42     6    33     0   0.0
96592  zuvelpa01    1986    0     0     0     0    21     0   0.0
96593  zuvelpa01    1987    0     0     7     1     6     0   0.0
96594  zuvelpa01    1988    0     0     0     0    49     0   0.0
96595  zuvelpa01    1989    0     0     0     5    15     0   3.0
96596  zuvelpa01    1991    0     0     0     2     0     0   0.0
96597  zuverge01    1951    0     0     0     0     0     0   0.0
96598  zuverge01    1952    0     0     0     0     0     0   0.0
96599  zuverge01    1954    0     0     0     0     0     0   0.0
96600  zuverge01    1955    0     0     0     0     0     0   0.0
96601  zuverge01    1956    0     0     0     0     0     0   0.0
96602  zuverge01    1957    0     0     0     0     0     0   0.0
96603  zuverge01    1958    0     0     0     0     0     0   0.0
96604  zuverge01    1959    0     0     0     0     0     0   0.0
96605  zwilldu01    1910    0     0     0     0     0    27   0.0
96606  zwilldu01    1914    0     0     0     0     0   154   0.0
96607  zwilldu01    1915    0     3     0     0     0   148   0.0
96608  zwilldu01    1916    0     0     0     0     0     9   0.0
96609   zychto01    2015    0     0     0     0     0     0   0.0
96610   zychto01    2016    0     0     0     0     0     0   0.0
96611   zychto01    2017    0     0     0     0     0     0   0.0

[96612 rows x 9 columns]

As you can see if you look at the data, individual players may play in more than one position in a season, although in many cases they play in only one position, and even if they play in more than one, they generally play in one position most of the time.  

In order not to overcomplicate, we'll simply assume that player's position is the one he played in most frequently during the season.  

To derive that from the data we do the following: (i) Create a new variable which is the value of the number of appearances in the position most frequently played in and then (ii) Define the position name as the one which is the same as the the most frequent.

In [ ]:
# (i) Find max number of appearances for each position

Appearances['Max_G'] = Appearances[["G_c","G_1b","G_2b","G_3b","G_ss","G_of","G_dh"]].max(axis=1)
display(Appearances)

        playerID  yearID  G_c  G_1b  G_2b  G_3b  G_ss  G_of  G_dh  Max_G
0      aardsda01    2004    0     0     0     0     0     0   0.0    0.0
1      aardsda01    2006    0     0     0     0     0     0   0.0    0.0
2      aardsda01    2007    0     0     0     0     0     0   0.0    0.0
3      aardsda01    2008    0     0     0     0     0     0   0.0    0.0
4      aardsda01    2009    0     0     0     0     0     0   0.0    0.0
5      aardsda01    2010    0     0     0     0     0     0   0.0    0.0
6      aardsda01    2012    0     0     0     0     0     0   0.0    0.0
7      aardsda01    2013    0     0     0     0     0     0   0.0    0.0
8      aardsda01    2015    0     0     0     0     0     0   0.0    0.0
9      aaronha01    1954    0     0     0     0     0   116   0.0  116.0
10     aaronha01    1955    0     0    27     0     0   126   0.0  126.0
11     aaronha01    1956    0     0     0     0     0   152   0.0  152.0
12     aaronha01    1957    0     0     0     0     0   150   0.0  150.0
13     aaronha01    1958    0     0     0     0     0   153   0.0  153.0
14     aaronha01    1959    0     0     0     5     0   152   0.0  152.0
15     aaronha01    1960    0     0     2     0     0   153   0.0  153.0
16     aaronha01    1961    0     0     0     2     0   154   0.0  154.0
17     aaronha01    1962    0     1     0     0     0   153   0.0  153.0
18     aaronha01    1963    0     0     0     0     0   161   0.0  161.0
19     aaronha01    1964    0     0    11     0     0   139   0.0  139.0
20     aaronha01    1965    0     0     0     0     0   148   0.0  148.0
21     aaronha01    1966    0     0     2     0     0   158   0.0  158.0
22     aaronha01    1967    0     0     1     0     0   152   0.0  152.0
23     aaronha01    1968    0    14     0     0     0   151   0.0  151.0
24     aaronha01    1969    0     4     0     0     0   144   0.0  144.0
25     aaronha01    1970    0    11     0     0     0   125   0.0  125.0
26     aaronha01    1971    0    71     0     0     0    60   0.0   71.0
27     aaronha01    1972    0   109     0     0     0    15   0.0  109.0
28     aaronha01    1973    0     0     0     0     0   105   0.0  105.0
29     aaronha01    1974    0     0     0     0     0    89   0.0   89.0
...          ...     ...  ...   ...   ...   ...   ...   ...   ...    ...
96582  zupcibo01    1992    0     0     0     0     0   114   5.0  114.0
96583  zupcibo01    1993    0     0     0     0     0   122   5.0  122.0
96584  zupcibo01    1994    0     1     0     2     0    30   1.0   30.0
96585   zupofr01    1957    8     0     0     0     0     0   0.0    8.0
96586   zupofr01    1958    1     0     0     0     0     0   0.0    1.0
96587   zupofr01    1961    4     0     0     0     0     0   0.0    4.0
96588  zuvelpa01    1982    0     0     0     0     1     0   0.0    1.0
96589  zuvelpa01    1983    0     0     0     0     2     0   0.0    2.0
96590  zuvelpa01    1984    0     0     6     0     6     0   0.0    6.0
96591  zuvelpa01    1985    0     0    42     6    33     0   0.0   42.0
96592  zuvelpa01    1986    0     0     0     0    21     0   0.0   21.0
96593  zuvelpa01    1987    0     0     7     1     6     0   0.0    7.0
96594  zuvelpa01    1988    0     0     0     0    49     0   0.0   49.0
96595  zuvelpa01    1989    0     0     0     5    15     0   3.0   15.0
96596  zuvelpa01    1991    0     0     0     2     0     0   0.0    2.0
96597  zuverge01    1951    0     0     0     0     0     0   0.0    0.0
96598  zuverge01    1952    0     0     0     0     0     0   0.0    0.0
96599  zuverge01    1954    0     0     0     0     0     0   0.0    0.0
96600  zuverge01    1955    0     0     0     0     0     0   0.0    0.0
96601  zuverge01    1956    0     0     0     0     0     0   0.0    0.0
96602  zuverge01    1957    0     0     0     0     0     0   0.0    0.0
96603  zuverge01    1958    0     0     0     0     0     0   0.0    0.0
96604  zuverge01    1959    0     0     0     0     0     0   0.0    0.0
96605  zwilldu01    1910    0     0     0     0     0    27   0.0   27.0
96606  zwilldu01    1914    0     0     0     0     0   154   0.0  154.0
96607  zwilldu01    1915    0     3     0     0     0   148   0.0  148.0
96608  zwilldu01    1916    0     0     0     0     0     9   0.0    9.0
96609   zychto01    2015    0     0     0     0     0     0   0.0    0.0
96610   zychto01    2016    0     0     0     0     0     0   0.0    0.0
96611   zychto01    2017    0     0     0     0     0     0   0.0    0.0

[96612 rows x 10 columns]

## Writing a function using 'def'

For the second part of the operation we will define a function, identifying the position name to be given to a player dependent on which position he appeared in most often.  

Functions are widely used in Python and we will encounter them again. Here we will not go into great detail into how functions are written, since this could take up an entire course in itself. The important point for us is that they can speed up the process of coding.

The first line of every function starts with the keyword 'def' which declares the function, followed by the name you give it, and then in parentheses the parameters of the function, and then a colon. In our case we call the function Position and its parameter is df.  

The next part of a function defines the actions to be executed, which in this case to return the position name which is most frequent in each row (i.e. player). Each possibility is listed.

That is the function. We then execute the function using the command .apply, specifying the df (Appearances). The 'axis=1' statement means that the function is applied row by row to create a new column (if we wrote axis = 0 it would be applied column by column to create a new row).

In [ ]:
# (ii) Assign each player season to a primary position

# Create definiton to position classification process
def Position(df):
    if (df['Max_G'] == df['G_c']): return "C"
    elif (df['Max_G'] == df['G_1b']): return "1B"
    elif (df['Max_G'] == df['G_2b']): return "2B"
    elif (df['Max_G'] == df['G_3b']): return "3B"
    elif (df['Max_G'] == df['G_ss']): return "SS"
    elif (df['Max_G'] == df['G_of']): return "OF"
    elif (df['Max_G'] == df['G_dh']): return "DH"

# Apply newly created definition to appearance data as variable 'POS'
Appearances['POS'] = Appearances.apply(Position, axis = 1)

display(Appearances)

        playerID  yearID  G_c  G_1b  G_2b  G_3b  G_ss  G_of  G_dh  Max_G POS
0      aardsda01    2004    0     0     0     0     0     0   0.0    0.0   C
1      aardsda01    2006    0     0     0     0     0     0   0.0    0.0   C
2      aardsda01    2007    0     0     0     0     0     0   0.0    0.0   C
3      aardsda01    2008    0     0     0     0     0     0   0.0    0.0   C
4      aardsda01    2009    0     0     0     0     0     0   0.0    0.0   C
5      aardsda01    2010    0     0     0     0     0     0   0.0    0.0   C
6      aardsda01    2012    0     0     0     0     0     0   0.0    0.0   C
7      aardsda01    2013    0     0     0     0     0     0   0.0    0.0   C
8      aardsda01    2015    0     0     0     0     0     0   0.0    0.0   C
9      aaronha01    1954    0     0     0     0     0   116   0.0  116.0  OF
10     aaronha01    1955    0     0    27     0     0   126   0.0  126.0  OF
11     aaronha01    1956    0     0     0     0     0   152   0.0  152.0  OF
12     aaronha01    1957    0     0     0     0     0   150   0.0  150.0  OF
13     aaronha01    1958    0     0     0     0     0   153   0.0  153.0  OF
14     aaronha01    1959    0     0     0     5     0   152   0.0  152.0  OF
15     aaronha01    1960    0     0     2     0     0   153   0.0  153.0  OF
16     aaronha01    1961    0     0     0     2     0   154   0.0  154.0  OF
17     aaronha01    1962    0     1     0     0     0   153   0.0  153.0  OF
18     aaronha01    1963    0     0     0     0     0   161   0.0  161.0  OF
19     aaronha01    1964    0     0    11     0     0   139   0.0  139.0  OF
20     aaronha01    1965    0     0     0     0     0   148   0.0  148.0  OF
21     aaronha01    1966    0     0     2     0     0   158   0.0  158.0  OF
22     aaronha01    1967    0     0     1     0     0   152   0.0  152.0  OF
23     aaronha01    1968    0    14     0     0     0   151   0.0  151.0  OF
24     aaronha01    1969    0     4     0     0     0   144   0.0  144.0  OF
25     aaronha01    1970    0    11     0     0     0   125   0.0  125.0  OF
26     aaronha01    1971    0    71     0     0     0    60   0.0   71.0  1B
27     aaronha01    1972    0   109     0     0     0    15   0.0  109.0  1B
28     aaronha01    1973    0     0     0     0     0   105   0.0  105.0  OF
29     aaronha01    1974    0     0     0     0     0    89   0.0   89.0  OF
...          ...     ...  ...   ...   ...   ...   ...   ...   ...    ...  ..
96582  zupcibo01    1992    0     0     0     0     0   114   5.0  114.0  OF
96583  zupcibo01    1993    0     0     0     0     0   122   5.0  122.0  OF
96584  zupcibo01    1994    0     1     0     2     0    30   1.0   30.0  OF
96585   zupofr01    1957    8     0     0     0     0     0   0.0    8.0   C
96586   zupofr01    1958    1     0     0     0     0     0   0.0    1.0   C
96587   zupofr01    1961    4     0     0     0     0     0   0.0    4.0   C
96588  zuvelpa01    1982    0     0     0     0     1     0   0.0    1.0  SS
96589  zuvelpa01    1983    0     0     0     0     2     0   0.0    2.0  SS
96590  zuvelpa01    1984    0     0     6     0     6     0   0.0    6.0  2B
96591  zuvelpa01    1985    0     0    42     6    33     0   0.0   42.0  2B
96592  zuvelpa01    1986    0     0     0     0    21     0   0.0   21.0  SS
96593  zuvelpa01    1987    0     0     7     1     6     0   0.0    7.0  2B
96594  zuvelpa01    1988    0     0     0     0    49     0   0.0   49.0  SS
96595  zuvelpa01    1989    0     0     0     5    15     0   3.0   15.0  SS
96596  zuvelpa01    1991    0     0     0     2     0     0   0.0    2.0  3B
96597  zuverge01    1951    0     0     0     0     0     0   0.0    0.0   C
96598  zuverge01    1952    0     0     0     0     0     0   0.0    0.0   C
96599  zuverge01    1954    0     0     0     0     0     0   0.0    0.0   C
96600  zuverge01    1955    0     0     0     0     0     0   0.0    0.0   C
96601  zuverge01    1956    0     0     0     0     0     0   0.0    0.0   C
96602  zuverge01    1957    0     0     0     0     0     0   0.0    0.0   C
96603  zuverge01    1958    0     0     0     0     0     0   0.0    0.0   C
96604  zuverge01    1959    0     0     0     0     0     0   0.0    0.0   C
96605  zwilldu01    1910    0     0     0     0     0    27   0.0   27.0  OF
96606  zwilldu01    1914    0     0     0     0     0   154   0.0  154.0  OF
96607  zwilldu01    1915    0     3     0     0     0   148   0.0  148.0  OF
96608  zwilldu01    1916    0     0     0     0     0     9   0.0    9.0  OF
96609   zychto01    2015    0     0     0     0     0     0   0.0    0.0   C
96610   zychto01    2016    0     0     0     0     0     0   0.0    0.0   C
96611   zychto01    2017    0     0     0     0     0     0   0.0    0.0   C

[96612 rows x 11 columns]

In [ ]:
# Exclude non-position players (designated hitters) and keep necessary variables

Appearances = Appearances[Appearances['Max_G'] > 0]
Appearances = Appearances[['playerID','yearID','POS']]
display(Appearances)

        playerID  yearID POS
9      aaronha01    1954  OF
10     aaronha01    1955  OF
11     aaronha01    1956  OF
12     aaronha01    1957  OF
13     aaronha01    1958  OF
14     aaronha01    1959  OF
15     aaronha01    1960  OF
16     aaronha01    1961  OF
17     aaronha01    1962  OF
18     aaronha01    1963  OF
19     aaronha01    1964  OF
20     aaronha01    1965  OF
21     aaronha01    1966  OF
22     aaronha01    1967  OF
23     aaronha01    1968  OF
24     aaronha01    1969  OF
25     aaronha01    1970  OF
26     aaronha01    1971  1B
27     aaronha01    1972  1B
28     aaronha01    1973  OF
29     aaronha01    1974  OF
30     aaronha01    1975  DH
31     aaronha01    1976  DH
32     aaronto01    1962  1B
33     aaronto01    1963  1B
34     aaronto01    1965  1B
35     aaronto01    1968  OF
36     aaronto01    1969  1B
37     aaronto01    1970  1B
38     aaronto01    1971  1B
...          ...     ...  ..
96554  zoskyed01    1999  3B
96567  zuberjo01    1996  1B
96568  zuberjo01    1998  OF
96569  zuletju01    2000  1B
96570  zuletju01    2001  1B
96576  zuninmi01    2013   C
96577  zuninmi01    2014   C
96578  zuninmi01    2015   C
96579  zuninmi01    2016   C
96580  zuninmi01    2017   C
96581  zupcibo01    1991  OF
96582  zupcibo01    1992  OF
96583  zupcibo01    1993  OF
96584  zupcibo01    1994  OF
96585   zupofr01    1957   C
96586   zupofr01    1958   C
96587   zupofr01    1961   C
96588  zuvelpa01    1982  SS
96589  zuvelpa01    1983  SS
96590  zuvelpa01    1984  2B
96591  zuvelpa01    1985  2B
96592  zuvelpa01    1986  SS
96593  zuvelpa01    1987  2B
96594  zuvelpa01    1988  SS
96595  zuvelpa01    1989  SS
96596  zuvelpa01    1991  3B
96605  zwilldu01    1910  OF
96606  zwilldu01    1914  OF
96607  zwilldu01    1915  OF
96608  zwilldu01    1916  OF

[55969 rows x 3 columns]

We now create dummy variables which correspond to the Hakes and Sauer regression: The variable 'Catch' has a value of one if the player position is 'C', and zero otherwise; 'Infld' (infielder excluding first base, as defined by Hakes and Sauer) has a value of one if the player's position is either '2B', '3B' or 'SS' and zero otherwise.

In [ ]:
# Create a indicator variable for catcher and infielder (2B, 3B, SS)

Appearances['Catch'] = np.where(Appearances['POS'] == "C", 1, 0)
Appearances['Infld'] = np.where((Appearances['POS'] == "2B") | (Appearances['POS'] == "3B") |
                                (Appearances['POS'] == "SS"), 1, 0)

display(Appearances)

        playerID  yearID POS  Catch  Infld
9      aaronha01    1954  OF      0      0
10     aaronha01    1955  OF      0      0
11     aaronha01    1956  OF      0      0
12     aaronha01    1957  OF      0      0
13     aaronha01    1958  OF      0      0
14     aaronha01    1959  OF      0      0
15     aaronha01    1960  OF      0      0
16     aaronha01    1961  OF      0      0
17     aaronha01    1962  OF      0      0
18     aaronha01    1963  OF      0      0
19     aaronha01    1964  OF      0      0
20     aaronha01    1965  OF      0      0
21     aaronha01    1966  OF      0      0
22     aaronha01    1967  OF      0      0
23     aaronha01    1968  OF      0      0
24     aaronha01    1969  OF      0      0
25     aaronha01    1970  OF      0      0
26     aaronha01    1971  1B      0      0
27     aaronha01    1972  1B      0      0
28     aaronha01    1973  OF      0      0
29     aaronha01    1974  OF      0      0
30     aaronha01    1975  DH      0      0
31     aaronha01    1976  DH      0      0
32     aaronto01    1962  1B      0      0
33     aaronto01    1963  1B      0      0
34     aaronto01    1965  1B      0      0
35     aaronto01    1968  OF      0      0
36     aaronto01    1969  1B      0      0
37     aaronto01    1970  1B      0      0
38     aaronto01    1971  1B      0      0
...          ...     ...  ..    ...    ...
96554  zoskyed01    1999  3B      0      1
96567  zuberjo01    1996  1B      0      0
96568  zuberjo01    1998  OF      0      0
96569  zuletju01    2000  1B      0      0
96570  zuletju01    2001  1B      0      0
96576  zuninmi01    2013   C      1      0
96577  zuninmi01    2014   C      1      0
96578  zuninmi01    2015   C      1      0
96579  zuninmi01    2016   C      1      0
96580  zuninmi01    2017   C      1      0
96581  zupcibo01    1991  OF      0      0
96582  zupcibo01    1992  OF      0      0
96583  zupcibo01    1993  OF      0      0
96584  zupcibo01    1994  OF      0      0
96585   zupofr01    1957   C      1      0
96586   zupofr01    1958   C      1      0
96587   zupofr01    1961   C      1      0
96588  zuvelpa01    1982  SS      0      1
96589  zuvelpa01    1983  SS      0      1
96590  zuvelpa01    1984  2B      0      1
96591  zuvelpa01    1985  2B      0      1
96592  zuvelpa01    1986  SS      0      1
96593  zuvelpa01    1987  2B      0      1
96594  zuvelpa01    1988  SS      0      1
96595  zuvelpa01    1989  SS      0      1
96596  zuvelpa01    1991  3B      0      1
96605  zwilldu01    1910  OF      0      0
96606  zwilldu01    1914  OF      0      0
96607  zwilldu01    1915  OF      0      0
96608  zwilldu01    1916  OF      0      0

[55969 rows x 5 columns]

So now we can make the last merge, to combine the fielding position data with the Master df, once again using playerID and userID as the matching variables.

In [ ]:
# Merge position data into Master data

Master = pd.merge(Master, Appearances, on=['playerID','yearID'], how = 'left')
display(Master)

,playerID,yearID,stint,G,AB,R,H,Doubles,Triples,HR,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP,PA,OBP,SLG,SalYear,teamID,lgID,salary,lnSal,debutyr,Exp,Arb,Free,POS,Catch,Infld
0,abbotje01,1998,1,89,244,33,68,14,1,12,41.0,3.0,3.0,9,28.0,1.0,0.0,2.0,5.0,2.0,260.0,0.298450,0.491803,1999,CHA,AL,255000,12.449019,1997,1,0,0,OF,0,0
1,abbotje01,2000,1,80,215,31,59,15,1,3,29.0,2.0,1.0,21,38.0,1.0,2.0,2.0,1.0,2.0,241.0,0.343096,0.395349,2001,FLO,NL,300000,12.611538,1997,3,1,0,OF,0,0
2,abbotku01,1994,1,101,345,41,86,17,3,9,33.0,3.0,0.0,16,98.0,1.0,5.0,3.0,2.0,5.0,371.0,0.290761,0.394203,1995,FLO,NL,119000,11.686879,1993,1,0,0,SS,0,1
3,abbotku01,1995,1,120,420,60,107,18,7,17,60.0,4.0,3.0,36,110.0,4.0,5.0,2.0,5.0,6.0,468.0,0.317597,0.452381,1996,FLO,NL,250000,12.429216,1993,2,0,0,SS,0,1
4,abbotku01,1996,1,109,320,37,81,18,7,8,33.0,3.0,3.0,22,99.0,1.0,3.0,4.0,0.0,7.0,349.0,0.307246,0.428125,1997,FLO,NL,650000,13.384728,1993,3,1,0,SS,0,1
5,abbotku01,1997,1,94,252,35,69,18,2,6,30.0,3.0,1.0,14,68.0,3.0,1.0,6.0,0.0,5.0,273.0,0.314607,0.432540,1998,OAK,AL,1000000,13.815511,1993,4,1,0,2B,0,1
6,abbotku01,1998,3,77,194,26,51,13,1,5,24.0,2.0,1.0,12,53.0,0.0,2.0,1.0,3.0,5.0,212.0,0.308057,0.417526,1999,COL,NL,900000,13.710150,1993,5,1,0,SS,0,1
7,abbotku01,1999,1,96,286,41,78,17,2,8,41.0,3.0,2.0,16,69.0,0.0,0.0,2.0,1.0,4.0,305.0,0.310231,0.430070,2000,NYN,NL,500000,13.122363,1993,6,1,0,2B,0,1
8,abbotku01,2000,1,79,157,22,34,7,1,6,12.0,1.0,1.0,14,51.0,2.0,1.0,0.0,1.0,2.0,173.0,0.283237,0.388535,2001,ATL,NL,600000,13.304685,1993,7,0,1,SS,0,1
9,abernbr01,2001,1,79,304,43,82,17,1,5,33.0,8.0,3.0,27,35.0,1.0,0.0,3.0,1.0,3.0,335.0,0.328313,0.381579,2002,TBA,AL,215000,12.278393,2001,0,0,0,2B,0,1
10,abernbr01,2002,1,117,463,46,112,18,4,2,40.0,10.0,4.0,25,46.0,0.0,6.0,8.0,2.0,8.0,504.0,0.288306,0.311015,2003,TBA,AL,300000,12.611538,2001,1,0,0,2B,0,1
11,abreubo01,1997,1,59,188,22,47,10,2,3,26.0,7.0,2.0,21,48.0,0.0,1.0,0.0,0.0,0.0,210.0,0.328571,0.372340,1998,PHI,NL,180000,12.100712,1996,1,0,0,OF,0,0
12,abreubo01,1998,1,151,497,68,155,29,6,17,74.0,19.0,10.0,84,133.0,14.0,0.0,4.0,4.0,6.0,589.0,0.408547,0.496982,1999,PHI,NL,400000,12.899220,1996,2,0,0,OF,0,0
13,abreubo01,1999,1,152,546,118,183,35,11,20,93.0,27.0,9.0,109,113.0,8.0,3.0,0.0,4.0,13.0,662.0,0.445619,0.549451,2000,PHI,NL,2933333,14.891650,1996,3,1,0,OF,0,0
14,abreubo01,2000,1,154,576,103,182,42,10,25,79.0,28.0,8.0,100,116.0,9.0,1.0,0.0,3.0,12.0,680.0,0.416176,0.553819,2001,PHI,NL,4983000,15.421543,1996,4,1,0,OF,0,0
15,abreubo01,2001,1,162,588,118,170,48,4,31,110.0,36.0,14.0,106,137.0,11.0,1.0,0.0,9.0,13.0,704.0,0.393466,0.542517,2002,PHI,NL,6333333,15.661337,1996,5,1,0,OF,0,0
16,abreubo01,2002,1,157,572,102,176,50,6,20,85.0,31.0,12.0,104,117.0,9.0,3.0,0.0,6.0,11.0,685.0,0.413139,0.520979,2003,PHI,NL,9100000,16.023785,1996,6,1,0,OF,0,0
17,abreubo01,2003,1,158,577,99,173,35,1,20,101.0,22.0,9.0,109,126.0,13.0,2.0,0.0,7.0,13.0,695.0,0.408633,0.467938,2004,PHI,NL,10600000,16.176365,1996,7,0,1,OF,0,0
18,abreubo01,2004,1,159,574,118,173,47,1,30,105.0,40.0,5.0,127,116.0,10.0,5.0,0.0,7.0,5.0,713.0,0.427770,0.543554,2005,PHI,NL,13100000,16.388123,1996,8,0,1,OF,0,0
19,abreubo01,2005,1,162,588,104,168,37,1,24,102.0,31.0,9.0,117,134.0,15.0,6.0,0.0,8.0,7.0,719.0,0.404729,0.474490,2006,PHI,NL,13600000,16.425580,1996,9,0,1,OF,0,0
20,abreubo01,2006,3,156,548,98,163,41,2,15,107.0,30.0,6.0,124,138.0,6.0,3.0,2.0,9.0,13.0,686.0,0.423977,0.461679,2007,NYA,AL,15000000,16.523561,1996,10,0,1,OF,0,0
21,abreubo01,2007,1,158,605,123,171,40,5,16,101.0,25.0,8.0,84,115.0,0.0,3.0,0.0,7.0,11.0,699.0,0.369099,0.444628,2008,NYA,AL,16000000,16.588099,1996,11,0,1,OF,0,0
22,abreubo01,2008,1,156,609,100,180,39,4,20,100.0,22.0,11.0,73,109.0,2.0,1.0,0.0,1.0,14.0,684.0,0.371345,0.471264,2009,LAA,AL,5000000,15.424948,1996,12,0,1,OF,0,0
23,abreubo01,2009,1,152,563,96,165,29,3,15,103.0,30.0,8.0,94,113.0,7.0,1.0,0.0,9.0,15.0,667.0,0.389805,0.435169,2010,LAA,AL,9000000,16.012735,1996,13,0,1,OF,0,0
24,abreubo01,2010,1,154,573,88,146,41,1,20,78.0,24.0,10.0,87,132.0,3.0,2.0,0.0,5.0,13.0,667.0,0.352324,0.434555,2011,LAA,AL,9000000,16.012735,1996,14,0,1,OF,0,0
25,abreubo01,2011,1,142,502,54,127,30,1,8,60.0,21.0,5.0,78,113.0,5.0,1.0,1.0,3.0,8.0,585.0,0.352740,0.364542,2012,LAA,AL,9000000,16.012735,1996,15,0,1,DH,0,0
26,abreujo02,2014,1,145,556,80,176,35,2,36,107.0,3.0,1.0,51,131.0,15.0,11.0,0.0,4.0,14.0,622.0,0.382637,0.580935,2015,CHA,AL,8666000,15.974918,2014,0,0,0,1B,0,0
27,abreujo02,2015,1,154,613,88,178,34,3,30,101.0,0.0,0.0,39,140.0,11.0,15.0,0.0,1.0,16.0,668.0,0.347305,0.502447,2016,CHA,AL,11666667,16.272246,2014,1,0,0,1B,0,0
28,abreuto01,2007,1,59,166,19,45,14,1,2,17.0,0.0,0.0,7,21.0,1.0,3.0,0.0,2.0,5.0,178.0,0.308989,0.403614,2008,LAN,NL,393000,12.881565,2007,0,0,0,3B,0,1
29,abreuto01,2013,1,53,138,21,37,12,3,2,14.0,0.0,2.0,6,33.0,1.0,1.0,1.0,1.0,5.0,147.0,0.301370,0.442029,2014,SFN,NL,745000,13.521139,2007,6,1,0,2B,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7754,zeileto01,1994,1,113,415,62,111,25,1,19,75.0,1.0,3.0,52,56.0,3.0,3.0,0.0,7.0,13.0,477.0,0.348008,0.469880,1995,SLN,NL,3700000,15.123843,1989,5,1,0,3B,0,1
7755,zeileto01,1995,3,113,426,50,105,22,0,14,52.0,1.0,0.0,34,76.0,1.0,4.0,4.0,5.0,13.0,473.0,0.304904,0.396714,1996,PHI,NL,2700000,14.808762,1989,6,1,0,3B,0,1
7756,zeileto01,1996,3,163,617,78,162,32,0,25,99.0,1.0,1.0,82,104.0,4.0,1.0,0.0,4.0,18.0,704.0,0.348011,0.435981,1997,LAN,NL,3100000,14.946913,1989,7,0,1,3B,0,1
7757,zeileto01,1997,1,160,575,89,154,17,0,31,90.0,8.0,7.0,85,112.0,7.0,6.0,0.0,6.0,18.0,672.0,0.364583,0.459130,1998,LAN,NL,3200000,14.978661,1989,8,0,1,3B,0,1
7758,zeileto01,1998,6,158,572,85,155,32,3,19,94.0,4.0,4.0,69,90.0,2.0,4.0,1.0,7.0,12.0,653.0,0.349693,0.437063,1999,TEX,AL,3200000,14.978661,1989,9,0,1,3B,0,1
7759,zeileto01,1999,1,156,588,80,172,41,1,24,98.0,1.0,2.0,56,94.0,3.0,4.0,1.0,7.0,20.0,656.0,0.354198,0.488095,2000,NYN,NL,4333333,15.281848,1989,10,0,1,3B,0,1
7760,zeileto01,2000,1,153,544,67,146,36,3,22,79.0,3.0,4.0,74,85.0,4.0,2.0,0.0,3.0,15.0,623.0,0.356340,0.466912,2001,NYN,NL,6833333,15.737323,1989,11,0,1,1B,0,0
7761,zeileto01,2001,1,151,531,66,141,25,1,10,62.0,1.0,0.0,73,102.0,3.0,6.0,0.0,2.0,15.0,612.0,0.359477,0.372881,2002,COL,NL,6833333,15.737323,1989,12,0,1,1B,0,0
7762,zeileto01,2002,1,144,506,61,138,23,0,18,87.0,1.0,1.0,66,92.0,3.0,1.0,0.0,7.0,27.0,580.0,0.353448,0.424901,2003,NYA,AL,1500000,14.220976,1989,13,0,1,3B,0,1
7763,zeileto01,2003,3,100,299,40,68,10,2,11,42.0,1.0,0.0,34,54.0,0.0,3.0,0.0,5.0,6.0,341.0,0.307918,0.384615,2004,NYN,NL,1000000,13.815511,1989,14,0,1,3B,0,1
7764,zimmery01,2007,1,162,653,99,174,43,5,24,91.0,4.0,1.0,61,125.0,3.0,3.0,0.0,5.0,26.0,722.0,0.329640,0.457887,2008,WAS,NL,465000,13.049793,2005,2,0,0,3B,0,1
7765,zimmery01,2008,1,106,428,51,121,24,1,14,51.0,1.0,1.0,31,71.0,1.0,3.0,0.0,4.0,12.0,466.0,0.332618,0.441589,2009,WAS,NL,3325000,15.016980,2005,3,1,0,3B,0,1
7766,zimmery01,2009,1,157,610,110,178,37,3,33,106.0,2.0,0.0,72,119.0,9.0,2.0,0.0,9.0,22.0,693.0,0.363636,0.524590,2010,WAS,NL,6350000,15.663965,2005,4,1,0,3B,0,1
7767,zimmery01,2010,1,142,525,85,161,32,0,25,85.0,4.0,1.0,69,98.0,6.0,4.0,0.0,5.0,16.0,603.0,0.388060,0.510476,2011,WAS,NL,9025000,16.015509,2005,5,1,0,3B,0,1
7768,zimmery01,2011,1,101,395,52,114,21,2,12,49.0,3.0,1.0,41,73.0,4.0,1.0,0.0,3.0,14.0,440.0,0.354545,0.443038,2012,WAS,NL,12000000,16.300417,2005,6,1,0,3B,0,1
7769,zimmery01,2012,1,145,578,93,163,36,1,25,95.0,5.0,2.0,57,116.0,8.0,2.0,0.0,4.0,20.0,641.0,0.346334,0.477509,2013,WAS,NL,14100000,16.461685,2005,7,0,1,3B,0,1
7770,zimmery01,2013,1,147,568,84,156,26,2,26,79.0,6.0,0.0,60,133.0,2.0,2.0,0.0,3.0,16.0,633.0,0.344392,0.464789,2014,WAS,NL,14000000,16.454568,2005,8,0,1,3B,0,1
7771,zimmery01,2014,1,61,214,26,60,19,1,5,38.0,0.0,0.0,22,37.0,0.0,0.0,0.0,4.0,6.0,240.0,0.341667,0.448598,2015,WAS,NL,14000000,16.454568,2005,9,0,1,OF,0,0
7772,zimmery01,2015,1,95,346,43,86,25,1,16,73.0,1.0,0.0,33,79.0,0.0,1.0,0.0,10.0,13.0,390.0,0.307692,0.465318,2016,WAS,NL,14000000,16.454568,2005,10,0,1,1B,0,0
7773,zobribe01,2006,1,52,183,10,41,6,2,2,18.0,2.0,3.0,10,26.0,1.0,0.0,2.0,3.0,2.0,198.0,0.260204,0.311475,2007,TBA,AL,383400,12.856834,2006,0,0,0,SS,0,1
7774,zobribe01,2008,1,62,198,32,50,10,2,12,30.0,3.0,0.0,25,37.0,1.0,2.0,0.0,2.0,4.0,227.0,0.339207,0.505051,2009,TBA,AL,415900,12.938200,2006,2,0,0,SS,0,1
7775,zobribe01,2009,1,152,501,91,149,28,7,27,91.0,17.0,6.0,91,104.0,4.0,2.0,1.0,4.0,7.0,599.0,0.404682,0.542914,2010,TBA,AL,438100,12.990202,2006,3,1,0,2B,0,1
7776,zobribe01,2010,1,151,541,77,129,28,2,10,75.0,24.0,3.0,92,107.0,1.0,3.0,7.0,12.0,10.0,655.0,0.345679,0.353050,2011,TBA,AL,4687300,15.360367,2006,4,1,0,OF,0,0
7777,zobribe01,2011,1,156,588,99,158,46,6,20,91.0,19.0,6.0,77,128.0,1.0,2.0,2.0,5.0,9.0,674.0,0.352679,0.469388,2012,TBA,AL,4687300,15.360367,2006,5,1,0,2B,0,1
7778,zobribe01,2012,1,157,560,88,151,39,7,20,74.0,14.0,9.0,97,103.0,7.0,3.0,2.0,6.0,13.0,668.0,0.376877,0.471429,2013,TBA,AL,5687300,15.553746,2006,6,1,0,OF,0,0
7779,zobribe01,2013,1,157,612,77,168,36,3,12,71.0,11.0,3.0,72,91.0,4.0,7.0,1.0,6.0,18.0,698.0,0.354376,0.401961,2014,TBA,AL,7000000,15.761421,2006,7,0,1,2B,0,1
7780,zobribe01,2014,1,146,570,83,155,34,3,10,52.0,10.0,5.0,75,84.0,4.0,1.0,2.0,6.0,8.0,654.0,0.354294,0.394737,2015,OAK,AL,7500000,15.830414,2006,8,0,1,2B,0,1
7781,zobribe01,2015,3,126,467,76,129,36,3,13,56.0,3.0,4.0,62,56.0,3.0,1.0,0.0,5.0,8.0,535.0,0.358879,0.449679,2016,CHN,NL,10500000,16.166886,2006,9,0,1,2B,0,1
7782,zuninmi01,2013,1,52,173,22,37,5,0,5,14.0,1.0,0.0,16,49.0,0.0,3.0,0.0,1.0,5.0,193.0,0.290155,0.329480,2014,SEA,AL,504100,13.130530,2013,0,0,0,C,1,0
7783,zuninmi01,2014,1,131,438,51,87,20,2,22,60.0,0.0,3.0,17,158.0,1.0,17.0,0.0,4.0,12.0,476.0,0.254202,0.404110,2015,SEA,AL,523500,13.168292,2013,1,0,0,C,1,0

# Running the regressions

As you have seen, organizing the data is a lot of work. The next stage - running the regressions - is in fact quite quick. This is not unusual. The skill with regression analysis generally involves (a) deciding what regression you want to run (b) obtaining the data and (c) structuring the data to fit your regression design. Once all this is done, the regressions calculations have been incorporated into the packages, and provide you with informative summaries that describe the regression.

In [ ]:
#Table 3 of Hakes and Sauer use only the data from 2000 to 2004 : so we define a df for these years only

MB_Data = Master[(Master.SalYear >= 2000) & (Master.SalYear <= 2004)]

In [ ]:
# Sometimes it helps to review the variables in the df - here we can see the names of the variables we need for the regressions:
# lnSal = b0 + b1 OBP + b2 SLG + b3 PA + b4 Arb + b5 Free + b6 Catch + b7 Infld

print(Master.columns.tolist())

['playerID', 'yearID', 'stint', 'G', 'AB', 'R', 'H', 'Doubles', 'Triples', 'HR', 'RBI', 'SB', 'CS', 'BB', 'SO', 'IBB', 'HBP', 'SH', 'SF', 'GIDP', 'PA', 'OBP', 'SLG', 'SalYear', 'teamID', 'lgID', 'salary', 'lnSal', 'debutyr', 'Exp', 'Arb', 'Free', 'POS', 'Catch', 'Infld']

Table 3 of Hakes and Sauer reports seven regressions, each covering a different time period. Each regression employs the same explanatory variables.

We start by running the regression from column 1 of Table 3, which covers all the years in the df: 2000 to 2004.

In [ ]:
# Regression for labor market valuation of OBP and SLG for seasons 2000-2004 (all) = Table 3 Column 1

import statsmodels.formula.api as smf
Val_All_lm = smf.ols(formula = 'lnSal ~ OBP + SLG + PA + Arb + Free + Catch + Infld', data=MB_Data).fit()
Val_All_lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  lnSal   R-squared:                       0.662
Model:                            OLS   Adj. R-squared:                  0.661
Method:                 Least Squares   F-statistic:                     485.7
Date:                Thu, 19 Dec 2024   Prob (F-statistic):               0.00
Time:                        06:44:16   Log-Likelihood:                -1928.6
No. Observations:                1741   AIC:                             3873.
Df Residuals:                    1733   BIC:                             3917.
Df Model:                           7
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     10.1090      0.164     61.773      0.000       9.788      10.430
OBP            1.4783      0.628      2.355      0.019       0.247       2.709
SLG            2.3884      0.316      7.553      0.000       1.768       3.009
PA             0.0031      0.000     25.962      0.000       0.003       0.003
Arb            1.2076      0.049     24.585      0.000       1.111       1.304
Free           1.8050      0.049     37.033      0.000       1.709       1.901
Catch          0.1115      0.057      1.972      0.049       0.001       0.222
Infld         -0.0502      0.041     -1.231      0.219      -0.130       0.030
==============================================================================
Omnibus:                        5.756   Durbin-Watson:                   1.493
Prob(Omnibus):                  0.056   Jarque-Bera (JB):                6.893
Skew:                           0.026   Prob(JB):                       0.0319
Kurtosis:                       3.304   Cond. No.                     1.84e+04
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.84e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

You should now compare the results of the two regressions. The values are not identical, but they are quite close.

<!-- ![MBreg%20compared%20Table%203.PNG](attachment:MBreg%20compared%20Table%203.PNG) -->

It's also noticeable that the standard errors (which are numbers in parentheses from the published paper) are also quite close to the standard errors from our regression.

Moreover, the key part of the Moneyball narrative is confirmed: taking the period as a whole, the size of the coefficient on slugging percentage is almost twice the size as the coefficient of on-base percentage, while the standard error is half the size. This means that in terms of player salaries, slugging percentage was more significant both in an economic sense and a statistical sense.  

If we run the regression for the period 2000-2003 (column 2 of Table 3) we also find our results are very close to those of Hakes and Sauer.

In [ ]:
# Regression for labor market valuation of OBP and SLG for seasons 2000-2003 = Table 3 Column 2

MB_Data_Pre = Master[(Master.SalYear >= 2000) & (Master.SalYear <= 2003)]
Val_Pre_lm = smf.ols(formula = 'lnSal ~ OBP + SLG + PA + Arb + Free + Catch + Infld', data=MB_Data_Pre).fit()
Val_Pre_lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  lnSal   R-squared:                       0.681
Model:                            OLS   Adj. R-squared:                  0.679
Method:                 Least Squares   F-statistic:                     423.2
Date:                Wed, 24 Feb 2021   Prob (F-statistic):               0.00
Time:                        20:36:33   Log-Likelihood:                -1512.2
No. Observations:                1398   AIC:                             3040.
Df Residuals:                    1390   BIC:                             3082.
Df Model:                           7
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     10.2248      0.176     58.008      0.000       9.879      10.571
OBP            0.7958      0.677      1.176      0.240      -0.532       2.123
SLG            2.4908      0.340      7.322      0.000       1.823       3.158
PA             0.0031      0.000     24.172      0.000       0.003       0.003
Arb            1.2559      0.054     23.432      0.000       1.151       1.361
Free           1.8729      0.053     35.018      0.000       1.768       1.978
Catch          0.1330      0.062      2.156      0.031       0.012       0.254
Infld         -0.0282      0.044     -0.639      0.523      -0.115       0.058
==============================================================================
Omnibus:                        7.962   Durbin-Watson:                   1.499
Prob(Omnibus):                  0.019   Jarque-Bera (JB):               10.336
Skew:                          -0.041   Prob(JB):                      0.00570
Kurtosis:                       3.413   Cond. No.                     1.82e+04
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.82e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

Comparing the coefficients and standard errors, the message is the same from both sets of results - before the publication of Moneyball, OBP was statistically insignificant, while the impact of SLG on salary was three times larger and statistically significant.  

<!-- ![MBreg%20compared%20Table%203%20no2.PNG](attachment:MBreg%20compared%20Table%203%20no2.PNG)  -->

We can continue to compare the regressions one by one, but as we did with Table 1, it makes more sense to format our results in a way that looks like Table 3.

In [ ]:
# Here we just run each regression by taking a subset for the relevant year, but we don't print out the results.

MB_Data_2000 = Master[(Master.SalYear == 2000)]
Val_2000_lm = smf.ols(formula = 'lnSal ~ OBP + SLG + PA + Arb + Free + Catch + Infld', data=MB_Data_2000).fit()
MB_Data_2001 = Master[(Master.SalYear == 2001)]
Val_2001_lm = smf.ols(formula = 'lnSal ~ OBP + SLG + PA + Arb + Free + Catch + Infld', data=MB_Data_2001).fit()
MB_Data_2002 = Master[(Master.SalYear == 2002)]
Val_2002_lm = smf.ols(formula = 'lnSal ~ OBP + SLG + PA + Arb + Free + Catch + Infld', data=MB_Data_2002).fit()
MB_Data_2003 = Master[(Master.SalYear == 2003)]
Val_2003_lm = smf.ols(formula = 'lnSal ~ OBP + SLG + PA + Arb + Free + Catch + Infld', data=MB_Data_2003).fit()
MB_Data_2004 = Master[(Master.SalYear == 2004)]
Val_2004_lm = smf.ols(formula = 'lnSal ~ OBP + SLG + PA + Arb + Free + Catch + Infld', data=MB_Data_2004).fit()

Having created the regressions, we can now display them in the same column format as Table 3, in the same way that we did with Table 1.

In [ ]:
from statsmodels.iolib.summary2 import summary_col
Header = ['All years','2000-2003','2000','2001','2002','2003','2004']
Table_3 = summary_col([Val_All_lm,Val_Pre_lm,Val_2000_lm,Val_2001_lm,Val_2002_lm,Val_2003_lm,Val_2004_lm,],\
                      regressor_order=['OBP','SLG','PA','Arb','Free','Catch','Infld','Intercept'],stars=True, \
                      float_format="'%.3f'",model_names = Header)
print(Table_3)

===========================================================================================
           All years   2000-2003     2000        2001        2002        2003       2004
-------------------------------------------------------------------------------------------
OBP       '1.478'**   '0.796'     '2.179'*   '0.132'     '0.595'     '1.890'     '4.353'***
          ('0.628')   ('0.677')   ('1.217')  ('1.209')   ('1.566')   ('1.585')   ('1.630')
SLG       '2.388'***  '2.491'***  '2.550'*** '3.224'***  '2.312'***  '1.945'**   '2.171'***
          ('0.316')   ('0.340')   ('0.610')  ('0.597')   ('0.724')   ('0.846')   ('0.820')
PA        '0.003'***  '0.003'***  '0.002'*** '0.003'***  '0.003'***  '0.003'***  '0.003'***
          ('0.000')   ('0.000')   ('0.000')  ('0.000')   ('0.000')   ('0.000')   ('0.000')
Arb       '1.208'***  '1.256'***  '1.296'*** '1.111'***  '1.289'***  '1.247'***  '1.044'***
          ('0.049')   ('0.054')   ('0.102')  ('0.100')   ('0.114')   ('0.114')   ('0.120')
Free      '1.805'***  '1.873'***  '1.914'*** '1.788'***  '1.937'***  '1.814'***  '1.560'***
          ('0.049')   ('0.053')   ('0.099')  ('0.097')   ('0.118')   ('0.115')   ('0.116')
Catch     '0.112'**   '0.133'**   '0.035'    '0.164'     '0.075'     '0.281'**   '0.066'
          ('0.057')   ('0.062')   ('0.121')  ('0.114')   ('0.126')   ('0.133')   ('0.138')
Infld     '-0.050'    '-0.028'    '-0.022'   '0.089'     '-0.073'    '-0.073'    '-0.097'
          ('0.041')   ('0.044')   ('0.084')  ('0.082')   ('0.092')   ('0.095')   ('0.103')
Intercept '10.109'*** '10.225'*** '9.902'*** '10.109'*** '10.313'*** '10.062'*** '9.530'***
          ('0.164')   ('0.176')   ('0.348')  ('0.318')   ('0.380')   ('0.389')   ('0.426')
===========================================================================================
Standard errors in parentheses.
* p<.1, ** p<.05, ***p<.01

Now we can compare the two versions in full:  

<!-- ![MBreg%20compared%20Table%203%20full.PNG](attachment:MBreg%20compared%20Table%203%20full.PNG) -->

Our version of Table 3 reproduces the Moneyball result very closely: SLG is consistently significant in a statistical sense (the ratio of the coefficient to the standard error is consistently above 2, while before the publication of Moneyball, OBP is consistently insignificant in a statistical sense. Then in 2004 not only does it become statistically significant, but the size of the coefficient is twice as large as SLG.  

How can we explain the fact that our estimates, although very close in general, are not identical, and in a few cases differ quite widely? One possible explanation is that since Hakes and Sauer wrote their paper in 2006, the Lahman database has been revised several times, and errors from previous versions may have been corrected. Another possibility is that, while we have tried to follow Hakes and Sauer's methodology exactly, we may have diverged from them in some small ways. For example, you can see that the number of observations for each regression is slightly different - and different samples will generally produce different estimates.  

Notwithstanding these small differences, our results are very close. It is a common problem in the sciences that results cannot be reproduced - it's a credit to Hakes and Sauer that there is no such problem with theirs.

## Self test

Replace OBP with Batting Average to see how have teams valued batting average over this timeframe?
When you do this, how does the R-squared of the regression model compare to H & S model for OBP and SLG?

In [ ]:
# Now save our Master file so we can re-use it later

Master.to_csv("../Data/Master.csv")